### ISSUE TITLE
Lookup Issue 

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#1]

**Comment by audhi3k** [comment]
Is the issue resolved, kindly check and update the correct status

**Comment by audhi3k** [comment]
Customization with new table to be done

**Comment by 3ktech** [comment]
@niranjand22 , ready for testing

**Comment by niranjand22** [comment]
Hi Mahesh, I have tested in Keltech UAT Environmnet. The Lookup is still taking so much time to load the provisional entry.

**Comment by Mahesh3ktech** [comment]
Hi Niranjan, I have reworked on the lookup issue. Now the lookup is not taking time to load. Kindly check and let me know.

**Comment by audhi3k** [comment]
Informed to client for testing on 25th Jan 2023

**Comment by audhi3k** [comment]
Client confirmed the UAT and to move to LIVE

**Comment by audhi3k** [comment]
Deployed in LIVE, and waiting client confirmation for closure

**Comment by audhi3k** [comment]
@niranjand22, convey the client for closure and if there is any issue, we can create as new ticket

**Comment by niranjand22** [comment]
client is on another location. his team will confirm for case closure.

**Comment by niranjand22** [comment]
Follow up mail is sent response not yet received

**Comment by audhi3k** [comment]
We are closing this ticket as there is no issues reported after deployment in LIVE i.e., 3 weeks
