### ISSUE TITLE
Responsibility Center Required for Customer, Vendor, Sales, Purchase, and Finance

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#10]

**Comment by audhi3k** [comment]
@niranjand22  can you check and update the status

**Comment by Mahesh3ktech** [comment]
@niranjand22, Change Request is completed can check and update the status.

**Comment by audhi3k** [comment]
Informed to client for UAT on 25th Jan 2023

**Comment by audhi3k** [comment]
Organize a meeting with Mr Praviin to discuss on the requirement relating to creation of customer from Sales Invoice

**Comment by niranjand22** [comment]
Vendor and Customer page -res ctr and biz code should be auto populated based on res ctr.

**Comment by niranjand22** [comment]
Purchase doc no. is not updating. rest all working fine

**Comment by Mahesh3ktech** [comment]
@niranjand22 Purchase no. series will update now, you can test and update.

**Comment by niranjand22** [comment]
Yes I tested..it is taking correct value

**Comment by niranjand22** [comment]
PRESENTED CHANGES TO PRAVINN. MOST THINGS ARE WORKING FINE NOW. 

POSTED SALES INVOICE NO SERIES POINTS NEEDS TO BE ADDRESSED ALONG WITH SOME MORE POINTS.

**Comment by niranjand22** [comment]
CLIENT IS ALSO TESTING

**Comment by audhi3k** [comment]
@niranjand22 can you list down what's the some more points to be addressed and also what is no series point

**Comment by niranjand22** [comment]
Once Mahesh do the further changes will test.

**Comment by niranjand22** [comment]
Sales Return Order changes are pending. Rest is done

**Comment by Mahesh3ktech** [comment]
@niranjand22, Sales return order is getting posted. Can you check and update.

**Comment by niranjand22** [comment]
Sales return order is working fine but when we post invoice through Sales Quote. In Posted doc it is taking no series from sales receivable setup not from location

**Comment by audhi3k** [comment]
@Mahesh3ktech client has given approval to deploy in LIVE, kindly update once deployed in LIVE
@niranjand22 kindly co-ordinate and update the status to the client

**Comment by niranjand22** [comment]
Sure

**Comment by niranjand22** [comment]
@Mahesh3ktech please update comments once published to live

**Comment by audhi3k** [comment]
@Mahesh3ktech, deploy the objects to LIVE, request for down time with the client

**Comment by Mahesh3ktech** [comment]
Responsibility Center deployment to prod server is completed. Client needs to confirm.

**Comment by audhi3k** [comment]
@niranjand22 , we will close this ticket on Monday, for client confirmation

**Comment by audhi3k** [comment]
Client hasn't raised any issue, so closing this ticket
