### ISSUE TITLE
Sandbox Env Creation For fervid

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#100]

**Comment by audhi3k** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72" lang=EN-IN style='tab-interval:36pt;
word-wrap:break-word'>



Sandbox   url: | https://businesscentral.dynamics.com/e5b7819e-2836-4dba-a4ad-eb9d5d14d2cd/Sandbox
-- | --
Email ID: | 3kt@fervidsmart.com
Password: | Fervid@3K



</body>

</html>
[Sandbox url:](https://businesscentral.dynamics.com/e5b7819e-2836-4dba-a4ad-eb9d5d14d2cd/Sandbox)	https://businesscentral.dynamics.com/e5b7819e-2836-4dba-a4ad-eb9d5d14d2cd/Sandbox
[Email ID: ](mailto:3kt@fervidsmart.com)	3kt@fervidsmart.com
Password: 	[Fervid@3K](mailto:Fervid@3K)
