### ISSUE TITLE
Charge Group Code

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#1000]

**Comment by rohit3k** [comment]
Hi Mr. @Amar-3KT Development has been done and Value entry is getting created, it is available on sandbox Environment please check and confirm.
cc: @audhi3k @gsudarsan3k

**Comment by Amar-3KT** [comment]
@rohit3k -Please check posted purchase invoice AHM.PI.2324.00184 it should create 4 document but currently creating only 2 document.

**Comment by audhi3k** [comment]
Resolved and deployed in LIVE
