### ISSUE TITLE
Job Journal Voucher - G/L code description in report

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1002]

**Comment by Prakash3K** [comment]
@Ejaz3KT  



![Image](https://github.com/3ktech/General/assets/140147250/0827901b-1149-4acd-b888-11ece48dc868)

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech UAT has been completed and client has confirmed to deploy the changes of report in the production company

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The Changes have been deployed in the production waiting for the client's confirmation

CC: @audhi3k @Mahesh3ktech

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k can we connect regarding this report

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam When we are running the voucher report the total amount of credit side is not printing correctly please fix the issue and for your reference, I am mentioning document no you can check this in the rolling debug sandbox

Reference: DMP230006

![Image](https://github.com/3ktech/General/assets/125632927/6d4f4214-0858-4e5a-b982-6c0961e3328e)

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

please check rollingdebug?

cc : @gsudarsan3k @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam I`ve tested report it is fine

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k  Madam please hide the GST G/L accounts 1. 31606, 2. 31603 in the report 

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The issue has been resolved Mr. @Prakash3K you can close this ticket with 10 hours of effort

CC: @audhi3k @sandhya3k
