### ISSUE TITLE
Business Central show overdue sales invoices

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1006]

**Comment by Prakash3K** [comment]
@niranjand22 


![Image](https://github.com/3ktech/General/assets/140147250/30bcbd77-071c-49b2-8def-1ad23ca30b2a)



![Image](https://github.com/3ktech/General/assets/140147250/d62ad43d-a899-40b2-9226-82074a530bc8)

**Comment by niranjand22** [comment]
I have checked. bal accounts no is missing for all the above  sales invoices.

also dates are mixed.and not from a specific period. @audhi3k

**Comment by niranjand22** [comment]
I have create sales invoice with bal gl account and without bal gl account.

By default bal gl account was not assigned in  Payment method. I aasiged Bal gl account and reslected in sales invoice so it got update. 

For some invoice i have not reselected the Payment method so 

![Image](https://github.com/3ktech/General/assets/116243958/2d14caed-e2d0-4caf-a5b9-db2862cfb0e6)

it is showing overdue after posting
