### ISSUE TITLE
Extras on Jet report/GL data

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1007]

**Comment by Prakash3K** [comment]
@Amar-3KT 

![Image](https://github.com/3ktech/General/assets/140147250/8f20d3f2-87a8-4c77-8bf9-145ff77ec12f)


[05. August (1).xlsx](https://github.com/3ktech/General/files/13359961/05.August.1.xlsx)

**Comment by Amar-3KT** [comment]
In jet report 3 fields need to add @3ktech @gsudarsan3k -Please assign technical for the same.

**Comment by sandhya3k** [comment]
@Amar-3KT 

can we connect for the above issue?

**Comment by Amar-3KT** [comment]
@sandhya3k -Yes

**Comment by Amar-3KT** [comment]
1) CE Sales Order No. QTQ (50100, Code[20])- from header
2) Customer name- From header
3) Item description- From line

**Comment by sandhya3k** [comment]
@Amar-3KT 

as discussed i mapped into the header fields into the excel report. please test.

[05.August.1 (1).xlsx](https://github.com/3ktech/General/files/13389725/05.August.1.1.xlsx)

**Comment by sandhya3k** [comment]
@Amar-3KT 

[05.August.1 (1).xlsx](https://github.com/3ktech/General/files/13390811/05.August.1.1.xlsx)

**Comment by Amar-3KT** [comment]
@sandhya3k - As discussed with you now Mr. Karthik d working on this issue. Please let me know once its done.
@sandhya3k -Any timeline for this issue?

**Comment by Amar-3KT** [comment]
@3ktech -Please update the status

**Comment by sandhya3k** [comment]
@Amar-3KT 

i will check with Karthik and update

**Comment by niranjand22** [comment]
.

**Comment by niranjand22** [comment]
hi @sandhya3k  can you update progress here

**Comment by sandhya3k** [comment]
can we connect ? @niranjand22

**Comment by audhi3k** [comment]
Ms @sandhya3k  and Mr @niranjand22  what's the status of this

**Comment by sandhya3k** [comment]
@audhi3k mam,

@niranjand22 sent a mail to jet report trainers. they were asking for some details about the issue, but i had an issue with the remote server for getting the details of the report.

**Comment by sandhya3k** [comment]
hi @niranjand22 ,

i explained the issue for the server to @Shasthara  once, i got the update from them i will share the details
