### ISSUE TITLE
RE: AR Access in Business central

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1008]

**Comment by Prakash3K** [comment]
@niranjand22 



![Image](https://github.com/3ktech/General/assets/140147250/e6779030-bb40-4fe5-b3f4-105cb39fa96d)

**Comment by niranjand22** [comment]
Completed the requested changes. waiting for cust confirmation.

cc -- @audhi3k

**Comment by niranjand22** [comment]
close this with 45 min. @Prakash3K  cc @audhi3k
