### ISSUE TITLE
Blocked Vendor should not get appeared in vendor list

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#1009]

**Comment by Mahesh3ktech** [comment]
hi @Ejaz3KT - changes has been done. kindly check and confirm.

@audhi3k, @gsudarsan3k

**Comment by Ejaz3KT** [comment]
We are waiting for the client information

CC: @audhi3k

**Comment by Jayanth3KT** [comment]
@Ejaz3KT  Why the status is in hold, kindly update.

CC: @audhi3k @Shasthara

**Comment by Ejaz3KT** [comment]
I`ve shown them how to block the vendor functionality to the client and it has been confirmed so we can close this ticket

CC: @audhi3k
