### ISSUE TITLE
Bin Code Not Visible in Warehouse pick Screen 

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1013]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 



![Image](https://github.com/3ktech/General/assets/140147250/005da492-6f02-4fc1-9ea0-d5d5a8cc426b)



![Image](https://github.com/3ktech/General/assets/140147250/89bbe98e-38b9-4ab1-a850-6a4b07b9c647)



![Image](https://github.com/3ktech/General/assets/140147250/e682ce47-fc89-4a9e-8d09-477c6c0287b3)



![Image](https://github.com/3ktech/General/assets/140147250/613b0633-602c-417f-b230-2f57867b2823)



![Image](https://github.com/3ktech/General/assets/140147250/d0490386-f4e7-4b23-8569-e344a27fa74d)



![Image](https://github.com/3ktech/General/assets/140147250/808d5977-73e8-4847-8f7f-faec6ffa0d41)



![Image](https://github.com/3ktech/General/assets/140147250/8ee9dc5c-4ee2-40f5-8490-3dcf59dece89)

**Comment by TabrejAlam3K** [comment]
We will connect with the cleint (Mr. Dhawal) to see the issues.

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/7bb49f68-302f-423c-a45b-a40c9597e820)

**Comment by TabrejAlam3K** [comment]
No any response receive from the client end.

CC : @Shasthara @audhi3k

**Comment by TabrejAlam3K** [comment]
Same scenarion required in the Staging Environment. We are waiting for New Staging Environment.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Microsoft Dynamics NAV
---------------------------

Lot No. LOT-000004200 is not available on inventory or it has already been reserved for another document.
---------------------------
OK
---------------------------

**Comment by TabrejAlam3K** [comment]
Issue analyzed Lot no. not available on warehouse shipment. User was on leave today.

CC : @audhi3k @Shasthara @Mahesh3ktech

**Comment by TabrejAlam3K** [comment]
I have done the session along with the user, they will check internally and come back if required tech support on this.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - how much time you have spend on this please update here.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - You can close this ticket from the support portal as well. I am closing this from the Git due to not responded by the Client.

CC : @audhi3k @Shasthara @Sarikab1222
