### ISSUE TITLE
Invoicing Error - ORD-13186-R7N9L5

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1014]

**Comment by Prakash3K** [comment]
@Amar-3KT 

User ID: tejal.shah@dodsgroup.com

![Image](https://github.com/3ktech/General/assets/140147250/cfdca7cb-3e2e-480a-995a-ba6ebb1ffbd7)

**Comment by niranjand22** [comment]
Connected with amber..need to analys the issue

**Comment by niranjand22** [comment]
hi @gsudarsan3k  need technical for this case.

cc @audhi3k

**Comment by rohit3k** [comment]
Hi Mr. @niranjand22 please check this issue it is working now. it seems there was some API hit issue for certain period, please check and confirm.

cc: @audhi3k @gsudarsan3k
