### ISSUE TITLE
Process and Dev KT required for subcon process

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1020]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 



![Image](https://github.com/3ktech/General/assets/140147250/d9ac66f7-1f20-421c-95af-7f05194f812f)

CC: @rohit3k @3ktech @gsudarsan3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @gsudarsan3k - Client want KT for the Development of UL Process related to Subcontracting Order. Please plan it for tomorrow they have already send the google meet invitation.

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
Mr. @Prakash3K - You can close this ticket from the support portal. Dev KT session is completed.

Total Effort Hours = 2 Hours

CC : @audhi3k @Shasthara
