### ISSUE TITLE
Issue in PO reopen

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1025]

**Comment by Prakash3K** [comment]
@Amar-3KT 



![Image](https://github.com/3ktech/General/assets/140147250/d4cfefc4-4bb2-4bcf-a19e-87ad0658f5da)

**Comment by Amar-3KT** [comment]
Mr. Himanshu not available for more details.

**Comment by Amar-3KT** [comment]
I have shown workflow process to Mr. Himanshu on Sandbox its working fine. Now he will check on production with user and will confirm.

**Comment by Jayanth3KT** [comment]
.

**Comment by Jayanth3KT** [comment]
Hi @gsudarsan3k Kindly assign technical resource on this ticket need to be debugged.

CC: @audhi3k @shivakumar3k

**Comment by Jayanth3KT** [comment]
Hi @sandhya3k In copy prod its working fine but in live. its not working ( All PO)

**Comment by audhi3k** [comment]
Ms @sandhya3k are you working on this task

**Comment by sandhya3k** [comment]
@audhi3k 
yes mam

**Comment by sandhya3k** [comment]
@Jayanth3KT 

As discussed, once u connect with the client then update here.

**Comment by Jayanth3KT** [comment]
@sandhya3k  Kindly debug the issue Live production PO No : kel.po.2324.1194 

@shivakumar3k

**Comment by audhi3k** [comment]
What the update Ms @sandhya3k  and Mr @Jayanth3KT

**Comment by sandhya3k** [comment]
@audhi3k 

Jayanth is testing for the issue mam

**Comment by Jayanth3KT** [comment]
Due to client un availability couldn't work on this.

CC: @audhi3k @shivakumar3k

**Comment by Jayanth3KT** [comment]
Completed

CC: @audhi3k @shivakumar3k
