### ISSUE TITLE
#TO has been created from 601 to N601 Location,while inwarding this TO its showing the error as base qty must be equal to zero

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1027]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 



![Image](https://github.com/3ktech/General/assets/140147250/13801299-7fd1-468e-bc21-59dc9b04a5a8)



![Image](https://github.com/3ktech/General/assets/140147250/65be07d8-c24a-4838-9de3-afe68ce94a35)

**Comment by TabrejAlam3K** [comment]
I have done the session with the Client and take Showcase Recording.

CC : @audhi3k @rohit3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam - As per our discussion yesterday with the client they want to create new Copy Production Environment because in Staging lot of dummy data is available.

For easily debug the production error in the Copy Production Company. Can you please suggest how we can do this?

CC : @Sarikab1222 @rohit3k

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/be87dddd-0c11-444c-a958-6f4bc3c84383)

**Comment by TabrejAlam3K** [comment]
No any response receive from the client end.

CC : @Shasthara @audhi3k

**Comment by TabrejAlam3K** [comment]
Same scenarion required in the Staging Environment. We are waiting for New Staging Environment.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
As per our discussion today Mr. Rewat will check with their internal team and let us know.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
User will post the Document RR-TO-0000047762 and confirm.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @Prakash3K - You can close this ticket from the support portal, I am closing this from the Git

**Total Effort Hours = 4 Hours**

![Image](https://github.com/3ktech/General/assets/116171982/4ec28135-9312-4de4-8a14-5281d663016a)

CC : @audhi3k @Shasthara
