### ISSUE TITLE
Issue Reported-post receive and post consume at UL Nav for job number OU-JWO2324-00310

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1029]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 

User ID: saran.kannan@urbanladder.com



![Image](https://github.com/3ktech/General/assets/140147250/f7eb1297-c223-422c-bd89-761784a4a707)



![Image](https://github.com/3ktech/General/assets/140147250/c28ed349-3629-4875-b0a2-f99f1890fc1e)



![Image](https://github.com/3ktech/General/assets/140147250/3a5f0275-183d-4f07-8788-c6c741610923)

**Comment by TabrejAlam3K** [comment]
Issue has been resolved while screen sharing session with Mr. Rewat and Ms. Subha

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - You can close this ticket from the support portal.

**Total effort hours = 1 Hours**

CC : @audhi3k  @Shasthara
