### ISSUE TITLE
RTB/CRTB not updating the Records in LCMS Response Queue even the Document is Posted

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1031]

**Comment by TabrejAlam3K** [comment]
Hi Mr. Kartik D @3ktech and Mr. @rohit3k - I need to discuss on urgent basis.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Mr. @Prakash3K - Create the case on the Support portal

Contact Person - viswa.accounts@lakshmisri.com

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K When we can connect for this as i need to Debug the code in your presence. 
cc: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Mr. @rohit3k - You have any daught on the process what i have shown to you because i am accupied on some other activity i will not spend to much time on code review.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Old Ticket #973 - I am closing old ticket

Mr. @Prakash3K - you can close the old ticket they have placed new ticket for the same issues.

CC : @audhi3k @Shasthara

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K As Per Discussion With you i did the change please make the test cases and test the scenario if any issue persists, please reach out to me.
cc: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
**Rohit Comments**
 i believe you are aware what we have had discussed yesterday. Karthik D and Shasthara M, was also there in the meeting 
that we can Move the changes together, because All previous work have been moved into UAT For Testing. now these ticket are newly came for work so i did it.. but it is in same branch, so we have to complete #972 ticket first otherwise it will cause problem for us.
CC : @audhi3k @3ktech  @rohit3k

**Comment by TabrejAlam3K** [comment]
This will be deployed at the time of deploying the Git #972 

CC : @audhi3k @Shasthara

**Comment by rohit3k** [comment]
Hi. Mr. @TabrejAlam3K we were supposed to inspect this issue with user. but after some days it started creating Entry inside response Table.

cc: @audhi3k

**Comment by TabrejAlam3K** [comment]
Ok Mr. @rohit3k - Let me check the few live entries if it is working fine then, I will discuss with the client and close this ticket.
Cc : @audhi3k

**Comment by TabrejAlam3K** [comment]
As per the last session with the client it is working fine, For older entries Invoice Doc is available. I am closing this ticket form the Git.

Mr. @Prakash3K - You can close this from the support portal **Total Effort Hours = 3 Hrs**

CC : @audhi3k @Shasthara
