### ISSUE TITLE
Whether it is possible to Call the Create IRN button automatically while posting the Delhi Branch Invoice

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1033]

**Comment by TabrejAlam3K** [comment]
Hi Mr. Kartik D @3ktech and Mr. @rohit3k - I need to discuss on urgent basis.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Mr. @Prakash3K - Create the case on the Support portal

Contact Person - viswa.accounts@lakshmisri.com

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K Requirement has been done and deployed on UAT please check and confirm.
cc: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k 
Requirement - After posting the Sales Invoice and Sales Credit memo for Delhi Branch imdiatly **Create IRN** Button should be triggered for the related posted documents.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
@rohit3k - I have tested on few documents, It is not working.

CC : @audhi3k

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K as i have asked you test this on more document which Transaction Type will not be B2C Have you tested this.?
cc: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - I will check and confirm you.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k  - This need to be deployed on the Production Environemnt. I have done the session with the Client he said they can test only in the production.

Note : Please make sure previous functionality will be still remain.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Waiting for Client response on this.

**Comment by TabrejAlam3K** [comment]
**Rohit Comments**
 i believe you are aware what we have had discussed yesterday. Karthik D and Shasthara M, was also there in the meeting 
that we can Move the changes together, because All previous work have been moved into UAT For Testing. now these ticket are newly came for work so i did it.. but it is in same branch, so we have to complete #972 ticket first otherwise it will cause problem for us.
CC : @audhi3k @3ktech  @rohit3k

**Comment by TabrejAlam3K** [comment]
Changes has been deployed in the Productin Environemnt. Thanks Mr. @rohit3k and Ms. @sandhya3k your prompt response.

waiting for client confirmation.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Client confirmed for closure while screen sharing session.

Mr. @Prakash3K - You can close this issues form the support portal as well with **Total Time effort = 3.5 Hours** 

CC : @audhi3k @Shasthara
