### ISSUE TITLE
MDT - Description error

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#1034]

**Comment by niranjand22** [comment]
Connected with Mr Pavan.

The issue is.

When There are two purchase lines in PI with same value ,same dimesion and diffrenrt description. It is creating same gl entry for both with 1st line description.

**Comment by niranjand22** [comment]
@Prakash3K  CAN U PLS UPDATE CASE NO IN TITLE

**Comment by niranjand22** [comment]
u can close this case 2hr @Prakash3K  cc @audhi3k

**Comment by Jayanth3KT** [comment]
@niranjand22 this ticket is closed in case portal, hence its not closed in GIT now closing it. 

CC: @audhi3k @Shasthara
