### ISSUE TITLE
UL production issues

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1035]
OU-JWO2324-00239

**Comment by Prakash3K** [comment]
@TabrejAlam3K 



![Image](https://github.com/3ktech/General/assets/140147250/9df4a93a-0f5e-4782-8307-3b639a6f724c)

**Comment by TabrejAlam3K** [comment]
Issue - 2 NIN-968 - Once Mr. Rewat will come we can discuss and close it.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Analysis is in progress.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k - When we can connect on this?

**Comment by TabrejAlam3K** [comment]
**Resolution of NIN-968**
**Revaluation Journal**
- Inventory Value (Revalued) - Putting Current Value * 2 for First Line Item
- Inventory Value (Revalued) - Putting Current Value as 0 for Second Line Item
- Post
- Run - Adjust Cost Item Entries

**Item Journal**
- Negative Adjustment for Item and and select Applies-to Entry of second line Item.
- Run - Adjust Cost Item Entries

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - You can close this ticket from the support portal. I am closing from the Git.
My Effort Hours = 5.75
Mr. @Mahesh3ktech Share you effort hours.

![Image](https://github.com/3ktech/General/assets/116171982/17460b64-a04a-4963-a8f6-b0cbcacfbd99)

CC : @audhi3k @Sarikab1222
