### ISSUE TITLE
Disable the Manual LCMS Push Button for Non-Administrator Users

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1036]
Requirement - Need to Disable the below button.

Posted Sales Invoice - Send Invoice to LCMS
Posted Sales Credit Memo -Send Credit to LCMS

**Comment by TabrejAlam3K** [comment]
Mr. @Prakash3K - Create the support ticket and assign the case id for this.

Contact Person - viswa.accounts@lakshmisri.com

CC : @audhi3k @Shasthara

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K As per requirement changes has been done, please check and confirm.
cc: @audhi3k  @gsudarsan3k  @3ktech

**Comment by TabrejAlam3K** [comment]
Ok Mr. @rohit3k - Let me check and update you.

cc: @audhi3k @gsudarsan3k @3ktech

**Comment by TabrejAlam3K** [comment]
Yes Mr. @rohit3k - It is working as per the Client requirement.

cc: @audhi3k @gsudarsan3k @3ktech

**Comment by TabrejAlam3K** [comment]
Waiting for Client response on this.

**Comment by TabrejAlam3K** [comment]
**Rohit Comments**
 i believe you are aware what we have had discussed yesterday. Karthik D and Shasthara M, was also there in the meeting 
that we can Move the changes together, because All previous work have been moved into UAT For Testing. now these ticket are newly came for work so i did it.. but it is in same branch, so we have to complete #972 ticket first otherwise it will cause problem for us.
CC : @audhi3k @3ktech  @rohit3k

**Comment by TabrejAlam3K** [comment]
Changes has been deployed in the Productin Environemnt. Thanks Mr. @rohit3k and Ms. @sandhya3k your prompt response.

waiting for client confirmation.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Client confirmed for closure while screen sharing session.

Mr. @Prakash3K - You can close this issues form the support portal as well with **Total Time effort = 3.5 Hours** 

CC : @audhi3k @Shasthara
