### ISSUE TITLE
Help Required: TDS Deduction

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1039]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/e0c999f5-f3f7-4b80-974e-a197048819d8)

**Comment by shivakumar3k** [comment]
Issue - TDS not getting calculated for Vendor Purchase Invoices for Vendor code V0001.

Solution - Assessee code not selected in Vendor master.
after selecting the assessee code in Vendor master TDS getting calculated as expected.
