### ISSUE TITLE
Restrict reversing transaction of posted entries

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1040]

**Comment by Prakash3K** [comment]
@Ejaz3KT 



![Image](https://github.com/3ktech/General/assets/140147250/cd42edc4-04a4-4cc6-b817-0fb3b29a80b2)



![Image](https://github.com/3ktech/General/assets/140147250/f242d7ad-6ff2-4271-9c47-479644f44e72)

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Please tell me the efforts hours you require for this task

CC: @audhi3k

**Comment by sruthi1017** [comment]
hi @Ejaz3KT 3-4 hrs

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I`ve tested this task the restrictions is working for some transactions and not working for some transactions Please check and update 

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Since we have waited for the budget approval for the past two weeks we are not getting any approval from the client so I am closing this ticket. 

CC: @audhi3k @sruthi1017

**Comment by Ejaz3KT** [comment]
Hi @audhi3k madam I've connected with Mr. Murali for getting the approval he is saying the hours which we have quoted is high try reduce the effort hours 

CC: @sruthi1017

**Comment by Ejaz3KT** [comment]
We have waited quite a long time for the budget approval but we are not get any response from the client. As of now we are closing this ticket as No response in future client approve the effort hours we will create new ticket

Mr. @Jayanth3KT Please close this ticket in support portal as No response

CC: @audhi3k @sruthi1017
