### ISSUE TITLE
Modification in Posted sales invoice report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#1041]
We have make the changes in the report need to showcase to the client and get confirmation to deploy in the production

CC: @audhi3k

**Comment by audhi3k** [comment]
Kindly deploy by 11th Dec 2023

**Comment by Ejaz3KT** [comment]
The issue has been resolved and the report is working fine so I am going to close this ticket

CC: @audhi3k @sruthi1017

**Comment by Ejaz3KT** [comment]
Mr. @Prakash3K Please close this ticket in the support portal with total effort = 4hours

CC: @audhi3k
