### ISSUE TITLE
RTB/CRTBs already posted in BC but is not getting updated in Snow fig

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1042]

**Comment by TabrejAlam3K** [comment]
[RTB CRTB Issues.xlsx](https://github.com/3ktech/General/files/13514741/RTB.CRTB.Issues.xlsx)

**Comment by TabrejAlam3K** [comment]
Analysis part i have completed, Let me connect with Client and update the new comments.

**Comment by audhi3k** [comment]
Mr @TabrejAlam3K what's the status

**Comment by TabrejAlam3K** [comment]
I have done the analysis part and already discussed with Mr. @3ktech and Mr. @rohit3k 

Issue - Invoice is posted but API Response Queue not generated with Invoice Doc but On the Azure Portal Invoice doc is available without API Response Queue lines.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Mr. @3ktech and Mr. @rohit3k - Please provide the solution for this as discussed.

@audhi3k @Shasthara

**Comment by audhi3k** [comment]
Mr @rohit3k kindly check and update the status

**Comment by audhi3k** [comment]
Mr @TabrejAlam3K can you connect with Mr @3ktech on this, as Mr @rohit3k not available today

**Comment by TabrejAlam3K** [comment]
Changes has been Deployed into the Production.

CC : @audhi3k @Sarikab1222 @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam - We can close this ticket.

**Comment by TabrejAlam3K** [comment]
We can close this ticket because from the snowfig side they have updated the Historical Data manually at snowfig side.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Closing this ticket

**Comment by Prakash3K** [comment]
Hi @TabrejAlam3K, can i know the total effort hours for closure 


CC: @audhi3k @Shasthara
