### ISSUE TITLE
Issue in customer aging report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#1043]
Hi @Mahesh3ktech The requirement is to match the customer card balance LCY amount in customer summary aging report and please tell me what are the efforts hours you requires for this task.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Since we have waited for the budget approval from past two weeks but we are not getting any approval from the client so I am closing this ticket. 

CC: @audhi3k

**Comment by audhi3k** [comment]
Hope you have conveyed to the client

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech Please update the status of this task

CC: @audhi3k

**Comment by Mahesh3ktech** [comment]
hi @Ejaz3KT Report is working fine, kindly check and update.

CC: @audhi3k @gsudarsan3k

**Comment by Ejaz3KT** [comment]
Ok @Mahesh3ktech

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam we have to do the below-mentioned changes
1. Rename the UNIT Column caption to Job No./Description and replace with job details column
2. Rename the Customer summary aging simp to Customer summary aging Desc for both RDL repot & excel report

**Comment by Ejaz3KT** [comment]
UAT has been done with Murali sir waiting for the confirmation to deploy the changes in the production

CC: @audhi3k @sandhya3k

**Comment by Ejaz3KT** [comment]
Deployment Has been done in the production environment we can close this ticket Mr. @Prakash3K you can close this ticket in the support portal with zero effort hours

CC: @audhi3k @Mahesh3ktech @sandhya3k
