### ISSUE TITLE
PI Description Error in GL Entries when Defereal schedule is tagged in Merit India CAS-01719-S5F7Q8

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#1044]

**Comment by niranjand22** [comment]
Hi @rohit3k , we have new requirements. The client wants Default or deferral schedule description to be printed in GL Entries  for the Expense Lines(which do not having GST)

**Comment by niranjand22** [comment]
![Image](https://github.com/3ktech/General/assets/116243958/56afe29f-30ba-4daf-867b-3679dcb8c62d)

**Comment by niranjand22** [comment]
[Description (1).xlsx](https://github.com/3ktech/General/files/13611952/Description.1.xlsx)

**Comment by audhi3k** [comment]
Mr @niranjand22 we can connect tomorrow

**Comment by niranjand22** [comment]
![Image](https://github.com/3ktech/General/assets/116243958/17cc2552-e40a-448b-88b2-b7b5b34e10fc)
