### ISSUE TITLE
Serial no is not linked with the Order

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1045]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 


![Image](https://github.com/3ktech/General/assets/140147250/56d54af7-ac99-43e4-99b8-af5987230491)

**Comment by TabrejAlam3K** [comment]
Requirement - Seller Serial No. Info Linked Web Order No. and Linked Web Order Line No. not updated.

**Comment by TabrejAlam3K** [comment]
When the Sales Order as Mark Fullfillment then Seller Serial No. Info page should be updated with the below fiels value.
1. Linked Web Order No. 
2. Linked Web Order Line No.

Manual Activity - When the user is clicking on Un Reserved button and Replan Barcode that time Seller Serial No. Info page get updated the above two field value.

**Comment by TabrejAlam3K** [comment]
Currently they have no such case to show case, Once come agin we will connect and showcase.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Mr. @Mahesh3ktech - Reference Date which i have received from the Client Users.

[Seller Serial No. Info NAV_NAVUSER 2023-12-12T05_58_35.xlsx](https://github.com/3ktech/General/files/13668375/Seller.Serial.No.Info.NAV_NAVUSER.2023-12-12T05_58_35.xlsx)

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - I got the 10 Hrs Approval on this, You can start working on this and get it completed by tomorrow before lunch.

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Wheter it was completed?

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Due to not responded by the Client side we are going to close the tickets.

Mr. @Prakash3K - **Total effort hours = 3 Hours**

CC : @audhi3k
