### ISSUE TITLE
Proforma Invoice issue

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1046]

**Comment by Prakash3K** [comment]
@Jayanth3KT and @Tushargupta3K 



![Image](https://github.com/3ktech/General/assets/140147250/b4f857dd-60e1-486d-b122-d14308bbae97)

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/47010bf6-e6e5-41c0-bc66-5d22ee453e8e)
