### ISSUE TITLE
Reg : BDR posting error

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1047]

**Comment by Prakash3K** [comment]
![Image](https://github.com/3ktech/General/assets/140147250/89683f5a-1f7a-4448-a6d9-fe7eb8e9351f)

CC: @Tushargupta3K

**Comment by audhi3k** [comment]
When they are getting this error.  What's the status

**Comment by Prakash3K** [comment]
This ticket is resolved during the call, so I'm closing this ticket in git.


CC: @audhi3k @Tushargupta3K
