### ISSUE TITLE
Contra Voucher Error

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#105]
While assigning the Dimension value the facing the error.

![Image](https://user-images.githubusercontent.com/116171982/217773591-df769532-176e-4f11-a3ff-377d717e60e5.png)

**Comment by TabrejAlam3K** [comment]
@sandhya3k  - See the attached error and resolved it.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k  - As per our discussion please update on.

**Comment by TabrejAlam3K** [comment]
Error Resolved

I have tested this now it's working fine. I am closing this ticket.

**Comment by sandhya3k** [comment]
ok @TabrejAlam3K
