### ISSUE TITLE
GST printing Issue in voucher register Cust report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#1050]
Hi @sandhya3k madam Please find the requirement mapping file for this task

[Voucher register report mapping.txt](https://github.com/3ktech/General/files/13611024/Voucher.register.report.mapping.txt)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
We have tried many ways to fix the issue in the reports but We are not getting any proper solution to fix the issue

CC: @audhi3k @sandhya3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

Can u replicate the scenario in stagingsadbox?

**Comment by Ejaz3KT** [comment]
Ok @sandhya3k I`ll replicate the same entries in sand box

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k madam Today at any cost we need to fix this issue 

CC: @audhi3k

**Comment by audhi3k** [comment]
hi... is any support required

**Comment by sandhya3k** [comment]
yes mam. i asked Sudarshan for help.

**Comment by audhi3k** [comment]
Mr @gsudarsan3k can you help and share the timeline to deliver it - Ms @sandhya3k

**Comment by gsudarsan3k** [comment]
Hi @Ejaz3KT  this report is completed as per the requirement. please test and get the confirmation from the client. let us know if any 

CC : @audhi3k  @sandhya3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k I`ve tested the report it is fine need to showcase to the client and get confirmation

CC: @audhi3k @gsudarsan3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k madam The UAT session has been done with the client and the client gave us the confirmation to deploy this into the production 

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The issue has been resolved we can close the ticket

CC: @audhi3k @sandhya3k
