### ISSUE TITLE
Restrict the User Setup Page based on Admin Permission

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1053]

**Comment by TabrejAlam3K** [comment]
Requirement - User Setup page should be accessable for admin users only.

Mr. @3ktech and Mr. @gsudarsan3k - Please align one resource on this task.

CC : @audhi3k @Shasthara

**Comment by Prakash3K** [comment]
Hi @TabrejAlam3K, can I know the contact person for this ticket.

**Comment by TabrejAlam3K** [comment]
Requirement - User Setup page should be accessable for admin users only.

Mr. @3ktech and Mr. @gsudarsan3k - Please align one resource on this task.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Once it will be completed please let me know.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
I have done the testing & uat with the client, it is working fine in the UAT Environment. waiting for customer confirmation.

CC : @audhi3k @Sarikab1222 @Shasthara

**Comment by TabrejAlam3K** [comment]
Tested in the Production Environment working fine,
Mr. @Prakash3K - You can close this ticket form the support portal **Total Consumed Hours = 4 Hrs** I am closing from the Git.

![Image](https://github.com/3ktech/General/assets/116171982/0e1d769e-6b5b-4f7c-b04f-181933be834b)

CC : @audhi3k @Sarikab1222
