### ISSUE TITLE
Unable to post Export sales invoice

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1054]

**Comment by Prakash3K** [comment]
@Ejaz3KT 


![Image](https://github.com/3ktech/General/assets/140147250/76f1caf7-01e4-4b6e-aeb3-f6f6f4a9bfb0)



![Image](https://github.com/3ktech/General/assets/140147250/2616b326-32e3-49cc-917f-4fae7e0d1085)

**Comment by Ejaz3KT** [comment]
I am looking into this issue
________________________________

**Comment by Ejaz3KT** [comment]
Hi team solution has been provided to the client we can close this ticket

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
HI @Prakash3K The issue has been resolved you can close this ticket in the support portal with 2 hours of effort

CC: @audhi3k @sandhya3k
