### ISSUE TITLE
Cash Receipt Voucher Error

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#106]
While assigning the dimension value for update the description.

![Image](https://user-images.githubusercontent.com/116171982/217773971-482f95a9-c05a-41d9-aa95-a39ce13e792b.png)

**Comment by TabrejAlam3K** [comment]
@sandhya3k - See the attached error and resolved it.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k  - As per our discussion please update on.

**Comment by TabrejAlam3K** [comment]
Error Resolved

I have tested it is working fine.

**Comment by sandhya3k** [comment]
ok @TabrejAlam3K
