### ISSUE TITLE
Add New lookup field name as  ARN/RFN no. in company information

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#1061]
Fitchner Requirement is to have one lookup field in company information where they can create the ARN no. and that field information we need to map in the sales invoice report 

CC: @audhi3k @gsudarsan3k

**Comment by Ejaz3KT** [comment]
Hi Mr. @Prakash3K Please create the support ticket and assign the case I`d for this ticket

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @johnbosco3K can you please update the status of this ticket

CC @audhi3k

**Comment by johnbosco3K** [comment]
Hi @Ejaz3KT,
I did not get Fichtner repository till so i informed karthik D.
 once i get it and will let you know the status.

CC @audhi3k

**Comment by Ejaz3KT** [comment]
Ok @johnbosco3K

**Comment by Ejaz3KT** [comment]
Hi @johnbosco3K I`ve tested the functionality it is working fine please publish the same changes in SANDBOXPRODNOV24 So I can show case the client and get approval

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
UAT has been completed waiting for the confirmation to deploy in the production

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
We are not able to deploy the changes in the Production company because it has not upgraded to the new version we are waiting for confirmation from the client side to upgrade to the new version

CC: @audhi3k @johnbosco3K @sandhya3k

**Comment by Ejaz3KT** [comment]
The deployment has been done waiting fore the client confirmation for closing the ticket

CC: @audhi3k @johnbosco3K

**Comment by Ejaz3KT** [comment]
@Prakash3K We have deployed the changes into the production client and also confirmed it is working fine so we can close this ticket
with the effort hours of 4 hours 

CC: @audhi3k @johnbosco3K
