### ISSUE TITLE
IRN Generation and API call for foreign Invoices

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1065]
Dear Sir,

Please find attached the error for generation of IRN and API call not getting generated for foreign currency invoices. the other snap available in the trailing mail where IRN not generated.

Below are some cases listed for today’s invoicing. Also please note that while attempting any changes we should not make other posting such as periodical collection entry and collection posting erroneous. 

**RTB number                       Invoice No.** 
0000883073                 LKS01-2324-02720
0000883042                 LKS01-2324-02719
0000883073                 LKS01-2324-02720
0000883040                 LKS01-2324-02717

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech @gsudarsan3k - Please align the resource for this ticket.

CC : @audhi3k

**Comment by Prakash3K** [comment]
Hi @TabrejAlam3K, can i know the contact person for this ticket.

CC: @Shasthara

**Comment by TabrejAlam3K** [comment]
bhupendra.bhakuni@lakshmisri.com and viswa.accounts@lakshmisri.com

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Client confirmed for deployment into the Production. Please plan for deployment.

CC : @audhi3k  @Shasthara @Sarikab1222

**Comment by TabrejAlam3K** [comment]
Changes has been Deployed into the Production.

CC : @audhi3k @Sarikab1222 @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam - We can close this ticket.

**Comment by TabrejAlam3K** [comment]
Whiel Generating the IRN error was coming. Screen Shot attached.

![Image](https://github.com/3ktech/General/assets/116171982/02ec8def-d315-4673-81a2-bb5fce74c54a)

 CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - As discussed, You will publish the latest changes by today after 9:30PM.

CC : @audhi3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

Now, published it into UAT

**Comment by TabrejAlam3K** [comment]
Fixes has been done in the production as well, We have tested the data in the Production Environmement.
1. Posted Sales Invoice - Create IRN Button
2. API Trans Log - While processing the UpdateDoc.

Mr. @Prakash3K you can close this ticket from the Support portal as well.

CC : @audhi3k
