### ISSUE TITLE
Job Task Group Validation

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1069]

**Comment by Prakash3K** [comment]
Hi @gsudarsan3k sir, Kindly assign technical person to this ticket.


CC: @audhi3k @3ktech

**Comment by Jayanth3KT** [comment]
Hi @johnbosco3K Can we connect regarding this ticket.

**Comment by Jayanth3KT** [comment]
Completed

CC: @audhi3k @Tushargupta3K
