### ISSUE TITLE
Currency Restatement Summary in BC

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#107]
See the attached text of mail caption.

Hi Audhi,

Currently we are doing currency restatement every month end in BC and it gets directly posted to resp. ledgers. 

But before posting, we need this to be loaded in general journals and we want to post it once confirmed with our computation checks. For this our main requirement is, "we need the summary of  Currency restatement calculation done by BC".

Pls do the needful on priority.

**Comment by audhi3k** [comment]
Training provided
