### ISSUE TITLE
TDS calculating wrongly for this entry

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1071]

**Comment by Prakash3K** [comment]
@niranjand22 



![Image](https://github.com/3ktech/General/assets/140147250/36e52afd-c7a3-4b99-969f-c6c755e87e97)



![Image](https://github.com/3ktech/General/assets/140147250/df963187-35b4-4516-aaab-63deaba753b0)

**Comment by shivakumar3k** [comment]
@Prakash3K Issue has be resolved and Received confirmation for Mr. Suresh sir regarding the same.
Please send a Mail to Suresh for confirmation.
