### ISSUE TITLE
LKS App Version Issues

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1074]
![Image](https://github.com/3ktech/General/assets/116171982/0675302d-5cef-4be8-a0c6-9af65f5bde32)

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Please highlight the issues which you are facing.

CC : @audhi3k @Sarikab1222 @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Can we close this ticket?

**Comment by Prakash3K** [comment]
Hi @TabrejAlam3K Can i create this ticket in Support portal?

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k wherever it is required, Please Confirm.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Can i close this ticket?

CC : @audhi3k

**Comment by sandhya3k** [comment]
yes

**Comment by TabrejAlam3K** [comment]
Closed as confirmed by the Ms. @sandhya3k 

CC : @audhi3k
