### ISSUE TITLE
Sales invoice templates - amend telephone number

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1076]

**Comment by Prakash3K** [comment]
Hi @niranjand22 sir,



![Image](https://github.com/3ktech/General/assets/140147250/31044b3e-7bdd-4f2b-a63d-0bfa4f7e5a09)

**Comment by niranjand22** [comment]
SI-PE001552

**Comment by sandhya3k** [comment]
can u share the report id ?

**Comment by niranjand22** [comment]
we have done the requested customisation. waitingfor cust cofirmation for closure

**Comment by niranjand22** [comment]
hi @Prakash3K  close this case with 4 hr
