### ISSUE TITLE
ECOMM-1539 : SwiftLink | BC | Design Documentation of all the APIs and the Job Queues implemented.

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1077]

**Comment by Prakash3K** [comment]
@Padma2717 


![Image](https://github.com/3ktech/General/assets/140147250/39b1d130-e315-420e-a80c-1f57d3bde5f1)



[SwiftLinkBC_DesignDocument (1).docx](https://github.com/3ktech/General/files/13684975/SwiftLinkBC_DesignDocument.1.docx)

**Comment by TabrejAlam3K** [comment]
Hi @Padma2717 - Please provde the estimated and approved hours for this ticket.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We are closing this ticket becasue this is already close over support portal.

CC : @audhi3k
