### ISSUE TITLE
7.	If the Vendor have PAN No. but they have not filled the ITR that time OG Healthcare deducting the 20% TDS Amount, Where we can setup this in the BC.

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1080]

**Comment by johnbosco3K** [comment]
![Image](https://github.com/3ktech/General/assets/153084240/848315b1-b832-43db-b6b5-abe2dfd38fae)

**Comment by TabrejAlam3K** [comment]
Functionality Discuss with Mr. @johnbosco3K He will implement the things and let us know.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Setups we have tested and showcase
1. Vendor ITR List page through the Vendor Card.
 - Finacial From
 - Finacial To
 - TDS Section

**Comment by TabrejAlam3K** [comment]
Working Fine

[Testcase 1080.xlsx](https://github.com/3ktech/General/files/13786013/Testcase.1080.xlsx)

**Comment by TabrejAlam3K** [comment]
Closing as Completed.
