### ISSUE TITLE
Bank Receipt Voucher - Multiple Interdivision entries created

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1081]

**Comment by Prakash3K** [comment]
![Image](https://github.com/3ktech/General/assets/140147250/648b8c2f-c890-4a26-b050-21dce988352a)



![Image](https://github.com/3ktech/General/assets/140147250/b512ce4b-de14-4243-9edf-6a1d3a0dbb85)

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k We have to republish the extension in production company to fix this issue

CC: @audhi3k @gsudarsan3k

**Comment by Ejaz3KT** [comment]
The issue has been resolved and showcased to the client waiting for the confirmation

CC: @audhi3k @sandhya3k

**Comment by Ejaz3KT** [comment]
@Prakash3K The issue has been resolved we can close this ticket with a total effort of 3 hours

CC: @audhi3k @sandhya3k
