### ISSUE TITLE
Facing an error while creating new Bank Account & below is the screenshot

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1084]
![Image](https://github.com/3ktech/General/assets/116171982/d447d701-a7eb-4e8b-b104-f6b05837e5df)

**Comment by TabrejAlam3K** [comment]
Mr. @Prakash3K and Mr. @Jayanth3KT - Create a support ticket and assigned it to me.

Contact Person : dikshant.jain@vridhihomefinance.com

CC : @audhi3k

**Comment by Jayanth3KT** [comment]
@TabrejAlam3K  Ticket created

**Comment by TabrejAlam3K** [comment]
Mr. @Jayanth3KT - Close this ticket as complted client confirmed.

**Total Effort Hours = .5 Hours**

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
Close as completed.
