### ISSUE TITLE
SyncForum Master Synching Issues

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1088]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 


![Image](https://github.com/3ktech/General/assets/140147250/e883de49-7363-42c5-b16d-c19b132dd6b1)

**Comment by TabrejAlam3K** [comment]
We have sended the Session required mail as per the session it will be actionable.

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
Summury of the Discussion
1. I will provide verify the data and revert back as per the data which i will received form the client end.
2. We have WriteOffAmount Entries at snowfig end but the related RTB's API Trans Log are not available in the BC. How we can resolved this case - Kartik D will suggest how we can do that.
3. BC need to send few additional field value to Snowfig called - Payment Date & Times
4. LKS will take care of this, If found anything they will highlight.

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Tabrej/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Tabrej/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


RTB   No. | BC Invoice No. | BC Response   Queue | Snowfig Status
-- | -- | -- | --
0000848651 | LKS02-2223-01867 | Success |  
0000850774 | LKS01-2223-02246 | Success |  
0000856192 | LKS02-2223-01387 | Success |  
0000856697 | LKS01-2223-01665 | Success |  
0000863638 | LKS11-2223-00076 | Success |  
0000863053 | LKS11-2223-00058 | Success |  
0000860650 | LKS11-2122-00381 | Success |  
0000868906 | LKS11-2122-00298 | Success |  



</body>

</html>

**Comment by TabrejAlam3K** [comment]
As discussed with Mr. Dipesh, he said currently there are no synching issues, If come in feature they will raise the ticket seprately.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
We will disucuss with the client for closure and close the ticket by today.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/c05e740a-fc1c-492e-81ce-12a1ee483b3e)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Mr. @Prakash3K - Close this ticket from the support portal. I am closing form the git.

CC : @audhi3k @Shasthara
