### ISSUE TITLE
Formulate Vridhi COA into BC format.

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#109]

**Comment by niranjand22** [comment]
Created the COA in BC format. We will finalise  in upcoming week.

**Comment by audhi3k** [comment]
The Chart of accounts seems to be fine except the points which we have discussed i.e., relating to comments on the GL Accounts.

We will connect on Monday.

Also create a new company in the Vridhi Sandbox and update the following:
1.	Run Tax Engine
2.	Create Configuration package with the related tables relating to Finance, Purchase, GST and TDS
3.	Import Chart of Accounts
4.	Import No. of Series and No. Series Lines
5.	Voucher Accounts

**Comment by niranjand22** [comment]
New Company is Created and also ran the Tax Engine .

**Comment by niranjand22** [comment]
2. Chart of accounts imported

**Comment by niranjand22** [comment]
CREATED VARIOUS CONFIG PACKAGE. NEED TO DISCUSS MORE WITH MRS AUDHI ON THIS

**Comment by audhi3k** [comment]
@niranjand22 ok, we will discuss this tomorrow

**Comment by niranjand22** [comment]
Standard No. Series has been added .

**Comment by niranjand22** [comment]
configuration package created

**Comment by niranjand22** [comment]
new No Series had been reimported. Sales invoice and posted sales invoice no. is remaining..will check with LMS system and configure it

**Comment by audhi3k** [comment]
@niranjand22, we will close this ticket on tomorrow get the confirmation from Mr Rajesh

**Comment by audhi3k** [comment]
@niranjand22, get confirmation

**Comment by audhi3k** [comment]
UAT and training is progress, so closing this ticket as any issues, will be resolved in UAT
