### ISSUE TITLE
Job work order in purchase lines

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1095]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 


![Image](https://github.com/3ktech/General/assets/140147250/24e31d2e-a744-4339-b872-8803e1bb459a)

**Comment by TabrejAlam3K** [comment]
UAT Done with the Client, He will confirm for deployment after review the Changes.

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
Due to not Response by the client side closing this ticket.

@Prakash3K you can close this ticket from the support portal as well **Total Effort Hours = 1 Hrs**

CC : @audhi3k @Shasthara
