### ISSUE TITLE
Status field should be add in vouchers

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#1099]
The fitchner team requirement is to have one status field in the lines of vouchers where user can easily know which is approved or pending for approval after sending the document for approval

CC: @audhi3k @sandhya3k @gsudarsan3k

**Comment by sandhya3k** [comment]
can we connect for above issue? @Ejaz3KT

**Comment by Ejaz3KT** [comment]
To do this customization we require 10 hours of time 
1. Analyzing  == 1 hours
2. Development and design == 6 hours
3. Testing and UAT == 3 hours

I need to connect with the client to get the approval for the effort hours we required to fulfill the requirement once we got the approval we can start the work

CC: @audhi3k @sandhya3k

**Comment by Ejaz3KT** [comment]
We required 10 hours to do this customization and I`ve conveyed the same to Mr. Murali and waiting for the budget approval

CC: @audhi3k @sandhya3k

**Comment by Ejaz3KT** [comment]
There is no response from the client for budget approval. we have end mail also but no response we get. As of now, we are closing this ticket as No response in the future client approves the effort hours we will create a new ticket

Mr. @Jayanth3KT Please close this ticket in the support portal as No response

CC: @audhi3k @sandhya3k
