### ISSUE TITLE
Master upload

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#110]
In customer card wrong GST registration no or state
DRD068
DRG084
DRG098
DRG113
DRM118
DRS250
DRS279
DRU028
DRJ047

Ship-to Add Need to correct address, gst no and state code for following customer
DRI067
DRU024
DRS250
IC000
DRU028

**Comment by Amar-3KT** [comment]
Imported:-
Sales & Receivable------Imported without No series(CUST,PRP,Credit MAS)
purchase & payable ----Imported without no series-VENDOR,P-RCPT
Ship to code

**Comment by audhi3k** [comment]
@Amar-3KT, update pending masters

**Comment by Amar-3KT** [comment]
TDS posting setup, Voucher account configuration and some dimensions and dimension value.

**Comment by audhi3k** [comment]
All masters and setups are completed, except Dimensions

**Comment by Amar-3KT** [comment]
Mail sent to Mr. Muthu regarding Dimensions but not received any reply

**Comment by audhi3k** [comment]
@Amar-3KT , send mail to Mr Singaravel for highlighting Dimension is pending

**Comment by Amar-3KT** [comment]
Mail has been sent to fichtner team
