### ISSUE TITLE
ORD-13385-L3T3L7

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1100]

**Comment by Prakash3K** [comment]
@niranjand22 


![Image](https://github.com/3ktech/General/assets/140147250/12c7a62c-94dd-49de-97fb-81833c7ab3bb)

**Comment by niranjand22** [comment]
hi @rohit3k ..the 
have this issue again

**Comment by niranjand22** [comment]
hi @Prakash3K  close this case with 14.5 hrs
