### ISSUE TITLE
Credit Memo Mandatory field

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1105]

**Comment by Prakash3K** [comment]
@Jayanth3KT 


![Image](https://github.com/3ktech/General/assets/140147250/99f1896c-de3b-441b-8f03-2c218e173965)



![Image](https://github.com/3ktech/General/assets/140147250/30690172-ed20-4e9b-9611-a5eaaa42dba9)

CC: @audhi3k

**Comment by Jayanth3KT** [comment]
For particular purchase invoice and particular sales credit memo is not created so qty is not taking hence client will confirm and proceeds with that.

CC: @audhi3k @shivakumar3k

**Comment by Jayanth3KT** [comment]
Completed
