### ISSUE TITLE
New Report Required -PO  GRN Bill Tracker

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1109]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/c6b843d9-658e-465a-9622-23a3dfec211a)



[New Microsoft Excel Worksheet.xlsx](https://github.com/3ktech/General/files/13771472/New.Microsoft.Excel.Worksheet.xlsx)

**Comment by Tushargupta3K** [comment]
@rohit3k @Manoj01021999 , as discussed the task related to adding field will be done by Rohit and task related to Excel report will be done by manoj.
Please confirm the tech efforts.

CC: @Prakash3K

**Comment by Jayanth3KT** [comment]
Hi @gsudarsan3k sir completed UAT with client & they also requierd addition flow coloums 

1, PO status 
2. Item No.
3. Item discription.

CC; @audhi3k @Tushargupta3K

**Comment by Jayanth3KT** [comment]
AS all requirement points completed wei'll be closing this ticket & considering new ticket for additional pionts.

CC; @audhi3k @gsudarsan3k @Tushargupta3K
