### ISSUE TITLE
E-Invoice Integration

### ISSUE THREAD

**Issue by panduc** [3ktech/General#113]

**Comment by 3ktech** [comment]
Authentication is done.
IRN creation for Posted Sales Invoice is developed
IRN creation for Posted Creditmemo is pending

**Comment by 3ktech** [comment]
There is an issue with the latest UAT credentials. The issue description has been forwarded to GST portal support provider

**Comment by panduc** [comment]
Working on Invoice testing with the New URL.  getting below error and checking the issue.

![Image](https://user-images.githubusercontent.com/110709312/219545080-0acb1124-294a-44e7-a5d7-8e38dffbf41d.png)

**Comment by audhi3k** [comment]
@TabrejAlam3K, kindly provide support and testing for eInvoicing

**Comment by TabrejAlam3K** [comment]
@audhi3k - Ok Mam,

**Comment by panduc** [comment]
@TabrejAlam3K  I'm not able to identify Posted Sales Invoice with GST after April 01 2021. Please create posted sales Invoice which should have GST Amount in NAV2016 and BC LKS Company. so that i will resume E-Invoice integration testing.

**Comment by TabrejAlam3K** [comment]
@panduc - GST Ledger Entries is available in the below company, but GST Amount is not there.

Company Name : **INSTITUTE OF BUSINESS LAWS**

![Image](https://user-images.githubusercontent.com/116171982/220094124-952b3576-f25b-413a-b2e3-b96127771039.png)

CC : @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K yes I know. as I mentioned above  to test  E Invoice we need the posted document created after April 01 2021.

**Comment by TabrejAlam3K** [comment]
@panduc - GST Ledger Entries is available after 1st April 2021.

See the attached snapshot.


![Image](https://user-images.githubusercontent.com/116171982/220246805-473c991f-37a1-4d34-ae5b-f91270994065.png)


CC : @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K as per the GST registration no: "07AAAFL1585H1ZD" it is configured in LKS Company. so we should test 

we have lot of other condition to be considered for E-Invoicing testing.
1. Posted Sales Invoice: Posting Date>10 April 2021 and "Short Cut Dimension 1 Code" =1 and "Location Code" = New Delhi
2. NOT (Ship2Add."Transaction Type" in [Ship2Add."Transaction Type"::B2C] --> Link Sales Invoice Header."Ship to Code" & "Sell-to Customer No." to Ship-to Address Table
3. Sales Invoice Header."IRN No."= ''
4. GST Registration No."Code" := 07AAAFL1585H1ZD.  

Company Name : INSTITUTE OF BUSINESS LAWS is not configured with GST No: 07AAAFL1585H1ZD no other configuration exists in NAV2016 and BC. Do you still suggests to enable them?
If so we have to enable setup in Company info P A N, GST Registration No and State for E-Invoice GST Reg No.

After all the analysis my point of view GST setup exists in LKS company but no GST invoice exists and in INSTITUTE OF BUSINESS LAWS company GST invoice Exists but no setup for E-invoice . i think they are not using E-Invoice integration. Could you please verify?

CC: @audhi3k

**Comment by audhi3k** [comment]
@panduc, as discussed yesterday Mr Tabrej will get the Document No. for which they have already generated EInvoice and will be replicate a new document with the document received

**Comment by audhi3k** [comment]
@TabrejAlam3K, do the following:
1. Check list of posted sales invoice header with IRN No. <> <blank>
2. Get the document no. for which EInvoice is generated by LKS team in NAV2016 for the month of September.
3. Get the pdf copy of Sales Invoice for the same document
4. Based on point 1 or point 2, create a new sales invoice replicating the document - share this document no to Mr Pandu for testing purposes

**Comment by TabrejAlam3K** [comment]
List of Posted Sales Invoice No. received which have already IRN No. generated.
1. LKS01-2223-01879
2. LKS01-2223-01880
3. LKS01-2223-01792
4. LKS01-2223-01793

Also received pdf copy

**Comment by audhi3k** [comment]
Ok, @TabrejAlam3K create new document similar to the document received and share the new document nos. to Mr Pandu

**Comment by TabrejAlam3K** [comment]
@panduc - See the below Sales Invoice Pre Document list

1. -RTB-1415-00001
2. -RTB-1415-00002
3. -RTB-1415-00003
4. -RTB-1415-00004

CC : @audhi3k

**Comment by audhi3k** [comment]
@panduc , kindly check the document and highlight if any support required from us

**Comment by TabrejAlam3K** [comment]
As per our discussion with Mr. Pandu he will update on after discussed with Mr. Kartik D

**Comment by panduc** [comment]
@TabrejAlam3K  Me and Tabrej created sample posted sales invoice in Nav2016 to test it. but we are getting timeout issue from GST portal for the UAT url(http://182.76.79.236:35001/EinvoiceTPApi-QA/authenticate). i've sent Email to vendor to resolve the issue.



![Image](https://user-images.githubusercontent.com/110709312/221456305-78a2f837-5124-4a74-aa85-6f151b5e3462.png)


CC: @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K we are able to send API request and receive API response successfully in NAV2016 and BC for Posted Sales Invoice.

Next Action Plan:
1. The Same fix apply to Sales credit Memo.
2. Response handling for Posted Sales invoice & Credit Memo.
3. QR Code management testing by reading from API Response file.

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
@panduc - When we can connect for testing.

**Comment by panduc** [comment]
@TabrejAlam3K  will let you know on completion of the remaining points.

**Comment by panduc** [comment]
API Response handling and QR Code management development and unit testing completed for Posted Sales Invoice.

Next action Plan:
apply the fixes to Posted sales Credit memo and unit testing. will be able to finalize the solution by 02 Mar 2023.

**Comment by panduc** [comment]
@TabrejAlam3K E-Invoice integration complete solution has been developed and completed the unit testing as well. Please start the functional testing.

Environment: UAT
Company: Lakshmi Kumaran & Sridharan

Posted Sales Invoice:  LKS01-2223-02352|LKS01-2223-02351
Posted Sales Credit Memo: CRN01-2223-00257|CRN01-2223-00258

Please Sync with me before you start the testing. I will explain the steps.

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
@panduc - As per our discussion let me test the E-Invoicing functionality first with different cases then will inform you.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@panduc @audhi3k 

I have tested E-Invoicing functionality on below documents.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



NAV16
--
Document Type | Invoice   Date | Invoice   No. | IRN   Status
New | 03-03-2023 | LKS01-2223-02355 | IRN Generated
New | 03-03-2023 | LKS01-2223-02356 | IRN Generated
Old | 24-02-2023 | LKS01-2223-02354 | IRN Generated
  |   |   |  
Business Central -   Invoice
Document Type | Invoice   Date | Invoice   No. | IRN   Status
Old | 21-10-2023 | LKS01-2223-02351 | IRN Generated
Old | 21-10-2023 | LKS01-2223-02352 | IRN Generated
New | 03-03-2023 | LKS01-2223-02355 | IRN Generated
New | 03-03-2023 | LKS01-2223-02356 | Error
  |   |   |  
Business Central -   Credit Memo
Document Type | Invoice   Date | Invoice   No. | IRN   Status
Old | 18-10-2022 | CRN01-2223-00257 | IRN Generated
Old | 18-10-2022 | CRN01-2223-00258 | IRN Generated



</body>

</html>

**Comment by panduc** [comment]
@TabrejAlam3K Thanks for the feedback. We are facing timeout issues with the portal. I've sent Email to concern team to resolve the issue. once the ULR/Portal is up I will resume to identify the root cause for issue you reported.

**Comment by TabrejAlam3K** [comment]
@panduc - Ok, once you get the response from the govt. portal we can sit and resolved the remaining things.

I am moving this into IN Progress

CC : @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K The issues has been fixed. Please check & confirm.

Note:
if you get Duplicate IRN. Please create new document and test.  sometimes it allows to create IRN for same document but sometimes it allows only once

**Comment by TabrejAlam3K** [comment]
@panduc - I have post the new document when i try to generate the IRN button is showing disabled.



![Image](https://user-images.githubusercontent.com/116171982/223092158-a02b918c-a8b6-4bc2-a8ed-88c754fa3827.png)

**Comment by panduc** [comment]
@TabrejAlam3K Please check if it is "Short Cut Dimension 1 Code" =1 

Copied from Trial post,
we have lot of other condition to be considered for E-Invoicing testing.

Posted Sales Invoice: Posting Date>10 April 2021 and "Short Cut Dimension 1 Code" =1 and "Location Code" = New Delhi
NOT (Ship2Add."Transaction Type" in [Ship2Add."Transaction Type"::B2C] --> Link Sales Invoice Header."Ship to Code" & "Sell-to Customer No." to Ship-to Address Table
Sales Invoice Header."IRN No."= ''
GST Registration No."Code" := 07AAAFL1585H1ZD.

**Comment by TabrejAlam3K** [comment]
@panduc - Tested with new posted documents and now it's working fine. I am moving this into the UAT.

**Comment by TabrejAlam3K** [comment]
@panduc - Need to Add the Custom Field on Ship-to Address Page **GST Reg No.**.
See the attached snapshot.

![Image](https://user-images.githubusercontent.com/116171982/225507881-908b7c38-7be2-4490-9864-f71e47b63daa.png)


CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Through screen sharing UAT Session is completed, Client will test the scenario internally and update on.

**Comment by audhi3k** [comment]
completed
