### ISSUE TITLE
TCS Setup Issue

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1133]

**Comment by Prakash3K** [comment]
@Jayanth3KT 


![Image](https://github.com/3ktech/General/assets/140147250/1867a18b-223b-4cc2-934d-0cd730dd1edb)

**Comment by TabrejAlam3K** [comment]
this has been cancled.
![Image](https://github.com/user-attachments/assets/7e12418e-4d94-432a-ac09-45c4450a5133)
