### ISSUE TITLE
Approval for re opening DOC

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1137]

**Comment by Jayanth3KT** [comment]
@sruthi1017  Kindly deploy the changes in live.

CC: @audhi3k @shivakumar3k

**Comment by sruthi1017** [comment]
Due to the server issue unable to deploy yesterday will try to deploy today.
CC: @audhi3k @Jayanth3KT

**Comment by Jayanth3KT** [comment]
Completed

CC: @audhi3k @shivakumar3k
