### ISSUE TITLE
BC Version upgradation

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#1138]
Hi @Prakash3K Please create this ticket in support portal and assign the case I`d

CC: @audhi3k @gsudarsan3k

**Comment by Ejaz3KT** [comment]
I`ve discuss with Mr. Murali sir regarding the Kuma vision he we confirm today about the upgradation 

CC: @audhi3k  @gsudarsan3k

**Comment by Ejaz3KT** [comment]
The Fitchner team is having an internal meeting with their management on  24th-Jan After that they are planning to update the production version this Thursday 25th Jan

CC: @audhi3k @gsudarsan3k

**Comment by Jayanth3KT** [comment]
@Ejaz3KT  can i know current status of this task.

**Comment by Ejaz3KT** [comment]
@Jayanth3KT The version has been upgraded we are waiting for the client confirmation to close the ticket

CC: @audhi3k
