### ISSUE TITLE
All the Voucher Testing

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#114]
1. Bank Receipt Voucher
2. Bank Payment Voucher
3. Cash Receipt Voucher
4. Cash Payment Voucher
5. Contra Voucher

**Comment by TabrejAlam3K** [comment]
@3ktech @audhi3k - Found some error in NAV16

NAV16 is not working when I try to run the Instances then we found some error see the attached snapshot. 

![Image](https://user-images.githubusercontent.com/116171982/219305836-d4d9713a-6ebb-446b-a6ff-5b982fed96a6.png)

**Comment by TabrejAlam3K** [comment]
1. **Bank Receipt Voucher** - Based on Apply to Doc No. - Owner 1 and Owner 2 Should be update in Voucher Line.
NAV16 - Working Fine
**BC - Not Working** @sandhya3k 

2. Bank Payment Voucher - Working Fine

@sandhya3k - Need to Check If Dimension value is available in related apply to Doc No. so it should be auto populate at the time of Apply to Doc No. Selection.

**Comment by TabrejAlam3K** [comment]
3. Cash Receipt Voucher - Based on Apply to Doc No. - Owner 1 and Owner 2 Should be update in Voucher Line.
NAV16 - Working Fine
**BC - Not Working** - @sandhya3k 

4. Cash Payment Voucher - Working Fine

@sandhya3k - Need to Check If Dimension value is available in related apply to Doc No. so it should be auto populate at the time of Apply to Doc No. Selection.

**Comment by TabrejAlam3K** [comment]
5. Contra Voucher - Working fine as per the scenario in NAV16 and BC.

**Comment by TabrejAlam3K** [comment]
Based on the Apply to Doc No. **Owner 1 Code and Owner 2 Code should be populate in Voucher Line** Please cross check it.

You need to check for below Vouchers.

1. Bank Receipt Voucher
2. Bank Payment Voucher
3. Cash Receipt Voucher
4. Cash Payment Voucher
5. Contra Voucher


CC @audhi3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K  As per our discussion, it's got updated all the fields please cross check ?

**Comment by TabrejAlam3K** [comment]
Thanks @sandhya3k - It's Working same like NAV16.

When the user move on the new line then Owner 1 and Owner 2 got updated. I am closing this ticket as completed.

CC : @audhi3k - You can confirm to the client for UAT.

**Comment by TabrejAlam3K** [comment]
Information passed to the Client for UAT he will confirm if they are face issues during the UAT.

**Comment by audhi3k** [comment]
@TabrejAlam3K, we will close this ticket on Monday, as they are doing internal UAT

**Comment by audhi3k** [comment]
Client hasn't raised any issue, so closing this ticket
