### ISSUE TITLE
Unable to reverse Bank receipt voucher - 100DBBR-C230192

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1140]

**Comment by Prakash3K** [comment]
@Ejaz3KT 


![Image](https://github.com/3ktech/General/assets/140147250/be7c4e7d-5b94-4ce5-a3da-61f6386694e8)



![Image](https://github.com/3ktech/General/assets/140147250/1bcceaef-6d2b-413a-bd31-9797e0a1f0fe)

**Comment by Ejaz3KT** [comment]
UAT has been done with the client waiting for the confirmation to deploy in to production

CC: @audhi3k @sandhya3k

**Comment by Ejaz3KT** [comment]
The issue has been resolved and client also confirmed so we can close this ticket

Mr. @Prakash3K you can close this ticket with 4 hours in support portal

CC: @audhi3k @sandhya3k
