### ISSUE TITLE
RTB not getting synced in BC

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1143]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 


![Image](https://github.com/3ktech/General/assets/140147250/998c8a01-bb8c-41a7-a94e-5bcdde6513fe)

**Comment by TabrejAlam3K** [comment]
We have increased the time interval of Job Queue and resynced the reocrds which was issues.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Please close this ticket form the support portal. 

**Total Effort Hours = 1.5 Hrs.**

![Image](https://github.com/3ktech/General/assets/116171982/5b66cb7e-6a11-4edc-9ed7-b98277d0c869)

CC : @audhi3k @Shasthara
