### ISSUE TITLE
Fw: Sub Contracting Locations - Jodhpur/Patalganga/Tauru

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1147]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/1e8eab81-1d40-42af-9fec-3200b3bf2822)



![Image](https://github.com/3ktech/General/assets/142868335/8a8db5c4-45d0-4189-ba6c-d48521d723b8)

**Comment by TabrejAlam3K** [comment]
Waiting for the few information from the client side.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/441e695d-f580-4f89-a043-69d0811cf4a5)

**Comment by TabrejAlam3K** [comment]
Hi @Prakash3K - Due to non-response by the client, please close this ticket from the support portal. I am going to close with Git.

**Total effort hours = 1 Hrs**

CC : @audhi3k @Shasthara
