### ISSUE TITLE
Incorrect Interdivision entries for Bank Payment Voucher No. 100DBBP232860

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1148]

**Comment by Prakash3K** [comment]
@Ejaz3KT 


![Image](https://github.com/3ktech/General/assets/140147250/01ead095-b6b4-49dd-ba6b-51e11fa87770)



[Bank Payment Voucher (2).xlsx](https://github.com/3ktech/General/files/13883918/Bank.Payment.Voucher.2.xlsx)

**Comment by Ejaz3KT** [comment]
The issue has been resolved and UAT has also completed with the client waiting for the confirmation to deploy the changes into production

CC: @audhi3k @Padma2717 @sandhya3k

**Comment by audhi3k** [comment]
Mr @Ejaz3KT what's the approval hours

**Comment by Ejaz3KT** [comment]
The Fitchner team has confirmed the interdivision entries has generating correctly so we can close this ticket

CC: @audhi3k @sandhya3k
