### ISSUE TITLE
IT support request

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1152]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/eb3f8517-ff20-4be3-beba-9c10877c9599)



[If requesting support (1).docx](https://github.com/3ktech/General/files/13945392/If.requesting.support.1.docx)

**Comment by audhi3k** [comment]
Mr @niranjand22 what is this

**Comment by niranjand22** [comment]
I have connected with agne for this ...there is technical error coming while posting the payemnt journal..and while preview posting it is noy shouwing any error.

**Comment by niranjand22** [comment]
![Image](https://github.com/3ktech/General/assets/116243958/54caf9f0-433d-47c2-ac93-0e51db7659a8)

connected with agne...analysed also and connected with sandhya..currently ms @sandhya3k is working on this

**Comment by niranjand22** [comment]
completed
