### ISSUE TITLE
DYN 365 BC / Fichtner India/ 3KT / 18.01.2024 / Mur-059 / Purchase Order - No. Series requirement

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1158]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/60f1f756-e4bb-4577-aca2-823e44be4290)

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam I`ve attached the document where the requirement of fitchner is clearly mentioned please go through the document and tell us how much effort hours you required to do this customization

[Fitchner_Purchase order No. series requirement.docx](https://github.com/3ktech/General/files/13988214/Fitchner_Purchase.order.No.series.requirement.docx)

CC:  @audhi3k

**Comment by Ejaz3KT** [comment]
UAT has been provided to the we can close this ticket 

@Prakash3K  please close this ticket with the 7 hours 

CC: @audhi3k @sandhya3k
