### ISSUE TITLE
DYN 365 BC / Fichtner India/ 3KT / 18.01.2024 / Mur-060 / Purchase Order report - template

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1159]

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam We have to modify these purchase order report as per the requirement and I`ve attached the PDF and mentioned what are the changes need to be done in this report


[PO report FI comments 18012024.pdf](https://github.com/3ktech/General/files/13987033/PO.report.FI.comments.18012024.pdf)


CC: @audhi3k

**Comment by Ejaz3KT** [comment]
@sandhya3k we got the confirmation and we start working on this report

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
UAT has been done with the client waiting for the confirmation to deploy the report in to production

CC: @audhi3k @sandhya3k

**Comment by Ejaz3KT** [comment]
The Purchase order report has been deployed into the production environment now I am going to close this ticket

CC: @audhi3k @sandhya3k
