### ISSUE TITLE
BC Purchase Order formatting

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1165]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/20fb191d-d264-492d-abc9-748adf3c96f2)



[PO-104687.pdf](https://github.com/3ktech/General/files/14004675/PO-104687.pdf)

**Comment by niranjand22** [comment]
Changes completed.

**Comment by Jayanth3KT** [comment]
Hi @niranjand22  This ticket is resolved in support portal kindly update status.

CC: @audhi3k

**Comment by niranjand22** [comment]
its resolved @Jayanth3KT  cc @audhi3k
