### ISSUE TITLE
Cancelling a PO in BC

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1166]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/d559ecf6-58e1-4733-b92b-60d52b28237c)

**Comment by Jayanth3KT** [comment]
Hi @niranjand22 This ticket is resolved in support portal kindly update status.

CC: @audhi3k

**Comment by niranjand22** [comment]
@Jayanth3KT  its resolved cc @audhi3k
