### ISSUE TITLE
Vrdhi Document Preparation

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#117]

**Comment by niranjand22** [comment]
The document is prepared.  Need to review this with Mrs Audhi.

**Comment by niranjand22** [comment]
Half documents have been reviewed. also highlighted changes from yesterday's call is done in doc.

**Comment by audhi3k** [comment]
Completed the Walkthrough with client.
@niranjand22 as discussed kindly update the document and share it with the client for approval.

**Comment by niranjand22** [comment]
Finalised doc has been shared to client for review and approval

**Comment by audhi3k** [comment]
@niranjand22 , we will close this ticket on Monday, for confirmation from the client

**Comment by audhi3k** [comment]
Client confirmed
