### ISSUE TITLE
Some Write-offs not getting posted to BC and are in Not Posted/In Transit status in Snowfig. (BC365 and Snowfig Syncing Issues)

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1177]

**Comment by TabrejAlam3K** [comment]
Hi @rohit3k - Is it Deployed into the Production?

CC : @audhi3k @Shasthara @sandhya3k

**Comment by TabrejAlam3K** [comment]
Deployment has been completed into the Production, We can close the ticket from the Support Portal. I am closing from the Git.

CC : @audhi3k @Shasthara @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please update why it is not yet deployed into the Production. Any dependencies ?

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - We can close this ticket form the Git, You can connect with Mr. @Shasthara and close the ticket from the Support portal.

CC : @audhi3k
