### ISSUE TITLE
Collection Detail - New Requirement

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#118]

**Comment by TabrejAlam3K** [comment]
Collection Detail Card
1. Cheque Amount LCY - It Should be Editable Filed
2. Cheque Amount - It Should be Editable Filed
3. Exchange Rate - It should be update based on the User inputs in the field (Cheque Amount LCY Or Cheque Amount)

User can input the value in either Cheque Amout or In Cheque Amount LCY

**Comment by audhi3k** [comment]
@TabrejAlam3K as discussed, kindly convey to the technical
@sandhya3k, kindly take up the requirement and incase any queries reach me

**Comment by TabrejAlam3K** [comment]
@sandhya3k - As per our discussion you got the requirement. Please ping me if you have to face any issues.

Page - Collection Detail Card (50078, Card)
Table - Collection Detail (50012)
Page - Currency Exchange Rates (483, List)
Table - Currency Exchange Rate (330)

**Comment by sandhya3k** [comment]
@TabrejAlam3K  please test the dev environment?

**Comment by TabrejAlam3K** [comment]
@sandhya3k - We will test it in UAT please move it to the UAT.

**Comment by sandhya3k** [comment]
@TabrejAlam3K  please test the UAT env now?

**Comment by TabrejAlam3K** [comment]
@sandhya3k - As per the requirement it's working fine.

Condition1 - When user input the value in **Check Amount LCY** then **Exchange rate** and **Cheque Amount** gone updated.

Condition1 - When user input the value in **Check Amount** then based on the Currency and Exchange rate **Cheque Amount LCY** gone updated.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

can u please test in UAT?

CC: @ @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - I have tested now it is working fine.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@audhi3k - Client give the confirmation for this. We can close this ticket.

**Comment by audhi3k** [comment]
completed
