### ISSUE TITLE
FW: Steinbock Barite Ltd. - case id 5050984

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1181]

**Comment by TabrejAlam3K** [comment]
Discussed and showcase to Mr. Dipesh Why it was heppend. Closing tickets from the Git.

Mr. @Prakash3K close this from the Support portal as well with **Time Effort = 3 Hrs**

![Image](https://github.com/3ktech/General/assets/116171982/280bc63c-e60f-4ba0-93b5-26f2a8aa3a60)

CC : @audhi3k @Shasthara
