### ISSUE TITLE
Grouphead Code and JV Application Invoice Approval

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1182]

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k - Need to discuss on this, when we can connect on this?

**Comment by audhi3k** [comment]
Case assigned to Mr @anandakumar3k for Technical

**Comment by TabrejAlam3K** [comment]
As per the Client UAT We have tested the below two points and found it is working in the UAT Environment Correctly, We can plan to move the changes into the Production.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/68b09c82-c573-4877-9db5-e9275bfed26f)

**Comment by TabrejAlam3K** [comment]
Deployment has been completed into the Production, We can close the ticket from the Support Portal. I am closing from the Git.

CC : @audhi3k @Shasthara @Prakash3K
