### ISSUE TITLE
Issue Reported - Repair Job Work #OU-JWO2324-00601

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1188]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 


![Image](https://github.com/3ktech/General/assets/140147250/912d3a57-9d80-436f-81b0-2e09107b0daa)



![Image](https://github.com/3ktech/General/assets/140147250/27ae805d-f04a-43d6-be48-0d4fb39b7801)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Is the issue deployed on the UL Production?

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @audhi3k Mam, Please share your time effort on this.

Mr. @rohit3k - Please share your time effort.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Please close this ticket from the support portal.

**Total Effort Hours = 4 Hrs**

CC : @audhi3k
