### ISSUE TITLE
DYN 365 BC / Fichtner India/ 3KT / 23.01.2024 / Mur-063 / Bank Payment Voucher - G/L Entry

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1198]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/7b39643d-7b0a-464a-b425-4e494709c0dd)

**Comment by Ejaz3KT** [comment]
The issue has been resolved @Prakash3K Please close this ticket in the support portal with 1 hour

CC: @audhi3k
