### ISSUE TITLE
Dods Tenant duplication

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#120]

**Comment by 3ktech** [comment]
Got a call from agency. The ticket will be forwarded to respective team and will get back to us.

**Comment by 3ktech** [comment]
@audhi3k , I sent you an email with the instructions to create ticket or to submit the info to MS. can you please involve team to actionize it.

**Comment by 3ktech** [comment]
Had a call with MS and sudarsan is taking this forward with client to send MS the required information.

**Comment by audhi3k** [comment]
@3ktech, Mr Karthik can you update the status

**Comment by Shasthara** [comment]
Sudharsan and karthik coordinating with customer

**Comment by Shasthara** [comment]
@Mahesh3ktech ,validate the source code
