### ISSUE TITLE
FW: Political Engagement Limited - Issued Reminder 500001

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1204]

**Comment by Prakash3K** [comment]
@niranjand22 


![Image](https://github.com/3ktech/General/assets/140147250/b8b0f318-430f-4bb2-8fee-ad8150a3f573)

**Comment by niranjand22** [comment]
msg from chris "Apologies Niranjan, I have been off for a couple of days and ned until the end of the week, thanks"

**Comment by niranjand22** [comment]
content 
"Dear Sir / Madam,

 

You are receiving this email to formally notify you that payment owed by you is now overdue. The payment was due on “insert date here”.

 

Could you please confirm when payment will be made."  @sandhya3k

**Comment by niranjand22** [comment]
Hi @Prakash3K  Close this case with 3.5 hrs. cc @audhi3k
