### ISSUE TITLE
App Registration in Azure portal, setup the postman authentication and test the API.

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1206]

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Create the support ticket and assign it to me.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi @Mahesh3ktech  - Is the task completed?

CC : @audhi3k @Shasthara

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K yes, it is completed and i spent 4.5 hours.

CC: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Shasthara - As Discussed, Mr. @Mahesh3ktech need to explain the such scenario to Mr. Dipesh on this.

CC : @audhi3k @3ktech @rohit3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - We can close this ticket form the Git, You can connect with Mr. @Shasthara and close the ticket from the Support portal.

CC : @audhi3k
