### ISSUE TITLE
LKS production Upgradation

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1209]

**Comment by TabrejAlam3K** [comment]
Hi @Prakash3K - Why you have not created the Support Case for this ticket? Please discuss with @sandhya3k If requried create the support ticket as well for this.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi @sandhya3k - Can we close this ticket from the Git?

CC : @audhi3k @Shasthara

**Comment by Prakash3K** [comment]
Hi @TabrejAlam3K sir, I was discussed with @sandhya3k ma'am before creating this task in git, she mentioned it is an internal task. If required to create in support portal, please provide Contact person for this ticket.




CC: @Shasthara, @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @Prakash3K - I am not asking for create the ticket on support portal.

**Comment by TabrejAlam3K** [comment]
Hi @sandhya3k - I am closing this ticket from the Git,

CC : @audhi3k @Shasthara
