### ISSUE TITLE
Field length issue for Description in General Journal Line

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#122]

**Comment by panduc** [comment]
@sandhya3k  As discussed please create new field "Description 3" text field with Length 100.  mapping should be done for All business the logics, Pages and reports. which already shared you.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

This is the list of objects which i have modified. can u please test dev Environment.?




![Image](https://user-images.githubusercontent.com/114206737/220073669-d3b8eb27-411a-4c9d-bebd-5368f09d8fab.png)

cc : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k  As per our discussion with Ms. @audhi3k Mam you need to move this customization in UAT first then we will start testing.

**Comment by audhi3k** [comment]
@sandhya3k, kindly move the object to LIVE for Testing purposes. Testing in Development and UAT will be double work for functional.

**Comment by sandhya3k** [comment]
ok @audhi3k  mam, need to take some time because we need to move the server

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Please confirm once it will completed.

**Comment by sandhya3k** [comment]
@TabrejAlam3K  can u please test the UAT env?

cc: @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - I am working on let me complete the testing then will update you on.

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Need your help on


![Image](https://user-images.githubusercontent.com/116171982/220288038-a15869bc-cc05-40b5-9007-87fa6d834151.png)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - As per our discussion Description is not populating more then 50 characters but based on Collection Receipt No. we have 56 characters value.

Please check it and ping me once you get anything or completed.

cc : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - It's working fine I am moving this into the UAT.

Thanks

**Comment by audhi3k** [comment]
As working fine, closing this ticket

**Comment by sandhya3k** [comment]
@panduc 

I have changed to customized field which is "description 3" to base field which is "description" in all pages, reports and code units. i was not able to comment the customized field in table level because i had faced a publishing error.

I have attached the excel where i have modified objects. `[]

[field length modified objects.xlsx](https://github.com/3ktech/General/files/10979292/field.length.modified.objects.xlsx)

@TabrejAlam3K 

Please test the development environment.

cc : @audhi3k 
`

**Comment by TabrejAlam3K** [comment]
@Ejaz3KT - As per our discussion i have taken your support on this and explained to you which scenario need to check and how to check. Please ping me if you have any query.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@Ejaz3KT - Please update the current status of the points.

CC : @audhi3k

**Comment by Ejaz3KT** [comment]
@TabrejAlam3K I`ve tested all the voucher descriptions all are working fine.

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
@Ejaz3KT - Thanks, I am moving this into the UAT.

**Comment by niranjand22** [comment]
Client has confrimed for closure
