### ISSUE TITLE
DYN 365 BC / Fichtner India/ 3KT / 14.02.2024 / Mur-066 / Sales register - Taxable value shown in Posted sales invoice and credit memo mismatch

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1224]

**Comment by Prakash3K** [comment]
@Ejaz3KT 


![Image](https://github.com/3ktech/General/assets/140147250/30192864-b1dc-48b0-b41f-5100df50ebd1)

**Comment by Ejaz3KT** [comment]
Hi We got the confirmation of the closer of this ticket so I am closing this ticket

@Prakash3K Please close this ticket in support portal with 4 hours

CC: @audhi3k @sandhya3k @Shasthara
