### ISSUE TITLE
UAT session - Functionality and Reports (Mail)

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#123]

**Comment by TabrejAlam3K** [comment]
@audhi3k - UAT related to the client LKS.

**Comment by TabrejAlam3K** [comment]
Dear Mr. Vishwanathan,

I hope you are doing well

I have tested all the points whatever we discussed in the UAT Session below. Please cross check and confirm if we missed anything.

1.	Collection Detailed Card
•	Cheque Amount LCY – Now it is Editable field (you can put the value here)
•	Validation on Check Amount LCY field – Based on whatever currency is available on the Collection Card Exchange Rate and Cheque Amount got updated.
•	Report of Batch Job For Discarded Entry.
2.	Bank Receipt Voucher
•	Income Account mandatory – Marked Mandatory
•	Applies-to Doc. No. – Amount, Debit Amount, Credit Amount, Owner 1, Owner 2 and Related Dimension Value got update when the users select the value in Applies-to Doc. No.
•	Description – It is updating based on 3rd line of Dimension Value Name. (functionality as nav16)
•	Field Length Issue on Check No. Field.
•	Debit and Credit Amount Column to be added in all the Vouchers. 
3.	Bank Payment Voucher 
•	Description – It is updating based on 3rd line of Dimension Value Name. (functionality as nav16)
•	Debit and Credit Amount Column to be added in all the Vouchers.
4.	Cash Payment Voucher
•	Description – It is updating based on 3rd line of Dimension Value Name. (functionality as nav16)
•	Debit and Credit Amount Column to be added in all the Vouchers.
5.	Cash Receipt Voucher
•	Description – It is updating based on 3rd line of Dimension Value Name. (functionality as nav16)
•	Debit and Credit Amount Column to be added in all the Vouchers.
6.	Contra Voucher
•	Description – It is updating based on 3rd line of Dimension Value Name. (functionality as nav16)
•	Debit and Credit Amount Column to be added in all the Vouchers.

**Comment by TabrejAlam3K** [comment]
No Response received from the Client side.

**Comment by TabrejAlam3K** [comment]
Points raise during the UAT Session

1. Need to create users in BC
    Bhupendra Singh
    Gaurav Kumar Raute
    Priyanka Gupta
2. Users Permission - Need to configure same as whatever available in NAV16.

**Comment by TabrejAlam3K** [comment]
Users Created in BC and SUPER Permission given for the Users for the time being.

Client Confirm it.

**Comment by TabrejAlam3K** [comment]
Review Mail send to the LKS team.

As per their response everything is working good.

**Comment by audhi3k** [comment]
We will hold this ticker this week

**Comment by TabrejAlam3K** [comment]
@audhi3k @Shasthara 

Response receive from the client.


![Image](https://user-images.githubusercontent.com/116171982/221768489-d51c0622-1133-489a-b2cb-ac4d018d6f7b.png)

**Comment by TabrejAlam3K** [comment]
No Mail response received form the Client side.

**Comment by TabrejAlam3K** [comment]
@panduc - As per our discussion please enable the field as per the snapshot you have taken.

**Comment by panduc** [comment]
@TabrejAlam3K  As discussed I've Enabled the field and the logic for Vendor Ledger Entry. Please Check and Confirm.

**Comment by TabrejAlam3K** [comment]
Working on Reviewing the NAV16 Page Field with BC.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

My customization is done once u open the cheque report, please let me know if u have face any challenges.

cc: @3ktech

**Comment by TabrejAlam3K** [comment]
@sandhya3k -You need to done the customization in UAT, during the client call we will request for show case to the client.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@audhi3k - I have updated the excel sheet for Comparison between NAV16 to BC.

[LKS Field Match Data.xlsx](https://github.com/3ktech/General/files/10964574/LKS.Field.Match.Data.xlsx)

**Note :** I have only comparing the field whatever the field is available on page level for user input from NAV16 to BC.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 
i have added all the fields where u mentioned in the excel sheet
please test the UAT environment.
cc: @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Ok let me check and update.

**Comment by TabrejAlam3K** [comment]
@sandhya3k - As per our discussion once you complete your customization on some fields please ping me then we can test all the vouchers on page level.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - I have tested it now it is available according to the excel sheet.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@audhi3k - Only 1 Point is pending (**Void Check after Posting**)

**Check Ledger Entreis**

1. Process Void Check -  ![Image](https://user-images.githubusercontent.com/116171982/226509139-07b959da-88c4-47ab-ae95-7a06ed30f9e8.png)

2. ![Image](https://user-images.githubusercontent.com/116171982/226509187-4c06dbb2-6fcf-4ace-b154-b39bf6570a97.png)


@Padma2717 - have you debug the above errors.

**Comment by TabrejAlam3K** [comment]
@Padma2717 - Please update the status of this ticket.

**Comment by niranjand22** [comment]
replicate the scenario in the chronus company(lks sandbox)

**Comment by TabrejAlam3K** [comment]
@audhi3k - Check Void scenario is not working in LKS Cronus Company.

**Comment by TabrejAlam3K** [comment]
@Padma2717 - Please update on Void Check on Posted Entries.

CC ; @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k -

Points : <html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



If   payment input panel has more than one transaction (more than one document   number), display of pre-posted voucher showing in clubbed view of all   transactions. – Not   resolved
--




</body>

</html>

Resolution Should be - After Dimension Value - Dimension Value Name should be come

**Comment by panduc** [comment]
@TabrejAlam3K Provided the data correction details Bank Account should have Currency Code and Currency should have Conv. LCY Rndg. Credit Acc. must have a value in Currency: Code=INR. 

Please discuss with Audhi and finalize the solution.

**Comment by TabrejAlam3K** [comment]
@audhi3k - We can close this ticket because we have created separate ticket in git for the pending points.
