### ISSUE TITLE
DYN 365 BC / Fichtner India/ 3KT / 19.02.2024 / Mur-068 / Purchase Register - Type of GST applied (RCM) information required

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1230]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/c0260e86-ec9e-4a83-b520-f7ecf32f09fc)



[Purchase register (2).xlsx](https://github.com/3ktech/General/files/14330928/Purchase.register.2.xlsx)

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k we got the approval for this task we can start the work

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi We got the confirmation of the closer of this ticket so I am closing this ticket

@Prakash3K Please close this ticket in the support portal with 5 hours

CC: @audhi3k @sandhya3k @Shasthara
