### ISSUE TITLE
Void Check issue due to Currency

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1238]

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please share the attached error snapshot.

![Image](https://github.com/3ktech/General/assets/116171982/a4a4dc21-5d40-456e-a740-ff8752d164e7)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi @rohit3k - Previously you have fix the same error for LKS, Please fix it again and book your hours agains 3K-Administration.

![Image](https://github.com/3ktech/General/assets/116171982/f096851d-37a6-43fd-afa3-f69d41194cc2)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam Mr. @rohit3k is not avaialble, whether we can provide this case to other technical?

**Comment by TabrejAlam3K** [comment]
Hi @rohit3k - Please fix the issues on urgent basis.

CC : @audhi3k @Shasthara

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K This kind of error Happens When we are not Having "Currency Code" Value in "Bank Account" Table.
because system is checking PostRoundingAmount while FinancialVoidCheck and it is a Functionality of Base we cannot bypass it.

cc: @audhi3k @Shasthara 

![Image](https://github.com/3ktech/General/assets/141296489/16592667-b076-4634-a541-f4af5691bb3d)

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/db705c40-585b-4b0a-b02d-dd436a19e88f)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
We are still waiting for response from the client side.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
While folloup with the Client.

![Image](https://github.com/3ktech/General/assets/116171982/d8e0f4fb-bf58-4791-ae32-fa8573f5b7ca)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/f06566cc-a1aa-4473-8711-37cf45490040)

**Comment by TabrejAlam3K** [comment]
Hi @rohit3k - As per our last session, have you made the changes accordingly?

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Mr. @anandakumar3k will share the estimated effort hours, and then we will get approval from the client.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @anandakumar3k - Please start your development activity and try to close it within the estimated hours.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/14018957-3345-4622-898f-1b49fe17c212)

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT - Please close this ticket from the support portal as completed, due to no response received from the client closing the ticket as confirmed by Mr. @Shasthara for closure.

CC : @audhi3k
