### ISSUE TITLE
FW: New Brussels Office - update sales invoice and sales credit memo templates in BC

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1239]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/f50cb9b6-aec6-4b10-9047-591f74fca08d)



![Image](https://github.com/3ktech/General/assets/142868335/cfe04f0d-ccce-4664-abf6-4ea1eb3955c8)



[SI-PE002042.pdf](https://github.com/3ktech/General/files/14358650/SI-PE002042.pdf)

**Comment by niranjand22** [comment]
hi @Prakash3K  closw this case..3 hrs
