### ISSUE TITLE
BC: Mary Malone can't print draft invoices

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1242]

**Comment by Prakash3K** [comment]
@niranjand22 


![Image](https://github.com/3ktech/General/assets/140147250/b45b7577-7f4b-4d5a-8cfb-f39413595a8e)

**Comment by niranjand22** [comment]
[BC INV-07658-Q1P4R7.pdf](https://github.com/3ktech/General/files/14662487/BC.INV-07658-Q1P4R7.pdf)

 draft invoice pdf

**Comment by niranjand22** [comment]
![Image](https://github.com/3ktech/General/assets/116243958/dc534afc-69d2-4d6c-9599-17f01f92324c)
