### ISSUE TITLE
Trial Balance with Dimension (BS Closing balance modifcation) MDT IND

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1248]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/6d5ef125-1689-486f-9f74-523c66c79f74)



[Trial Balance With Dimension (15).xlsx](https://github.com/3ktech/General/files/14384210/Trial.Balance.With.Dimension.15.xlsx)

**Comment by niranjand22** [comment]
close this with 4 hr @Jayanth3KT
