### ISSUE TITLE
Zoho UAT and Deployment in LIVE

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#125]

**Comment by audhi3k** [comment]
@Mahesh3ktech, kindly co-ordinate with Mr Praveen on Zoho integration

**Comment by audhi3k** [comment]
@Mahesh3ktech, check the issue in purchase price export and then prepare the plan for GoLIVE

**Comment by audhi3k** [comment]
Purchase Price export is confirmed by Zoho Team and by Pioneer
@Mahesh3ktech, kindly share the plan for GoLIVE

**Comment by Mahesh3ktech** [comment]
Go Live process and plan:
1. Need take object backup and then objects merging to Live environment.
2. Setting up the job queue to run the process automatically.

**Comment by Mahesh3ktech** [comment]
Zoho Master deployment in Live is completed.

**Comment by audhi3k** [comment]
There was no issues highlighted, hence closing this ticket
