### ISSUE TITLE
RE_ DYN 365 BC _ Fichtner India_ 3KT _ 21.09.2023 _ Mur-016 _ Vendor Payment Upload

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1257]

**Comment by Ejaz3KT** [comment]
Hi We got the confirmation of the closer of this ticket so I am closing this ticket

@Prakash3K Please close this ticket in the support portal with 3 hours

CC: @audhi3k @sandhya3k @Shasthara
