### ISSUE TITLE
Posting Error while Rework consumption

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1260]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 


![Image](https://github.com/3ktech/General/assets/140147250/4b6afe1d-e220-4f43-825d-845b8df5a5ad)

**Comment by TabrejAlam3K** [comment]
IC-JW324-00717
OU-JWO2324-00767

Error : Microsoft Dynamics NAV
---------------------------

Item No. must be equal to 'FNSGCB43CW35100'  in Item Ledger Entry: Entry No.=9927885. Current value is 'RMHAMI0000021X'.
---------------------------
OK
---------------------------

**Comment by TabrejAlam3K** [comment]
attached the ILE

[CAS-01983-J3T3B7.xlsx](https://github.com/3ktech/General/files/14509128/CAS-01983-J3T3B7.xlsx)

![Image](https://github.com/3ktech/General/assets/116171982/5f68ba51-6035-4bfa-9427-fa7612a956c4)

**Comment by TabrejAlam3K** [comment]
As discussed with Mr. Shifiullah over the phone, there is no such issue currently; when it comes again, they will come back with us.

**Comment by TabrejAlam3K** [comment]
Holding this ticket till April 5, 2024, after that we will close the ticket.

**Comment by TabrejAlam3K** [comment]
We can close this ticket based on the discussion with the client.

CC : @audhi3k @Shasthara
