### ISSUE TITLE
Auto posting of Sales records through job queue.

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1265]

**Comment by TabrejAlam3K** [comment]
[Default04_03_2024_12_20_35.xlsx](https://github.com/3ktech/General/files/14477884/Default04_03_2024_12_20_35.xlsx)
[Transaction Log (1).xlsx](https://github.com/3ktech/General/files/14477882/Transaction.Log.1.xlsx)
[Transaction Log.xlsx](https://github.com/3ktech/General/files/14477883/Transaction.Log.xlsx)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech, Once you have made the changes, please let me know for unit testing.

CC : @audhi3k  @Shasthara

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - i have done changes. kindly check and update.

CC: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
I have attached Test Case

[Test Case_RRIN_004.xlsx](https://github.com/3ktech/General/files/14491691/Test.Case_RRIN_004.xlsx)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/7daaf0d7-8b3c-446d-8649-deaa8ecd4f28)

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K issue has been resolved kindly check.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech, I have done the manual testing, and the process is working fine. Please let me know when we can test the fully automated process.

Testing Status : Pass (Manual)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Discuss with Mr. Mahesh that he will complete all the development activity by today, after that, we will test and close the issues.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - I am waiting for your response on this. Is the last issue resolved?

**Comment by TabrejAlam3K** [comment]
Hi @Mahesh3ktech - As discussed below, changes need to be correct.
1. Posted No. is not coming on Transaction log page
2. Sales Line - Qty to Ship and Qty to Invoice not validated.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - We have tested and found it is working fine. Closing this ticket.

[Transaction Log (5).xlsx](https://github.com/3ktech/General/files/14930448/Transaction.Log.5.xlsx)

CC : @audhi3k
