### ISSUE TITLE
Issue found in NAV

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1272]
Re: NIN-2102 To has been created from N601 to subcon location while inwarding the TO its showing error like base qty must be equal to zero
[#1282](https://github.com/3ktech/General/issues/1282)

**Comment by Prakash3K** [comment]
@TabrejAlam3K 

User ID: deepak.jangid@urbanladder.com



![Image](https://github.com/3ktech/General/assets/140147250/8d0db61d-e644-49d6-b4ed-2b8a8deb3afd)



![Image](https://github.com/3ktech/General/assets/140147250/7ee2c1fa-1772-44db-8844-a8746d92e786)

**Comment by TabrejAlam3K** [comment]
Manual Activity Client User are doing
1.	On the Reservation Entry page, you are modifying the quantity for shipment lines.
2.	Deleting the duplicate surplus reservation lines.

**Comment by TabrejAlam3K** [comment]
I am waiting for Mr. @johnbosco3K response with the estimated time effort which we need to share with the client.

**Comment by TabrejAlam3K** [comment]
Holding this ticket till April 5, 2024, after that we will close the ticket.

**Comment by TabrejAlam3K** [comment]
We can close this ticket based on the discussion with the client.

CC : @audhi3k @Shasthara
