### ISSUE TITLE
Issue: barcodes are not being auto assigned to line items.

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1279]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 



![Image](https://github.com/3ktech/General/assets/140147250/b488a5a7-d755-4c94-8575-34ad66f43b07)

**Comment by TabrejAlam3K** [comment]
Holding this ticket till April 5, 2024, after that we will close the ticket.

**Comment by TabrejAlam3K** [comment]
We can close this ticket based on the discussion with the client.

CC : @audhi3k @Shasthara
