### ISSUE TITLE
Re: NIN-2102 To has been created from N601 to subcon location while inwarding the TO its showing error like base qty must be equal to zero

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1282]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/5f386ed8-3324-4c6d-9b92-132e64014cef)

**Comment by TabrejAlam3K** [comment]
Duplicate ticket of Issue found in NAV [#1272]

**Comment by TabrejAlam3K** [comment]
Holding this ticket till April 5, 2024, after that we will close the ticket.

**Comment by TabrejAlam3K** [comment]
We can close this ticket based on the discussion with the client.

CC : @audhi3k @Shasthara
