### ISSUE TITLE
Jet report error

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1283]

**Comment by Prakash3K** [comment]
@niranjand22 


![Image](https://github.com/3ktech/General/assets/140147250/d1f286a1-2f12-41f7-89e5-281c2d7a7fe5)



![Image](https://github.com/3ktech/General/assets/140147250/7da9adf9-2bc9-4601-a7bf-80e7455b997c)

**Comment by niranjand22** [comment]
RESLOVED BY CLIENT
