### ISSUE TITLE
Dynamics 365 Business Central - Infosense Technologies Private Limited - High Priority

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1285]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/1ec06dd1-566d-46c3-b2cb-553fda7f38b1)

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT - Close this ticket from the support portal as it has been completed and confirmed by the client.
**Effort hours = 1 hour**

![Image](https://github.com/3ktech/General/assets/116171982/d6aa11d1-ac44-4c99-942a-7dbe56ec00b5)

CC : @audhi3k @Shasthara
