### ISSUE TITLE
Data Migration to BC -Opening Balances as of 31st December duly

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#129]

**Comment by audhi3k** [comment]
@Amar-3KT , send mail to Mr Singaravel stating that the Opening Balance can be uploaded only after Dimension (dependency)

**Comment by audhi3k** [comment]
@Amar-3KT, create for configuration package or opening balance upload functionality

**Comment by Amar-3KT** [comment]
All data has been uploaded.
