### ISSUE TITLE
DYN 365 BC / Fichtner India/ 3KT / 21.03.2024 / Mur-073 / PO Module - using Resource in line and PO from Job WBS unable to create due to no. series

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1291]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/c35d8154-5ffe-4b65-bab6-4193dc2834ca)



![Image](https://github.com/3ktech/General/assets/142868335/612bbe3b-06df-48dc-8841-d49882eeffd2)

**Comment by Ejaz3KT** [comment]
Hi fitchner team is doesn't require this customization they are fine with the standard format so I am canceling this ticket

CC: @audhi3k @Shasthara @sandhya3k
