### ISSUE TITLE
VAT submission

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1293]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/81196816-e2aa-4ab8-b9f4-f760dbcf750b)

**Comment by niranjand22** [comment]
hi @Jayanth3KT  pls mention the complte ss so i can see who has sent the mail..then i can reach them accordingly

**Comment by Jayanth3KT** [comment]
From: Pasquale.Docile@dodsgroup.com


![Image](https://github.com/3ktech/General/assets/142868335/0d788e53-35bb-4eab-ae78-0917d10928c5)
