### ISSUE TITLE
Stock movement report

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1295]

**Comment by TabrejAlam3K** [comment]
Hi @Prakash3K - Create the support ticket and assign it to me.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi @Prakash3K  - Srinivasan.M@umaglobal.co

**Comment by TabrejAlam3K** [comment]
Session schedule for tomorrow between 10:30AM to 11:00AM.

**Comment by TabrejAlam3K** [comment]
We got the requirement from the client and required a technical discussion with you. When can we connect on this?
Report ID - 1001 (Inventory Valuation)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Required to add the below fields
1. Purchase Qty
2. Purchase Value
3. Purchase Return Qty
4. Purchase Return Value
5. Sales Qty
6. Sales Value
7. Sales Return Qty
8. Sales Return Value
9. Closing Qty
10. Closing Value

**Comment by TabrejAlam3K** [comment]
Closing Balance = (Opening Stock + Purchase + Sales Return)-(Sales + Purchase Return)

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - As discussed, please provide the effort on this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - We got approval on this. You can start your development activity on this and complete it within the committed hours.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @NityaNirlipta - I have added the fiedl mapping excel sheet here for you referances.

[Field Mapping CAS-02015-N7Y0R3.xlsx](https://github.com/3ktech/General/files/14757515/Field.Mapping.CAS-02015-N7Y0R3.xlsx)

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - Please update the current status here.

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta Please update the current status here.

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - What is the status of the Report?

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - Please let us know when we can start testing on this.

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K - Once I complete it, I will Let You Know.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @NityaNirlipta - Still, the report is not coming correctly. Please checka and update.
1. Sales Value
2. Sales Return Value

**Comment by TabrejAlam3K** [comment]
Discuss with Ms. Sandhya and Mr. Mahesh, he guys facing some challanges while publishing the issue in the production. Once fixed he will inform.

**Comment by TabrejAlam3K** [comment]
Hi @Varunmk3k as discussed, this ticket will be closed along with ticket #1375

**Comment by TabrejAlam3K** [comment]
Closing the ticket as verbal confirmation give by the client over teams call.

![Image](https://github.com/3ktech/General/assets/116171982/245151df-aed3-4960-a5a5-d887bada9971)
