### ISSUE TITLE
Purchase order to be sent to Vendor over email with CC with the internal team State wise

### ISSUE THREAD

**Issue by shivakumar3k** [3ktech/General#1296]

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - As discussed over call, Please provide your input here.

CC : @audhi3k @Sarikab1222

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K, As discussed changed the body message as blob. kindly update the body message and test.

CC: @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
Hi @Mahesh3ktech - See the below snapshot, We are unable to put the value in the respective fields.

![Image](https://github.com/3ktech/General/assets/116171982/c7b2ec3b-3233-4d6c-a886-c273951d3205)

CC : @audhi3k @Sarikab1222 @Varunmk3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech Please deploy the changes into production. The client confirms for deployment.

CC : @audhi3k @Sarikab1222

**Comment by Varunmk3k** [comment]
Hi @Mahesh3ktech Please Expand the length on the CC mail in States.

CC: @audhi3k @TabrejAlam3K

**Comment by Mahesh3ktech** [comment]
hi @Varunmk3k @TabrejAlam3K as discussed, changed the length of character to 250 as standard.

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Confirmation Mail Received

![Image](https://github.com/3ktech/General/assets/116171982/b0c56604-17dd-4b8b-aef1-4d6be62cb668)
