### ISSUE TITLE
Taxation error in Credit Memo

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1328]

**Comment by Varunmk3k** [comment]
Hi @Mahesh3ktech Taxable value is not coming correctly.

[document (38).pdf](https://github.com/3ktech/General/files/14904979/document.38.pdf)

CC: @TabrejAlam3K @audhi3k

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K as discussed corrected taxable value in copy prod environment. kindly check and confirm.

CC: @audhi3k @Varunmk3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please deploy the changes into Production, Client Confirmed, for deployment & closure.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - This issue not yet deployed in production. Please help us on a priority basis.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Discuss with Ms. Sandhya and Mr. Mahesh, he guys facing some challanges while publishing the issue in the production. Once fixed he will inform.

**Comment by TabrejAlam3K** [comment]
Hi @Mahesh3ktech and @sandhya3k - Please update on this wheter is it deployed into the Production?

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT - Close this ticket as completed and confirmed by the client.

![Image](https://github.com/3ktech/General/assets/116171982/7849e794-2e2c-4f88-8a58-d6774fcad93b)

CC : @audhi3k @Varunmk3k
