### ISSUE TITLE
DYN 365 BC / Fichtner India/ 3KT / 04.04.2024 / Mur-077 / PO report - Budget Reference No.

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1329]

**Comment by Ejaz3KT** [comment]
Hi Sandhya Madam Fitchner requirement is to rename the vendor order no. to Budget Ref no. and the same caption we need to add in the PO 


[POR240001.pdf](https://github.com/3ktech/General/files/14867025/POR240001.pdf)


CC: @audhi3k @sandhya3k @Shasthara

**Comment by Ejaz3KT** [comment]
We got the confirmation from the client to close this ticket 

CC: @audhi3k @sandhya3k @Shasthara
