### ISSUE TITLE
DYN 365 BC / Fichtner India/ 3KT / 05.04.2024 / Mur-078 / Fixed Asset - No. of days Depreciation

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1333]

**Comment by Prakash3K** [comment]
@Ejaz3KT 


![Image](https://github.com/3ktech/General/assets/140147250/c43b9353-223e-4be9-bbeb-0ff4d8e9dbc2)

**Comment by Ejaz3KT** [comment]
We got the confirmation from the client to close this ticket 

CC: @audhi3k @sandhya3k @Shasthara
