### ISSUE TITLE
Update Dimensions in EF Data flow

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1334]

**Comment by Prakash3K** [comment]
@niranjand22 


![Image](https://github.com/3ktech/General/assets/140147250/eb52197f-d8e3-40b6-a489-8305b62e2adb)



![Image](https://github.com/3ktech/General/assets/140147250/496dd051-a97d-44ce-8022-6d271475f551)

**Comment by niranjand22** [comment]
Hi @audhi3k , We had calls with the TP team. They are currently awaiting approval from their IT team and management for the Eventforce credentials. Once they receive confirmation, they will share the credentials with us.

cc @sandhya3k  @gsudarsan3k
