### ISSUE TITLE
Short Close all the Sales Orders till 23rd March

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1336]

**Comment by TabrejAlam3K** [comment]
Hi @shivakumar3k - We have short-closed the sales order until March 23, 2024. Please cross check and update.

CC : @Jayanth3KT @audhi3k

**Comment by Jayanth3KT** [comment]
Hi sir kindly confirm this issue whether Its UCPL issue or OG health care issue (As you have mentioned to create as OG but you have created as UCPL ) Kindly confirm.


![Image](https://github.com/3ktech/General/assets/142868335/c814567b-2e89-45a7-a49f-fa9855b090d1)

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT this is related to UCPL, Sorry typing mistak.

**Comment by TabrejAlam3K** [comment]
Hi @shivakumar3k - Closing this ticket as completed.
