### ISSUE TITLE
FW: 1 of your flow(s) have failed - EF_Update the Last Invoice Number

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1340]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/143fb390-7b39-4b10-87a0-b3307a1977b7)

**Comment by niranjand22** [comment]
HI @Jayanth3KT  This is for Murali(crm). kindly remove from here and assign to murali,
