### ISSUE TITLE
Purchase credit memo format

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1341]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/82d569ee-75d5-4607-8dd5-ed5d9565a3eb)



[Sales Credit Memo PSCM_0973.pdf](https://github.com/3ktech/General/files/14940901/Sales.Credit.Memo.PSCM_0973.pdf)

**Comment by TabrejAlam3K** [comment]
Approval Mail Received.

![Image](https://github.com/3ktech/General/assets/116171982/8821b39f-7f28-4f7f-b736-cad1a154881e)

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - We have done the UAT with the client and found the below points need to be correct.
1. Ref. Invoice No.
2. Invoice Total = Total
3. Tax Amount in (Words)

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT - Close this task from the support portal as completed and confirmed by the client.
effort hours = 12 hours.

![Image](https://github.com/3ktech/General/assets/116171982/e868550c-bbf4-49bf-9572-05ded5c51209)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT Close this tikcet as completed and confirmed by the client. 
effort hours = 12 hours

CC : @audhi3k
