### ISSUE TITLE
Error code - 5002 - E-invoice not generated

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1342]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/641ac2cb-4934-45ac-a6ec-8991e2825f98)

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT - Close this ticket as completed and confirmed by the client.
**Effort Hours = 3 Hrs**

![Image](https://github.com/3ktech/General/assets/116171982/f37a4621-671c-46c3-ae8a-4d33463ad4ef)

CC : @audhi3k
