### ISSUE TITLE
Infra scheme discount per unit column restricted 2 decimal

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1346]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/32398322-693b-489c-8b37-8028cf846807)

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT - Close this ticket from the support portal as it has been completed and confirmed by the client.
**Effort hours = 3 hours**

![Image](https://github.com/3ktech/General/assets/116171982/92c13a18-ee67-459a-b729-a7d3b5d0fa04)

CC : @audhi3k @Shasthara
