### ISSUE TITLE
Invoice format additional lines needs to be added

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1347]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 

![Image](https://github.com/3ktech/General/assets/140147250/06da4a5b-e773-4809-a5e9-ab57abf063d2)

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - We got the approval, Please start your activity on the this.

![Image](https://github.com/3ktech/General/assets/116171982/d717657e-590c-4055-82e3-9b531e22c2ca)

CC : @audhi3k @Shasthara

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K  Kindly create a Entry type as G/L Account in posted sales invoice as I couldn't able to find any entry as G/L Account. 
Cc:- @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - We have done the internal testing it is not working. Can we connect on this?

**Comment by TabrejAlam3K** [comment]
Sales Order No. - SO/2252
Sales Price Group - TN-SS
Item No. : USASIP010RLN

**Comment by TabrejAlam3K** [comment]
Hi Mr. @johnbosco3K - this we have tested but it is still not working as per expectations and requirement.

**Comment by TabrejAlam3K** [comment]
Validation Points
1. Sales Price List - If Infrastructure Scheme Boolean is true, then the GL Code & the GL Description should be editable else that should be non-editable.
2. Sales Order Line - In Scheme Fields if the value is Infrastructure, then need to remove the field value.

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please confirmed whether the points has been deployed or not.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation from the client side, hence closing this ticket from the git.

![Image](https://github.com/3ktech/General/assets/116171982/53170d0c-c32f-45e6-b753-52ec8a2747af)

CC : @audhi3k @Jayanth3KT
