### ISSUE TITLE
Distribution

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1360]

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT close this ticket from the support portal.

**Comment by TabrejAlam3K** [comment]
Closed

**Comment by TabrejAlam3K** [comment]
Hi @audhi3k Mam and Mr. @johnbosco3K - We got the approval on this.

![Image](https://github.com/3ktech/General/assets/116171982/438e5410-f3f5-4662-8bd8-6d0a5c43579b)

**Comment by TabrejAlam3K** [comment]
As per our last discussion, some calculation error happened during the KT session. Please update whether that error has been fixed?

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - I have done one level of complete testing. We have some questions on this.

[TestCase_Distribution_11June2024.xlsx](https://github.com/user-attachments/files/15793299/TestCase_Distribution_11June2024.xlsx)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Sure @audhi3k  Mam, When we can connect on this Mam?

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - We have done the testing on distribution and found some steps where the data is not updating correctly. Can we connect and discuss?

[Distribution Testing.xlsx](https://github.com/user-attachments/files/15908076/Distribution.Testing.xlsx)

CC : @audhi3k

**Comment by johnbosco3K** [comment]
Hi @TabrejAlam3K , Can we connect and discuss

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @audhi3k mam, I have done the process testind and attaching the tested documents.

[Distribution Testing.xlsx](https://github.com/user-attachments/files/15909479/Distribution.Testing.xlsx)

CC : @johnbosco3K - you can find the attached excel.

**Comment by TabrejAlam3K** [comment]
Client was not available for do the UAT.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Waiting for client Mr. Srinivasan response on this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam, We have done the UAT, they have raise new query on this, can we connect and discuss the issues.

CC : @johnbosco3K

**Comment by TabrejAlam3K** [comment]
We was connected with the client he said currently the responsible person leaved from the organization, he will discussion who will be responsible person for this and let us know based on that we will arrange the next session.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please deploy the changes into the production and let us know.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Due to non-response we are closing the ticket.

![Image](https://github.com/user-attachments/assets/50f68275-3469-45bb-a0ba-68c3c450cc19)

CC : @audhi3k
