### ISSUE TITLE
Setup NAV 2009 in azure

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#137]

**Comment by 3ktech** [comment]
@Mahesh3ktech , as discussed, take the installation setup from Mr.Singaravel and do the installation in the server I shared with you.
CC: @audhi3k

**Comment by Shasthara** [comment]
Increase Disk C: storage space,

**Comment by Shasthara** [comment]
Mahesh checking with Padma

**Comment by Shasthara** [comment]
This task is out of scope; please provide me with effort hours after the analysis is completed.

**Comment by Shasthara** [comment]
Time and material based
