### ISSUE TITLE
Required new table and page where we can capture all the Customer Ledger Entries fields value.

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1374]
Updated Sheet with Field Mapping

[Copy of Sample Collection Apportionment Table.xlsx](https://github.com/user-attachments/files/15585264/Copy.of.Sample.Collection.Apportionment.Table.xlsx)

[Copy of Sample Billing Apportionment Table.xlsx](https://github.com/user-attachments/files/15757057/Copy.of.Sample.Billing.Apportionment.Table.xlsx)

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - I have added the Excel sheet with Field Mapping.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - I have tested Collection Apportionment, and it is not working as per our expectations for what we have discussed. See the below fields, which are still missing.
1. Client Name
2. Location Code
3. Currency Code
4. Owner 1
5. Owner 2
6. Group Head
7. SubGroup Head Name
8. Posted
CC : @audhi3k

**Comment by johnbosco3K** [comment]
@TabrejAlam3K , Above Fields are not there in GL Entry field mapping. Please check and revert

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Do the necessary changes.
1. You need to change the caption of the button "General ledger Entres" to "Get Collection Entries."
2. The Get Collection Button requires a relationship with customer ledger entries.
3. Edit Dimension Set Entries required to capture the dimension or modification in the dimension.

**Comment by TabrejAlam3K** [comment]
1. While clicking on post button enties line should get posted if document no. having the same.
2. Memo No., Memo Date and Applied Date should come from the Applied entries.
3.

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Do the below changes and let us know for testing.
1. Client Name = Description
2. Memo No. = Applied Document No.
3. Memo Date = Applied Posting Date
4. LCY Gross and LCY Net = Gross Amount
5. Mark all the line non editable accept Gross Amount

**Comment by TabrejAlam3K** [comment]
We have done the UAT with the user (Mr. Viswanathan Sir), he said he will come back on this by today EOD. Based on their confirmation, we will close this ticket.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Sequence of Posted Billing Apportionment list pages.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Tabrej/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Tabrej/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Date of   creation | User ID | Bill No. | Bill Date | Branch Code | Case ID | Client Name | Owner 1 in CRN | Owner 2 in CRN | Billing Contact Name | Billing Description | Billing Currency | Total Amount (in Billing   currency) | Total amount in INR | REIMBURSABLE Exp | Service Tax | Net Biling In (INR) | CRN No. | CRN Date | Owner 1 in Bill | Owner 2 in Bill | Case Practice | Case Area | Case Process | Case Solution | Case Activity Type | Client Code | Sub Group Name | Group Head
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
System   Created At | System Created By | LKS01-2324-02244 | 26-10-2023 | 1 | 5048241 | MAHIMA ENTERPRISES |   |   | NEERAJ | Towards professional   charges for the drafting replies (on behalf of company and Mr. Dinesh) in   show cause notice no. 04/2022 dated 18.05.2023 and SCN C No. VIII(ICD   FBD)6/SCN/Mahima Entp/450 of 2021 dated 28.12.2021 regarding the   classification of various LED Pixel Diode under chapter 85 of the Customs   Tariff Act, 1975. | INR | 1,25,000.00 | 1,25,000.00 | 0 | 0 | 1,25,000.00 |   |   | JYOTI.PAL | RACHIT.JAIN | Tax - Indirect | Customs | Litigation | Drafting | Reply | 22958 |   | All India Customs



</body>

</html>

**Comment by johnbosco3K** [comment]
Hi @TabrejAlam3K , I need additional 3 hours for this changes

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please chek the alignment and sequence of the Coulm, It should be same as excel.

[Posted Collection Apportionment 12-6-24.xlsx](https://github.com/user-attachments/files/15820578/Posted.Collection.Apportionment.12-6-24.xlsx)
[Posted Billing Apportionment 12-6-24.xlsx](https://github.com/user-attachments/files/15820577/Posted.Billing.Apportionment.12-6-24.xlsx)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please support on this, this should be closed by today.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - The sequence of the column fields is still not reflected, Please correct it.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Change the Caption of the below fields.
1. LCY Gross = Total Amount (in Billing currency)
2. Gross Amount = Total amount in INR
3. LCY Net = Net Biling In (INR)

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - A new additional requirement comes against the same ticket.
Required two new Reports
1. Collection Apportionment Report
2. Billing Apportionment Report

[Posted Billing Collection apportionment tested entries.xlsx](https://github.com/user-attachments/files/15908449/Posted.Billing.Collection.apportionment.tested.entries.xlsx)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K 
1. Merge Bill and CRN is - Billing Apportionment Report
2. Customer Collection is - Collection Apportionment Report

[Customer Collection (21).xlsx](https://github.com/user-attachments/files/15909172/Customer.Collection.21.xlsx)
[Merged Bill and CRN (9).xlsx](https://github.com/user-attachments/files/15909173/Merged.Bill.and.CRN.9.xlsx)

**Comment by TabrejAlam3K** [comment]
Report filter option should be as below
1. Collection Apportionment Report

![Image](https://github.com/3ktech/General/assets/116171982/3bfd49b2-18cc-4fe1-ab36-61f9a42dd487)

2. Billing Apportionment Report

![Image](https://github.com/3ktech/General/assets/116171982/7ca27325-f348-405e-85de-b69c8b752abb)

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K 
Need to add cutomer report under Report section 
1. Collection Apportionment Report you can add after Customer Collection Report
2. Billing Apportionment Report you can add after Merge Bill and CRN

**Comment by TabrejAlam3K** [comment]
Partially Confirmation we got, waiting for final confirmation.

![Image](https://github.com/3ktech/General/assets/116171982/d92f73a7-0f04-4a25-ab13-962c95876db2)

CC : @audhi3k

**Comment by johnbosco3K** [comment]
Hi @TabrejAlam3K , When can we deploy to Live?
CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - you can deploy only the Collection Apportion Functionalitya and Report in the Production after office hours 9:30PM.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation on this from the client side.

![Image](https://github.com/3ktech/General/assets/116171982/f968725b-398c-432b-996a-b982aa36c308)

CC : @audhi3k
