### ISSUE TITLE
Send Posted Sales Invoice pdf to customer

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#138]

**Comment by Shasthara** [comment]
Development is completed by sandya

**Comment by sandhya3k** [comment]
@Shasthara @audhi3k testing need to be done

**Comment by sandhya3k** [comment]
@3ktech  
Testing is completed. got the email from my account.

cc: @audhi3k

**Comment by Shasthara** [comment]
mahesh to cordinate with Sandhya to share source code

**Comment by sandhya3k** [comment]
@3ktech 
I published the code in UAT Please test the UAT environment @TabrejAlam3K. 

cc: @audhi3k

**Comment by niranjand22** [comment]
Invoice is sending to customer. have to check on Job queue currently we have t trigger it manually.

**Comment by TabrejAlam3K** [comment]
As per the last discussion with Ms. @sandhya3k report is triggered based on job queue. As per the last testing job queue is running successfully but mail not triggered to the customer.

@sandhya3k - Have you done the unit testing.

**Comment by TabrejAlam3K** [comment]
Job queue is running successfully and Mr. Niranjan got the email more then 50.

**Comment by niranjand22** [comment]
two mails are getting triggered multiple times. one is posed sales invoice and other is junk or system invoice

**Comment by sandhya3k** [comment]
@3ktech 

Now, it's coming E-mails properly as per the invoice no. when the job queue is runs.
@TabrejAlam3K , I changed to your mail id can u test the job queue in UAT environment?

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - I have tested it today morning

See the attached Received Mail Snapshot.


![Image](https://user-images.githubusercontent.com/116171982/223906635-d18c8d60-52d3-48d5-ad27-1893320bc8eb.png)

![Image](https://user-images.githubusercontent.com/116171982/223906697-bbf8fdd3-8e36-4b94-96e8-226115ab6e63.png)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
See the attached Posted Sales Invoice Data


![Image](https://user-images.githubusercontent.com/116171982/223907548-adbe3121-4ae8-40b6-ae44-7a3ce26dda45.png)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - As per our discussion based on the LCMS Response Queue page data it is working fine and mail is triggered based on that. I am moving this into the UAT.

**Comment by audhi3k** [comment]
completed
