### ISSUE TITLE
ErrorCode": "5002" - E-Invoice not generated due to location field error

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1380]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/3f317836-6695-40ba-ad45-01781eac366f)

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT - You created the issue and not assigned it to me. Why?

CC : @audhi3k @Varunmk3k

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/b3e49203-fff0-4841-8469-e4c3c376a9e7)

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT - Close this ticket as completed and confirmed by the client.
**Effort hours = 4 hours**

![Image](https://github.com/3ktech/General/assets/116171982/54663402-9a67-47a6-b09e-70ca089e3bd8)

CC : @audhi3k
