### ISSUE TITLE
Vendor Outstanding New Report for Email Attachment.

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1384]

**Comment by TabrejAlam3K** [comment]
We are attaching approval email snapshot.

![Image](https://github.com/3ktech/General/assets/116171982/28092c92-3b30-491e-8ae1-bb705b2fb382)

**Comment by Varunmk3k** [comment]
Hi @TabrejAlam3K, Done the Internal Testing and we are ready to do the UAT along with the Client.

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT - Close this ticket as completed and confirmed by the client.

![Image](https://github.com/3ktech/General/assets/116171982/7849e794-2e2c-4f88-8a58-d6774fcad93b)

CC : @audhi3k @Varunmk3k
