### ISSUE TITLE
Error - e-invoice is not generated due to pincode does not match with state.

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1389]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/e64f6d25-0715-4be1-a317-7fa9509dbdb7)

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT - Close this ticket from the support portal as completed and confirm by the client.
effort hours = 1 hours

![Image](https://github.com/3ktech/General/assets/116171982/a548859f-b073-4005-90e6-55195a3211c8)

CC : @audhi3k
