### ISSUE TITLE
Upload Source files in Git

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#139]

**Comment by sandhya3k** [comment]
@3ktech  

I took the latest source file from server and created a branch which is MASTER and UAT to GIT.

[(https://github.com/sandhya3k/LKSBase-Development)]

I provide the how to download the source file from git.

  *Create an empty folder and open the new project to that empty folder
* Click the initialize repository
*Click the git bash and follow the below3 commands.
       Git remote add origin https://github.com/sandhya3k/LKSBase-Development.
        Git config --global user. Email "Your Mail Id"
         Git config --global user.name "Your Name"
* Click the source control and go to PULL
* Let them download the source and along the branches.




cc: @panduc  @Mahesh3ktech @audhi3k

**Comment by sandhya3k** [comment]
@3ktech 

I have taken the latest source file from server and merged to GIT.

CC: @audhi3k @panduc
