### ISSUE TITLE
Changes in the WIP report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#1399]

**Comment by Ejaz3KT** [comment]
Hi @Jayanth3KT Can you please create this new ticket in the support portal with 4 hours

@sandhya3k @audhi3k

**Comment by Jayanth3KT** [comment]
Hi sir kindly mention contact person for this ticket

**Comment by Ejaz3KT** [comment]
We are completed the points that fitchner team has raised so I am closing ticket in any case issue has raised we can reopen this ticket or create new one
CC: @audhi3k @sandhya3k

**Comment by Ejaz3KT** [comment]
We are completed the points that fitchner team has raised so I am closing ticket in any case issue has raised we can reopen this ticket or create new one
CC: @audhi3k @sandhya3k
