### ISSUE TITLE
Vendor payment report

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1404]
[Vendor Payment Report-Template.xlsx](https://github.com/3ktech/General/files/15186518/Vendor.Payment.Report-Template.xlsx)

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - The requirement got changed.
In the vendor ledger entries required the below new custom fields.
1. Payment Doc No.: The value will come from the applied entries . as **Document No**.
2. Payment Date - value will come from the applied entries . as the **posting date**.

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta, Please share the time and effort for this.

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K, I need 2 hrs extra for the above requirement.

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - No need to develop the report part, you can do the below things only.

In the vendor ledger entries required the below new custom fields.

Payment Doc No.: The value will come from the applied entries . as Document No.
Payment Date - value will come from the applied entries . as the posting date.

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - We got the approval please start your activity.

![Image](https://github.com/3ktech/General/assets/116171982/4435d9f9-8f9d-43d2-a82c-968b2ead9224)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @NityaNirlipta - Please update on this.

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - You can use the below filter to get the value.

![Image](https://github.com/3ktech/General/assets/116171982/1174f1a5-f9c5-45ab-803f-5b4a6f97bc49)

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K , Its done . Check it

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Deploy the changes into production.

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Is it deployed into the Production?
CC : @Varunmk3k

**Comment by TabrejAlam3K** [comment]
Deployment in the Production Environment Done, Waiting for Closure confirmation from the Client side.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 and Mr. @johnbosco3K - Is it deployed?

CC : @audhi3k

**Comment by sruthi1017** [comment]
hi Mr. @TabrejAlam3K - it is deployed CC: @johnbosco3K @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @sruthi1017 - Still not yet reflecting in the Production Environment. See the below snapshot, Mr. @johnbosco3K - Helop us here to deploy the changes into the production.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Please confirm whether the issue has been deployed in to the Production?
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K @NityaNirlipta @sruthi1017 - Please confirm whether the points have been deployed or not.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation from the client side, hence closing this ticket from the git.

![Image](https://github.com/3ktech/General/assets/116171982/53170d0c-c32f-45e6-b753-52ec8a2747af)

CC : @audhi3k @Jayanth3KT
