### ISSUE TITLE
PO Layout & Value Setup

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1406]

**Comment by TabrejAlam3K** [comment]
1. Company log should be come in page background
2. Amount should be come in the formatting
3. Signature left alignment.
4. Complete PO Alignment need to be fix.

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta as discussed Watermark log shold be repeat in all the pages.

**Comment by TabrejAlam3K** [comment]
GST Calculation also required.

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - As discussed, please make the below changes and let me know. Please share the additional effort hours as well.
1. You need to adjust the watermark logo in the center of the page.
2. Remove the Header and Line gap
3. GST byfication required with %.
![Image](https://github.com/3ktech/General/assets/116171982/93bf9975-55f0-415f-9048-94c86d11ff08)

CC : @audhi3k

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K  I need 3hrs to complete this.

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
you can start your activity Mr. @NityaNirlipta

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - we got the additional effort hours approval, Please start your activity.

![Image](https://github.com/3ktech/General/assets/116171982/068290ba-b8bc-423d-9267-51289df23ab5)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @NityaNirlipta - Please update on this.

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K ,
1) Logo is fixed .
2) Header and line gap is fixed.
only GST byfication is left , I will complete it within 1st half.

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - Is it Done?

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K  , Its little complicated taking time to complete , need some more time

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - Please take help from Mr. @johnbosco3K and get it completed by today.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @NityaNirlipta - Please update on this.

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please provide updates on this.

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please finish this task by today, Client is asking again and again.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - See below for additional requirements.
1. You need to adjust the watermark logo in the center of the page.
2. GST byfication required with %.
![Image](https://github.com/3ktech/General/assets/116171982/93bf9975-55f0-415f-9048-94c86d11ff08)

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - Please update the ticket development progress.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please fix the below points related to this task.
1. Tax Code Disc - Remove **DED 0.00**
2. Amount in Chargeable (in Words). - Amount is words coming with Taxable Amount, It should come based on the Total(INR).
3. This is a computer-generated Invoice - It should be **This is a computer-generateda purchase order**.
4. S. No. - not coming for some order.

CC : @audhi3k

**Comment by johnbosco3K** [comment]
Hi @TabrejAlam3K , I need an hour for the changes please check and revert

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - We have done the internal testing; let's do the UAT with the client and inform you for deployment in production.

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - early morning please plan to deploy this changes into the production.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - is the deployment done?
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - have you deployed the changes in production?
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please do the changes which we have duscussed and let us know, we need to confirm to client as well.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @audhi3k Mam, we got the closure confirmation.

![Image](https://github.com/3ktech/General/assets/116171982/adbf54b3-58be-42c5-9e4e-481c2b4b38cd)
