### ISSUE TITLE
3KT Project - Process Discussion

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#141]

**Comment by TabrejAlam3K** [comment]
22-02-2023 - Discuss with Mr. Prashant on Masters of BC
1. Chart of Accounts
2. Vendor
3. Customer
4. Fixed Assets

Required the Chart of Account data from Mr. Prashant

**Comment by audhi3k** [comment]
@TabrejAlam3K , kindly share the master templates for the above

**Comment by TabrejAlam3K** [comment]
@audhi3k - Shared the list of Master

Chart of Accounts
Vendor
Customer

**Comment by TabrejAlam3K** [comment]
All the masters has been provided to the Mr. Prashant, still wait for their reply mail,

**Comment by TabrejAlam3K** [comment]
I will do the follow-up with Mr. Prashant and confirm.

**Comment by TabrejAlam3K** [comment]
I have ping to Mr. Prashant but till now we haven't receive any response from.

**Comment by TabrejAlam3K** [comment]
I have created a sample file for 3KT Project.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



Department | Modules | Process | Masters
-- | -- | -- | --
Finance | AR | Customers | Chart of Accounts
  |   | Sales Invoice | Customers
  |   | Sales Credit Memo | Vendors
  | AP | Vendor | Fixed Assest
  |   | Purchase Invoice | Dimensions
  |   | Purchase Credit Memo | Items
  | General Ledger | Chart of Accounts |  
  |   | General Journal |  
  |   | Journal Voucher |  
  | Cash Management | Bank Accounts |  
  |   | Payment Journal |  
  |   | Cash Receipt Voucher |  
  |   | Cash Payment Voucher |  
  |   | Bank Receipt Voucher |  
  |   | Bank Payment Voucher |  
  |   | Contra Voucher |  
  | Fixed Assets | Fixed Asset |  
  |   | FA G/L Journals |  
  |   | FA Journals |  
  |   | FA Reclassification Journals |  
  | Reports | List of Base Reports of Finance |  
Sales | Sales | Contacts |  
  |   | Items/G/L Accounts |  
  |   | Sales Quotation |  
  |   | Sales/Service Order |  
  | Reports | List of Base Reports of Sales|  
Purchase | Purchase | Contacts |  
  |   | Items/G/L Accounts |  
  |   | Purchae Quotation |  
  |   | Purchase Order |  
  | Reports | List of Base Reports of Purchase|  



</body>

</html>

**Comment by TabrejAlam3K** [comment]
No Response received from Mr. Prashant

**Comment by TabrejAlam3K** [comment]
Today morning again i pinged to Mr. Prashant.

**Comment by TabrejAlam3K** [comment]
Credential of 3KT Project is not available.

**Comment by TabrejAlam3K** [comment]
Error we are facing during the login.

![Image](https://user-images.githubusercontent.com/116171982/224000078-b76e93f2-f07f-4cb5-9bf0-fd42c1f80839.png)

**Comment by TabrejAlam3K** [comment]
I have received Chart of Accounts list from Mr. Prashant. Currently I am not able to access the 3KT BC.

**Comment by Ejaz3KT** [comment]
@audhi3k I`ve prepared chart of account document please review the document madam

**Comment by Ejaz3KT** [comment]
@audhi3k Madam, I`ve updated the chart of accounts document and mailed you madam please review the document.

**Comment by Ejaz3KT** [comment]
I`ve Shared the Vendor and customer templates to Mr. prashanth
