### ISSUE TITLE
Flash

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1412]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/fb7ec8d1-f322-486f-b4c5-560fe6eb0efe)






[Sales register.xlsx](https://github.com/3ktech/General/files/15198990/Sales.register.xlsx)

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT assign this task to Mr. Sohan MP.

**Comment by TabrejAlam3K** [comment]
It is related to PoweBI Report and assigned to Mr. Sohan MP

**Comment by Jayanth3KT** [comment]
Hi @TabrejAlam3K  kindly update current status.

CC: @audhi3k

**Comment by audhi3k** [comment]
This is Power BI, align to Mr Sohan


Regards,
Audhi Lakshmi S
Nav/D365BC – Practice Lead
3K Technologies,
9941199474
56/3, Vakil Square,  BTM Layout 1,
Bangalore, Karnataka.
India 560029.
Book time with Audhilakshmi S ***@***.***?anonymous&ep=pcard>
