### ISSUE TITLE
debtors TB balance with ageing

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1415]

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT - Create the case in the support portal and assign the case id for this.

CC : @audhi3k

**Comment by shivakumar3k** [comment]
Informed client to do Ledger reconciliation to verify the Values.

**Comment by TabrejAlam3K** [comment]
We got the confirmation mail from the client as completed.

![Image](https://github.com/3ktech/General/assets/116171982/fa96091e-928f-4038-922d-9e5446aa1390)
