### ISSUE TITLE
FRD preparation

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#142]

**Comment by niranjand22** [comment]
Till purchase..document is finalised and sent to shasthara

**Comment by audhi3k** [comment]
Draft FRD is provided

**Comment by audhi3k** [comment]
FRD walkthrough is completed on 6th March 2023, 4 points which was highlighted in the session to be included in FRD and also the list of reports

**Comment by audhi3k** [comment]
FRD Submitted for client confirmation
