### ISSUE TITLE
FW: PO price issue - reg

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#144]
![Image](https://user-images.githubusercontent.com/116243958/221530028-e694ec8d-454e-4a8c-b1e7-04845e8adf16.png)

**Comment by audhi3k** [comment]
Waiting for information from the client

**Comment by audhi3k** [comment]
Dear Mr Senthil,

The standard process:
Direct Unit Cost field is editable, and the value will be populated from purchase price else from Last direct cost in item card, which can overwrite.

Customized
This field is changed to non-editable, but the functionality remains the same.

Current Requirement 
If the price is not available in the purchase price then it should be updated as zero in purchase order.

To customize the current requirement we would require 4.5 hours, kindly approve the same to proceed further.
Analysis – 1 hour
Development – 2 hours
Testing – 0.5 hours
UAT – 0.5 hours
Deploy – 0.5 hours


Regards,
Audhi Lakshmi S

**Comment by audhi3k** [comment]
Dear Mr Senthil,

Thanks for approving.

We have completed the task in UAT database, kindly check and confirm to deploy in LIVE.


Thanks & Regards,
Audhi Lakshmi S

**Comment by audhi3k** [comment]
Dear Mr Senthil,

Thanks for confirming on the closure.


Regards,
Audhi Lakshmi S
