### ISSUE TITLE
Booking TCS at the time of booking purchase invoices & Sale invoice based on threshold limit

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1448]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/76189014-1193-4c3d-a034-5f81b8343eba)

**Comment by TabrejAlam3K** [comment]
Hi @shivakumar3k - Here, you marked it as completed, but the client has asked for an update.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @shivakumar3k - why you have closed this tikcet from the support portal without the client confirmation. I have received the call from Mr. Krishna on this, He told without our confirm you have closed the ticket.

CC : @audhi3k @Jayanth3KT

**Comment by shivakumar3k** [comment]
Closer Confirmation received & TCS & TDS setup done in Live company.



![Image](https://github.com/3ktech/General/assets/141639359/c56e3c18-7f0d-4855-a279-37ae6d56e2d2)
