### ISSUE TITLE
Report for Stock movement

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1452]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/586c5505-7251-479e-bd9b-a8fa7f5aed8e)

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - Here we need to add the below fields in the Report Output.
1. Consumption Qty
2. COnsumption Value

Original Report is - **Inventory Valuation New**

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please add the below field and populate the value.

Consumption Qty
COnsumption Value
The original report is - Inventory Valuation New ()

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - We got the approval, You can start your development activity.

![Image](https://github.com/3ktech/General/assets/116171982/d2e4c739-d59d-482a-ba56-e072f109f0f3)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - The report is not coming correctly.

![Image](https://github.com/3ktech/General/assets/116171982/d6a025d8-499c-4a68-91bc-e34252b2e955)

**Comment by TabrejAlam3K** [comment]
Item Ledger Entries

![Image](https://github.com/3ktech/General/assets/116171982/e738b339-5837-4c3b-9adb-2ae534129b96)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @johnbosco3K - Report is not working as per the expection or what we have discussed.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K as discussed and informed earlier, Consumption qty and Value is not coming, We have done some tested entries as well.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K  - have you checked the value which is not coming in the report.
CC : @audhi3k

**Comment by johnbosco3K** [comment]
Hi @TabrejAlam3K , I will explain you how to get expected output can we connect?
CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
by mistake closed.

**Comment by TabrejAlam3K** [comment]
Client was not available for do the UAT.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K Can we connect on this because report is not coming correctly.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Waiting for client Mr. Srinivasan response on this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Custome report not reflecting in the UAT Environment. Please check and publish the extension.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/user-attachments/assets/c7c78e18-fd80-4509-ab7b-2b9ad2598523)

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K once you deployed the latest changes into the production, Please let us know.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation on this from the client side, Now we can close the support ticket.

![Image](https://github.com/user-attachments/assets/b42c0037-efaa-4c60-a95f-591a92fd5ab9)

CC : @audhi3k
