### ISSUE TITLE
Report linking purchase against corresponding sales and distribution cost

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1453]

**Comment by TabrejAlam3K** [comment]
We will take this task once the #1360 ticket get completed.

**Comment by TabrejAlam3K** [comment]
Closing the tikcet due to duplicate.

![Image](https://github.com/3ktech/General/assets/116171982/b515b064-ff4a-4496-92cd-ebb3f38c38ba)

CC : @audhi3k
