### ISSUE TITLE
Report of purchase price/sale price/master price statewise wise item number wise for a period

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1454]

**Comment by TabrejAlam3K** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Tabrej/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Tabrej/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Sale | Period |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
Item | Description | Uom | Quantity | Unit Cost | Rate | State Code



</body>

</html>

**Comment by TabrejAlam3K** [comment]
Required two different reports. Format we have attached.

[CAS-02198-P2T2N5.xlsx](https://github.com/3ktech/General/files/15411910/CAS-02198-P2T2N5.xlsx)
1. Sales Price Report
2. Purchase Price Report

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - You can start your activity, we got approval from the client.

![Image](https://github.com/3ktech/General/assets/116171982/8961d8e8-f7e9-497d-bbc3-684a3edb0a6a)

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please provide updates on this.

**Comment by johnbosco3K** [comment]
Unit price issue is fixed.

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - See and fix the below issues.
1. Purchase Price Report - Fix the state code issue, it is currently coming as blank.
2. Sales Price Report - Fix the unit price issues, Currently the unit price value is coming in wrong.

**Comment by johnbosco3K** [comment]
Have you tried any new transaction to test the report?

**Comment by johnbosco3K** [comment]
![Image](https://github.com/3ktech/General/assets/153084240/73334c0c-3f13-4ad9-a401-92bfa959a2f9)

**Comment by TabrejAlam3K** [comment]
We are not able to complete the UAT because Mr. Srinivasan is on leave today.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - we got the approval on this ticket, you can start your development activity.
1. Purchase Price List - **Technical Hrs 12**
2. Sales Price List - **Technical Hrs 10**

CC : @audhi3k

**Comment by johnbosco3K** [comment]
Hi @TabrejAlam3K , New Format Attachment is not available. Please add here

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - I have attached the new Excel format as per our discussion. See below.

[Purchase Price and Sales Price.xlsx](https://github.com/user-attachments/files/15880342/Purchase.Price.and.Sales.Price.xlsx)

CC : @audhi3k

**Comment by johnbosco3K** [comment]
Hi @TabrejAlam3K , This attachment is old format, can you add new.
CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K 

[Posted Collection Apportionment (1).xlsx](https://github.com/user-attachments/files/15880919/Posted.Collection.Apportionment.1.xlsx)
[Posted Billing Apportionment (1).xlsx](https://github.com/user-attachments/files/15880920/Posted.Billing.Apportionment.1.xlsx)

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - I have done the internal testing on the below report. There are a few things we need to correct.
1. Purchase Price Report
**Tons** - It should be in two decimal places.
**Amount in Cr INR** - It should be in two decimal places.
**Price per KG** - It should be in two decimal places.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please updade on this, this is priority task which we was expecting to close by today.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - As discussed, Data is not coming properly as per the posted transaction.

![Image](https://github.com/3ktech/General/assets/116171982/9611df31-8c44-4aad-816f-ae6a6c383dd6)

CC : @audhi3k

**Comment by johnbosco3K** [comment]
Hi @TabrejAlam3K , Data are fetched from Purchase Invoice Line only. You are checking item ledger entries.

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Sales Price Report format required just like Purchase Price Report format, currenlty format is not coming correctly, Please correct it and let us know.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Waiting for client Mr. Srinivasan response on this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Custome report not reflecting in the UAT Environment. Please check and publish the extension.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/user-attachments/assets/1b7ce16f-2200-477a-b135-ce353c108a9f)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @johnbosco3K - Please plan to move the below report into the proudction.
1. Purchase Price Report

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - As discussed and informed, Please deploy this changes into the Production.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K once you deployed the latest changes into the production, Please let us know.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation on this from the client side, Now we can close the support ticket.

![Image](https://github.com/user-attachments/assets/b42c0037-efaa-4c60-a95f-591a92fd5ab9)

CC : @audhi3k
