### ISSUE TITLE
TDS is not getting reversed in credit notes

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1458]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/6672946a-5e21-40af-b28a-0ed06e25e24b)

**Comment by TabrejAlam3K** [comment]
Closing this ticket as completed, we need to raise a new ticket for the new requirement related to the SMAE ticket.

![Image](https://github.com/3ktech/General/assets/116171982/b171ff03-3edc-4326-a924-a4d833d7491f)
