### ISSUE TITLE
The id from which voucher is entered and the date, time should be displayed in ledger/vendor line item/customer line item

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1459]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/b93108a8-9f29-4845-b2af-7757d7cd6701)

**Comment by TabrejAlam3K** [comment]
We are going to discuss with the client afterthat we will update the current status.

**Comment by TabrejAlam3K** [comment]
Need to enable the below fields
1. SystemCreatedAt 
2. SystemCreatedBy 
3. SystemModifiedAt 
4. SystemModifiedBy

**Comment by TabrejAlam3K** [comment]
1. General Ledger Entries
2. Customer Ledger Entries
3. Vendor Ledger Entries.

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please provide updates on this.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @johnbosco3K - tested not yet enabled the original fields which we have required.

**Comment by TabrejAlam3K** [comment]
Deployment in the Production Environment Done, Waiting for Closure confirmation from the Client side.

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation from the client side as completed in production.

![Image](https://github.com/3ktech/General/assets/116171982/b76aab66-ff68-4926-b097-635e8c55c730)
