### ISSUE TITLE
DYN 365 BC / Fichtner India/ 3KT / 17.05.2024 / Mur-084 / Purchase and Sales register - Additional fields

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1460]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/e9eb45c6-9f51-476a-a744-9b6e584e9d45)



[Sales Register_Apr'2024.xlsx](https://github.com/3ktech/General/files/15348827/Sales.Register_Apr.2024.xlsx)
[Purchase register April 24.xlsx](https://github.com/3ktech/General/files/15348826/Purchase.register.April.24.xlsx)

**Comment by Ejaz3KT** [comment]
We have deployed the changes in to production environment waiting for the client confirmation

CC: @audhi3k  @sandhya3k

**Comment by Ejaz3KT** [comment]
Hi Team The issue has been resolved and confirm by the client we can close this ticket

CC: @audhi3k @sandhya3k
