### ISSUE TITLE
RE: Stock statement vs TB

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1462]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/243cbea9-8803-4354-a10a-3f5fb63e43e5)



[Inventory Valuation Mar24.xlsx](https://github.com/3ktech/General/files/15349148/Inventory.Valuation.Mar24.xlsx)

**Comment by shivakumar3k** [comment]
Explained the reason for Mismatch to Mr. Srinivasan sir and received the closer confirmation.



![Image](https://github.com/3ktech/General/assets/141639359/24df5ff7-484c-486d-9306-f9674e190b2a)
