### ISSUE TITLE
There should be an option for entering exchange rates in system and assign GL codes for gain/loss

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1463]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/c7cb24b2-e705-4424-ade5-f59b79b8ba95)

**Comment by TabrejAlam3K** [comment]
We are going to discuss with the client afterthat we will update the current status.

**Comment by TabrejAlam3K** [comment]
Deployment in the Production Environment Done, Waiting for Closure confirmation from the Client side.

**Comment by TabrejAlam3K** [comment]
Hi @audhi3k  Mam, We got the closure confirmation from the client side.

![Image](https://github.com/3ktech/General/assets/116171982/ae492ab1-5d8c-4f31-aae2-a6f6812702e1)
