### ISSUE TITLE
Vendor and customer statements should show clearing document

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1464]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/c5fa7d1f-b7f0-4196-909d-da7646496f9f)

**Comment by TabrejAlam3K** [comment]
Hi @audhi3k  Mam, we got the the closure confirmation on this.

![Image](https://github.com/3ktech/General/assets/116171982/71aa59fa-784a-4668-b901-eea8b8885431)
