### ISSUE TITLE
Vendor group-employee,salt,atta,admin,transporter,MSME to be mandatory

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1465]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/cba02aae-94b6-43f4-a53e-3a8742fafc9b)

**Comment by TabrejAlam3K** [comment]
We need to add 5 new fields on Vendor Card as boolean field.
1. Employee
2. Salt
3. Atta
4. Admin
5. MSME

**Comment by TabrejAlam3K** [comment]
1. Purchase Order
2. Purchase Invoice

**Comment by TabrejAlam3K** [comment]
We need to create 1 field called "**Vendor Group Type**" and below are the options
1. Employee
2. Salt
3. Atta
4. Admin
5. MSME

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - You can start your activity, we got approval from the client.

![Image](https://github.com/3ktech/General/assets/116171982/92e6dda9-91a8-414a-b424-10eb653969f9)

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please provide updates on this.

**Comment by TabrejAlam3K** [comment]
This is coming correctly.

![Image](https://github.com/3ktech/General/assets/116171982/a3e1aa6b-80f4-4efe-aa69-4d2dc8a0278f)

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Additional requirements are listed below.
1. need to add the below fields separately
    MSME Vendor - Boolean
    MSME Certificate No. - Text
    MSME Valid Upto - Date
2. Create the New table and list page
  Vendor Group Type

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - We can deploy this changes into the production. We have done the UAT and client confirmed for Deploy in the Production.

**Comment by TabrejAlam3K** [comment]
Deployment in the Production Environment Done, Waiting for Closure confirmation from the Client side.

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation from the client side for production environment.

![Image](https://github.com/3ktech/General/assets/116171982/62913d8e-06d2-4341-9850-955badc1d559)
