### ISSUE TITLE
When we run the general ledger or special ledger, vendor code, name, customer code, name should appear.

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1466]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/471afd40-f751-4058-896e-30736670ff1b)

**Comment by TabrejAlam3K** [comment]
You need to add the below fields to the **General Ledger Enties** and populate the realed value from the respective master. 
1. Customer No.
2. Customer Name
3. Vendor No.
4. Vendor Name

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please provide updates on this.

**Comment by TabrejAlam3K** [comment]
Deployment in the Production Environment Done, Waiting for Closure confirmation from the Client side.

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation from the client side as completed in production.

![Image](https://github.com/3ktech/General/assets/116171982/b76aab66-ff68-4926-b097-635e8c55c730)
