### ISSUE TITLE
Fichtner Priority Task 28/02/23

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#148]
![Image](https://user-images.githubusercontent.com/116243958/222044878-b6f6baa9-6ab3-4b23-9f0c-638494b2af2f.png)

**Comment by niranjand22** [comment]
checked and updated to client

**Comment by niranjand22** [comment]
they also asked to create base calender..that is also created

**Comment by audhi3k** [comment]
@niranjand22  validate the masters and setup in Production Environment

**Comment by niranjand22** [comment]
This is done. Changes are updated to Amar. he is working on this

**Comment by audhi3k** [comment]
Closing the ticket
