### ISSUE TITLE
UAT/Training

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#149]

**Comment by niranjand22** [comment]
•	Discussed Chart Of Accounts.
•	Discussed Asset Category and Subcategory
•	Discussed Vendor Master
•	Discussed Vendor Bank Master
•	Discussed about GST Group Code and HSN Code.

**Comment by niranjand22** [comment]
Discussed no. series
Discussed config package
Company Information

**Comment by niranjand22** [comment]
	Discussed Dimension, Dimension Values. 
	Discussed Bank Account Mater.
	Discussed Fixed Asset Master.

**Comment by niranjand22** [comment]
	Discussed Purchase invoice for fixed asset, and purchase invoice with GST reversal.
	Discussed Payment Journal vouchers, Bank Journal vouchers, and General Journal Batches.
	Discussed Journal Voucher, Standard Journal.
	Discussed Financial reporting, Analysis Reporting.

**Comment by niranjand22** [comment]
HSN-GST Group and GST rates  has to be configured.
TDS has to be configured

**Comment by niranjand22** [comment]
Key Points: 
	Discussed Purchase invoice with TDS, Financial Reports.
	Discussed Recurring General Journal.
	Discussed Bank Reconciliation, Statutory Payments, and GST Settlement.
	Discussed Vendor detail trial balance, Day book Vendor Ledger entry, and Aged Accounts payable.
Actions Items:
	The 3KT team should explain recurring journals with GST and TDS related to Purchases to the Vridhi team.

**Comment by niranjand22** [comment]
•	Discussed purchase invoice for a fixed asset with the registered vendor with GST.
•	Discussed purchase invoice for a fixed asset with an Unregistered vendor.
•	Discussed Purchase invoice for a fixed asset wherein 50% of GST accounted as GST and the remaining balance as capitalization.
•	Discussed purchase invoice for expenses with TDS.
•	Discussed purchase invoice for expenses wherein 50% of GST is accounted as GST and the remaining balance as expenses.

**Comment by niranjand22** [comment]
•	Discussed Prepayment or advance payment to the vendor with TDS.
•	Discussed Purchase invoice and apply or deduct the advance payment amount from that particular invoice.
•	Discussed Fixed assets, calculate deprecation, and salvage value.
•	Discussed customer cards, sales invoices, and the sale of a fixed asset.
•	Discussed Payment for direct expenses, salary expenses, and TDS payment.
•	Discussed GST reversal
•	Discussed Aged account payable report, vendor trial balance, cash book, day book, bank book, and financial reporting.

**Comment by niranjand22** [comment]
	Discussed purchase invoice expenses with TDS and GST.
	Discussed Payment for TDS.
	Discussed GST Payment. 
	Discussed vendor-detail trail balance, GSTR-3B, and financial reporting.

**Comment by niranjand22** [comment]
Key Points: 
	Discussed Deferral Template card, and Deferral Schedule.
	Discussed Chart of Accounts, Net change, and Balance.
	Discussed Financial Reporting, Row Definition, and Column Definition.
Actions Items:
	Vridhi team should fill the data in the templates and share it with the 3KT team.

**Comment by niranjand22** [comment]
they have sent COA for live
