### ISSUE TITLE
mismatch in quantity

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1490]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/4744e1c7-8fab-4a67-8362-15dd3712395d)

**Comment by TabrejAlam3K** [comment]
Hi @shivakumar3k - have you done anything on this?

**Comment by shivakumar3k** [comment]
Item Ledger reconciliation has been completed for Item number ANNZ100. Here's an explanation for the quantity mismatch:

1. During purchase, the user not considered the purchase return.
2. A negative adjustment was manually entered by the user in May 2023, which was not system-generated.
3. Regarding sales, a shipment was made against sales order number SO/0327 on August 22, 2023, but the sales invoice was not generated. Consequently, there exists a quantity discrepancy between the sales register and the Item Ledger entries.

**Comment by shivakumar3k** [comment]
Closing with Client approval

![Image](https://github.com/3ktech/General/assets/141639359/eeb75697-bf2c-4125-b038-ceb13e397934)
