### ISSUE TITLE
Need a fix for ECOMM-1550: SwiftLink | BC | Modify your extension so it’s compatible with the version 24.2.19868.0

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1491]

**Comment by Jayanth3KT** [comment]
Hi @Shasthara  sir kindly create Consulatant name as Annand.

**Comment by TabrejAlam3K** [comment]
Hi @anandakumar3k - Please provde the estimated and approved hours for this ticket.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Based on the support poral i am closing this tikcet as completed.

CC : @audhi3k
