### ISSUE TITLE
Ammendment in sale invoice

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1494]
[Sales.Invoice.Report.12.xlsx](https://github.com/user-attachments/files/15573743/Sales.Invoice.Report.12.xlsx)

[FDD_Ammendment in sale invoice_CAS-02239-Q2W3C2.xlsx](https://github.com/user-attachments/files/15605259/FDD_Ammendment.in.sale.invoice_CAS-02239-Q2W3C2.xlsx)

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/eb219da7-d831-4086-88b7-14fb94eae233)

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K Can we connect on this to discuss?

**Comment by TabrejAlam3K** [comment]
Hi @sruthi1017 - As discussed about the requirement, Please analyse and share the time effort before starting the activity.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @sruthi1017 - I have added the above excel sheet with name (FDD_Ammendment in sale invoice_CAS-02239-Q2W3C2.xlsx)

**Comment by TabrejAlam3K** [comment]
Uma Consumer Product Pvt Ltd. - Complete address should be come from the Location Master.

![Image](https://github.com/3ktech/General/assets/116171982/09a80731-225a-4e96-a1b7-7f173ef47450)

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - Please update the ticket development progress.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - Please merge this changes into the master. Mr. @johnbosco3K Please deploy this changes into production.

CC : @audhi3k

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K  Sure i will merge the changes to master

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - early morning please plan to deploy this changes into the production.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - is the deployment done?
CC : @audhi3k

**Comment by johnbosco3K** [comment]
Hi @TabrejAlam3K  , It's already deployed

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation.

![Image](https://github.com/3ktech/General/assets/116171982/37adb0b0-0b33-4e61-9968-437770775aed)

CC : @audhi3k
