### ISSUE TITLE
Dash Board SKU concerns

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1495]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/771380bb-dfc9-4d82-a6bc-c241896aa2ac)

**Comment by TabrejAlam3K** [comment]
@Jayanth3KT - this is related to Power BI Report. check and assign to respective person.

**Comment by TabrejAlam3K** [comment]
@Jayanth3KT - this is related to Power BI Report. check and assign to respective person.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Closed as compled based on confirmation given by Mr. Sohan.

CC : @audhi3k
