### ISSUE TITLE
Dispatch from details needs to be added in Sales invoice

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1496]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/ec5a1fed-bf90-4e7e-8ba5-e545771c81fb)







[Sales Invoice Report (12).xlsx](https://github.com/user-attachments/files/15541828/Sales.Invoice.Report.12.xlsx)

**Comment by TabrejAlam3K** [comment]
Hi @audhi3k Mam, Closig this ticket as duplicate as dicussed with the client.
