### ISSUE TITLE
DYN 365 BC / Fichtner India/ 3KT / 03.06.2024 / Mur-086 / Additional column required in Customer - Summary Aging Simp

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1497]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/830d4a8b-ab8a-4d8d-ac2d-4abe4812fa16)






[CUSTOMER SUMMARY AGING SIMP-From BC as of 31st march 2024.xlsx](https://github.com/user-attachments/files/15541878/CUSTOMER.SUMMARY.AGING.SIMP-From.BC.as.of.31st.march.2024.xlsx)

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam we got the approval for this ticket we can start working on it 

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
UAT session of customer aging report is completed client has confirm to deploy the report in production @sandhya3k madam I`ll inform you the deployment timings please be ready to deploy the report

CC: @audhi3k @sandhya3k

**Comment by Ejaz3KT** [comment]
Mr. Murali sir will give the permission for deployment of customer aging report changes tomorrow evening

CC: @audhi3k @sandhya3k

**Comment by Ejaz3KT** [comment]
Waiting for the client confirmation for clouser

**Comment by Ejaz3KT** [comment]
Client Has confirmed we can close this ticket
