### ISSUE TITLE
Erro while posting Purchase Invoice

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#15]
It occurs for sales and purchase when it has TDS

**Comment by 3ktech** [comment]
@Mahesh3ktech , can you please update if you have got the connection back?
CC: @audhi3k

**Comment by 3ktech** [comment]
Still there is no access to BC for the further investigation.

**Comment by 3ktech** [comment]
@Mahesh3ktech , the credentials are ready i hope. you have to start with this.

**Comment by 3ktech** [comment]
@audhi3k  and @Amar-3KT  will test the same in standard system to replicate the issue and will share feedback

**Comment by 3ktech** [comment]
Ticket has been raised with MS. Yet to receive response.

**Comment by audhi3k** [comment]
Microsoft is analysing on the issue and Mr Amarjeet is co-ordinating with them

**Comment by audhi3k** [comment]
@Mahesh3ktech, kindly co-ordinate with Mr Amarjeet, @Amar-3KT

**Comment by Amar-3KT** [comment]
In 3KT demo error not showing. Working on Fichtner demo

**Comment by Amar-3KT** [comment]
In 3KT demo and Fichtner UAT now its working fine.

Its TDS section related issue. I have deleted tds section and created new, now i am able to post all purchase invoices with concessional code.

cc @audhi3k @Mahesh3ktech
