### ISSUE TITLE
Vridhi Changes

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#150]

**Comment by niranjand22** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Change Bank Branch   no to IFSC Code | Bank
-- | --
Change Bank Branch no to IFSC Code | Vendor Bank
Change Caption from VAT Registration to   CIN. | Vendor/Company Information
Employee Bank Details Should be captured | captured as customization in the Dimension value
  | Employee => Bank Details to be capture (Dimesnion value   table)
  | Bank Account No.
  | IFSC Code
  | Bank Name
  | Bank Branch Name
Bank Duplicacy Pop up in Employee Bank   Details |  
  |  
Bank Duplicacy Pop up(Account no should   be unique) | Vendor Bank



</body>

</html>

**Comment by niranjand22** [comment]
Hi @Mahesh3ktech  
1.Please add IFSC and Bank Account field in Vendor Bank List Page
2. Please add Posting group in bank/cash payment voucher

cc. @audhi3k

**Comment by Mahesh3ktech** [comment]
@niranjand22 both the changes have been done, Kindly check and update.

**Comment by niranjand22** [comment]
Posting group is okay but Bank account has been added twice in vendor bank list page. @Mahesh3ktech

**Comment by Mahesh3ktech** [comment]
Bank account is rectified, and it will show once. 
Posting Group added in Journal Voucher page.
