### ISSUE TITLE
Sending invoice via email from BC

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1500]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/c645b758-ef95-431d-a02b-e5042a0f7d02)




[SI-PE003787 ∙ ETNO (PPAR - BELGIUM).pdf](https://github.com/user-attachments/files/15567657/SI-PE003787.ETNO.PPAR.-.BELGIUM.pdf)

**Comment by niranjand22** [comment]
hi @Jayanth3KT  make sure you are putting contact person name

**Comment by Jayanth3KT** [comment]
@niranjand22 For TP you are the primary consultant right sir, Kindly mention if i am done wrong somewhere.

**Comment by niranjand22** [comment]
Case is resolved.

@audhi3k

**Comment by niranjand22** [comment]
> [@niranjand22](https://github.com/niranjand22) For TP you are the primary consultant right sir, Kindly mention if i am done wrong somewhere.

Hi @Jayanth3KT , I mean to say...when you assign the case ..make sure you also specifiy who is contact person from client site..ie who has raised the ticket.
