### ISSUE TITLE
Sales person report

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1502]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/8bbce015-beb3-4e5d-9a35-064b27a58a00)

**Comment by niranjand22** [comment]
[Sales Person Report Merit UK.xlsx](https://github.com/user-attachments/files/15815037/Sales.Person.Report.Merit.UK.xlsx)

Pls find field mapping file @sandhya3k  Lets connect 

CC @audhi3k
