### ISSUE TITLE
DYN 365 BC / Fichtner India/ 3KT / 06.06.2024 / Mur-087 / Bank receipt voucher - cost centre to populate based on cost unit

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1508]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/9776f474-e99c-4b51-8b4a-c0dd2efa10f1)

**Comment by Ejaz3KT** [comment]
Closing the ticket due client is not responding

CC: @audhi3k @sandhya3k
