### ISSUE TITLE
RE: BC and Jetreport Queries

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#151]
you please help me out with few basics step for adding new user to the BC and accessing the Jet report.
 
We have the tenant in India (meritgroup.co.uk).

**Comment by niranjand22** [comment]
CAS-01184-R4G9X4

**Comment by niranjand22** [comment]
New user swathi and pawan are getting jet report Plugin error when they are opening the excel file with jet report  .
 They have installed same plugin version which their colleagues are using.

**Comment by niranjand22** [comment]
once they share the error ss.. i will notify Kartik D

**Comment by niranjand22** [comment]
sentfollow up to ribinson

**Comment by niranjand22** [comment]
they have not responded for follow up

**Comment by audhi3k** [comment]
@niranjand22, kindly co-ordinate Mr KarthikD

**Comment by niranjand22** [comment]
Issue has been resolved by them -reported by the client.
