### ISSUE TITLE
Reverse Transaction issue

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1519]

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT - Assign the case id for this.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - As discussed, Please provide the detials. Why it is working for General Ledger Entries and not working for Customer Ledger Entries.
CC : @audhi3k

**Comment by johnbosco3K** [comment]
Hi @TabrejAlam3K , Can you replicate issue into sandbox.

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K and @sruthi1017 - Please deploy the chages and let us know, we need to confirm to client as well.
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam, we got the closure confirmation.

![Image](https://github.com/3ktech/General/assets/116171982/1a07fb20-f34a-4934-be9c-173e2840c651)
