### ISSUE TITLE
Outbound integration authentication issue,

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#152]

**Comment by Mahesh3ktech** [comment]
Client should share the Adrenalin username and password to test the process.

**Comment by Shasthara** [comment]
# 127 Dependency

**Comment by Mahesh3ktech** [comment]
Microsoft Authenticator is enabled for all the users, need to be disabled for adrenalin team user ID so that we can test.
Same point going to be discussed with client on today review meeting.

**Comment by Mahesh3ktech** [comment]
As discussed with Ms.Padma, I'm trying to change the method access token generation with predefined. 
We required some more time to test that method.

**Comment by Mahesh3ktech** [comment]
We done the development with OAuth 2.0 methodology and its standard and suggested by Microsoft and we conveyed the same thing to Fichtner and Adrenalin team.

Now the Adrenalin team informed us that they will check feasibility and revert to us.

Waiting for Adrenalin team replay.

**Comment by niranjand22** [comment]
completed
