### ISSUE TITLE
System releases for 240200

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1539]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/8d1b54c2-7df5-4d0a-9f39-0f522dd6f55d)



![Image](https://github.com/3ktech/General/assets/142868335/ab23fadb-fc25-4f04-a884-51c47a27a21a)

**Comment by niranjand22** [comment]
Hi @Jayanth3KT , pls update the email address or name of the person from client side. So we can connect with them
