### ISSUE TITLE
API Key for Purchase templet

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1544]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/011201d2-f1b8-4152-8e14-6392c5ffa26c)

**Comment by TabrejAlam3K** [comment]
Hi @sandhya3k - Have you started the activity?

CC : @audhi3k @johnbosco3K

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K and @sandhya3k - Please update on this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K and @sandhya3k - Please estimate the hours and let us know, We need to inform Client as well.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - We got the approval on this, you can start your activity and try to complete it on time.

![Image](https://github.com/user-attachments/assets/cdeb1fc2-7aa7-4f6d-b84c-ef921cfbeb8a)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
[Auto_Purchase_Templet.Infosense.xlsx](https://github.com/user-attachments/files/16369688/Auto_Purchase_Templet.Infosense.xlsx)

**Comment by TabrejAlam3K** [comment]
Hi @sandhya3k - When we can start testing on this?

CC : @audhi3k

**Comment by sandhya3k** [comment]
Hi @Tabrej ***@***.***>,

Post lunch will connect and test.

Thanks & Regards
Sandhya M|Associate Consultant

3K Softech Pvt Ltd (Subsidiary of 3K Technologies)

Direct : +918121999723| Email: ***@***.******@***.***>


________________________________

**Comment by TabrejAlam3K** [comment]
Hi @sandhya3k - I tested it is working fine in case of Manual activity by the user. Please confirqure the job queue for auto testing.

Note : Please check and remove the mandatory fields for - **Start Data**, **End date** and **Deferral Code**

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
waiting for client response on this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We have final UAT session with the client at 4:30PM today, we will update the status based on the uat session.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation on this from the client side. We can close the tikcet from the support portal.

![Image](https://github.com/user-attachments/assets/00965d1a-acdb-40fc-82c1-72f7a66149c8)

CC : @audhi3k
