### ISSUE TITLE
creating new SKUs

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#155]

**Comment by audhi3k** [comment]
We have created a new field in Item card as RRL Item No., which should be updated in UL company with Item no. of RRL

**Comment by TabrejAlam3K** [comment]
Today need to test and confirm.

**Comment by TabrejAlam3K** [comment]
Facing some error when we try to proceed the IC Inbox Transaction.


![Image](https://user-images.githubusercontent.com/116171982/224000504-3dd5946a-993d-4300-8db8-9ddf5011024b.png)

**Comment by TabrejAlam3K** [comment]
Facing some error and it is already highlighted to Mr. Padma.

**Comment by audhi3k** [comment]
Object Merged to PerProd-Complete Testing to be done on PreProd
