### ISSUE TITLE
RE: Flowing of Invoice No. under Financial report having a drilling down facility to retrieve the transactions

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1551]

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please plan to deply the changes into the production.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - have you deployed the changes in Production?

CC : @audhi3k

**Comment by johnbosco3K** [comment]
Hi @TabrejAlam3K , This is already deployed in production. Please check and confirm.

CC @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please deploy this changes into the production after 8:00PM today.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K -Please deploy the changes into the production. Client confirmed for deployment.

![Image](https://github.com/user-attachments/assets/6ccc8cbe-747a-48ad-8d60-cdbdacc26f17)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation on this from the client side.

![Image](https://github.com/user-attachments/assets/956501b1-61da-4db8-920a-4bfcdd90a98e)

CC : @audhi3k
