### ISSUE TITLE
DYN 365 BC / Fichtner India/ 3KT / 04.07.2024 / Mur-089 / Unable to do Get receipt lines in purchase invoice - 100PJ240352

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1554]

**Comment by Prakash3K** [comment]
@Ejaz3KT 


![Image](https://github.com/3ktech/General/assets/140147250/9eaf21d8-c08c-451d-be54-5faf90cbcccf)

**Comment by Ejaz3KT** [comment]
Issue has been resolved by Mr. Amarjeet and we got the confirmation for closure 

CC: @audhi3k  @sandhya3k  @Amar-3KT
