### ISSUE TITLE
E invoice not generating

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1555]

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT and @Prakash3K - Provide the case id for this.

CC : @audhi3k

**Comment by Prakash3K** [comment]
Hi @TabrejAlam3K sir, can I know the user ID

**Comment by TabrejAlam3K** [comment]
@Prakash3K - they have sended email on mySupprt@3ktechnologies.com

User - Krishna Rao

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please provide the estimated effort hours on this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - We got the approval on this, you can start your development activity.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please resolved the below error, we are getting while generating the E-Invoice
Document No. : **TST0043 ∙ M/s. SUNSHINE GLOCAL**
Error Message : [
  {
    "ErrorCode": "5002",
    "ErrorMessage": "The field Assessable Amount (Total Amount - Discount) must match the regular expression '^

d+.?

d{0,2}$'."
  },
  {
    "ErrorCode": "5002",
    "ErrorMessage": "The field Assessable Amount (Total Amount - Discount) must be between 0 and 999999999999.99."
  },
  {
    "ErrorCode": "5002",
    "ErrorMessage": "The field Total Amount (Unit Price * Quantity) must match the regular expression '^

d+.?

d{0,2}$'."
  },
  {
    "ErrorCode": "5002",
    "ErrorMessage": "The field Total Amount (Unit Price * Quantity) must be between 0 and 999999999999.99."
  },
  {
    "ErrorCode": "5002",
    "ErrorMessage": "The field Total Item Value must match the regular expression '^

d+.?

d{0,2}$'."
  },
  {
    "ErrorCode": "5002",
    "ErrorMessage": "The field Total Item Value must be between 0 and 999999999999.99."
  },
  {
    "ErrorCode": "5002",
    "ErrorMessage": "The field Assessable Amount (Total Amount - Discount) must match the regular expression '^

d+.?

d{0,2}$'."
  },
  {
    "ErrorCode": "5002",
    "ErrorMessage": "The field Assessable Amount (Total Amount - Discount) must be between 0 and 999999999999.99."
  },
  {
    "ErrorCode": "5002",
    "ErrorMessage": "The field Total Amount (Unit Price * Quantity) must match the regular expression '^

d+.?

d{0,2}$'."
  },
  {
    "ErrorCode": "5002",
    "ErrorMessage": "The field Total Amount (Unit Price * Quantity) must be between 0 and 999999999999.99."
  },
  {
    "ErrorCode": "5002",
    "ErrorMessage": "The field Total Item Value must match the regular expression '^

d+.?

d{0,2}$'."
  },
  {
    "ErrorCode": "5002",
    "ErrorMessage": "The field Total Item Value must be between 0 and 999999999999.99."
  }
]

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K -Please deploy this changes into the production environment.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
waiting for client closure confirmation on this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We will close the below ticket by EOD. 

![Image](https://github.com/user-attachments/assets/c6807ab8-2dcf-4a26-a6d6-f193391845eb)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the clsoure confirmation on this from the client side. We can close the tikcet from the Support Portal.

![Image](https://github.com/user-attachments/assets/4672c24c-a401-4dd1-9822-ff576905c9f4)

CC : @audhi3k
