### ISSUE TITLE
ERP Item Master Card update req..:CAS-01185-J7P9T1

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#156]

**Comment by niranjand22** [comment]
WAITING FOR CLIENT INFO

**Comment by niranjand22** [comment]
COMPELETD IN UAT, WAITING FOR CONFERMATION TO DEPLOY IN LIVE

**Comment by niranjand22** [comment]
3 HRS CONSUMED

**Comment by audhi3k** [comment]
We have completed the field customization in UAT and moved to LIVE
Added the following fields:
1. Last Modified by
2. Created By
3. Created On

**Comment by audhi3k** [comment]
Dear Mr Vimal Raj,

Through screen sharing session we have tested the scenarios in LIVE and was working fine. 

As per your confirmation we are closing this ticket.


Regards,
Audhi Lakshmi S
