### ISSUE TITLE
Master data-Column Requirements

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1562]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/f0c5221d-04d6-4df6-a27d-abdbb3d41b6d)

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K we need to enable the below field on the below list pages.
List of Pages
1. Customer List (22, List)
2. Vendor List (27, List)
3. Item List (31, List)

List of Fields
1. SystemCreatedAt 
2. SystemCreatedBy
3. SystemModifiedAt
4. SystemModifiedBy

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
1. Customer List (22, List)
2. Vendor List (27, List)
3. Item List (31, List)
4. Item Ledger Entires
5. Customer Ledger Entries
6. Vendor Ledger Entries
7. General ledger entries

**Comment by TabrejAlam3K** [comment]
Hi @sruthi1017 - We required discussion on this. once you back online let us know. every page you have give the wrong caption for SystemCreateAt

![Image](https://github.com/user-attachments/assets/0a002bd0-fea5-41a8-9e02-890d4068ccbb)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sruthi1017 - In uat environment you was give correctly.

![Image](https://github.com/user-attachments/assets/a49feb40-6c1f-4543-8728-b2f3ba2bf1e8)

**Comment by TabrejAlam3K** [comment]
Waiting for client closure confirmation.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We will close the below ticket by EOD. 

![Image](https://github.com/user-attachments/assets/c6807ab8-2dcf-4a26-a6d6-f193391845eb)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the clsoure confirmation on this from the client side. We can close the tikcet from the Support Portal.

![Image](https://github.com/user-attachments/assets/4672c24c-a401-4dd1-9822-ff576905c9f4)

CC : @audhi3k
