### ISSUE TITLE
TDS payment posting entry..

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1566]

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/user-attachments/assets/28da144e-7431-45a0-b9ee-021cdc86657d)

**Comment by TabrejAlam3K** [comment]
Waiting for client closure confirmation.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation on this

![Image](https://github.com/user-attachments/assets/fcbd22c1-3bc3-4cd6-8a4d-586636a2648b)

CC : @audhi3k
