### ISSUE TITLE
Id Mapping Issue

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1569]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/user-attachments/assets/dd61b05d-12e7-474f-8a8f-3e715c3e2de0)

**Comment by TabrejAlam3K** [comment]
Id mapped and informed client for check in the Production Environment.

CC  @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation on this from the client side.

![Image](https://github.com/user-attachments/assets/d33f5ca1-3110-4ac1-ac29-e62c9e795499)

CC : @audhi3k @Shasthara
