### ISSUE TITLE
Work flow:CAS-01186-L9J0D8

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#157]

**Comment by audhi3k** [comment]
Dear Mr Senthil,

As analysed in the screen sharing session, the purchase approval will be generated based on MFG Category (on purchase order – “PO WO Category”).

If the MFG category is <blank> then 1st Approver is PRABU, if MFG category is service then it is BOOPALAKRISHNAN

Kindly update the MFG Category (PO WO Category) correct to trigger the respective approval.

Kindly confirm on the closure.
