### ISSUE TITLE
TDS Payment posting

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1572]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/user-attachments/assets/8d699da9-36eb-415a-99d1-469893b5cfb0)



![Image](https://github.com/user-attachments/assets/f3d54370-9924-4cda-9e6a-31a3476a7ad9)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @shivakumar3k - Please update the current status of this ticket.

CC : @audhi3k

**Comment by shivakumar3k** [comment]
Closed With Customer Confirmation.

![Image](https://github.com/user-attachments/assets/fcd8c2cd-4db8-4b65-89bb-1c5c0be2161a)
