### ISSUE TITLE
TB account code and name should come in two different columns

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1598]

**Comment by Prakash3K** [comment]
As per discussion with Mr. Senthil, he will check with Pujas and come back with requirement 


CC: @Tushargupta3K @audhi3k

**Comment by Prakash3K** [comment]
TB account code need to create one report and show to Pujas in Excel for confirmation 


CC: @Tushargupta3K

**Comment by TabrejAlam3K** [comment]
Mr. @Tushargupta3K - If you requested to close the tikcet from the support portal, then you need to close the tikcet from git as well.

![Image](https://github.com/user-attachments/assets/13e4e8f6-14d2-4195-9e3a-bb2297798131)

CC : @audhi3k
