### ISSUE TITLE
Vridhi-BPV New Fields Add

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#163]
In Bank Payment voucher.
Four Fields has to be Added.

1. Employee Bank Account No
2. Employee IFSC Code
3. Vendor Bank Account No
4. Vendor IFSC code

When Account type is selected as Employee ..Emplyee Bank details fields should be updated. (Accnt No and IFSC)
and when account type is selected as Vendor- Vendor bank detail has to be updated.(Accnt No and IFSC)

**Comment by niranjand22** [comment]
cc @audhi3k

**Comment by Mahesh3ktech** [comment]
Added new fields and functionality and tested, it's working. kindly close this ticket.
