### ISSUE TITLE
Dimension visibility in Reports

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#164]
Client Shared the Snapshot for the Voucher Reports.

![Image](https://user-images.githubusercontent.com/116171982/224902364-3d215b2a-fa7d-44d9-8fde-d94ae80e73f7.png).

**Comment by TabrejAlam3K** [comment]
Currently this is available in BC.

![Image](https://user-images.githubusercontent.com/116171982/224904030-7b2de866-455b-4213-9b35-278f99a1bac3.png)

**Comment by TabrejAlam3K** [comment]
@sandhya3k - I have shared the snapshot of both the Application NAV16 and BC.

CC : @audhi3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K 
i hope u checked in the UAT environment.

cc: @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Related to this is we have another report with same dimension issues.

**NAV16 Sanpshot. - Report Filter and Report ID**
![Image](https://user-images.githubusercontent.com/116171982/225271721-c26932e9-0d96-4ed0-bba7-35c259e88ef5.png)

**NAV 16 Output File**
![Image](https://user-images.githubusercontent.com/116171982/225272500-4d7fca1b-fde8-4d88-bda4-33ded4bc25c4.png)

**BC Sanpshot. - Report Filter and Report ID**
![Image](https://user-images.githubusercontent.com/116171982/225271926-f22da70a-ff79-4faf-8553-5bca85e62461.png)

**BC Output File**
![Image](https://user-images.githubusercontent.com/116171982/225273325-5c7d11a5-d68f-41a5-97e0-465f1d1cade9.png)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k 

BC Report ID - Posted Voucher (18041, Report Request)

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Once it will completed please let me know.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Please update on.

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Please update once it will completed.

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Please apply the same code in BC

**General Ledger Entries ---> On Page Action ---> Print Voucher**

![Image](https://user-images.githubusercontent.com/116171982/226504358-c7195230-5288-4d3e-844d-f4a772e59431.png)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - I have tested it now it is working fine.

I am attaching reference snapshot.


![Image](https://user-images.githubusercontent.com/116171982/226508283-aed9b101-c9bc-4f56-ad1b-81f022a6d800.png)

CC : @audhi3k
