### ISSUE TITLE
Check Print Preview

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#165]

**Comment by TabrejAlam3K** [comment]
@sandhya3k - you have discussed with Ms. Audhi

CC : @audhi3k

**Comment by sandhya3k** [comment]
@TabrejAlam3k
i have done from my end. please test the Dev env

**Comment by TabrejAlam3K** [comment]
@sandhya3k - See the attached Snapshot as per our discussion


![Image](https://user-images.githubusercontent.com/116171982/225235146-d7d4ba13-2021-44a8-b1ee-f00c396d8440.png)

Date format should be - **DD-MM-YYYY**
Amount in Words should be - **FOURTY FIVE LAKH SIXTY SEVEN THOUSAND NINE HUNDRED RUPEES AND ZERO PAISA ONLY**

CC : @audhi3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K 
As per our discussion at the last meeting, you suggested report id 50017, for which report I did the changes. now, you changed the report id: 50031 which report has a different logic is there so, i need to take some time to work it out.

cc: @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - As per our discussion please change the date format and ping me then we can test and close it.

**Comment by TabrejAlam3K** [comment]
@sandhya3k - I have tested it now it is working fine.

![Image](https://user-images.githubusercontent.com/116171982/225248978-9b634cde-368e-481e-9276-862415007b8b.png)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - HDFC Cheque-M14 (50131, Report Request)

Date format should be in (DD-MM-YYYY)

**Comment by TabrejAlam3K** [comment]
@sandhya3k - No it is coming correctly 

Thanks

![Image](https://user-images.githubusercontent.com/116171982/225866004-705b6f09-ed73-48aa-83ba-cfa46fd275be.png)

**Comment by sandhya3k** [comment]
@Shasthara  @narayana3kt 

Todai will sit with client and complete the report for LKS

cc: @audhi3k

**Comment by TabrejAlam3K** [comment]
![Image](https://user-images.githubusercontent.com/116171982/232691257-a78a7d70-0d03-4919-8dd2-6dd6cf01879b.png)

**Comment by TabrejAlam3K** [comment]
![Image](https://user-images.githubusercontent.com/116171982/232698522-03525670-b776-499c-9c0d-dfce4be78d86.png)

**Comment by TabrejAlam3K** [comment]
NAV16 Report Properties

![Image](https://user-images.githubusercontent.com/116171982/232718234-b4d75af0-7997-46bb-b0a3-8e351fa456f4.png)

**Comment by sandhya3k** [comment]
@TabrejAlam3K 
we already applied the nav 2016 dimensions but bc is not coming properly

**Comment by sandhya3k** [comment]
@TabrejAlam3K  

two reports have been printed as per client requirement and deployed in production.

cc : @audhi3k  @Shasthara @narayana3kt
