### ISSUE TITLE
GST Integration related queries

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1655]

**Comment by Prakash3K** [comment]
Hi @sandhya3k ma'am, client confirmed to deploy changes in production. Kindly deploy Delivery challan report changes and E-way bill cancel watermark changes in production, after 6:30 PM today

![Image](https://github.com/user-attachments/assets/ac9b5086-ceb0-44b0-8f3a-59e55e1e072e)



CC: @Tushargupta3K @audhi3k @rohit3k

**Comment by Prakash3K** [comment]
Client confirmed to close this ticket.


CC: @audhi3k @Tushargupta3K
