### ISSUE TITLE
Release the item qty from SO/24-25/2054

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1656]
**Dear Team,

As discussed with Mr. Tabrej, the item code USAMAI005TPF – 300 PAC & USASJI005TPF – 340 PAC were mentioned in item tracking line in SO/24-25/2054. The SO is not posted as Sales invoice, it was pre closed. So that, we could not able to use this qty to another SO. Please release this item qty from the mentioned SO number.**

**Comment by TabrejAlam3K** [comment]
UCPL team is on leave dut to holiday, we are unable to discuss the issues.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - As discussed earlier required your soupport to fix the issues.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation from the client side over the teams chat.

![Image](https://github.com/user-attachments/assets/5df12bad-9c47-45e6-ade1-97f11a74ef6f)

CC : @audhi3k
