### ISSUE TITLE
Posted Sales Invoice doesn't have value - HDSI242501000003

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1657]

**Comment by Prakash3K** [comment]
Solution provided over the call, waiting for client confirmation for closure 


CC: @Tushargupta3K @audhi3k

**Comment by Tushargupta3K** [comment]
Discussed with Senthil, NO such validation can be inserted to block posting lines having Amount = 0 , since we have many cases of 100% discount. Senthil will check to manage it operationally.
