### ISSUE TITLE
: Minor enhancement the getSalesOrderHeader API (ECOMM-1288)

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#167]

**Comment by niranjand22** [comment]
cc @audhi3k

**Comment by Shasthara** [comment]
@Padma2717  to update

**Comment by Padma2717** [comment]
GetSalesOrderHeader API delivered as per customer requested. now it is under customer testing.

**Comment by Padma2717** [comment]
Minor enhancement of getSalesOrderHeader API deployed into production. Kindly close this ticket.
