### ISSUE TITLE
Attachments are missing in Posted PI - High

### ISSUE THREAD

**Issue by Varunmk3k** [3ktech/General#1687]

**Comment by Prakash3K** [comment]
Issue:
We encountered an issue where, in the case of invoicing via the Purchase Order, the system is not transferring attachments from the Purchase Order to the Posted Purchase Invoice. This issue occurs specifically when using the "Post and Print" button, which is standard functionality in Business Central.

Solution and Process:

1. Current Process (Attachments Flowing Properly):

The attachment customization currently works for the following process: 

a. The user creates a Purchase Order, and attaching a file is mandatory before sending it for approval.
b. Goods Receipt Note (GRN) is done via the Warehouse Receipt, and attaching a file is also mandatory before posting.
c. When invoicing is done through the Purchase Invoice page by using "Get Receipt Line," attachments from the Purchase Order and Warehouse Receipt automatically flow to the Purchase Invoice.
d. In Posted Purchase invoice those attachments will flow automatically 

2. Proposed Customization for Purchase Order Invoicing:

We propose extending the attachment flow functionality to the Purchase Order invoicing process as follows:

a. The user creates a Purchase Order, and attachments are mandatory before sending for approval. 
b. GRN is done through the Warehouse Receipt, and attachments are mandatory before posting.
c. When the user posts the invoice directly from the Purchase Order page, the attachments from both the Purchase Order and Warehouse Receipt should flow to the Posted Purchase Invoice automatically. 
d. Before posting the Purchase Invoice, attaching a file should be mandatory. 
e. Once posted, users should not be able to delete attachments from the Posted Purchase Invoice.



CC: @audhi3k @Tushargupta3K @johnbosco3K

**Comment by Prakash3K** [comment]
We are closing this ticket as all changes have been made and deployed to production. We have not received closure confirmation from the client, since last 2 weeks. If any issues arise in the future, they will be consider as a new ticket.

CC: @audhi3k @Tushargupta3K @TabrejAlam3K
