### ISSUE TITLE
List of Sales Invoice Reports before Posting

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#169]
List of Sales Reports before posting having an issues.

**Comment by TabrejAlam3K** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



Report ID | Report Caption | Comments/Error Message
-- | -- | --
50148 | MEMO   OF FEES | Invalid language ID supplied: 0.
50156 | MEMO   OF FEES (GST) | The length of the string is 101,   but it must be less than or equal to 100 characters. Value: KINDLY PAY IN   FAVOUR OF "LAKSHMI KUMARAN & SRIDHARAN" AND QUOTE THIS INVOICE   NO. WHILE MAKING PAYMENT
50157 | Branch Draft Invoice GST | Invalid language ID supplied: 0.
50161 | IBL Tax Draft GST/Credit Memo | Invalid language ID supplied: 0.
50000 | Test Sales Invoice | Rendering output for the report   failed and the following error occurred: The Format expression for the text   box ‘Sales_Line__Service_Tax_Amount_’ refers to the field   ‘Sales_Line__Service_Tax_Amount_Format’. Report item expressions can only   refer to fields within the current dataset scope or, if inside an aggregate,   the specified dataset scope. Letters in the names of fields must use the   correct case.



</body>

</html>

**Comment by TabrejAlam3K** [comment]
@sandhya3k or @panduc - Can any one look into this on priority.

CC : @audhi3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K please test the UAT environment.

No :RTB-1415-00014

cc: @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - I have tested with same documents and now i found **Amount in Words** coming wrongly in all the reports. Please check and confirm.

50148 | Amount   in Words is coming Wrongly
50156 | Amount   in Words is coming Wrongly
50157 | Amount   in Words is coming Wrongly
50161 | Amount   in Words is coming Wrongly
50000 | Amount   in Words is coming Wrongly


CC : @audhi3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K  

It's done. please, test and let me know.

cc: @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - I have tested it, Now it looks good.

Report ID 50000 - Showing some message popup, See the attached sanpshot.

![Image](https://user-images.githubusercontent.com/116171982/225799968-d23d710d-7992-49d8-bec5-bb8a7e1db821.png)

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Please remove the message and confirm, based on that we can close the ticket

**Comment by TabrejAlam3K** [comment]
@sandhya3k - I have tested and now It is working fine.

CC : @audhi3k

**Comment by niranjand22** [comment]
get confirmation for closure.
