### ISSUE TITLE
Item Card - Oty. On PO Released

### ISSUE THREAD

**Issue by Varunmk3k** [3ktech/General#1693]

**Comment by Prakash3K** [comment]
UAT session done with client, waiting for client confirmation to deploy in production

CC: @Tushargupta3K @audhi3k

**Comment by Prakash3K** [comment]
Client confirmed to close this ticket
![Image](https://github.com/user-attachments/assets/323515b5-10e7-4eca-bf37-301a12c947a0)



CC: @Tushargupta3K @audhi3k
