### ISSUE TITLE
E-invoice Error:CHAVANS

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#170]

**Comment by niranjand22** [comment]
waiting for client apporval for hours

**Comment by niranjand22** [comment]
as of now alternate solution provided with json prep file

**Comment by niranjand22** [comment]
Client has asked to hold

**Comment by Shasthara** [comment]
@niranjand22 to update

**Comment by niranjand22** [comment]
Client Put It on hold and nno response after that
