### ISSUE TITLE
Sales Invoice format went wrong and E-invoice not generating - High

### ISSUE THREAD

**Issue by Varunmk3k** [3ktech/General#1719]

**Comment by Prakash3K** [comment]
Hi @rohit3k sir, kindly provided confirmation to deploy changes in production. Kindly deploy in production in between 1:15PM to 1:30PM today
![Image](https://github.com/user-attachments/assets/d61ecdaf-6a1e-469c-877b-87964ac90ea0)

CC: @Tushargupta3K @audhi3k

**Comment by rohit3k** [comment]
HI @Prakash3K deployment Has been done 

cc: @gsudarsan3k @Tushargupta3K

**Comment by Prakash3K** [comment]
Client confirmed to close this ticket 


CC: @audhi3k @Tushargupta3K
