### ISSUE TITLE
DYN 365 BC / Fichtner India/ 3KT / 12.09.2024 / Mur-095 / Project Ledger entries - required in Purchase orders

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1722]

**Comment by Ejaz3KT** [comment]
Waiting for the closer confirmation

**Comment by TabrejAlam3K** [comment]
We are closing the ticket as completed based on the support portal.

![Image](https://github.com/user-attachments/assets/b84a3107-35bf-4309-9e07-9a6f936c521f)

CC : @audhi3k
