### ISSUE TITLE
JV - Renumbering issue.

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1723]

**Comment by Prakash3K** [comment]
Solution Provided over the call, waiting for client confirmation to close this ticket


CC: @Tushargupta3K @audhi3k @TabrejAlam3K

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - what is the estimated and approved hours for this tikcet. you have not updated **Client Approved Hrs**

CC : @audhi3k

**Comment by Prakash3K** [comment]
Senthil sir confirmed to close this ticket


CC: @Tushargupta3K @audhi3k @Tushargupta3K
