### ISSUE TITLE
E-invoice/Eway bill for Sales

### ISSUE THREAD

**Issue by Varunmk3k** [3ktech/General#1729]

**Comment by Prakash3K** [comment]
Analyzed and solution provided over call, waiting for client confirmation to close this task 



CC: @audhi3k @Tushargupta3K

**Comment by Prakash3K** [comment]
Senthil sir confirmed to close this ticket, PAN number issue in customer. solution provided over the call


CC: @Tushargupta3K @TabrejAlam3K
