### ISSUE TITLE
Create New Company

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#173]

**Comment by niranjand22** [comment]
Please create New Company in NAV

 

Company Name: Sankar and Parvathi Estate Pvt. Ltd (SPEPL)

 

We will share the chart of accounts shortly.

**Comment by audhi3k** [comment]
Dear Mr Senthil,

Through Screen sharing session we have created the new company and explained about configuration package to upload the Chart of Accounts.


Regards,
Audhi Lakshmi S

**Comment by audhi3k** [comment]
Dear Mr Senthil,

We can connect again to upload the Chart of Accounts is once formulated at your end.


Regards,
Audhi Lakshmi S

**Comment by audhi3k** [comment]
Closure as there no escalation
