### ISSUE TITLE
RE: Bank Charges GST not calculation / Rounding off issues

### ISSUE THREAD

**Issue by Varunmk3k** [3ktech/General#1730]

**Comment by Prakash3K** [comment]
![Image](https://github.com/user-attachments/assets/1604be9b-8073-40aa-81b2-1226267a3fee)
Recent update from Microsoft team

CC: @audhi3k @Tushargupta3K @TabrejAlam3K

**Comment by Prakash3K** [comment]
![Image](https://github.com/user-attachments/assets/1e9e621b-b7cc-48e7-be7a-1a073d0dc48b)
Recent Update from Microsoft team

CC: @audhi3k @Tushargupta3K @TabrejAlam3K

**Comment by Prakash3K** [comment]
Changes are done in Production waiting for client confirmation to close this ticket 


CC: @audhi3k @TabrejAlam3K

**Comment by Prakash3K** [comment]
Client confirmed to close this ticket 


CC: @audhi3k @TabrejAlam3K
