### ISSUE TITLE
TCS should charge on Gross value

### ISSUE THREAD

**Issue by Varunmk3k** [3ktech/General#1739]

**Comment by Varunmk3k** [comment]
![Image](https://github.com/user-attachments/assets/56b80942-f31a-49e6-8974-a42539342eb6)

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation from the client side.

![Image](https://github.com/user-attachments/assets/b1149fb3-8dfd-41d1-a832-5bdd1191a735)

CC : @audhi3k
