### ISSUE TITLE
Creation of Bite Back Ltd on Dynamics

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1746]
![Image](https://github.com/user-attachments/assets/b7e114d8-cedd-4fb0-ae23-065c87cd2af9)

**Comment by niranjand22** [comment]
will be connecting with clint to take closre, and raise new tickit for additinal points. @TabrejAlam3K

**Comment by TabrejAlam3K** [comment]
Hi @Vivek-K-Sinha closing this tikcet as close over the support portal.

CC : @audhi3k
