### ISSUE TITLE
Creation of Conservative Home Ltd on Dynamics

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1747]
![Image](https://github.com/user-attachments/assets/f4cf2836-6796-487b-bfcc-3ad32a3460e8)

**Comment by Amar-3KT** [comment]
Client raised following 2 issues

![Image](https://github.com/user-attachments/assets/1f808a69-3cbb-460d-90cc-d61c3ec34000)

**Comment by Amar-3KT** [comment]
**1) Template has been shared with Ms. Ana. Also given training related to template creation.
2) In jet report we need to add following 3 companies.** 

![Image](https://github.com/user-attachments/assets/ebd86c23-d717-4db0-9116-790f70b271bd)


**we need to update companies' data for GL GBP and dimensions sheets.**

![Image](https://github.com/user-attachments/assets/dd27bdfc-3924-4c00-9764-c9cd93d0b611)

**Comment by Amar-3KT** [comment]
[07. October.xlsx](https://github.com/user-attachments/files/17828943/07.October.xlsx)

**Comment by Amar-3KT** [comment]
22-11-2024----We are not able to access remote desktop some issue in excel. Ms. Ana checking with IT team and will update us once its resolved.

**Comment by Amar-3KT** [comment]
26-11-2024 msg has been sent to Ms. Ana for remote desktop excel issue. Waiting for her reply....

**Comment by Amar-3KT** [comment]
Now we are able to access.

**Comment by Amar-3KT** [comment]
We are not able to access server

**Comment by TabrejAlam3K** [comment]
Hi @Vivek-K-Sinha Closing this ticket as close over the support portal.

CC : @audhi3k
