### ISSUE TITLE
Creation of Conservative Intelligence Ltd on Dynamics

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1748]
![Image](https://github.com/user-attachments/assets/4e49061f-8427-4a8c-858b-7b7d3c1de952)

**Comment by niranjand22** [comment]
will be connecting with clint to take closre, and raise new tickit for additinal points. @TabrejAlam3K

**Comment by TabrejAlam3K** [comment]
Hi @Vivek-K-Sinha - Close the tikcet from the git.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @Vivek-K-Sinha Closing this ticket as close over the support portal.

CC : @audhi3k
