### ISSUE TITLE
E-invoice Error:CAS-01191-S6J9R3

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#175]
We checked the BC card internally, for SEZ zone nature of supply should be SEZWP or SEZWOP option.

But, we are unbale to edit nature of supply, please make it editable.
 

![Image](https://user-images.githubusercontent.com/116243958/226514398-d2ade406-88c8-44d2-95be-40be042d0ba2.png)

**Comment by niranjand22** [comment]
CC @audhi3k

**Comment by audhi3k** [comment]
What the status of it @niranjand22

**Comment by niranjand22** [comment]
@Mahesh3ktech  please update once you made nature of supply field editable

**Comment by niranjand22** [comment]
We checked the BC card internally, for SEZ zone nature of supply should be SEZWP or SEZWOP option.But, we are unbale to edit nature of supply, please make it editable.-- Jagan

**Comment by niranjand22** [comment]
mahesh wiill do the changes once he is free from current task

**Comment by niranjand22** [comment]
![Image](https://user-images.githubusercontent.com/116243958/227431264-48f50e61-8f52-42fa-8cc5-e4a024671872.png)

CURRENTLY TWO OPTION ARE THERE IN NATURE OF SUPPLY FIELD

**Comment by niranjand22** [comment]
new nature of supply filed had to be created with options

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<style>

</style>
</head>

<body link=blue vlink=purple>



B2B
B2C
SEZWP
SEZWOP
EXPWP
EXPWOP
DEXP



</body>

</html>

**Comment by niranjand22** [comment]
currently they are using json prep file for generating e invoice

**Comment by Mahesh3ktech** [comment]
Mr.Niranjan asked me to hold the task, he is going to raise the ticket with microsoft regarding the issue.

**Comment by Shasthara** [comment]
@niranjand22, Need update

**Comment by niranjand22** [comment]
it is not pending with us issue is raised to Microsoft

**Comment by Shasthara** [comment]
@niranjand22 to update
