### ISSUE TITLE
Freight on Sales needs to incorporate in Sales report

### ISSUE THREAD

**Issue by Varunmk3k** [3ktech/General#1754]

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - We got the approval on this from the client side, You can start your activity.
**This is high priority task.**
![Image](https://github.com/user-attachments/assets/8cb5aaa9-aa6d-46d2-a51c-bd54445f9abe)
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - why this is not yet deployed into the production.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the closure confirmaton for the same from the client side. We can close the tikcet.

![Image](https://github.com/user-attachments/assets/99008ac8-c1f8-4e98-986f-110631f5cf66)

CC : @audhi3k
