### ISSUE TITLE
Practice Session for Manoj

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#176]

**Comment by Manoj01021999** [comment]
@Padma2717 @3ktech @audhi3k 
#sales flow -created a custom field form sales header to entries and posted sales invoices
#purchase flow-created a custom field from purchase header to entries and posted purchase invoices 
@Padma2717 validated the task
and given other task

**Comment by Manoj01021999** [comment]
@audhi3k has assigned a task
working on it not getting the output

**Comment by Manoj01021999** [comment]
@audhi3k assignment task has been done

**Comment by Manoj01021999** [comment]
@audhi3k @3ktech 
Narayana sir has given a assignment on workflow
going through it

**Comment by Manoj01021999** [comment]
@audhi3k @3ktech 
working on workflow (internal training)

**Comment by Manoj01021999** [comment]
@audhi3k @3ktech 
was working on deploying tenant Customization and seen  video's in Udemy

**Comment by Manoj01021999** [comment]
@audhi3k @3ktech 
Padma has given the assignment of sales order in 2nd half

**Comment by Manoj01021999** [comment]
@3ktech @audhi3k 
Padma has  assigned to create sales flow in BC

**Comment by Manoj01021999** [comment]
@3ktech @audhi3k 
From Purchase Order
After Order Action create new action "Vendor List"
and show me the vendor List

it was done
