### ISSUE TITLE
Posing Date and PO number need to added in Posted Warehouse Receipt's Standard Report

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1763]
**Posing Date and PO number need to added in Posted Warehouse Receipt’s Standard Report**
![Image](https://github.com/user-attachments/assets/829be422-3b79-4fb9-ba72-05863a06e37b)

**Comment by Prakash3K** [comment]
Client confirmed to close this ticket 


CC: @audhi3k @Tushargupta3K
