### ISSUE TITLE
Practice Session for shruthi

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#177]

**Comment by sruthi1017** [comment]
@Padma2717 @3ktech @audhi3k 
#sales flow-completed the task, flow a custom field from sales header to entries and posted sales invoice 
#purchase flow-completed the task, flow a custom field from purchase header to entries and posted purchase invoice
#item master too
@Padma2717 Validated the tasks and given another task

**Comment by sruthi1017** [comment]
worked on some changes of TDS declaration report regarding Fervid, and page alignments and sales flow in BC
