### ISSUE TITLE
Business Central is not working

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1770]
![Image](https://github.com/user-attachments/assets/7e8d9bb1-7c75-4442-8e60-1a543e65f3cf)

**Comment by TabrejAlam3K** [comment]
Hi @Ejaz3KT - We got one new tikcet and assigned to you, Please check and start your activity on this.

CC : @audhi3k

**Comment by Ejaz3KT** [comment]
Ok @Tabrej ***@***.***> sir
________________________________

**Comment by Ejaz3KT** [comment]
This ticket has been canceled by the client

CC: @TabrejAlam3K @audhi3k
