### ISSUE TITLE
FA Register updation:CAS-01195-M8Q4H2

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#178]
FA Register - We have already developed the Custom Reports.

Client want to add something in the same reports.

**Comment by TabrejAlam3K** [comment]
I have discussed with Ms. Sandhya we will connect on later.

**Comment by niranjand22** [comment]
HI @TabrejAlam3K  UPDATE THE REQUIREMENTS IN DETAIL AND EXPLAIN TO MS SHRUTHI.

**Comment by TabrejAlam3K** [comment]
@sruthi1017 - See the below requirement for FA Registers.

Required three column in the output data below
1. Posting Date From - It is FA Posting Date
2. Posting Date To - It is FA Posting Date
3. Monthly Depreciation - The value Should come from the FA Ledger Entries based on the user inputs (Posting Date)
4. FA Posting Date - Required this field on Report Input Screen.

**Comment by TabrejAlam3K** [comment]
@sruthi1017 - Please update me once it will completed based on that we can forward to the client for testing.

You need to done this customization on Sandbox first.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sruthi1017 - I have provided to you the Sandbox credential. Please update on we need to close this immediately, Client asked many time for this issues.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sruthi1017 - As per our discussion We couldn't able to found the changed in sandbox as per our discussion. 

**See the attached Snapshot.**
![Image](https://user-images.githubusercontent.com/116171982/227828633-f0eabd23-f8bd-405a-b6c8-436f977b93ed.png)

CC : @audhi3k

**Comment by sruthi1017** [comment]
@TabrejAlam3K-i have added the filed fa posting date and, the three columns in output layout it is working in my local account and facing the issue in coding with the data flow.
![faregisters](https://user-images.githubusercontent.com/116153105/227830744-3091e52f-5667-48ef-af60-02debcf259bf.PNG)
but when i try to publish it in the sandbox environment iam getting this error
![fasandbox](https://user-images.githubusercontent.com/116153105/227831027-44318837-b5fb-4db4-9f82-939a7436846f.PNG)

**Comment by TabrejAlam3K** [comment]
@sandhya3k @sruthi1017 


![Image](https://user-images.githubusercontent.com/116171982/227849972-8d5106da-ced6-4c9d-8ee9-8674e820b550.png)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - It is not working, Can we connect on

**Comment by TabrejAlam3K** [comment]
@Mahesh3ktech - It is not working, Can we connect on

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k  - It is not competed yet, Please completed it as on priority.

![Image](https://user-images.githubusercontent.com/116171982/229693508-f90c9dcc-25fd-47b1-8ad8-8ae25b77712f.png)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
I have tested and forwarded to the Client, Waiting for their comments on

CC : @audhi3k @niranjand22

**Comment by Shasthara** [comment]
@TabrejAlam3K, need update

**Comment by niranjand22** [comment]
@TabrejAlam3K  please drop the latest update here

**Comment by TabrejAlam3K** [comment]
1. Posting Date From - It is FA Posting Date.
2. Posting Date To - It is FA Posting Date.
3. Monthly Depreciation - The value Should come from the FA Ledger Entries based on the user inputs (Posting Date).

Mr. @niranjand22 - If you required any clarification on please let me know.

**Comment by niranjand22** [comment]
will update mr pawan to check and confirm

**Comment by niranjand22** [comment]
client wants this to be published in live..then they can check with their data..in UAT sufficient data and setup is not available

**Comment by niranjand22** [comment]
@sruthi1017  this need to be deployed in live..kindly deploy once ms sandhya is back

**Comment by niranjand22** [comment]
Hi @sandhya3k  can you deploy this to live envirnment

**Comment by sandhya3k** [comment]
@niranjand22 
please check i deployed in production.

cc : @audhi3k

**Comment by audhi3k** [comment]
Mr @niranjand22 why this is still pending ... Whether client confirmed. can we close the ticket

**Comment by audhi3k** [comment]
Mr @niranjand22, kindly close this ticket

**Comment by 3ktech** [comment]
@niranjand22 , i understood from @sruthi1017 that she needs more input to start this development. can you please guide her with the required information.

**Comment by niranjand22** [comment]
@3ktech    Yes kartik..  @TabrejAlam3K  Please share the initial field mapping file. Then I can explain to Sruthi

**Comment by niranjand22** [comment]
Hi Reporting is generating the data now. Showed this report ms swathi.
There are three change we have to do.

1. In Request Page- Change Caption of From Date to Depreciation Start Date , and To Date to Depreciation End Date.
2.  In excel Generated Report Cahnge the Title of The report from Output Layout to- FA Register
3.  Remove the last two column getting repeated twice in report. @sruthi1017  Please do this changes once u confirm u to do


Ms Swathi is
 doing testing..she will confirm as soon as possible

**Comment by niranjand22** [comment]
[FA Customer Report_MDT_RSP.xlsx](https://github.com/3ktech/General/files/12171816/FA.Customer.Report_MDT_RSP.xlsx)
[FA Ledger Entries_MDT_RSP.xlsx](https://github.com/3ktech/General/files/12171815/FA.Ledger.Entries_MDT_RSP.xlsx)

**Comment by niranjand22** [comment]
"I have tested the FA registers report in production and found below queries, once these are cleared i shall test further.

Monthly depreciation total is not matching with actuals in Trial balance
Cummulative depreciation total is not matching with Closing balance in Trial balance 
Pls change the output layout report heading to "FA Register"
Pls change column name "Depreciation (2)" to "Cummulative Depreciation((2)" 
Sold/write off values are incorrect
W & X columns to be removed" swathi

**Comment by niranjand22** [comment]
Changes are done. Swathi will checl and confitm

**Comment by 3ktech** [comment]
@niranjand22 , if it is with swathi, please change the status accordingly

**Comment by niranjand22** [comment]
@3ktech  One point is pending from Shruthi side. Write Off sold off column not updating value

**Comment by 3ktech** [comment]
@sruthi1017 , can you finish this first?

**Comment by niranjand22** [comment]
Hi @sruthi1017  recived update from swathi... In sold off write off column pls add this to condition to populate the Sold off write off value.
![Image](https://github.com/3ktech/General/assets/116243958/13870dc8-e727-4874-9b29-ae862fb48d48)

**Comment by sruthi1017** [comment]
This report is completed further modifications will be taken in another ticket.
