### ISSUE TITLE
Transfer shipment in single report`-BC

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1784]
![Image](https://github.com/user-attachments/assets/2cf61f4a-6071-4107-9083-b3cab1db180c)

**Comment by Prakash3K** [comment]
Hi @TabrejAlam3K sir, this Ticket is assigned to Vivek sir

**Comment by Prakash3K** [comment]
Solution provided over the call, waiting for client confirmation to close this ticket 


CC: @audhi3k @Tushargupta3K

**Comment by Prakash3K** [comment]
Bala M confirmed to close this ticket 


CC: @audhi3k @Tushargupta3K @TabrejAlam3K
