### ISSUE TITLE
CHAVANS: D365 Mail Communication

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1787]
![Image](https://github.com/user-attachments/assets/0f60e9ee-843b-48c5-85c5-3e9c986ffc10)

**Comment by TabrejAlam3K** [comment]
Hi @shivakumar3k - there are no updates here since long time. Please update the status.

CC : @audhi3k

**Comment by shivakumar3k** [comment]
Hello @TabrejAlam3K ,
Above issuer related CRM, Kindly check with CRM team.

**Comment by TabrejAlam3K** [comment]
Ok thanks, we are closing this tikcet due to non-bc tikcet.
