### ISSUE TITLE
Reg- Vendor posting group  Filter issue

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1788]
![Image](https://github.com/user-attachments/assets/e9f47846-77de-433e-9874-5b564b917e39)

**Comment by Prakash3K** [comment]
Issue resolved and UAT done with client


CC: @audhi3k @Tushargupta3K

**Comment by Prakash3K** [comment]
Client confirmed to close this ticket 


CC: @audhi3k @Tushargupta3K @TabrejAlam3K
