### ISSUE TITLE
Purchase Order-Nav-CAS-01194-Z9Y8S8

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#179]
Please implement below changes in Purchase Order.

 

Following fields should not be modified after approval. It should be reopened for any modification after approval.

Transport Method

PO Category

Invoicing Location

Navigate/Comments (Payment Terms & Warranty)

Navigate/Terms And Conditions

 

Following fields to be mandated before sending for approval

PO-WO Category

Quote no

**Comment by audhi3k** [comment]
Dear Mr Senthil,

We have analysed requirement we would require 5 hours, kindly approve to proceed further

Analysis – 0.5 hour
Development – 3 hours
Testing – 0.5 hour
UAT – 0.5 hours
Deploy – 0.5 hours


Regards,
Audhi Lakshmi S

**Comment by audhi3k** [comment]
Dear Mr Senthil,

Thanks for the approving the hours.

We will start with the development and update the status.


Regards,
Audhi Lakshmi S

**Comment by audhi3k** [comment]
Dear Mr Senthil,

Thanks for the confirmation to deploy in LIVE.

We have deployed in LIVE, kindly check and confirm on closure.
Regarding Comment in Terms and Condition, we will analysis and update.


Regards,
Audhi Lakshmi S

**Comment by audhi3k** [comment]
Dear Mr Senthil,

As discussed we have completed mandatory of PO-WO Category and relating to Mandate of Term and Condition – not feasible as it from other area 

Kindly confirm on closure

**Comment by audhi3k** [comment]
Client confirmed on closure
