### ISSUE TITLE
Separate CC Mail for Salt and Atta

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1817]

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - We need to add the below field over the table(State (18547)) as well as over page(States (18547, List)).
**Add the below fields as new**
1. Vend Outstanding CC E-mail (SALT)
2. Purchase Order CC E-Mail (SALT)
3. Posted Sales Invoice CC E-Mail (SALT)
4. Sales Credit Memo CC Email (SALT)
5. Customer Outstanding CC Email (SALT)

**Rename the below fields**
1. Vend Outstanding CC E-mail = Vend Outstanding CC E-mail (ATTA)
2. Purchase Order CC E-Mail = Purchase Order CC E-Mail (ATTA)
3. Posted Sales Invoice CC E-Mail = Posted Sales Invoice CC E-Mail (ATTA)
4. Sales Credit Memo CC Email = Sales Credit Memo CC Email (ATTA)
5. Customer Outstanding CC Email = Customer Outstanding CC Email (ATTA)

**Condition** : while sendin the mail from posted sales invoice if posted sales invoice line having the value in field Gen. Prod. Posting Group::ATTA then ATTA CC mail should come from the state master or if posted sales invoice line having the value in field Gen. Prod. Posting Group::SALT then SALT CC mail should come from the state master.
![Image](https://github.com/user-attachments/assets/a0b40d39-5dca-4ba2-b870-1ba28b95c3fd)

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please share the effort estimation for this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - We got the approval on this from the client side.

![Image](https://github.com/user-attachments/assets/886820bb-0ce9-4bf6-86f8-ea648182ca29)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - third condition is not working, Please check the below condition and let us know.
Condition : If Sales Invoice line having the value in the fields Gen. Prod Posting Group ATTA and SALT then ATTA CC mail should come.
Referance Document : **SIUC/24-25/2207|SIUC/24-25/2223|SIUC/24-25/2224**

CC : @audhi3k

**Comment by johnbosco3K** [comment]
Hi @TabrejAlam3K ,
 It's fixed

**Comment by TabrejAlam3K** [comment]
**Additional Requirement with additional Efforts**

Hi @johnbosco3K - As discussed, Please add the below field over the customer card and enable over the page as well under the communication tab.
1. ATTA CC Mail
2. SALT CC Mail

Validation : You need to check first over the customer card if the value is available then you need to pick the respective CC Mail form the customer master otherwise you need to pick from the State Master.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - I checked the CC Mail but still not coming from the customer master. Please check and fix it.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please deploy the changes into production and confirm. We need to take the closure confirmation on this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation on this from the client side. we can close the tikcet.

![Image](https://github.com/user-attachments/assets/9e30b64f-c8d4-4e9d-850f-36f080467b0c)

CC : @audhi3k
