### ISSUE TITLE
Assembly Order Report

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1822]

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K Please share the effort estimation on this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
[Assembly Order Report.xlsx](https://github.com/user-attachments/files/17544651/Assembly.Order.Report.xlsx)

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - As discussed, you need to develop the fresh report form the Item Ledger Entries. See the attached excel for you referances.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - Please update on this.

CC : @audhi3k

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K - I Will Complete it by today 1st half.

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - Do the below changes which we found while doing the internal testing.
1. Document No. field is not appearing in the report
2. Value should be left alignment.
3. Entry Type should be Assembly Consumption only.

CC : @audhi3k @johnbosco3K

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K - Above all the points are Completed with report.

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please deploy the changes into the production, Client confirm for deployment.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - Merge the changes into the Master and confirm to Mr. @johnbosco3K 

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K and @NityaNirlipta, Is it deployed into the production?

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @NityaNirlipta - As discussed, please take the help from Mr. John and close the ticket by today, because this is the most priority ticket.

CC : @audhi3k @johnbosco3K

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation on this from the client side.

![Image](https://github.com/user-attachments/assets/ed156fac-6fdc-4071-badc-3b542903e7f2)

CC : @audhi3k
