### ISSUE TITLE
Reg- Item attributes

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1823]
Dear Team,

                While creating Item attributes we are getting error. Kindly check and do the needful
Pls find the list of EAN which are getting the error

8903439890186
8903439890193
8903439890209
8903439890216
8903439890223

![Image](https://github.com/user-attachments/assets/31d92a2d-b9f6-4a5c-ba94-d3c70e3a1118)

**Comment by Prakash3K** [comment]
Analysis done and solution provided over the call to client, waiting for Arun sir confirmation to close this ticket



CC: @audhi3k @Tushargupta3K @TabrejAlam3K

**Comment by Prakash3K** [comment]
Client confirmed to close this ticket


CC: @audhi3k @Tushargupta3K @TabrejAlam3K
