### ISSUE TITLE
Customer aging report need to add 3 fields

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#184]
Please add Cost unit, Cost Center and customer name in Report

**Comment by Amar-3KT** [comment]
@Mahesh3ktech 
Any update

**Comment by Amar-3KT** [comment]
@Ejaz3KT @Mahesh3ktech 
As discussed, please add 3 fields in Customer aging report.

**Comment by niranjand22** [comment]
@Mahesh3ktech  pls update status

**Comment by Mahesh3ktech** [comment]
@Amar-3KT - Customer summary Aging report field adding is completed, Kindly check and update.

**Comment by Mahesh3ktech** [comment]
Completed the report and testing also done.
today ill publish to production.

**Comment by Shasthara** [comment]
@Amar-3KT to check with client

**Comment by Amar-3KT** [comment]
Its done and confirmed by Savitha S
