### ISSUE TITLE
RE: BC Error

### ISSUE THREAD

**Issue by Varunmk3k** [3ktech/General#1842]

**Comment by Varunmk3k** [comment]
![Image](https://github.com/user-attachments/assets/8ddf4657-13c8-44e0-aedd-2f632259751b)

**Comment by Varunmk3k** [comment]
![Image](https://github.com/user-attachments/assets/e830fdd4-1316-4401-a5c0-fbb0316e64a4)

**Comment by Prakash3K** [comment]
Client confirmed to close this ticket 


CC: @audhi3k @Tushargupta3K @TabrejAlam3K
