### ISSUE TITLE
Sales order dataport

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#185]

**Comment by Mahesh3ktech** [comment]
Mr.Singaravel is asked me hold the task currently their employees are busy with other internal tasks once they get free they will provide the NAV 2009  server access to work on Sales dataport.

**Comment by Amar-3KT** [comment]
Fichtner server not available due to security reason.

**Comment by Amar-3KT** [comment]
We have created dataport on UAT and shown to Mr. Murali.  After his confirmation we will create on Live.

**Comment by Shasthara** [comment]
@Amar-3KT to check with client.

**Comment by Amar-3KT** [comment]
Live server not available
