### ISSUE TITLE
Matter is not getting synced

### ISSUE THREAD

**Issue by Varunmk3k** [3ktech/General#1850]

**Comment by Varunmk3k** [comment]
![Image](https://github.com/user-attachments/assets/6ca96d17-c884-44b0-b622-9b8d2701cf44)

**Comment by TabrejAlam3K** [comment]
Json
{'Case': [{'case_id': '5060740', 'office_id': 29585, 'client_id': 850, 'matter_type': 'Litigation', 'case_Document_Name': '', 'case_activity_type': 'Appearance', 'matter_sub_type': 'Hearing', 'case_branch': 'Chandigarh', 'category': 'Tax - Indirect', 'sub_category': 'GST', 'case_rain_maker': '', 'case_rain_giver': '', 'case_forum': '', 'case_subforum': '', 'case_creation_date': '2024-10-22', 'case_Referance_Type': '', 'case_number': 'APPEAL NO. APPL/COMM/GST/102/2024-GST\x02-APL-LDH', 'case_forum_city': '', 'case_target_forum': 'Appeal Authority - Ludhiana', 'case_target_forum_city': 'LUDHIANA', 'case_target_subforum': '', 'case_manager': 'krati.s', 'case_partner': 'krati.s', 'correspondance_contact_id': 45157, 'billing_contact_id': 45157, 'group_code': 3, 'practice_code': 3, 'resource': ''}]}

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation on this from the client side.

![Image](https://github.com/user-attachments/assets/2142e8a1-9d91-44e2-9f01-7be31183b078)

CC : @audhi3k
