### ISSUE TITLE
RE: Posting error

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1851]

**Comment by Prakash3K** [comment]
Waiting for Kumar G sir confirmation to close this ticket

CC: @audhi3k @Tushargupta3K @TabrejAlam3K

**Comment by Tushargupta3K** [comment]
This issue happened due to bulk upload posting at another user session.
Since bulk upload shifted to night it must not arise again.

**Comment by Prakash3K** [comment]
Client confirmed to close this ticket 


CC: @audhi3k @TabrejAlam3K
