### ISSUE TITLE
RE: CREDIT MEMO POSTING ERP ERROR ( 12.11.24 )

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1856]
I can’t able to POST THE CREDITMEMO AFTER 31.10.2024 RECEIVED MATERIALS AGAINTS PURCHASE INVOICE …KINLDLY DO THE NEEDFU..

![Image](https://github.com/user-attachments/assets/98770671-d8c4-47fc-867b-93d02933f7ea)

**Comment by Prakash3K** [comment]
Solution provided over the call and client confirmed to this ticket 


CC: @audhi3k @Tushargupta3K @TabrejAlam3K
