### ISSUE TITLE
Pay TCS Entries Issues

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#186]
T.C.A.N no is not updated in Posted TCS Entries.

**Comment by TabrejAlam3K** [comment]
Issue has been completed and forward to the Client for testing once Ms. Vimla will confirm then we will close this one.

**Comment by TabrejAlam3K** [comment]
Client Confirmation

![Image](https://user-images.githubusercontent.com/116171982/227123240-fec1d2a7-0896-4d4c-b454-e66b2ba2b719.png)

**Comment by niranjand22** [comment]
HEY @TabrejAlam3K  PLEASE PROVIDE DETAILS OF CONTACT PERSON FOR THIS CASE.

NAME ,EMAIL,PHONE

**Comment by TabrejAlam3K** [comment]
Contact Person

Name : Vimala Srinivasan
Email : vimala.srinivasan@meritgroup.co.uk
