### ISSUE TITLE
RE: CREDIT MEMO POSTING ERP ERROR ( 12.11.24 ) - reminder --2

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1869]
![Image](https://github.com/user-attachments/assets/8ebb1252-ad29-4654-a0ba-50b27b603558)

![Image](https://github.com/user-attachments/assets/25a2366c-dc14-4fa1-a1f6-1f00abf6a2e4)

**Comment by Prakash3K** [comment]
Solution provides to Arun sir and Tapash sir, waiting for client confirmation to close this ticket

**Comment by Prakash3K** [comment]
Client confirmed to close this ticket 


CC: @audhi3k @Tushargupta3K
