### ISSUE TITLE
TDS/TCS Declaration Report

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#188]

**Comment by niranjand22** [comment]
[3. Declaration_ 194Q 2021_2022.docx](https://github.com/3ktech/General/files/11096502/3.Declaration_.194Q.2021_2022.docx)

**Comment by niranjand22** [comment]
above report with field mapping

**Comment by niranjand22** [comment]
cc @audhi3k pls asssign tech on this case

**Comment by niranjand22** [comment]
Explained report requirnment to @sandhya3k  and shruthi

**Comment by niranjand22** [comment]
[TDS  Declaration_ 194Q 2021_2022 WIT FIELDS.docx](https://github.com/3ktech/General/files/11144809/TDS.Declaration_.194Q.2021_2022.WIT.FIELDS.docx)

**Comment by sruthi1017** [comment]
@niranjand22 completed the report and published in the fervid sandbox environment can u please check whether it is working fine
CC @audhi3k

**Comment by niranjand22** [comment]
Hi @sruthi1017  , Total revenue check boc is not getting selected

**Comment by sruthi1017** [comment]
@niranjand22 i'll check and update

**Comment by sruthi1017** [comment]
@niranjand22 i updated total revenue check box is selecting can u check

**Comment by niranjand22** [comment]
yes @sruthi1017 its updating now.

few more points need to correct.

1. while giving input for report as Posting Date. Please insert space in Posting Date.
2.  When we are zooming the report it is very unclear and blurred.

**Comment by niranjand22** [comment]
![Image](https://user-images.githubusercontent.com/116243958/231352067-e28846d8-3366-4642-9975-9192f8d21a30.png)

it gets blurred while zooming or printing

**Comment by sruthi1017** [comment]
Hi @niranjand22 i re arranged all the alignments, can u check whether it is working fine or is it still blur

**Comment by niranjand22** [comment]
Hi I have checked this report with transaction. Check box in not getting ticked based on total amount. We will connect on this. @sruthi1017

**Comment by niranjand22** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



No. | TDS Declration Points
-- | --
  |  
1 | For Revenue Calculation Take data from Sales Amount LCY in Customer   Ledger Entry (filter doc type as Invoice and Credit memo)
2 | For Revenue Calculation Take data from Purchase  Amount LCY in Vendor Ledger Entry (filter   doc type as Invoice and Credit memo)
3 | Report Alignment
4 | Add Previous year Text in line no 3
5 | In Line 5 Please map Fiscal Year and in same line previous year of fiscal   year has to be mapped.
  |  
6 | Had to cross check with Mr Shreedhar on the Name of the person who will   generate the report.



</body>

</html>

**Comment by sruthi1017** [comment]
Waiting for @niranjand22 to connect ifhe explain the scenario for some points i'll done it

**Comment by sruthi1017** [comment]
hi @niranjand22 added all the above-mentioned points and changed the report alignment and published can u check and confirm it is working fine or not

**Comment by niranjand22** [comment]
Hi Mr @Ejaz3KT  Please update the status latest here for this report

**Comment by Ejaz3KT** [comment]
Hi Mr. @niranjand22 they need some changes in this report

CC: @audhi3k

**Comment by niranjand22** [comment]
@Ejaz3KT  Please design a report for the customer.

**Comment by Ejaz3KT** [comment]
@niranjand22 Changes has done in the report need to showcase to the client and get confirmation

CC: @audhi3k

**Comment by niranjand22** [comment]
client apporved the customization.
