### ISSUE TITLE
Meeting recordings

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1881]
![Image](https://github.com/user-attachments/assets/33dae4f9-18e3-4e30-a874-b57dbabd17ad)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Vivek-K-Sinha - Please connect with Mr. @niranjand22 and provide the recording to the client. It is pending from long time.

CC : @audhi3k

**Comment by niranjand22** [comment]
hI @Vivek-K-Sinha  and @TabrejAlam3K  Microsoft Sharepoint/Teams allows recording backups only for the past 90 days, so we no longer have access to those recordings. 

cc @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @niranjand22 - Please pass this information to the client.

CC : @audhi3k

**Comment by niranjand22** [comment]
@TabrejAlam3K  this is informed to client by prudvi. will close this after reply from cleint

**Comment by TabrejAlam3K** [comment]
Hi @niranjand22 Closing this ticket as closed over the support portal.

CC : @audhi3k
