### ISSUE TITLE
FW: PO Required for Track lights supply works_LULU Mall, Kochi Store

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1882]
Dear ERP Team,

We need to Edit the closed purchase order archive. Pls give the acess.

For Material GST changes from 12% to 18% from Lightbook PO242501000158, dt.8.5.2024 / bill# 274, dt.10.5.24.

Ø  Request Location: Shubhada-business head –corporate office

**Comment by Prakash3K** [comment]
Client confirmed to close this ticket 


CC: @audhi3k @TabrejAlam3K
