### ISSUE TITLE
RE: ERROR IN ERP

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1886]
Dear Support Team,

Vendor Ledger Entries, Clearing Invoice against Payment is having issue.

Kindly check the below shared screen shot and fix ASAP.

![Image](https://github.com/user-attachments/assets/566d709b-a8a0-490a-8206-16cd695c2bb2)

**Comment by Prakash3K** [comment]
Closing this issue due to no response 


CC: @audhi3k @TabrejAlam3K
