### ISSUE TITLE
The length of the string is 4, but it must be less than or equal to 3 characters. Value: null.

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1888]
The user encountered an error while exporting a JSON file for creating an E-Invoice: "The length of the string is 4, but it must be less than or equal to 3 characters. Value: null."

![Image](https://github.com/user-attachments/assets/19d35878-7bf7-47be-8ff6-051d7d1da974)

**Comment by shivakumar3k** [comment]
![Image](https://github.com/user-attachments/assets/99eb1bed-cb3a-4657-9031-d3fb787d621c)
