### ISSUE TITLE
Material Indent

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#189]

**Comment by niranjand22** [comment]
![Image](https://user-images.githubusercontent.com/116243958/233538585-b6b37e87-4315-4d00-8da2-005d8dbeecf0.png)

**Comment by niranjand22** [comment]
1. while generating the report it is running endless loop
2. In indent process also it is generating the report

**Comment by niranjand22** [comment]
Customization is notr complted. In Progress

**Comment by niranjand22** [comment]
Hi Mr @Ejaz3KT  Please update the status here

**Comment by Ejaz3KT** [comment]
Hi Mr. @Niranjan ***@***.***> I’ve tested the indent process  two lists are available like requisition, and issue indent slip but purchase inden action page is not there Mr. Mahesh is working on it.

CC: @Audhilakshmi ***@***.***>

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Amar-3KT** [comment]
Please create same workflow templates for requestion so that we can use approval functionality.

**Comment by Amar-3KT** [comment]
Indent related process shown to Ms. @sruthi1017 and Mr. @Mahesh3ktech 
As discussed ,Kindly do the needful.

CC @audhi3k

**Comment by Amar-3KT** [comment]
@sruthi1017 Kindly update the status.

**Comment by Amar-3KT** [comment]
Workflow now working fine.
@Mahesh3ktech Kindly check record not creating from issue and indent slip list to Indent purchase action.

**Comment by Mahesh3ktech** [comment]
Hi @Amar-3KT, try to create a record and update.

**Comment by Amar-3KT** [comment]
@Mahesh3ktech 
 We are getting error:- 

The metadata object Table 50150 was not found for the compiler with emit version 22005.


Page Edit - Workflow - MS-REQUISITIONAPW-01 ∙ Requisition Approval Workflow has to close.

**Comment by Amar-3KT** [comment]
Issue has been resolved Working fine

**Comment by Ejaz3KT** [comment]
@Mahesh3ktech I am facing this error while testing the material indent process can you please resolve this error ASAP

CC: @audhi3k 

![Image](https://github.com/3ktech/General/assets/125632927/5d673123-1bd1-4928-bfdb-94df60b80deb)

**Comment by Mahesh3ktech** [comment]
hi @Ejaz3KT, issue is resolved, kindly check that existing workflow will work.

**Comment by audhi3k** [comment]
UAT to client was done on 26th May2023
