### ISSUE TITLE
Post Dated Cheque (PDC)

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#190]

**Comment by Ejaz3KT** [comment]
@audhi3k Madam I've shared with you the post-dated design document

**Comment by sandhya3k** [comment]
@audhi3k 

I have done the customer and vendor part karthik assigned another task yesterday evening 7PM. I need to start today

@Shasthara

**Comment by sandhya3k** [comment]
@Ejaz3KT 

Please test on Sandbox environment.

cc: @audhi3k

**Comment by Ejaz3KT** [comment]
@sandhya3k  Ok I will test and update you

CC: @audhi3k

**Comment by niranjand22** [comment]
3kt team need to connect with client

**Comment by Ejaz3KT** [comment]
I`ve tested the PDC process and need to get confirmation from Audi Lakshmi madam.

CC: @audhi3k

**Comment by 3ktech** [comment]
hi @sandhya3k , can you take care of the below mentioned poits?

Provision to post pdc without lines.
Cues with reminders based on the setup
control to post the pdc = later than cheque date

Lookup to invoice only

Customer / Vendor there should be separate page

Cc: @audhi3k , @Shasthara

**Comment by sandhya3k** [comment]
@3ktech 

1 point is pending.

cc : @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

please test above points in sandbox env

cc: @audhi3k  @3ktech

**Comment by Ejaz3KT** [comment]
MS. @sandhya3k Madam, I`ll test the PDC process and I`ll update you

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 
please test an sandbox environment

**Comment by Ejaz3KT** [comment]
@sandhya3k Madam there is an issue I`ve dedicated while testing the PDC process  when we get any error while posting the PDC document automatically moves to PDC archive list Please resolve this issue ASAP

@audhi3k Madam

**Comment by sandhya3k** [comment]
@Ejaz3KT 
please let me know when ur available

cc : @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

I hope, it is working fine, if any issues please let me know.

cc : @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

Please test on sandbox environment?

cc : @audhi3k

**Comment by audhi3k** [comment]
There are new tickets created for the issues in PDC, #493 , #471 , #458 
closing this ticket
