### ISSUE TITLE
Credit memo posted using charge item- CN report incomplete

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1902]

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - Please merge the changes into the master.

Mr. @johnbosco3K - Please plan to deploy the changes into production by today after office hours.

CC : @audhi3k

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K - I have Merged my changes to Master.

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K and @NityaNirlipta - Is it deployed into the production?

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation from the client side.

![Image](https://github.com/user-attachments/assets/c7d3e161-bb8b-4809-8cf4-178c9a4d0903)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
IGST Amount and TCS Amount having the diffrences.
