### ISSUE TITLE
Purchase Quote Comparison

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#191]

**Comment by Ejaz3KT** [comment]
Ms. @sandhya3k I`ve Mailed you the purchase quote design document

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Shasthara  

Not yet started for this task

**Comment by sandhya3k** [comment]
@Ejaz3KT 

please test in sandbox for purchase quote comparison. once as per client requirement it will coming correctly another  part we will discuss

cc : @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

please test the sandbox environment?


cc: @audhi3k

**Comment by Ejaz3KT** [comment]
@sandhya3k I`ve tested the purchase quote comparison it is working fine 

CC: @audhi3k

**Comment by niranjand22** [comment]
@Ejaz3KT  please showcase to client

**Comment by Ejaz3KT** [comment]
I have explained about the process of purchase quote to the fervid team.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
@sandhya3k Please make changes in the purchase quote as we discuss in the call

Fervid requires the option to reopen the closed purchase quote, and they can convert that purchase quote into order.

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

As discussed, please test and update 

cc : @audhi3k

**Comment by Ejaz3KT** [comment]
Ms. @sandhya3k madam I`ve tested the purchase quote and need to showcase it to the client to get confirmation.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
I`ve showcased the purchase Quote functionality to Ms. Jhansi.

CC: @audhi3k

**Comment by audhi3k** [comment]
Waiting for Client confirmation

**Comment by Ejaz3KT** [comment]
Ms. Jhansi has confirmed

**Comment by Ejaz3KT** [comment]
As client has confirmed we can close this ticket 

CC: @audhi3k
