### ISSUE TITLE
Sales register report mismatch with Ledger entries

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1910]

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - TCS value is not calculating properly in the Sales Register Report. I have attached the excel sheet here.

[Sales Register-Apr24 to Nov24.xlsx](https://github.com/user-attachments/files/18032723/Sales.Register-Apr24.to.Nov24.xlsx)

CC : @audhi3k @Varunmk3k

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta As discussed,
1. Please check why the TCS value is not matching as per the General Ledger Entries.
2. Remove the G/L Account No. 5389 from the report, Value should not come for this g/l account under the sales register.

CC : @audhi3k

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K - Above Points are completed, Kindly Check and let me know.

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the closure on this from the client side. We can close the tikcet.

<img width="730" alt="Image" src="https://github.com/user-attachments/assets/95290e0c-4324-4784-bfa4-2f4774fffd49" />
<img width="728" alt="Image" src="https://github.com/user-attachments/assets/5019b2a3-970b-45f1-a851-9eb7ee201840" />


CC : @audhi3k
