### ISSUE TITLE
Create new field in Item master as "Variant"

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1917]

**Comment by TabrejAlam3K** [comment]
Hi @johnbosco3K - Please add the below field in the item master and enable the same under the Item List Page and Item Card Page.

1. Add the new field called "Item Varient" on the Item Master table. 
2. Enable the custom field "Item Varient" on the Item List page and Item Card page.

Before starting, please share the effort estimation on this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @NityaNirlipta - As discussed
1. Create new table called "Item Varient New" with two fields 1. Code(20) and 2. Description(100)
2. Add a new field called "Item Varient" in the Item Master and give the relation with the above table called "Item Varient New".
3. Enale the new field called "Item Varient." in the Item List Page and Item Card Page.

Before starting, please send the technical effort estimation.

CC : @audhi3k

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K - Technical Effort Hours - 4hrs
CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @TabrejAlam3K - As discussed, please proceed. I will take the approval.

CC : @audhi3k

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K - I Completed all the above points, Kindly check and if anything required let me know.
CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @NityaNirlipta - Please merge your changes into the master and get it deployed into the production by today.

CC : @audhi3k @johnbosco3K

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K - Okay Once I Complete I will Let you know.

CC: @audhi3k @johnbosco3K

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K - I completed , Kindly check and let me know .

CC: @audhi3k @johnbosco3K

**Comment by NityaNirlipta** [comment]
Hi @TabrejAlam3K - I Merged My changes to master.

CC: @audhi3k @johnbosco3K

**Comment by TabrejAlam3K** [comment]
We got the closure on this from the client side.

<img width="726" alt="Image" src="https://github.com/user-attachments/assets/aa2d32cb-b2e2-4f55-b5f5-183e5254ebd5" />

CC : @audhi3k
