### ISSUE TITLE
RE: ERROR " not able to adjust payment against invoices (import vendor

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1924]
Dear team,

Pls find below screen shot not able to adjust payment against invoices (import vendor)

![Image](https://github.com/user-attachments/assets/ee25f282-b739-4cf4-b776-f2f1831b5ba2)

**Comment by Prakash3K** [comment]
Today EOD we will close this ticket, due to not response 


CC: @audhi3k @TabrejAlam3K

**Comment by Prakash3K** [comment]
Solution provided over the call waiting for client confirmation to close this ticket 


CC: @TabrejAlam3K @audhi3k

**Comment by Prakash3K** [comment]
Hi @TabrejAlam3K sir, closure detailed mentioned below

Total consumed hours : 1 hours
Clouser date and mode: 23/12/2024, over the call
Person: Arun IT and Kavin
