### ISSUE TITLE
ERROR  in Credit memo

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1926]
Hi Team,

While posting the CN for additional discount  below error  is showing. We don’t have existing invoice ref no. for SOR business.

Kindly check with 3KT team and have to proceed the CN  without reference No.

![Image](https://github.com/user-attachments/assets/1c1a9620-be67-492c-9744-f57103a2d4fd)

**Comment by Prakash3K** [comment]
Solution provided over the call waiting for client confirmation to close this ticket 



CC: @audhi3k @TabrejAlam3K

**Comment by TabrejAlam3K** [comment]
Hi @Prakash3K - You marked this as waiting for client confirmation, but the status not yet changed. 

CC : @audhi3k

**Comment by Prakash3K** [comment]
Client confirmed to close this ticket 

Hi @TabrejAlam3K sir, closure details are mentioned below
 consumed hours: 2
Closure date and mode: 19/12/24 & over the call
Person : Arun IT
