### ISSUE TITLE
BANK PAYMENT VOUCHER AMOUNT

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1927]
Dear Team,

While complete the Bank payment &  after taking the printout the amount shown wrongly in the voucher, I selected one amount in the entry of Rs. 61190/- and applied entries are also shown one invoice number only.

But in two amount shown in the voucher. Pls check and revert back asap.

![Image](https://github.com/user-attachments/assets/5a23c0e0-b7fc-4f2c-a486-0d61ea631308)

**Comment by Prakash3K** [comment]
Hi @TabrejAlam3K sir, closure detailed mentioned below

Total consumed hours : 2 hours
Clouser date and mode: 23/12/2024, over the call
Person: Kavin
