### ISSUE TITLE
Invoice Schedule Against The orders

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#193]

**Comment by sandhya3k** [comment]
@Shasthara 

Not yet started 

cc : @audhi3k

**Comment by sandhya3k** [comment]
@audhi3k 

Today, iam going to connect @Padma2717

**Comment by audhi3k** [comment]
duplicate
[Multi Payment methods for Sales#381](https://github.com/3ktech/General/issues/381)
