### ISSUE TITLE
FW: Error- nothing to process

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1935]
Hi team,

Issue in Transfer order while send to uc Error is attached below in trail mail

![Image](https://github.com/user-attachments/assets/111f70d0-2afb-4a07-aacb-7e45110f5b2a)

**Comment by Tushargupta3K** [comment]
Support provided to kavin in call with sudarsan. RCA duplicate item in transfer order.
CLient confirmed to close over call.

**Comment by TabrejAlam3K** [comment]
Hi @Tushargupta3K - You have requested a closer, but you have not updated the efforts.

CC : @audhi3k

**Comment by Tushargupta3K** [comment]
Updated in github.
