### ISSUE TITLE
Check Printing

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#194]

**Comment by Shasthara** [comment]
@niranjand22 to share the check format

**Comment by Ejaz3KT** [comment]
This is the check format shared by the fervid team

[8. PDC Format.xlsx](https://github.com/3ktech/General/files/11197096/8.PDC.Format.xlsx)

**Comment by Manoj01021999** [comment]
@3ktech @audhi3k 
I had created the excel report ,but still now i didnt received the field mapping and requirements in the request page
waiting for  it

**Comment by Manoj01021999** [comment]
Excel report is created ,waiting for update form functional team regarding requirements of a request page

**Comment by Manoj01021999** [comment]
@Ejaz3KT 
cc : @audhi3k 
Excel report is created ,requesting  for update form functional team regarding requirements of a request page
pass the values and check the report

**Comment by 3ktech** [comment]
@Ejaz3KT, can you add more values to the requirement so that it can be taken up for development.
Cc: @audhi3k

**Comment by niranjand22** [comment]
@TabrejAlam3K  please discuss with @Ejaz3KT  on this

**Comment by TabrejAlam3K** [comment]
As per discussion with Mr. @Ejaz3KT - We need to get the proper requirement from the Client.

CC : @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Manoj01021999 As we discussed in the call please find the field mapping of check printing

[Check Printing Format.xlsx](https://github.com/3ktech/General/files/12158600/Check.Printing.Format.xlsx)

 

CC: @TabrejAlam3K sir, @audhi3k madam

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 As we discussed in the call please take up this task and start preparing this report 

CC: @audhi3k Madam

**Comment by Ejaz3KT** [comment]
Hi please find the final output of the check printing report 

![Image](https://github.com/3ktech/General/assets/125632927/16533abd-fcef-4362-a687-40e8bb6e43b3)

CC: @audhi3k @TabrejAlam3K @sruthi1017

**Comment by Ejaz3KT** [comment]
I`ve connect with the Mr. Sreedhar on phone call he told me he will connect with me at 4pm today

CC; @audhi3k

**Comment by Ejaz3KT** [comment]
Hi in the morning Mr. Sreedhar sir told me he will connect today for the reports UAT session but unfortunately, he had a meeting with the director so he told me he will connect tomorrow

CC; @audhi3k

**Comment by Ejaz3KT** [comment]
Hi I`ve shown this check printing report  to the fervid client they told me the report is fine and they will test and confirm

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi client has confirmed the check printing report it is fine we can close this ticket

CC: @audhi3k
