### ISSUE TITLE
Shipment Of Goods To Customer

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#195]

**Comment by panduc** [comment]
Ejaz has to explain the requirement in detail. he mentioned that will discuss Audhi and show it in system.

Today I will do the follow up with him.

**Comment by Shasthara** [comment]
@Ejaz3KT - Please coordinate with pandu

**Comment by Shasthara** [comment]
Assign this task to padma depends on her work load

**Comment by Shasthara** [comment]
@Padma2717

**Comment by Amar-3KT** [comment]
@Padma2717 
In-Transit Code must have a value in Transfer Header: No.=. It cannot be zero or empty.

We are getting this error while posting dispatch. Kindly check....

**Comment by Padma2717** [comment]
Hi @Amar-3KT 

That is comes under the Sales and Receivable setup Reclass Jnl TemplateName and Reclass Jnl BatchName

**Comment by Amar-3KT** [comment]
Yes we have already updated.

**Comment by Padma2717** [comment]
Hi Amar, Kindly test now

**Comment by Amar-3KT** [comment]
Hi @Padma2717 
Getting error- There is nothing to release for transfer order .

**Comment by Amar-3KT** [comment]
@panduc 
As discussed, Please check error---In-Transit Code must have a value in Transfer Header: No.=. It cannot be zero or empty.

**Comment by panduc** [comment]
@Amar-3KT  I've fixed the mentioned issue and found few other issues & fixed them as well.  

Please test and share your feedback.

After reading the code seems the flow should be optimized. let's discuss about it.

CC: @audhi3k

**Comment by Amar-3KT** [comment]
@panduc We are not able to post receive. Item available in In-Transit location 


![Image](https://github.com/3ktech/General/assets/111888825/2a7cb42c-e2f2-4260-bb58-e5dbf49baa01)



![Image](https://github.com/3ktech/General/assets/111888825/e8c91afd-164c-49d8-bb3a-5cb37024ac9c)

**Comment by Amar-3KT** [comment]
@Mahesh3ktech Please look into this.

**Comment by Amar-3KT** [comment]
@Mahesh3ktech We are getting following error at the time of post return:-

The Item Journal Batch does not exist. Identification fields and values: Journal Template Name='TRANSFER',Name='TRANSFER'

**Comment by Mahesh3ktech** [comment]
@Amar-3KT, post return issue has been resolved, kindly check.

working on post receipt issue.

**Comment by Mahesh3ktech** [comment]
@Amar-3KT, post receipt is resolved, working on post return issue.

**Comment by Mahesh3ktech** [comment]
Hi @Amarjeet, Post return is resolved. kindly test and update.

**Comment by Amar-3KT** [comment]
![Image](https://github.com/3ktech/General/assets/111888825/0b9c1613-5373-489e-a447-43d1aa05325f)

we are getting above error while posting post receive. Inventory available on In transit location.

**Comment by Mahesh3ktech** [comment]
hi @Amar-3KT, all the points are completed with validations, kindly check and update.
