### ISSUE TITLE
Reg-OPTION IS NOT SHOWN(Accounts)

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1952]

**Comment by Tushargupta3K** [comment]
The Ticket was regarding, the Co-pilot option not visible in BRS page.

Connected with HIPL team, mentioned them the new place of co-pilot function availble in BRS card and list page. and also helped them to reconcile the Entries.

Time consumed :1.5 hr
Closure confirmed by Stella and Arun over call.
