### ISSUE TITLE
FW: SALES STAGING ERROR FOR A SQUARE TECHNOLOGIES

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1955]

**Comment by Varunmk3k** [comment]
Dear 3KT team,

 

Below Error is showing in the sales staging. I have checked the customer card in BC and the particular customer is created by me but the Ship to address is not created by me. BC is auto creating the Ship to address for this customer even the GST & PAN are available. It seems technical issue behind this invoice posting. 

![Image](https://github.com/user-attachments/assets/b7d140d0-934f-40c2-b85a-1af59d581477)

**Comment by Prakash3K** [comment]
Hi @TabrejAlam3K sir, closure detailed mentioned below

Total consumed hours : 0.5 hours
Clouser date and mode: 23/12/2024, over the call
Person: Kavin
