### ISSUE TITLE
Item Error issue

### ISSUE THREAD

**Issue by Varunmk3k** [3ktech/General#1956]

**Comment by Varunmk3k** [comment]
<html>
<body>
<div class="ck-content" style="--ck-image-style-spacing: 1.5em; --ck-inline-image-style-spacing: calc(var(--ck-image-style-spacing) / 2); --ck-color-selector-caption-background: hsl(0, 0%, 97%); --ck-color-selector-caption-text: hsl(0, 0%, 20%); font-family: Segoe UI; font-size: 11pt;" data-wrapper="true" dir="ltr"><p class="MsoNormal" style="margin: 0;">Dear Team,</p><p class="MsoNormal" style="margin: 0;">&nbsp;</p><p class="MsoNormal" style="margin: 0;">Your team have approved the 2 code but the status of the code is pending in approval.</p><p class="MsoNormal" style="margin: 0;">&nbsp;Code is attached for your reference.</p><p class="MsoNormal" style="margin: 0;">&nbsp;</p><figure class="table" style="display: table; width: 461.55pt;">
SKU
--
8903439780630
8903439871338

</figure></div>
</body>
</html>

**Comment by Prakash3K** [comment]
Client confirmed to close this ticket 

Hi @TabrejAlam3K sir, Closure details are mentioned below

Consumed hours: 0.5
Closure date and mode: 18/12/2024 & Call
approved person: Kavin

CC: @audhi3k
