### ISSUE TITLE
FW: ERP ERROR -CHANDRAN   warehouse error

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1961]

**Comment by Prakash3K** [comment]
Issue has been resolved waiting for client confirmation to close this ticket


CC: @audhi3k @TabrejAlam3K

**Comment by Prakash3K** [comment]
Hi @TabrejAlam3K sir, closure detailed mentioned below

Total consumed hours : 2.5 hours
Clouser date and mode: 23/12/2024, over the call
Person: Kavin
