### ISSUE TITLE
Reg- Permission error Traning

### ISSUE THREAD

**Issue by Varunmk3k** [3ktech/General#1968]

**Comment by Varunmk3k** [comment]
![Image](https://github.com/user-attachments/assets/c28a1b8d-7ae0-4a9b-9539-059b6b867016)

**Comment by Prakash3K** [comment]
Hi @TabrejAlam3K sir, closure detailed mentioned below

Total consumed hours : 2 hours
Clouser date and mode: 20/12/2024, over the call
Person: Arun IT

CC: @audhi3k
