### ISSUE TITLE
Error in Sales staging With  Myntra  Customer.

### ISSUE THREAD

**Issue by Varunmk3k** [3ktech/General#1974]

**Comment by Varunmk3k** [comment]
![Image](https://github.com/user-attachments/assets/33b4831c-66ce-41d7-a991-e2e8ab5d607d)

**Comment by TabrejAlam3K** [comment]
Hi @Prakash3K Client Estimated Hrs, Client Approved Hrs and ETS are still blank

CC : @audhi3k

**Comment by Tushargupta3K** [comment]
The issue resolved over the meeting with client. Shown the mapping and RCA.
ESt hrs 2
Approved hrs 2

Meeting attended by @gsudarsan3k  @Tushargupta3K
