### ISSUE TITLE
Delivery Challan - changes

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#198]
n the Delivery Challan we need following changes,

 

1.     On the top “ DELIVERY CHALLAN”

2.     Non-Returnable or Returnable can print downside or within bracket

3.     We need GST Rate and Tax amount

4.     While creating DC we need option  to select -Supply/Own Use/Job work/Others and same to be print in DC.

**Comment by audhi3k** [comment]
Dear Mr Senthil,

As per our last discussion on the context of the mail two days before, we are yet to receive the Delivery challan report and the changes.

We would like to have call at 3 pm, kindly confirm your convenience to be proceed further on this case


Regards,
Audhi Lakshmi S

**Comment by audhi3k** [comment]
Dear Mr Rajesh,

We have completed the points, kindly check and confirm on closure


Regards,
Audhi Lakshmi S

**Comment by audhi3k** [comment]
Dear Mr Rajesh,

1.	We need GST Rate and Tax amount – Not working 
2.	While creating DC we need option to select -Supply/Own Use/Job work/Others and same to be print in DC. – No field available to select => On Request page Purpose is added
3.	Pin Code in address field not reflecting – Please bring the “ Post code” Field both in “Ship from Address” and “Ship to Address”  column.

The above points are completed, for point 1 in the transfer order the Structure should be selected as GST and calculate structure value to be done to get the GST, if the GST is available in the transfer shipment the value will be populated in the report.

Kindly check and confirm.

**Comment by niranjand22** [comment]
Dear Ms. Audilakshmi,
We need GST Rate and Tax amount – Not working  - As discussed this details need in our DC kindly provide on priority basis .

**Comment by niranjand22** [comment]
@audhi3k  client is asking for update on this case

**Comment by niranjand22** [comment]
![Image](https://github.com/3ktech/General/assets/116243958/29c7ade2-d3f7-4b14-8bb0-13ded9979e88)
![Image](https://github.com/3ktech/General/assets/116243958/dcd1cdfc-e614-472c-a6aa-82d35c363037)

**Comment by niranjand22** [comment]
mail sent to client -- This is Standard Report report and we have to analyse  why this wrong values are getting populated, then only we can make comment on this issue.

**Comment by niranjand22** [comment]
@audhi3k  Please Prioritize this ticket they need it urgently

**Comment by niranjand22** [comment]
1.GST amount is calculating wrongly in Report
2. They Want DC Purpose Field with drop down option--- "Branch Transfer within state ", "Job work ", "Supply ","Others-“provision required for manual feeding  “. Also this field value should be displayed in DC Purpose field in DC report

![Image](https://github.com/3ktech/General/assets/116243958/04810105-f52d-4745-b14b-c6bf82a12ab6)
![Image](https://github.com/3ktech/General/assets/116243958/6365e491-1d1b-4128-bb3e-f9ae7ea4e3ac)

**Comment by niranjand22** [comment]
Navigation to Generate Report

Search "Posted Transfer Shipment"> Filter with No "ND/KT7WS/PW2324/0006" OR "ND/KT7WS/PW2324/0006" > Select and open the record>Action> Click "Print Transfer Shipment Shipment GST">Preview

**Comment by niranjand22** [comment]
Hello Ramesh, 

Thank you for the call. I appreciate your confirmation that the DC Purpose field is functioning correctly. 

Additionally, you raised three more points for consideration. 
1.	The caption 'Invoice No' in the DC Report should be replaced with DC No.
2.	The caption 'Invoice Date' should be replaced with DC Date.
3.	We have noticed that GST is not being calculated when performing non-returnable transfers within the state.
cc
@audhi3k

**Comment by niranjand22** [comment]
PWTO/2324/0241

**Comment by niranjand22** [comment]
![Image](https://github.com/3ktech/General/assets/116243958/6231bd15-d2da-446f-b5c1-761d76be82a7)

I have completed the 1st and 2nd Point.

3rd Point --I checked..GST is not applicable in same state transfer


cc @audhi3k
