### ISSUE TITLE
Fw: ERP Error PO CATEGORY ERROR

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#199]
![Image](https://user-images.githubusercontent.com/116243958/228154805-f0ccb8e2-9f25-400f-9122-90bae5754708.png)

**Comment by audhi3k** [comment]
Dear Mr Senthil,

The PO Category is blank, hence. error and if the PO-WO Category is defined PO Category will be blank.

If PO Category is mandatory, then don't update PO-WO Category.


Regards,
Audhi Lakshmi S

**Comment by audhi3k** [comment]
Dear Mr Senthil,

Thanks for confirming on closure of the ticket


Regards,
Audhi Lakshmi S
