### ISSUE TITLE
FW: Request for invoice against advance CAS-01201-L4C3C7

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#200]

**Comment by audhi3k** [comment]
Dear Mam,

Couldn’t make GRN below PO - PWC/21-22/DPO228


![Image](https://user-images.githubusercontent.com/121653651/228161746-5be4a1a6-0ee4-4508-a619-bdf6b6e24c35.png)

**Comment by audhi3k** [comment]
Dear Mr Senthil,

Thanks for confirming on the closure


Regards,
Audhi Lakshmi S
