### ISSUE TITLE
New Points Raise by LKS - 28-03-2023

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#201]
During the Short Session Client raised the below points

1. Page 50084 (For Super User Only)
- Check Amount (LCY) - It Should be editable
- Exchange Rate - It Should be editable
- Client TAN - It Should be editable
- Client Bank - It Should be editable
- Client Bank Name - It Should be editable

2. Page 50070 and 50078 - It should be not editable if the Submitted Boolean is true.
3. Bank Receipt Voucher - While selecting the Collection No. Exchange got updated based on the Collection Card which we have selected on Receipt line
4. While Selecting the Apply to Doc No. - Amount should always in credit amount
5. Post Application Error for Foreign and Domestic Customers.
6. Validation over on - Voucher Amount always be equal to or less then from the Invoice Amount.

**Comment by TabrejAlam3K** [comment]
Snapshot for Points No. 5 -

NAV16 Snapshot.

![Image](https://user-images.githubusercontent.com/116171982/228422973-3452b7e2-b72d-42bd-8734-34f7f0707366.png)

BC Snapshot.

![Image](https://user-images.githubusercontent.com/116171982/228423021-bf2ba8e8-0f7b-442c-a722-ed2170e0b785.png)


Post Application Error-

![Image](https://user-images.githubusercontent.com/116171982/228423164-8e88321f-bdcb-4357-bfb3-4cfe381318dd.png)

**Comment by panduc** [comment]
@Tablrej, I've Completed point 1 & 2 Page 50084 and Page 50078 
General Ledger Entries Page Ext 50084 and Report 50203. all 3 points in UAT. Please check and confirm.

**Comment by panduc** [comment]
General Ledger Entries --> Actions --> Print voucher

![Image](https://user-images.githubusercontent.com/110709312/228591172-d4ba00bb-c1fc-4f5c-8533-4d724ff08614.png)

**Comment by TabrejAlam3K** [comment]
@panduc @sandhya3k - Need to close the below points on urgent basis.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



By Mail | Description – It is updating   based on 3rd line of Dimension Value Name. (functionality as   nav16) – It should be last line and not on 3rd line in a   static manner. | InProgress
-- | -- | --
By Mail | Cheque voiding: Before posting   void is possible.  After posting void is not possible.  We require   this facility to be in place. | InProgress
UAT Session | Page 50084 (For Super User   Only)        1. Check Amount (LCY) - It Should   be editable        2. Exchange Rate - It Should be   editable        3. Client TAN - It Should be   editable        4. Client Bank - It Should be   editable        5. Client Bank Name - It Should be   editable | InProgress
UAT Session | While Selecting the Apply to Doc   No. - Amount should always in credit amount | InProgress
UAT Session | Bank Receipt Voucher -   Validation over on - Payment Amount always be equal to or less then from the   Apply Invoice Amount. | InProgress



</body>

</html>

CC : @audhi3k

**Comment by audhi3k** [comment]
Mr @panduc, can you update the status
