### ISSUE TITLE
CancelRTB is not Working

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#202]

**Comment by TabrejAlam3K** [comment]
@3ktech - Please update on is it Completed.

CC ; @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K  from 13th to next 16 char is Invoice or Credit Memo No. Please test with this naming.

**Comment by TabrejAlam3K** [comment]
@panduc - Taking under review.

**Comment by TabrejAlam3K** [comment]
@panduc - Working Fine but Mr. Somendra will confirm then we can close this

CC : @audhi3k
