### ISSUE TITLE
Action is required - Posted Sales Invoice Page

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#204]
Send Invoice to LCMS action is required in the Posted Sales invoice Page

**Comment by TabrejAlam3K** [comment]
@3ktech - Please update on is it Completed.

CC ; @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K  Created new action and deployed in UAT & DEV. Please check and confirm.



![Image](https://user-images.githubusercontent.com/110709312/228806023-628f66bd-8205-40fc-9104-445b6768f2cb.png)

**Comment by TabrejAlam3K** [comment]
@panduc - I found it - Can you please explain it here what is there functionality, When I clicked on **Send Invoice to LCMS** what will happen.
