### ISSUE TITLE
Action is required - Posted Sales Credit Memo Page

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#205]
Send Credit Memo to LCMS action is required in the Posted Sales Credit Memo Page

**Comment by TabrejAlam3K** [comment]
@3ktech - Please update on is it Completed.

CC ; @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K  Created new action and deployed in UAT & DEV. Please check and confirm.



![Image](https://user-images.githubusercontent.com/110709312/228806404-102fc651-08ba-4a9e-9a0a-8d9d8ae3f1b8.png)

**Comment by TabrejAlam3K** [comment]
@panduc - I found it - Can you please explain it here what is there functionality, When I clicked on **Send Credit to LCMS** what will happen.
