### ISSUE TITLE
Add Debit amount field credit amount field in job G/L journal Page

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#214]

**Comment by Ejaz3KT** [comment]
Please add Debit amount column and Credit amount column in Job G/L journal Page

**Comment by sruthi1017** [comment]
@Ejaz3KT it is done and the changes has been merged and published

**Comment by niranjand22** [comment]
@sruthi1017 please update status for this case

**Comment by sruthi1017** [comment]
@Ejaz3KT it has been published to the production environment can u please check it out 
cc @audhi3k

**Comment by Ejaz3KT** [comment]
@sruthi1017 I`ve tested the Debit amount column and credit amount column in the Job G/L journal and It is working fine.

CC; @audhi3k
