### ISSUE TITLE
Sales Invoice Report Alignment

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#215]

**Comment by Ejaz3KT** [comment]
Ficthner Team requirements:

1. Posted Sales Invoice Report Alignment 
2. In Sales Invoice Header Increase Manpower/Description Length up to (400)
3. In Sales Invoice Line Increase Invoice/Description Length up to (400)
4. In Sales Invoice Header Reference No (Ref No.) Increase Length up to (200)

**Comment by Mahesh3ktech** [comment]
@Ejaz3KT, Changes has been done can you check and update.

**Comment by Ejaz3KT** [comment]
@Mahesh3ktech I`ve Mailed to Fitchner team and waiting for their confirmation.

cc: @audhi3k

**Comment by niranjand22** [comment]
Mr Singarvel will update on this

**Comment by niranjand22** [comment]
completed
