### ISSUE TITLE
POSTED SERVICE INVOICE PRINT ERROR

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#216]

**Comment by audhi3k** [comment]
Dear Mr Ayyappan,

In the report total amount issue is fixed, kindly check and confirm. 


Regards,
Audhi Lakshmi S

**Comment by audhi3k** [comment]
Dear Mr Ayyappan,

Thanks for confirming on closure


Regards,
Audhi Lakshmi S

**Comment by niranjand22** [comment]
HI @audhi3k , Please forward me the mail in which this case was raised

**Comment by niranjand22** [comment]
Dear Mam,

Waiting for your call

Thanks & Regards, 
N.Senthilnathan


![Image](https://github.com/3ktech/General/assets/116243958/95bf11c9-ef8f-4a82-bbaa-cbbaf67aa36c)
