### ISSUE TITLE
Report Cust Detailed Aging 50105 Issues

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#218]
Error Response

![Image](https://user-images.githubusercontent.com/116171982/229700797-b7951c16-46d8-43c8-b876-f3512ec26186.png)

**Comment by TabrejAlam3K** [comment]
@audhi3k - This error happen during the Report testing with Mr. Viswanathan sir, Please align a technical who will resolved this issues.

**Comment by panduc** [comment]
@TabrejAlam3K @audhi3k  the rport 50105 is working fine. 

I'Ve tested in UAT. 
Filters: Customer C00040 Starting Date 01.10.2022 Ending Date: 20.10.2022

**Comment by niranjand22** [comment]
@TabrejAlam3K  check with client on closure

**Comment by TabrejAlam3K** [comment]
As of now not error is coming while running the report. We need to test with the client.

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/1cfaa3b6-aa99-4313-9d5e-d983632788cf)

**Comment by TabrejAlam3K** [comment]
As of now we are going to close this issue because client not responded on since long time, We are assuming the issue is working fine.

CC : @audhi3k
