### ISSUE TITLE
New Reports requirement - BC (Merit)

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#219]
New Reports Requirement in BC

1. Report 1 - Need to add some Dimension(Value Should be come in the respected column) column in the additional field in the Report Output Data
2. Report 1 - Need to add Location(Value Should be come in the respected column) column in the additional field in the Report Output Data

**Comment by TabrejAlam3K** [comment]
Attached Sample Report Format.

[Report 1_Trial Balance (with all Dimension combinations) - Copy_MDT_RSP.xlsx](https://github.com/3ktech/General/files/11145562/Report.1_Trial.Balance.with.all.Dimension.combinations.-.Copy_MDT_RSP.xlsx)
[Report 2_Trial Balance (with Location Dimension combinations)_MDT_RSP.xlsx](https://github.com/3ktech/General/files/11145563/Report.2_Trial.Balance.with.Location.Dimension.combinations._MDT_RSP.xlsx)

**Comment by niranjand22** [comment]
waitning for approval  for time

**Comment by niranjand22** [comment]
follow up sent to Mr Pawan

**Comment by Shasthara** [comment]
@niranjand22 , Need update

**Comment by niranjand22** [comment]
Hi @Mahesh3ktech , Client has approved the hours ..please start this activity.

**Comment by sandhya3k** [comment]
@niranjand22 

i have some clarification for field mapping.

cc : @audhi3k

**Comment by niranjand22** [comment]
Hi Ms @sandhya3k Please update the status here

**Comment by Shasthara** [comment]
@niranjand22 to update

**Comment by sandhya3k** [comment]
@niranjand22  can u explain the functionality of the customization?

**Comment by niranjand22** [comment]
Hi @sandhya3k  we can connect for this in day

**Comment by sandhya3k** [comment]
@niranjand22 

Please test in sandbox environment 

Report id : Trail Balance (50107)

cc : @audhi3k

**Comment by niranjand22** [comment]
Hi Sandhya,

![Image](https://github.com/3ktech/General/assets/116243958/dce223d6-d80a-41af-9181-c1010b64bbd1)



![Image](https://github.com/3ktech/General/assets/116243958/084ae927-896e-468b-a8b3-70140806f23c)

**Comment by niranjand22** [comment]
@sandhya3k  following points.

2. Please add G/l Account name.
3.  Please hide dimension set id column
4. Please make debit and credit column little wide
5. Align Report to Centre

**Comment by niranjand22** [comment]
@sandhya3k  please update the progress

**Comment by niranjand22** [comment]
Hi @sandhya3k , I have updated some modification kindly  complete and update here

**Comment by niranjand22** [comment]
i will update here after testing

**Comment by niranjand22** [comment]
Please add G/l Account name.
Please hide dimension set id column
Please make debit and credit column little wide
Align Report to Centre

**Comment by niranjand22** [comment]
Its working fine

**Comment by niranjand22** [comment]
@sruthi1017  Please change caption of Cutomised trial balance to ..**Trial Balance with Dimension**

**Comment by sruthi1017** [comment]
@niranjand22 completed the changes as u mentioned.

**Comment by niranjand22** [comment]
@sruthi1017 Clients wants few more changes..

1. Heading and Header Should be available on all the page.
2. Make it same format (appearance wise) as Detail Trial balance
3. In the End Total  Column is required

**Comment by niranjand22** [comment]
@sruthi1017 kindly update

**Comment by sruthi1017** [comment]
hi @niranjand22 the points mentioned above are completed. can u check whether the report is working fine

**Comment by niranjand22** [comment]
i have checked..ms swathi will check and confim

**Comment by niranjand22** [comment]
Client wants Net change header on top of debit and credit
total earning should only be calculated for account starting from 5 no. and >
balance amount should be added ..balance as of posting date end

**Comment by sruthi1017** [comment]
@niranjand22 updated the report with the points mentioned, test whether the changes are fine

**Comment by niranjand22** [comment]
They neeed balance column also..similar to detail trial balance....where balance column will show the balance as of last posting date provided.. @audhi3k  need your help on this

**Comment by niranjand22** [comment]
![Image](https://github.com/3ktech/General/assets/116243958/991823fc-93fc-4332-89e6-dccd28a98407)
![Image](https://github.com/3ktech/General/assets/116243958/928b4adc-448f-4b2f-9732-a7b691a7882b)

**Comment by niranjand22** [comment]
Points to Change

1. Net Change  Grey heading should be extended to Balance column
2. Dimension Cation should be same as detail trial balance
3. Totaling is required with respect to 1s , 2s and 3s etc no. series.
4. Total Earning should be calculated from account no starting from 5 no. series and ownwards.
5.grand  Total of balance

@sruthi1017  we need to perform this changes..lets connect I will explain u this over call

**Comment by audhi3k** [comment]
@3ktech, align @sruthi1017 to complete this

**Comment by audhi3k** [comment]
Mr @niranjand22 and Ms @sruthi1017 , Update the status

**Comment by niranjand22** [comment]
Further requested changes are done. I have asked client to check in confirm.
cc--@audhi3k

**Comment by niranjand22** [comment]
@sruthi1017  Once deployed to live please confirm

**Comment by niranjand22** [comment]
client confirmed for closure

cc @audhi3k
