### ISSUE TITLE
"For the sales invoice with Transaction  Type => B2B,SEZWOP,EXPWOP - EInvoice is required  so only this case it should be manual and for other cases it to  automated for Delhi location also (Enhancement point)"

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#229]

**Comment by Shasthara** [comment]
@audhi3k , please verify this ticket and align. this ticket was not discussed today morning.

**Comment by sandhya3k** [comment]
@TabrejAlam3K  

please test the UAT environment 

cc : @audhi3k @Shasthara

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

please test on UAT environment.

cc: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - I have tested with above cases but still it is not working.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - As per our discussion( @TabrejAlam3K @audhi3k @sandhya3k ) Please update it here once it will get completed.

**Comment by TabrejAlam3K** [comment]
Ms. Sandhya is working on she will update once it will get completed.

**Comment by TabrejAlam3K** [comment]
It is working fine i have tested with below scenario.

1. Posted Sales Invoice No. - LKS-1718-03651 (B2B) - Invoice not downloaded auto
2. Posted Sales Invoice No. - LKS-1718-03652 (B2C) - Invoice get downloaded auto. 

In Sales Invoice and Posted Sales Invoice **Client Transaction Type** field is there.

**Comment by TabrejAlam3K** [comment]
Confirmed on 3rdMay

CC : @audhi3k
