### ISSUE TITLE
Cost Centre to be updated while selecting the application

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#23]

**Comment by Amar-3KT** [comment]
Cost center done for only bank payment voucher other voucher are pending

**Comment by sandhya3k** [comment]
Now, I am working on another task @Amar-3KT once, i complete the task i will start to work on this issue.

**Comment by sandhya3k** [comment]
@Amar-3KT  as per our discussion i hope all vouchers it's working fine. If it's not please let me know?

**Comment by Amar-3KT** [comment]
In all voucher cost center updating now need client confirmation.

**Comment by audhi3k** [comment]
@Amar-3KT , send mail to Mr Singaravel for closure of the ticket

**Comment by audhi3k** [comment]
Client hasn't raised any issue, so closing this ticket
