### ISSUE TITLE
"Posting date should be updated with the work date,  irrespective of the value in posting date"

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#230]

**Comment by TabrejAlam3K** [comment]
@panduc - It is not working i have tested infront of Ms. Sandhya, Please look

Document No. - 0000833303
Document Posting Date - 02-04-2023

Work Date is - 07-04-2023

CC : @audhi3k @Shasthara

**Comment by audhi3k** [comment]
UAT done with client
