### ISSUE TITLE
"Draft Invoice - HSN to be same as posted sales invoice  (Enhancement point)"

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#232]

**Comment by sandhya3k** [comment]
@TabrejAlam3K  

 i have updated the HSN code to all draft reports. i deployed in UAT environment

here i mentioned the list the of the reports.

50152 "Draft Credit Note GST"
50148 "Draft Invoice GST"
50150 "Branch Draft Invoice GST"
50161 "IBL Tax Draft GST/Credit Memo"
50157 "Branch Draft Invoice GST(Devp)"
50156 "Draft Invoice GST(dev)"

cc : @audhi3k

**Comment by audhi3k** [comment]
UAT completed with client
