### ISSUE TITLE
Report IBL Tax Invoice GST 50153

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#235]

**Comment by Shasthara** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



Report ID | Name | MenuSuite/Page | Status given by 3KT | Further remarks by LKS Team
-- | -- | -- | -- | --
50153 | IBL Tax Invoice   GST | Posted Sales   Invoice | Completed | Footer carried   another company details and not IBL,  Description details completely   incorrect including Event and Venue details.
50143 | Credit IBL Note   GST | Posted Sales   Credit Memo | Completed | Event and venue   details are not appearing in the description column
50036 | Customer Detailed   Aging (NEW) | Finance Report | Completed | Field length   issue
50019 | Accounts Voucher   Report | Finance Report | Completed | Nothing gets   displayed
50000 | IBL Draft GST | Sales Invoice Pre | Completed | Incorrect   template and please link with correct template based on earlier remarks for   other cases of IBL
50203 | Print Voucher | Finance Report | Completed | Correctly coming   - still cheque number  not coming



</body>

</html>

**Comment by TabrejAlam3K** [comment]
@sandhya3k Discussed - Please update on once it will get completed

CC : @audhi3k @Shasthara

**Comment by audhi3k** [comment]
UAT done with client
