### ISSUE TITLE
Merge Description => Enhancement point

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#243]
If on the sales line Merge Line Boolean is true the Merge Description 1 and Merge Description 2 should be print on the report description.

**Comment by panduc** [comment]
@TabrejAlam3K 
I've verified Posted Sales invoice GST report 50146 has the solution. but other reports like Posted Inv Logo, Posted Branch In Logo, Sales Inv Logo etc in NAV 2016 printing multiple lines(Merge description functionality is available).

It should be new enhancement.

Please prepare the list of report in excel check it in NAV 2016 Merge description functionality enabled and not enabled reports. Discuss with customer and let us know.

**Comment by audhi3k** [comment]
Reply from Mr Viswanathan
This is required for all cases.  Please do the needful after the go-live environment.

**Comment by panduc** [comment]
@audhi3k @TabrejAlam3K 
The below reports merge description enabled.
RTB/Sales Invoice:
50156 -> "Draft Invoice GST(dev)"
50157 "Branch Draft Invoice GST(Devp)"
50161 "IBL Tax Draft GST/Credit Memo"

Posted Sales Invoice:
50146 -> "Tax Invoice GST"
50149 "Branch Tax Invoice GST"
50003 INVOICE_IBL_FINAL
50170 "Tax Invoice GST Logo"
50171 "Branch Tax Invoice GST Logo"

**Comment by TabrejAlam3K** [comment]
Completed - Report ID 50150 to delink

CC : @audhi3k
