### ISSUE TITLE
Reports to be listed down as seperate report memu => Enhancement point

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#248]

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Once it will completed please informed so that we can close this points.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Client will provide the list of missing report then we can add those reports also in this menu.

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/c7289854-e9ef-45dd-b8b1-548e6632f6b9)

**Comment by TabrejAlam3K** [comment]
No any response receive from the client side.

**Comment by TabrejAlam3K** [comment]
We are closing this ticket if required we will create the new ticket in git in future.

CC : @audhi3k
