### ISSUE TITLE
Testing Issue In BC 365-LKS

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#25]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/DELL/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/DELL/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<div ccp_infra_version=3 ccp_infra_timestamp=1673013761559 ccp_infra_user_hash=2696106709
ccp_infra_copy_id=85285c35-82ec-455e-96f4-95494b45eb13 data-ccp-timestamp=1673013761559>

<body link="#0563C1" vlink="#954F72">

Sr No. | Issue Description | Tested By | Testing Date | Comments | Status
-- | -- | -- | -- | -- | --
1 | Bank Receipt Voucher- In   "Collection No" field drop down list not available | Amarjeet Singh | 06-01-2023 | In Nav 2016 working fine | Open
2 | RTB and CRTB not available on role   center-CRTB related option not available in search box | Amarjeet Singh | 06-01-2023 | Account manager role assign to User5 | Closed
3 | In Change log entries table data not   available in bc365 | Amarjeet Singh | 06-01-2023 | In Nav 2016 Log entries available- Record deleted by 3KT | Internal Discussion
4 | Third party Sandbox not available-Need to   check Sales module and related things | Amarjeet Singh | 06-01-2023 | Sprt case | Open
5 | While posting bank receipt voucher   getting error:- "Too many key fields were specified, so "Cust.   Ledger Entry" could not be retrieved. The number of fields in the   primary key is 1." | Amarjeet Singh | 06-01-2023 | As of now working fine | Closed
6 | While selecting from state in gst rate Getting error: Linked   Attribute ID must have a value in Tax Rate Column Setup: Tax Type=GST, Column   ID=3. It cannot be zero or empty | Amarjeet Singh | 09-01-2023 | In BC getting error | Closed
7 | The Sales Cr.Memo Header does not exist. Identification fields   and values: No.='' While posting sales invoice but after error invoice posted | Amarjeet Singh | 09-01-2023 | Working Fine | Closed
8 | The Sales Cr.Memo Header does not exist. Identification fields   and values: No.=''	at the time posting sales invoice from get shipment | Amarjeet Singh | 09-01-2023 | Working Fine | Closed
9 | The Sales Invoice Header does not exist. Identification fields   and values: No.='' While posting sale shipment from order | Amarjeet Singh | 09-01-2023 | Working Fine | Closed
10 | The Sales Invoice Header does not exist. Identification fields   and values: No.= While Posting Sales Credit memo | Amarjeet Singh | 09-01-2023 | Working Fine | Closed
11 | The transaction cannot be   completed because it will cause inconsistencies in the G/L Entry table. Check   where and how the CONSISTENT function is used in the transaction to find the   reason for the error.     Contact your system administrator.     Tables can be marked as inconsistent during comprehensive tasks, such as   posting. This prevents data from being updated incorrectly. | Amarjeet Singh | 11-01-2023 | In BC while posting cash payment voucher | Closed
12 | In customer card list - Email Customer Aging--You can not   execute this report!!! | Amarjeet Singh | 11-01-2023 | In BC and NAV Both getting error | Open
13 | Not able to open Nav database(In Developer) for user 5 | Amarjeet Singh | 11-01-2023 |   | Closed
14 | Bank rcpt voucher-Button "Get Open posted line for TCS on Payment   calculation" not vailable | Amarjeet Singh | 12-01-2023 | In nav 2016 action Menu button available but in Bc not available | Open
15 | Bank payment voucher and bank receipt voucher-Button "Import   Salary" not vailable | Amarjeet Singh | 12-01-2023 | In nav 2016 Navigate Menu button available but in Bc not available | Open
16 | Bank payment voucher-Report "HDFC ChECK MULTI LINE" not   vailable(Check printing new 50031) | Amarjeet Singh | 12-01-2023 | In nav 2016 Navigate Menu Report available but in Bc not available | Open

</body>

</html>

**Comment by audhi3k** [comment]
Done
