### ISSUE TITLE
Merged Bill and CRN ID 50138 - Report brings all values as Zero

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#253]

**Comment by audhi3k** [comment]
![Image](https://user-images.githubusercontent.com/121653651/230648614-bcd55a51-f07f-4e95-aaaa-d3f3cdadf897.png)

**Comment by TabrejAlam3K** [comment]
@audhi3k - We need to change the logic instead of Amount to Customer.

**Comment by TabrejAlam3K** [comment]
@audhi3k - Mr. Viswanathan asked about the status of the Reports.

**Comment by panduc** [comment]
@TabrejAlam3K The changes BillAmount(Local& Foreign Currency) has been completed and deployed changes in UAT. Please check and Confirm.

**Comment by TabrejAlam3K** [comment]
Client had tested it during the session he will confirm for closure.

**Comment by TabrejAlam3K** [comment]
Confirmed on 3rdMay
