### ISSUE TITLE
Send updated status back to LCMS

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#255]

**Comment by TabrejAlam3K** [comment]
Today we will test with the client user Mr. Somendra and update it here

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
LKS Team is not available for testing - Mr. Somendra is also trying to connect with the related users but still not response received from their side.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
@3ktech - Mr. Kartik D Please update on whatever we discussed with the client.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by 3ktech** [comment]
@TabrejAlam3K , you will have to do system integration testing with somendra. the fix was already updated in the UAT instance.

**Comment by 3ktech** [comment]
changes deployed @TabrejAlam3K , pls test this.

**Comment by TabrejAlam3K** [comment]
@TabrejAlam3K need to test along with the client user Mr. Somendra.

**Comment by TabrejAlam3K** [comment]
Need to test with the client.

**Comment by audhi3k** [comment]
To be Test by Mr Somendara and update once all the issue is get completed

**Comment by TabrejAlam3K** [comment]
Hi Mr. Kartik D @3ktech - the functionality of Send Updated status send back to LCMS is not working currently we have tested in UAT environment.

**Comment by 3ktech** [comment]
@TabrejAlam3K what is the issue over here? can you share me your analysis over here?
@audhi3k

**Comment by TabrejAlam3K** [comment]
Mr. Somendra need to change the code level in LCMS Side and confirm.

**Comment by TabrejAlam3K** [comment]
Hi Mr. Kartik D @3ktech - Please apply your changes for the below company in UAT Environment. Currently the functionality is only working for **LKS Company**.

1. V.Lakshmikumaran
2. V.SHRIDHARA

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech Kartik D - Please confirm the status whether it is deployed or not.

CC : @audhi3k @narayana3kt

**Comment by TabrejAlam3K** [comment]
UAT is going on with the client (Mr. Somendra)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech (Kartik D) - You can deploy it for other 2 companies client has confirmed it is working fine in LKS UAT.

![Image](https://github.com/3ktech/General/assets/116171982/3d9fee21-7fb0-45fb-a3a3-f2dc8b0dd521)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. Kartik D @3ktech - Please deploy it for two other companies(VLK & VSH) and Production as well. It is still pending since long.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
I have done the testing with the client in other two companies VLK & VSH, Process is working fine but still they need some to cross verify the functionality again. **We are holding this point till today Evening after that we will move this changes into the production after the client confirmation**.

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Client confirmed for closer via Mail.

![Image](https://github.com/3ktech/General/assets/116171982/c92292df-e575-41fc-bb91-f3868ec4b7a5)
