### ISSUE TITLE
Permission Set for Balan P. - Enhancement Points

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#258]

**Comment by TabrejAlam3K** [comment]
@niranjand22 - Please update the status and comments.

**Comment by niranjand22** [comment]
Currently we have created Mumbai BAsed persmission to user balan p in UAT company and asked k vishwa to check. waiting for their resposnse

**Comment by TabrejAlam3K** [comment]
@sandhya3k - We have done some changes in Sruthi's local Machine please connect with Ms. @sruthi1017 and get the information and deployed it in Dev/UAT/Sandbox then need to move into the Production.

CC : @audhi3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K 
i have published the sruthi changes in Dev/Sandbox/UAT please test and confirm then i will deploy to the prod

cc : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - I have tested this into the UAT it is working fine. Please move this changes into the Production.

**Comment by TabrejAlam3K** [comment]
User are not able to login with the **Hyderabad BC** Users. We need to check this.

**Comment by TabrejAlam3K** [comment]
Error During Login in to UAT Company

![Image](https://github.com/3ktech/General/assets/116171982/04149782-3e49-4c49-832f-482bbbefd16f)

**Comment by TabrejAlam3K** [comment]
Client Requirement - they want to view the record base on the user setup location

Example - If user setup have location New Delhi so user can view the entries only for New Delhi location

Collection Details List.Location Code = User Setup.Location Code

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - tested in UAT it is working fine please move this changes into the Production.

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/34e51212-bbe4-483d-878a-451e579a9233)

**Comment by TabrejAlam3K** [comment]
As of now we are going to close this issue because client not responded on since long time, We are assuming the issue is working fine.

CC : @audhi3k
