### ISSUE TITLE
6. Branch GST Invoice - logo

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#262]
State and State code not displaying full if the Name for Customer is printing in multiple line (branch 3 - invoice no. 4 for this year)

**Comment by panduc** [comment]
@TabrejAlam3K it's done and deployed in UAT. Please check and confirm

**Comment by panduc** [comment]
Report fix applied on 50170 and 50171

**Comment by TabrejAlam3K** [comment]
@panduc - Now it is printing in both the report 50170 and 50171 **(Name of Country of Destination : CANADA)**

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc  Please look this - State Code is not displaying in the Reports.

Credit Note Branch Logo (50175, Report Request)
Credit Note GST Tax Logo (50176, Report Request)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - Manual Report it is working fine but we need to find out which report going auto download there the company logo is not coming.

CC : @audhi3k

**Comment by panduc** [comment]
It new changes deployed in UAT. Tested and Tabrej confirmed to LIVE.

I've merged it to Master to deploy in Production.

**Comment by TabrejAlam3K** [comment]
Please confirm this fixes has been deployed in production.

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/33a0ca79-5ff1-444e-965c-65a8cb8f9fd9)

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/708e2aa6-54ed-44ea-bafc-6ae1dfeac687)

**Comment by TabrejAlam3K** [comment]
As of now we are going to close this issue because client not responded on since long time, We are assuming the issue is working fine.

CC : @audhi3k
