### ISSUE TITLE
9. Cheque printing should be printed from NameExt from DimensionValue

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#263]

**Comment by panduc** [comment]
As discuss with Audi the reports 50031 and 50131 shall be modified. identified the place I would like to clarify and modify the reports.

**Comment by panduc** [comment]
@TabrejAlam3K Changes done in Page Ext 50121. Deployed in UAT. Please check and confirm.

**Comment by TabrejAlam3K** [comment]
@panduc - Report 50131 it is working fine and bringing the description as Dimension Value.Name 1 Ext.

50031 - It is not working.

CC : @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K  report 50031 modified to print Dimension value name 2 Ext.  deployed the change in UAT. Please check and Confirm.

**Comment by TabrejAlam3K** [comment]
Completed (Closed by LKS on 29-04-23
