### ISSUE TITLE
10. Customer Collection 50073

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#265]
Customer Collection => Client Name, Reimbursement Amount, Currency Rate, if the collection is partial - Reimbursement amount to checked

**Comment by TabrejAlam3K** [comment]
@audhi3k - We have analyzing the Data between BC to NAV16.

Data is not migrated properly.

Customer No. - 55|21085|21050|9828|20879|6081|6699|18955|20470|9590|20881|7686|407|6353|20251|579|22027|470|4586

**Comment by TabrejAlam3K** [comment]
@audhi3k - I am working on once it will completed i will informed you.

**Comment by TabrejAlam3K** [comment]
@panduc - Now Client Name is working fine on Reports - Customer Collection.

We need to sit back with Ms. @audhi3k Mam and discuss the - Reimbursement Amount, Currency Rate

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@panduc - Reimbursement alone it is pending.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - Can you please update on.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by panduc** [comment]
@TabrejAlam3K  Yesterday Audhi mentioned she is busy other activities and suggests to check with you for Reimbursement Amount calculation. Let's connect today discuss on the same and i will enable the logic.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by Shasthara** [comment]
Pandu to analysis and share logic to @TabrejAlam3K

**Comment by panduc** [comment]
Reim_Exp := 0;
                R_SIL1.SetRange(R_SIL1."Document No.", Docno);
                R_SIL1.SetFilter(R_SIL1.Description, 'REIMBURSABLE');
                if R_SIL1.FindFirst then begin
                    repeat
                        Reim_Exp += R_SIL1.Amount;
                    until
                     R_SIL1.Next = 0;
                    if Curr_Rate <> 0 then begin
                        "Cust. Ledger Entry".CalcFields(Amount);
                        CLE.Reset;
                        CLE.SetRange("Document No.", Docno);
                        if CLE.FindFirst then;
                        CLE.CalcFields("Remaining Amount");
                        CLE.CalcFields(Amount);
                        //MESSAGE(
                        //IF CLE."Remaining Amount" > 0 THEN
                        Reim_Exp := (Reim_Exp / CLE.Amount) * (Abs("Cust. Ledger Entry".Amount)) * Curr_Rate;
                        //Reim_Exp := Reim_Exp * Curr_Rate
                    end else begin
                        "Cust. Ledger Entry".CalcFields(Amount);
                        CLE.Reset;
                        CLE.SetRange("Document No.", Docno);
                        if CLE.FindFirst then;
                        CLE.CalcFields("Remaining Amount");
                        CLE.CalcFields(Amount);
                        //MESSAGE(
                        //IF CLE."Remaining Amount" > 0 THEN
                        Reim_Exp := (Reim_Exp / CLE.Amount) * (Abs("Cust. Ledger Entry".Amount));
                    end;
                    //     MESSAGE('%1..%2',Reim_Exp,Docno);
                end;

**Comment by panduc** [comment]
@TabrejAlam3K  Please check the logic written in collection report.
1. calculation Sales invoice Line amount if Description is "REIMBURSABLE"
3.  Remaining Amount = (Sales Line Amount/Customer Ledger Entry Amount)Customer Ledger Entry Amount

Please do let me know if you need any clarification

**Comment by TabrejAlam3K** [comment]
We have tested on below documents and it is working fine.

Document No. - LKS01-1718-00001|BRPI/DE/1718/06/0003|BR/AHD/2223/12/0001

**Comment by TabrejAlam3K** [comment]
Gross Amount is coming blank it should be Applied Amount. Mr. @panduc Please check the logic of the Report.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - Gross Amount is Coming in UAT can you move this change in to the Production we can with the client and close it.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - See the below client comments.

In April 2023, the first line is coming correctly.  In the next 5 lines, the Gross amount is getting reflected by adding Gross collection of the previous line and the gross collection of the current line.  Subsequently, for about the majority of the cases, the gross collection amount of the previous line is getting repeated in the current line of Gross amount.  There is no uniformity of occurrence of this pattern. Therefore, please check and resolve the issue.


CC : @audhi3k @Shasthara

**Comment by panduc** [comment]
@TabrejAlam3K not clear of Client comments. as i mentioned yesterday. Let's connect and discuss on the same.

**Comment by narayana3kt** [comment]
Hi Tabrej

Please close this

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - As per our discussion please make the changes and confirm for testing.

**Comment by panduc** [comment]
Need Functional support to identify the expected output.

**Comment by TabrejAlam3K** [comment]
1st Customer Ledger Entries.

![Image](https://github.com/3ktech/General/assets/116171982/caf01352-dd99-4380-b14a-77e6951bc770)

![Image](https://github.com/3ktech/General/assets/116171982/c858fbab-7921-43d9-b293-d40a647faed7)

2nd Customer Ledger Entries.

![Image](https://github.com/3ktech/General/assets/116171982/6ae6c0a0-2147-4b46-a9c4-005f4ac4d37e)

**Comment by panduc** [comment]
Explained the logic by reading. Tabrej is check what is the issue and what is the expected output.

**Comment by panduc** [comment]
@TabrejAlam3K  Deployed the latest fix in LKS Sandbox tested for those 6 it is coming correctly. please test it from your side and confirm.

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
I have tested and verify the data randomly as of now it is working fine Mr. @panduc Please move this changes into the production for client testing.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k and Mr. @panduc - Please deployed into the Production and confirm.

**Comment by panduc** [comment]
@TabrejAlam3K  Deployment to Production and sandbox has been done.

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/9161af35-1abe-4414-b010-bd171f551b7b)

**Comment by TabrejAlam3K** [comment]
As of now we are going to close this issue because client not responded on since long time, We are assuming the issue is working fine.

CC : @audhi3k
