### ISSUE TITLE
7. Posting the Credit Memo => Error

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#267]

**Comment by panduc** [comment]
@TabrejAlam3K  Please Create scenario in UAT and let me know.

**Comment by TabrejAlam3K** [comment]
The client are facing the below error on Sales Credit Memo Pre Reports.

**Snapshot-1**
![Image](https://user-images.githubusercontent.com/116171982/232010542-31e694e0-1c8c-4ced-aaaa-9553d89bdc5a.png)

**Snapshot-2**
![Image](https://user-images.githubusercontent.com/116171982/232010703-dfbf9f41-6efe-409d-818b-024d405aaed4.png)

**Comment by TabrejAlam3K** [comment]
I have reviewing it in the Production Environment.

CRN01-2324-00002 - 0000871768 - It is already posted.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Confirmed by the client on 17-05-2023 as completed.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Confirmed by the client on 17-05-2023 as completed.

CC : @audhi3k @Shasthara
