### ISSUE TITLE
Owner1 and Owner2 not displaying in Journal line and not in GL Entries after posting

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#269]

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Consider the Shortcut Dimension 12 and 13.

**Comment by TabrejAlam3K** [comment]
We have tested in NAV16 and BC, If we are using base Shortcut Dimension 7 and 8 then the value are coming in Owner 1 and 2, but if we are using the custom field called Shortcut Dimension 12 and 13 then the functionality is not happening in NAV16 as well as in BC.

CC : @audhi3k - What we can do on please suggest.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

Now it is getting updated from g/l setup shortcut dimension 12 and 13 code when selecting the dimensions action button in bank receipt voucher

cc : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - In the UAT it is working fine. You can move this into the Production Environment.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
@sandhya3k - I have tested in UAT (Pre and Post both document are populating the value owner1 and owner2) - you can move this into the production.

Tested Documents (Journal Batch BR-DEL - Document No. - BRPI/DE/2324/01/005)

CC : @audhi3k @Shasthara @narayana3kt

**Comment by sandhya3k** [comment]
@TabrejAlam3K  i deployed in production please test

@Shasthara @audhi3k @narayana3kt

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - In Production we can not do any transaction please wait till the client confirmation. We had tested in UAT as per the requirement it is working fine.


@Shasthara @audhi3k @narayana3kt

**Comment by TabrejAlam3K** [comment]
@panduc - Please inform us once you deployed the Changed in the Sandbox and UAT Environment.

CC : @audhi3k @Shasthara

**Comment by panduc** [comment]
Hi @TabrejAlam3K It is published to UAT.  please check for some specific entry.

I'm deploying in Sandbox. will confirm once it is done.

**Comment by panduc** [comment]
@TabrejAlam3K  Deployment done in both  Sandbox and UAT Environment. Please check and confirm.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - I am not able to run the report whatever you have developed. Report get auto disconnected after 20-25min Please let me know how we can test it.

CC : @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K  I've enabled commit function for every 500 records and deployed the latest changes to UAT and Sandbox.

Please test and share your feedback. if you face any error please take screenshot and share it with me.

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - It is working fine in UAT Environment. Can you move this changes into the Production.

**Comment by TabrejAlam3K** [comment]
I have already Run the Process report for this and Owner1 and Owner2 is generated for all the General Ledger Entries. Client need to test and confirm.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Client need to confirm whether the dimension value is modifying correctly on general ledger entries.

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/0dff1546-3179-4f0d-b759-b77aff6a528d)

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/773f1436-f53b-4f99-9219-355e51da7fb1)

**Comment by TabrejAlam3K** [comment]
As of now we are going to close this issue because client not responded on since long time, We are assuming the issue is working fine.

CC : @audhi3k
