### ISSUE TITLE
3. Collection detail - filter should remain after selecting

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#270]

**Comment by TabrejAlam3K** [comment]
@3ktech - Please update me on once it will completed so that we can test and close this issues.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
As per our internal discussion this functionality is not available in BC and this is not doable in BC.


CC : @audhi3k @Shasthara @narayana3kt

**Comment by Shasthara** [comment]
@3ktech to update feasibility

**Comment by sandhya3k** [comment]
@TabrejAlam3K  

I asked to Karthik for this issue. He said it is a nativity of lookup page behavior. 

cc: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
need to convey to the client. Currently it is not feasible.

**Comment by TabrejAlam3K** [comment]
As per the our internal discussion - Currently it is not doable in current version of BC.

**Comment by TabrejAlam3K** [comment]
Need to convey to the client currently it is not doable.

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/9646c18d-6f43-4020-af8d-88d58ceafaad)

**Comment by TabrejAlam3K** [comment]
As of now we are going to close this issue because client not responded on since long time, We are assuming the issue is working fine.

CC : @audhi3k
