### ISSUE TITLE
2. Cheque print alignment

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#271]
Client need to technical support.

**Comment by TabrejAlam3K** [comment]
@sandhya3k - you need to sit with the client and work up on the measurement of actual cheque printing.

**HDFC Cheque-M14 (50131, Report Request)**

CC : @audhi3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K  can u align the meeting with client?

**Comment by TabrejAlam3K** [comment]
@sandhya3k - See the below errors.


![Image](https://user-images.githubusercontent.com/116171982/232121437-3a887330-b046-4fae-9646-d3fc768f4dda.png)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Have you resolved the error based on the last comments.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by sandhya3k** [comment]
@TabrejAlam3K  
Now , iam working on it

cc: @audhi3k  @Shasthara  @narayana3kt

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Currently it is coming like the below snapshot. Can i share this to the client for self testing in UAT


![Image](https://user-images.githubusercontent.com/116171982/232397832-42c63f35-cd94-444a-9bc3-34937d023709.png)

**Comment by sandhya3k** [comment]
@TabrejAlam3K  
Yes tabrej

**Comment by TabrejAlam3K** [comment]
![Image](https://user-images.githubusercontent.com/116171982/232691149-97f388a7-51d6-41e7-9ae5-487285566553.png)

**Comment by TabrejAlam3K** [comment]
Ms. @sandhya3k  need to sit with the client on system to fix and close on the below points on Monday 22-05-2023

1. Check Print Alignment
3. Email Reports

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Please update the current status.

**Comment by sandhya3k** [comment]
The client will confirm the report.

**Comment by sandhya3k** [comment]
@TabrejAlam3K  
As discussed, please check @audhi3k  mam related to the issue.

**Comment by sandhya3k** [comment]
Waiting for the client response

cc : @audhi3k  @TabrejAlam3K

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Report is still coming as blank and considering first line of the Gen. Journal Line records.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Please deployed it into the production and confirm.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 
i deployed in production please check

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Now it is working fine in Production.

**Comment by TabrejAlam3K** [comment]
Mr. Viswanathan Sir will test and confirm on physical copy of cheque.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Please sit with Mr. Viswanathan Sir on Monday 26-062023 and fixed it.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
New ticket is created for this so we are closing this tickets. 

Related ticket is #548
