### ISSUE TITLE
1. Document Date - System date by default

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#272]
Document Date - System date by default, Posting Date - (Creation date - should be workdate => in Vouchers)

![Image](https://user-images.githubusercontent.com/116171982/231337486-899fbfb8-5fb1-44d2-987c-11e2b5278ed2.png)

**Comment by sandhya3k** [comment]
@TabrejAlam3K  please test in UAT

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Tested in Production it is working fine for Bank Receipt Voucher.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Completed (Closed by LKS on 29-04-23
