### ISSUE TITLE
purchase invoice comment information should be print in voucher register report Cust

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#276]
They require to print comment information of purchase invoice in voucher register report

**Comment by niranjand22** [comment]
update the comments here @Ejaz3KT

**Comment by Ejaz3KT** [comment]
I`ve explained to Mr. @Manoj01021999 He started working on this task

CC: @audhi3k

**Comment by Manoj01021999** [comment]
@audhi3k 
initially the requirement was given as G/L register post testing confirmed as purcommentLine
so the status is IN progress

**Comment by Ejaz3KT** [comment]
Mr. @Manoj01021999 Please Follow the step as we discuss in the morning and resolve the issue.

CC: @audhi3k

**Comment by Manoj01021999** [comment]
@Ejaz3KT issue is resolved kindly do testing

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
@Manoj01021999 The report is fine please deploy this to the live production

CC: @audhi3k

**Comment by Manoj01021999** [comment]
Mr. @Ejaz3KT comment is working fine for Live production
if the issue is related to other field kindly create a new ticket
CC: @audhi3k

**Comment by Manoj01021999** [comment]
![Image](https://user-images.githubusercontent.com/126780544/235581583-17109a22-3bdd-4b7d-9cf8-72c232999219.png)



![Image](https://user-images.githubusercontent.com/126780544/235581605-2d91b74f-beef-4ddb-8817-80590eecfec0.png)

**Comment by Ejaz3KT** [comment]
@Manoj01021999 After discussing with @audhi3k madam we will close the both tickets
