### ISSUE TITLE
Add comment field in job G/L journal page

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#277]
They requires to add comment field in job G/L journal page and comment information should be print on voucher register report

**Comment by sruthi1017** [comment]
Hi @Ejaz3KT the comment field is added and published in sandbox of fitchner, today will deploy in the production if it is working fine

**Comment by sruthi1017** [comment]
i added the comment field in job g/l journal and g/l entry and made the changes in the layout

**Comment by sruthi1017** [comment]
hi @Ejaz3KT the changes has been moved to the production environment
