### ISSUE TITLE
Description Field Length Issue

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#278]
Fichtner Team requirements:

In Sales Invoice Header Increase Manpower/Description Length up to (400)
In Sales Invoice Line Increase Invoice/Description Length up to (600)
In Sales Invoice Header Reference No (Ref No.) Increase Length up to (300)

**Comment by Ejaz3KT** [comment]
@Mahesh3ktech This task is assign to you

**Comment by Mahesh3ktech** [comment]
@Ejaz3KT - Changes have been done, kindly test and update.

**Comment by Amar-3KT** [comment]
@Ejaz3KT @Mahesh3ktech 
After filling all description report showing in 2 page.

**Comment by Mahesh3ktech** [comment]
@Amar-3KT @Ejaz3KT -
Report is corrected and changes has been done. Kindly check and update.

**Comment by Ejaz3KT** [comment]
@Mahesh3ktech Mr. Amarjeet has tested the description fields as it is working fine, Please deploy from UAT to the production

CC: @audhi3k @Amar-3KT

**Comment by niranjand22** [comment]
working in UAT, to be deployed in Prod env. @Mahesh3ktech

**Comment by niranjand22** [comment]
Hi @sandhya3k ,  Can you please deploy changes to live. Mr mahesh is on leave

**Comment by sandhya3k** [comment]
@niranjand22  i called to Mahesh, he said available in second half that time i will deploy the production

**Comment by Mahesh3ktech** [comment]
Deployed the report to production. kindly check and update.

**Comment by Shasthara** [comment]
@Amar-3KT to check with client
