### ISSUE TITLE
Purchase order Report

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#280]

**Comment by Mahesh3ktech** [comment]
@Ejaz3KT, yesterday I discussed and asked doubts, can we connect today to clarify those doubts and will complete the report today.

**Comment by Mahesh3ktech** [comment]
@Ejaz3KT, Completed and need to test the report.

**Comment by Mahesh3ktech** [comment]
@Ejaz3KT, Good morning.
Kindly test the report and update.

**Comment by Ejaz3KT** [comment]
Ok Mr. @Mahesh ***@***.***> I will test and update you

CC: @Audhilakshmi ***@***.***>

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Mahesh3ktech** [comment]
@Ejaz3KT, Terms and Conditions changes has been done. kindly check and update.

**Comment by Ejaz3KT** [comment]
Mr. @Mahesh3ktech as we discussed related to GST amount is not printing in the report so I request you to please resolve this issue ASAP.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Yesterday I showed the purchase order report to the client
1. They want terms and conditions in line wise not side by side.
2. we have to replace purchase executive to authorized signatory
3. Under authorized signatory add Fervid smart solutions.
 
CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Mr. @Mahesh3ktech is working on this task he told he will complete this by tomorrow afternoon 

CC: @audhi3k

**Comment by Mahesh3ktech** [comment]
Hi @Ejaz3KT, changes have been done. kindly check and update.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech As we discussed please make the changes in the report ASAP

CC: @audhi3k

**Comment by Mahesh3ktech** [comment]
hi @Ejaz3KT, Changes are completed, kindly test and update.

**Comment by audhi3k** [comment]
For enhancement in PO - new ticket with No. 488 was created.  Hence closing this ticket
