### ISSUE TITLE
application should happen both from invoice to payment or payment to Invoice and currently it is happening payment to Invoice.

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#282]

**Comment by TabrejAlam3K** [comment]
@audhi3k - We need to sit along with you for this functionality.

CC : @Shasthara @narayana3kt

**Comment by niranjand22** [comment]
@TabrejAlam3K  Please check the functionalities on this task

**Comment by TabrejAlam3K** [comment]
Document Reference Documents.
![Image](https://github.com/3ktech/General/assets/116171982/93afbf40-fe1a-4140-baa0-7b9c80e5c0dc)

Error Message 
**The Cust. Ledger Entry does not exist. Identification fields and values: Entry No.='0'**

"Event Subscriber"(CodeUnit 50007).OnCustPostApplyCustLedgEntryOnBeforePostDtldCustLedgEntries line 35 - LKS Base development by 3K Technologies
"Gen. Jnl.-Post Line"(CodeUnit 12).OnCustPostApplyCustLedgEntryOnBeforePostDtldCustLedgEntries(Event) line 2 - Base Application by Microsoft
"Gen. Jnl.-Post Line"(CodeUnit 12).CustPostApplyCustLedgEntry line 58 - Base Application by Microsoft
"CustEntry-Apply Posted Entries"(CodeUnit 226).CustPostApplyCustLedgEntry line 43 - Base Application by Microsoft
"CustEntry-Apply Posted Entries"(CodeUnit 226).Apply line 25 - Base Application by Microsoft
"CustEntry-Apply Posted Entries"(CodeUnit 226).OnRun(Trigger) line 7 - Base Application by Microsoft
"CustEntry-Apply Posted Entries"(CodeUnit 226).OnRunPreview line 6 - Base Application by Microsoft
"Gen. Jnl.-Post Preview"(CodeUnit 19).OnRunPreview(Event) line 2 - Base Application by Microsoft
"Gen. Jnl.-Post Preview"(CodeUnit 19).RunPreview line 4 - Base Application by Microsoft
"Gen. Jnl.-Post Preview"(CodeUnit 19).PreviewStart line 17 - Base Application by Microsoft
"Gen. Jnl.-Post Preview"(CodeUnit 19).Preview line 7 - Base Application by Microsoft
"CustEntry-Apply Posted Entries"(CodeUnit 226).PreviewApply line 11 - Base Application by Microsoft
"Apply Customer Entries"(Page 232).PostDirectApplication line 45 - Base Application by Microsoft
"Apply Customer Entries"(Page 232)."Preview - OnAction"(Trigger) line 2 - Base Application by Microsoft
"CustEntry-Apply Posted Entries"(CodeUnit 226).RunApplyCustEntries line 16 - Base Application by Microsoft
"CustEntry-Apply Posted Entries"(CodeUnit 226).ApplyCustEntryFormEntry line 33 - Base Application by Microsoft
"Customer Ledger Entries"(Page 25)."Apply Entries - OnAction"(Trigger) line 6 - Base Application by Microsoft

**Comment by panduc** [comment]
Checking the issue.

**Comment by panduc** [comment]
not clear about the issue.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - Please look this issue the same scenario with same document No. in NAV16 it is working fine but in BC it is showing some error.

BC Snapshot. - Error Message i have mansion in above comments.

![Image](https://github.com/3ktech/General/assets/116171982/dcfa9eca-572b-4d23-9674-4083e42b91f9)

NAV16 Snapshot.

![Image](https://github.com/3ktech/General/assets/116171982/69cf9355-6917-4797-a134-e3dd1588a323)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - Please update the latest status.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by panduc** [comment]
@TabrejAlam3K  I've identified the root cause and implemented the solution.  Doing unit testing and will let you know once testing is passed.
CC : @audhi3k @Shasthara @narayana3kt

**Comment by panduc** [comment]
@TabrejAlam3K  I've completed the Unit testing and It is working fine in Sandbox.  Preview post is working so you should be able to post it.

Tested: Open: Yes and Customer: 9861 (same case mentioned above).

Please test it in Sandbox and confirm.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - In Sandbox Preview Post is working Fine. Please tell me you have done changes from backend or we need to done something from Front End.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by panduc** [comment]
@TabrejAlam3K It's a Technical fix on top of the existing customization. 

If all working fine. Please confirm? so that we shall we deploy in Production.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - Please move this into the Production and let me know.

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/bb395c98-1740-4609-a596-392a503bddbd)

**Comment by TabrejAlam3K** [comment]
As of now we are going to close this issue because client not responded on since long time, We are assuming the issue is working fine.

CC : @audhi3k
