### ISSUE TITLE
Dimensions are not displaying in GL Entries, Ex: Case

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#283]

**Comment by TabrejAlam3K** [comment]
![Image](https://user-images.githubusercontent.com/116171982/231928549-092e2872-9b2b-4f79-8d0d-6af8be5745f2.png)

**Comment by TabrejAlam3K** [comment]
Need to analyzing the points with Ms. @audhi3k 

CC : @Shasthara @narayana3kt

**Comment by Shasthara** [comment]
@TabrejAlam3K - Update the status/comment

**Comment by TabrejAlam3K** [comment]
As per the discussion with Ms. AudhiLakshmi we will considered this point in last.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

shell we discuss above the issue ?

**Comment by TabrejAlam3K** [comment]
![Image](https://user-images.githubusercontent.com/116171982/235155600-f032d8b6-5f07-4d45-9894-60d94d0de3fd.png)

**Comment by TabrejAlam3K** [comment]
I have already Run the Process report for this and Case is generated for all the General Ledger Entries. Client need to test and confirm.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
this is the similar points of #269

**Comment by TabrejAlam3K** [comment]
Client need to confirm whether the dimension value is modifying correctly on general ledger entries.

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/1f4eb19d-c32a-40fb-945b-8d07f1281db4)

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/e1f5b620-1e28-46a0-a7cc-b05936c1be96)

**Comment by TabrejAlam3K** [comment]
As of now we are going to close this issue because client not responded on since long time, We are assuming the issue is working fine.

CC : @audhi3k
