### ISSUE TITLE
NKG India IFRS company to resore from backup:

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#286]
In F drive there is one back up saved dated 19th Feb 23. Please restore only "NKG India IFRS" company alone to LIVE DB. May be alter the company and update.

**Comment by niranjand22** [comment]
Please allocate technical resource for this if required.
cc @audhi3k

**Comment by niranjand22** [comment]
@audhi3k  Please allocate technical resource for this if required.

**Comment by niranjand22** [comment]
@panduc  to check with.

**Comment by panduc** [comment]
@niranjand22  Please share the Server details, DB Backup and SQL server details to start with it.

The approach is:
1. Restore 19th Feb 2023 Backup.
2.  Rename Company NKG India IRFS to "NKG India IFRS New"
3.  Export as file
4. Import a file to LIVE DB.

**Comment by panduc** [comment]
@niranjand22 The above mentioned steps executed. Please check and confirm.

After confirmation we have to the cleanup. delete new DB we restored to export company.

**Comment by niranjand22** [comment]
@audhi3k currency issue was checked by amar but not yet roslved

**Comment by Shasthara** [comment]
@niranjand22 Update the status

**Comment by niranjand22** [comment]
Back up restorationw was done.
