### ISSUE TITLE
LCMS Related Issues 15-04-2023

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#288]
1. User have completed the RTB and posted successfully form BC side and In API log it is showing success, but in the LCMS side they have not received updates.

2. LKS are using old storage account, but we are using new storage account - we need to considered the older storage account.

**Comment by TabrejAlam3K** [comment]
I will test with the client user Mr. Somendra and confirm back.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
LKS Team is not available for testing - Mr. Somendra is also trying to connect with the related users but still not response received from their side.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
@3ktech - Mr. Kartik D Please update on whatever we discussed with the client.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by 3ktech** [comment]
The Creditmemo Number format

CRN04-2324-00005 - LKS
VLC01-2324-00001 - VLK
VSC02-2324-00001- VSH

Using this identifier system has to forward the file to respective company

@TabrejAlam3K @audhi3k

**Comment by 3ktech** [comment]
@TabrejAlam3K , the changes have been shared for merging with @sandhya3k .

**Comment by 3ktech** [comment]
@TabrejAlam3K  changes are deployed in UAT. Please test this along with somendra and let me know your feedback
@Shasthara , @audhi3k

**Comment by niranjand22** [comment]
Mr Tabrej will connect with cl,ient today

**Comment by TabrejAlam3K** [comment]
I will share the No. series format to the client for changing

CRN04-2324-00005 - LKS
VLC01-2324-00001 - VLK
VSC02-2324-00001- VSH

**Comment by TabrejAlam3K** [comment]
Yes - Same in Sl.No.6
