### ISSUE TITLE
Inventory Valuation Report- Additional filter Require-Pioneer

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#289]
Dear Madam,

 

We need an Inventory valuation report store-wise but there is no option to select the “Location code” filter in the report.

 

While doing the GRN we are feeding the “Location Code” field, please bring the same in the filter list under the Inventory valuation report.

 

This will enable us to get the store-wise report.

 

Please prioritize our requirements.

 

 

Previous three requirements are also not finished, please provide the timeline to close the each issue.

**Comment by niranjand22** [comment]
cc @audhi3k

**Comment by audhi3k** [comment]
Dear Mr Rajesh,

Please find below the screenshot on the location filter for your reference.  Kindly check and confirm on closure

**Comment by audhi3k** [comment]
Dear Mr Rajesh,

Thanks for confirmation on closure
