### ISSUE TITLE
Re: Help Required; BC Setup Posted Sales Invoice Page Customization

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#290]
Need your help with the below BC set up.

1.	Creation of new filter/alter of posted sales view items.

![Image](https://user-images.githubusercontent.com/116243958/232373219-8be606f1-7da1-4182-8873-9d3d74a74937.png)

**Comment by niranjand22** [comment]
will connect with client today

**Comment by niranjand22** [comment]
cliiwnt is busy he will connect after this week

**Comment by niranjand22** [comment]
Mr Jagan want multiple column to be added in posted sales invoice page..he will share the excel file

**Comment by niranjand22** [comment]
[Posted Sales Invoices (1).xlsx](https://github.com/3ktech/General/files/11475216/Posted.Sales.Invoices.1.xlsx)

**Comment by niranjand22** [comment]
They want only 1st line HSN and They are fine with comma separation on multiple payment received date.

I will share the field mapping

**Comment by niranjand22** [comment]
[Posted.Sales.Invoices.1.xlsx](https://github.com/3ktech/General/files/11503928/Posted.Sales.Invoices.1.xlsx)

**Comment by niranjand22** [comment]
I have done the field mapping.. @audhi3k  Need your help for Multiple Payment Received dated field mapping

**Comment by niranjand22** [comment]
client has asked to hold this and prioritize tcs setup first

**Comment by niranjand22** [comment]
Hi @sruthi1017 , we have done field mapping for this .. let me know once you are avaialble we will connect.


cc @audhi3k

**Comment by niranjand22** [comment]
[Posted.Sales.Invoices.1 (4).xlsx](https://github.com/3ktech/General/files/11945457/Posted.Sales.Invoices.1.4.xlsx)

**Comment by niranjand22** [comment]
Hi @sruthi1017  pls update me once customisation is done

**Comment by niranjand22** [comment]
Had uat.. with Jagan..confirm for deploy @sruthi1017

**Comment by audhi3k** [comment]
Deployed in LIVE
