### ISSUE TITLE
Cheque No. Is not bringing in the Daily Collection Report (50066)

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#292]
![Image](https://user-images.githubusercontent.com/116171982/232455061-20518b72-2a0b-42ca-ac66-76a39a2aa320.png)

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Please enable the Cheque No. 2 field on page level and map the same field in to the Reports

See the below Page id and Field Snapshot.
![Image](https://user-images.githubusercontent.com/116171982/232665169-211bfebe-2306-418a-abe7-0904e3c316a3.png)

**Comment by sandhya3k** [comment]
![Image](https://user-images.githubusercontent.com/114206737/232964534-ff8491eb-e0e5-4fe9-9dd8-12b4b4d5ea4e.png)

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

when ur available please let me know we will discuss this issue?

**Comment by TabrejAlam3K** [comment]
@sandhya3k - I have tested it in the Production, now the cheque no. is coming in the reports as well.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
Confirmed by the client on 17-05-2023 as completed.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Confirmed by the client on 17-05-2023 as completed.

CC : @audhi3k @Shasthara
