### ISSUE TITLE
Sales Quote Report

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#293]
Create a sales quote report for fervid client

**Comment by Ejaz3KT** [comment]
@Manoj01021999 This sales quotation report task is assign to you

**Comment by Ejaz3KT** [comment]
@sruthi1017 I`ve tested the report GST is not calculating is showing blank in the GST column Please solve this issue ASAP.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
@sruthi1017 For GST calculation you need to connect with Ms. Padma madam she we guide you on this. After getting the information from Ms. Padma madam develop the report ASAP.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
@sruthi1017 I`ve tested the sales quote report it is fine. need to showcase to the client and get confirmation

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Ms. @sruthi1017 as we discuss in the call please make the changes in the sales quote. 

CC: @audhi3k

**Comment by sruthi1017** [comment]
hi @Ejaz3KT changes has been done in the sales quote as u mentioned yesterday, test it whether it is working fine

**Comment by Ejaz3KT** [comment]
@sruthi1017 As we discussed please make the changes in the report ASAP

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Please let me know when we can connect on

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - As per our discussion please update your latest comments here.

**Comment by sruthi1017** [comment]
Hi Mr. @TabrejAlam3K done changes as u mentioned and alignment as @Ejaz3KT mentioned

**Comment by Ejaz3KT** [comment]
The Final output of sales quote report 

[Sales Quote Report.pdf](https://github.com/3ktech/General/files/11661499/Sales.Quote.Report.pdf)

CC: @audhi3k, @TabrejAlam3K @sruthi1017

**Comment by Ejaz3KT** [comment]
![Image](https://github.com/3ktech/General/assets/125632927/b3f61765-80b9-4bfd-a083-02a7e3d9090d)
Ms. @sruthi1017 when I removed GST for 2 line items it is still calculating the GST please resolve this issue

CC: @audhi3k , @TabrejAlam3K

**Comment by Ejaz3KT** [comment]
The Final output of sales quote report

[Sales Quote Final Report.pdf](https://github.com/3ktech/General/files/11712170/Sales.Quote.Final.Report.pdf)

CC: @audhi3k @TabrejAlam3K @sruthi1017

**Comment by TabrejAlam3K** [comment]
Mr. @Ejaz3KT need to showcase with the client today 13-06-2023.

**Comment by TabrejAlam3K** [comment]
Mr. @Ejaz3KT - Have you done the UAT Session with the client, Please update the status here.

CC : @audhi3k

**Comment by Ejaz3KT** [comment]
@TabrejAlam3K sir no I haven`t showcased it to the client.

**Comment by TabrejAlam3K** [comment]
Mr. @Ejaz3KT - Please update the current status of the ticket.

**Comment by Ejaz3KT** [comment]
@TabrejAlam3K Sir Client inform me after testing the sales process they will give confirmation on this report

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Ejaz3KT - So I am moving this into the client confirmation.

**Comment by Ejaz3KT** [comment]
@TabrejAlam3K Waiting for the client confirmation

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The fervid team is testing on it after testing is completed they will give confirmation

CC: @audhi3k @TabrejAlam3K
