### ISSUE TITLE
Report alignment

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#295]

**Comment by sandhya3k** [comment]
I have aligned 3 reports as per client requirements and need to be done one report for internal testing. i asked to create a invoice for stock transfer out once i will get the update from senthil, i will complete

cc : @audhi3k @Shasthara

**Comment by sandhya3k** [comment]
client had raised the issue through mail for contract service report functionality as per requirement i also completed the point and informed to client for testing. this thing also waiting for client response.

cc: @audhi3k  @Shasthara

**Comment by niranjand22** [comment]
Hi @sandhya3k , Can you please forward me the mail..in which the issue was raised
