### ISSUE TITLE
Re: Mismatch of Debtor balance in COA vs Ageing report:CAS-01215-Y0F3D2

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#296]

**Comment by Shasthara** [comment]
@niranjand22 to update the status..

**Comment by niranjand22** [comment]
In Customer Detail aging invoice entry  PSI/CHE/FY23-26 not showing ...but in Details Customer Trial Balance it is showing.

Technical team support required to debug the error

**Comment by niranjand22** [comment]
[document (31).pdf](https://github.com/3ktech/General/files/11403574/document.31.pdf)
[document (30).pdf](https://github.com/3ktech/General/files/11403575/document.30.pdf)

**Comment by niranjand22** [comment]
Hi Ms Swathi,

You are generating a customer detailed ageing report for Cust No-  CU-MR100012 with an Ending Date of 31-03-23.

In this report Invoice no PSI/CHE/FY23 -26 entry is not showing because the due date for this invoice is 20-04-23.

If you adjust your ending date filter based on the due date this invoice entry will also come in the report.

**Comment by niranjand22** [comment]
Customer Detailed Aging Report shows data based on due date but they want data based on posting date

**Comment by niranjand22** [comment]
[14:24] Swathi Gopalam

Hi Niranjan, in aged accounts receivable itself we have option for posting date & document wise



now its fine, then you can close the query
