### ISSUE TITLE
New WIP report need to create

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#299]
We are waiting for Mr. Murali fields mapping document to approve and if required any changes he will update.
Currently Mr. Singaravel and Mr. Murali working on it.

**Comment by niranjand22** [comment]
details to be given by Cleint

**Comment by Amar-3KT** [comment]
As discussed with Mr. singaravel, He is working on field mapping documents. Soon will provide all details.

**Comment by niranjand22** [comment]
@Amar-3KT  please infor either to close or move forward with this tiket

**Comment by Amar-3KT** [comment]
As discussed with Mr. Singaravel Sir, he will connect with me tomorrow.

**Comment by Amar-3KT** [comment]
No response from Fichtner side.

**Comment by TabrejAlam3K** [comment]
For non information from the client. We are closing the case.
