### ISSUE TITLE
E-Invoice Report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#300]
Ms. @sruthi1017 I`ve share you E-invoice format with field mapping please start the work.

**Comment by sruthi1017** [comment]
Ejaz has given the confirmation regarding field mapping on friday evening, completed the layout and logical part is balance

**Comment by sruthi1017** [comment]
almost completed the report informed to @Ejaz3KT to test, only amount in words field is pending unable to publish the changes in UAT fervid.

**Comment by Ejaz3KT** [comment]
@sruthi1017 I`ve tested the E-Invoice report the report is fine but need to do some changes in the report.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
After discussing with client need to do some changes on E-invoice report 

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
@sruthi1017  has developed the E-invoice report  as per the client requirement need to showcase to them and get the confirmation from the client

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
@sruthi1017 Please resolve the Amount In Words issue ASAP. and update the status here

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
@sruthi1017 As we discussed please make the changes in the report ASAP

1. Add ship to city,
2. Add ship to Postcode
3. Add Ship to Name
4. Add Ship to State
5. Add comma for all the amounts

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
[e - Invoice Template.xlsx](https://github.com/3ktech/General/files/11624690/e.-.Invoice.Template.xlsx)

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Please let me know when we can connect on

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - As per our discussion please update your latest comments here.

**Comment by sruthi1017** [comment]
Hi Mr. @TabrejAlam3K done all the changes except the 4 copies - tried with different ways it is not working need help to complete this requirement

**Comment by Ejaz3KT** [comment]
@sruthi1017 Please update the status of E-invoice report and the report details are not printing properly have a look on the report

[Sales invoice report.pdf](https://github.com/3ktech/General/files/11712125/Sales.invoice.report.pdf)

CC: @audhi3k @TabrejAlam3K

**Comment by Ejaz3KT** [comment]
I`ve to test this report with the client and need to get confirmation from the client

CC: @audhi3k @TabrejAlam3K @sruthi1017

**Comment by TabrejAlam3K** [comment]
Mr. @Ejaz3KT  need to showcase with the client tomorrow 14-06-2023, because they want do some transaction related to the report.

**Comment by TabrejAlam3K** [comment]
Mr. @Ejaz3KT - Have you done the UAT Session with the client, Please update the status here.

CC : @audhi3k

**Comment by Ejaz3KT** [comment]
The fervid team is still stuck in the purchase process so I have not given UAT session on e-invoice report

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Mr. @Ejaz3KT - Please update the current status of the ticket.

**Comment by Ejaz3KT** [comment]
@TabrejAlam3K Sir Client inform me after testing the sales process they will give confirmation on this report

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Ejaz3KT - So I am moving this into the client confirmation.

**Comment by TabrejAlam3K** [comment]
Mr. @Ejaz3KT - you have changed the status from **Cust_Confirmation** to **InProgress** but you have not mentions any comment on this git issues why.

CC : @audhi3k

**Comment by Ejaz3KT** [comment]
@TabrejAlam3K  sir After changing the status I`ve updated the comments and screenshot of the issue here. I don`t know why it has not updated sir

**Comment by sruthi1017** [comment]
@Ejaz3KT - all the changes you mentioned is completed and the gst calculation is working fine in UAT of sandbox, can u please check
CC : @audhi3k @TabrejAlam3K

**Comment by TabrejAlam3K** [comment]
Mr. @Ejaz3KT - Please update you latest comment here.

**Comment by Ejaz3KT** [comment]
@Tabrej ***@***.***>sir need to show case to the client and get confirmation

CC: @Audhilakshmi ***@***.***>

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Ejaz3KT - Please update the latest comment here.

**Comment by Ejaz3KT** [comment]
The fervid team is testing on it after testing is completed they will give confirmation

CC: @audhi3k @TabrejAlam3K
