### ISSUE TITLE
1.	RTB requests remains in ‘In Billing Process

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#302]

**Comment by Shasthara** [comment]
Vivek to share the list with 3 KT team attached the xls for RTBs in In Billing process

**Comment by Shasthara** [comment]
@TabrejAlam3K  Please verify this ticket as the client has already shared the file. : https://3ktechnologies22-my.sharepoint.com/:x:/g/personal/shasthara_m_3ktechnologies_com/EZOSARjJ3c9AiSwE06mS3oUBzqRoZyLjpo3H8ba4czD_Pw?e=jn2Oxg

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Shasthara Let we discussed in today meeting then we will work upon.

CC : @audhi3k @narayana3kt

**Comment by 3ktech** [comment]
We have sent all the missing RTBs to LCMS. the next action item is with Somendra to fix the data

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Shasthara 

I have fixed it and forward to the Client(Mr. Somendra) will test and confirm the current status.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Mr. Somendra has to confirm.

**Comment by TabrejAlam3K** [comment]
Confirmed by the client on 17-05-2023 as completed.

CC : @audhi3k @Shasthara
