### ISSUE TITLE
CRTBs posted from accounts but not getting update in Snowfig and CRTB status remains ‘In Cancellation Process

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#303]

**Comment by 3ktech** [comment]
@TabrejAlam3K , as discussed, you will have to change the no series as discussed and test this with somendra
Cc: @audhi3k , @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. Kartik D( @3ktech ) - I will test it today and confirm.

CC : @audhi3k @narayana3kt @Shasthara

**Comment by TabrejAlam3K** [comment]
Need to share the No. Series format to Mr. Viswanathan sir for changing the no. series format in production.

**Comment by TabrejAlam3K** [comment]
We have tested with the client but still it is not working.

**Comment by TabrejAlam3K** [comment]
@audhi3k - Mr. Somendra is out of office he will ping me once he will back.

![Image](https://user-images.githubusercontent.com/116171982/237004180-8db60ed1-009f-40a2-b1a7-94dbb77a83d0.png)

**Comment by TabrejAlam3K** [comment]
@audhi3k - Mr. Somendra had confirm for this issues. It is working fine in UAT Environment.

**Comment by audhi3k** [comment]
Confirmed by Mr Vivek's mail dated 10th May 2023

**Comment by TabrejAlam3K** [comment]
I have done the changes with below steps.

1. Download the Invoice with respected posted sales credit memo.
2. Upload on the Blob Storage - Prod
3. See the Invoice Doc get updated or not
4. Copy the Invoice Doc URL form Blob Storage
5. Update it in the LCMS Response Queue line where Invoice No. is generated.
6. Check the Status on LCMS

**Comment by TabrejAlam3K** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



Posted   Credit Note No. | Invoice Description | Invoice URL
-- | -- | --
873210 | LCMS-BC-CRN-00008732100515230515231237.pdf | https://lcmsd365storage.blob.core.windows.net/lcms365prod/LCMS-BC-CRN-00008732100515230515231237.pdf
873208 | LCMS-BC-CRN-00008732080515230515231238.pdf | https://lcmsd365storage.blob.core.windows.net/lcms365prod/LCMS-BC-CRN-00008732080515230515231238.pdf



</body>

</html>

**Comment by TabrejAlam3K** [comment]
For above RTB's Status is updating correctly in LCMS.

![Image](https://github.com/3ktech/General/assets/116171982/23ffe9c3-f8d1-4bb7-8c50-341df50275f0)

**Comment by TabrejAlam3K** [comment]
Confirmed by the client on 17-05-2023 as completed.

CC : @audhi3k @Shasthara
