### ISSUE TITLE
Collection/payments received once updated by accounts in BC365 but the mail notification that goes to respective case partner show the collection amount as Rs 0.

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#305]

**Comment by Shasthara** [comment]
Somendra will share the field details with Karthik

**Comment by 3ktech** [comment]
@TabrejAlam3K , the fix is given. pls test it with somendra.

**Comment by 3ktech** [comment]
The fix is applied in the production environment and asked somendra to monitor and share the feedback

**Comment by Shasthara** [comment]
@TabrejAlam3K Please update the status

**Comment by TabrejAlam3K** [comment]
Client had confirm during the session. It is completed.
