### ISSUE TITLE
Control should be enabled to sales invoice based on RTB invoice( enhancement)

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#310]

**Comment by Shasthara** [comment]
![Image](https://user-images.githubusercontent.com/117992956/233544370-8b29ed32-61c4-41ff-b565-a24898d166ea.png)

**Comment by TabrejAlam3K** [comment]
@3ktech - Mr. Kartik D will update the status on.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech (Kartik D) - Please leave your comments here.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k Please connect with Mr. Kartik D and get the information about the changes

**Comment by TabrejAlam3K** [comment]
@sandhya3k 


**API Trans Log**
![Image](https://user-images.githubusercontent.com/116171982/234841493-54a884cb-4d41-4b38-bf44-88affe53e789.png)

**Sales Invoice with Same RTB No.**
![Image](https://user-images.githubusercontent.com/116171982/234841566-6dce7ac4-dfa9-44a9-b798-0107fd2248be.png)

**Posted Sales Invoice with Same RTB No.**
![Image](https://user-images.githubusercontent.com/116171982/234841627-c59eed5f-49b8-47f7-8e4a-b1bdc7730b7f.png)

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

please test an UAT environment?

cc: @audhi3k  @Shasthara  @narayana3kt

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - It is working as per the expectation in UAT Environment.

cc: @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
I have tested with below RTB's

![Image](https://user-images.githubusercontent.com/116171982/235049920-fcfdbd48-0322-45d7-ae80-fc66a3d14112.png)

![Image](https://user-images.githubusercontent.com/116171982/235049949-6d859e89-a318-46d1-a18a-d82b9d9e479a.png)

**Comment by TabrejAlam3K** [comment]
Confirmed on 3rd May.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - It is not working for CRTB it mean Sales Header and Sales Credit Memo Header.

CC : @audhi3k
