### ISSUE TITLE
Sales invoice comment information should be print in voucher register report Cust

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#312]
The Fichtner team wants to print sales invoice comment information in the voucher register report cust

**Comment by Ejaz3KT** [comment]
Mr. @Manoj01021999 I am assigning this task to you.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
@Manoj01021999 I`ve tested this and the report is working fine so please deploy this to the live production.

CC: @audhi3k

**Comment by Manoj01021999** [comment]
Mr. @Ejaz3KT comment is working fine for Live production
if the issue is related to other field kindly create a new ticket
CC: @audhi3k
