### ISSUE TITLE
Customer aging report need to add Comment

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#314]
Please add comment in "invoice description" field.

**Comment by Shasthara** [comment]
Waiting for client confirmation

**Comment by Shasthara** [comment]
@Amar-3KT to update on it

**Comment by Mahesh3ktech** [comment]
@Amar-3KT, Comment field added, kindly check and update.

**Comment by niranjand22** [comment]
@Mahesh3ktech  To check whether it is published in UAT

**Comment by Shasthara** [comment]
Please update the status

**Comment by Amar-3KT** [comment]
@Mahesh3ktech Please update the status.

**Comment by Amar-3KT** [comment]
As discussed with Mr. Mahesh, Today he will resolve this issue.

**Comment by niranjand22** [comment]
Hi Mr @Mahesh3ktech  please update on this task

**Comment by Mahesh3ktech** [comment]
Hi @Amar-3KT, Changes has been done. can you check and confirm.

**Comment by Amar-3KT** [comment]
Hi @Mahesh3ktech Its working fine on UAT please deploy on Live. After client confirmation will close this ticket

**Comment by Amar-3KT** [comment]
On live we have uploaded. Client not responding for closure.....
