### ISSUE TITLE
Daily Collection” Page ID 50066 “Location Code”  coming blank

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#320]

**Comment by TabrejAlam3K** [comment]
Clients Comments

Report “Daily Collection” Page ID 50066 “Location Code” is coming blank and client name is coming up to 50 characters only. Location code is not flown in all others like Bank Reconciliation statemen, customer collection Report, etc.

1. Report 50066 - Location Code is Missing
2. Customer Collection Report 50073 - Location Code is Missing
3. Bank Reconciliation Statement - Apply Bank Acc. Ledger Entries (381, ListPart) - Location Code is Missing

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Location code is missing in the Report Daily Collection. When we will connect to discuss and close it.

CC : CC : @audhi3k @narayana3kt @Shasthara

**Comment by TabrejAlam3K** [comment]
@sandhya3k - this is working find in the UAT. Please move this change in to the Production.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
Confirmed by the client on 17-05-2023 as completed.

CC : @audhi3k @Shasthara
