### ISSUE TITLE
UPLOAD OF OPENING BALANCE CUST/VEND/BANK/FA

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#328]

**Comment by niranjand22** [comment]
@Amar-3KT Post the transaction and get the confirmation from the client

**Comment by Amar-3KT** [comment]
Customer Balance has been posted. other setup need to be done.

**Comment by Amar-3KT** [comment]
vendor opening posted. @Ejaz3KT kindly check with client

**Comment by Amar-3KT** [comment]
Also  Bank opening kindly check with client.

Only FA pending we are working on it.

**Comment by Amar-3KT** [comment]
Fa posting group updated in fa line and other fields updated

Fa posting group setup data not available- Account no blank

**Comment by Amar-3KT** [comment]
@Ejaz3KT All opening has been posted. Kindly show to client and get confirmation.

**Comment by audhi3k** [comment]
in UAT it's completed
