### ISSUE TITLE
RE: LR 75'ft Trailer placement - HT24 Blade for Pariyur amman - Ranipet to Pazhavoor

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#347]
cc @audhi3k

**Comment by niranjand22** [comment]
Dear sir

As discussed HT24 Blade not Transfer TNPRD to TN7WP-RanI  ,some error show it

**Comment by niranjand22** [comment]
i have checked  itme is not avaialble in inventory TNPRD-RANI location

**Comment by niranjand22** [comment]
waiting for reply from client

**Comment by audhi3k** [comment]
Dear Mr Ramesh,

The stock are reserved against production order, if you want to transfer cancel the reservation and proceed.

To client reservation entry
Open Item Ledger entry, Click Reservation entries

To cancel reservation entry
In the reservation entries, click cancel reservation

**Comment by audhi3k** [comment]
Through screen sharing session we completed it
