### ISSUE TITLE
New Points Raised by LKS - 01-05-2023

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#348]
1. Role Center should be enable for User and User don't have permission to switch any other role center.
2. In Collection Detail List - Location Should be filter base on User Setup Location.
3. Daily Collection Client Name having length issues.
4. Shortcut Dimension 7 and 8 should be considered but currently it is considering Shortcut Dimension 12 and 13.
5. Bank Account Reconciliation - Custom Check No. 2.
6. Draft Invoice - Company Name is print wrongly.
7. Bank Receipt Voucher - Allow Multiple Posting Group error while selecting the Income Account field.

**Comment by TabrejAlam3K** [comment]
Point No. 6 - I have tested for the below Draft Invoice Reports.

Draft Invoice GST (50148, Report Request)
Draft Invoice GST(dev)' (50156, Report Request)
Branch Draft Invoice GST(Devp)' (50157, Report Request)
IBL Tax Draft GST/Credit Memo (50161, Report Request)

**Comment by TabrejAlam3K** [comment]
Please check the latest update on the below Points with responsible persons.

1. Role Center should be enable for User and User don't have permission to switch any other role center. - **Mr. Niranjan need to Check**
2. In Collection Detail List - Location Should be filter base on User Setup Location. - **New Requirement**
3. Daily Collection Client Name having length issues. - **Need to Deployed in Prod (Mr. Pandu is Working)**
4. Shortcut Dimension 7 and 8 should be considered but currently it is considering Shortcut Dimension 12 and 13. - **Mr. Kartik D need to suggest what we can do for this**
5. Bank Account Reconciliation - Custom Check No. 2. - **Need to Deployed in Prod (Mr. Pandu is Working)**
6. Draft Invoice - Company Name is print wrongly. - **Working**
7. Bank Receipt Voucher - Allow Multiple Posting Group error while selecting the Income Account field. **Working (Wait till Client Confirmation).**

CC ; @audhi3k @Shasthara

**Comment by panduc** [comment]
@TabrejAlam3K  Point 3 and point 5 completed. tested and as confirmed we are moving to Production.

**Comment by Shasthara** [comment]
@TabrejAlam3K For next time please register each issues in GitHub separately
