### ISSUE TITLE
While entering the Bank receipt ,Interdivision entries are created in foreign currency value and not in INR value

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#349]
Please update currency code in interdivision line after this issue will be resolved.

**Comment by sandhya3k** [comment]
@Amar-3KT 

Now, it's working as per requirement. i deployed in production also

cc : @audhi3k

**Comment by Amar-3KT** [comment]
Currency picking but exchange rate not updating as per line exchange rate.

**Comment by niranjand22** [comment]
Please update the latest status @Amar-3KT

**Comment by Amar-3KT** [comment]
Ms. Padma working on it...BC Server responding very slow.....
Currently stuck in Loop- Creating to many interdivision entries

**Comment by Amar-3KT** [comment]
Looping issue still there..

**Comment by Amar-3KT** [comment]
Its working fine and confirmed by Mr. Muthu. @Padma2717 Please do the same for all vouchers and Deploy on Production

**Comment by Padma2717** [comment]
done

**Comment by niranjand22** [comment]
@Amar-3KT  to get confimation on closure from client

**Comment by Amar-3KT** [comment]
Mail has been sent. waiting for client closure.

**Comment by Amar-3KT** [comment]
Client not yet confirmed....
