### ISSUE TITLE
Export to excel functionality is not working for employee: Pallavi. CAS-01223-S7S2F6

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#352]

**Comment by niranjand22** [comment]
Hi Lakshmi

Please note below issues to be addressed immediately if possible at keltech environment.

1.	Export to excel functionality is not working for employee: Pallavi.
2.	In COA new two fields required - MIS Group 1, MIS Group 2, MIS Group 3 is available, Please create another two fields like MIS Group 4 and MIS Group 5 
3.	In GL entry please bring all dimension values
4.	Request you to remove State line dimension

**Comment by panduc** [comment]
@niranjand22 MIS Group 4 and MIS Group 5 fields created in KELTECHUAT230722 DB. Please check and confirm.

Export to Excel issue please with check users availability.

**Comment by niranjand22** [comment]
user profile got corrupted ,system is not allowing to delete the user profile and reinstate the user

**Comment by niranjand22** [comment]
@panduc .. Please check on this case

**Comment by panduc** [comment]
@niranjand22 as discussed there was did you checked with user. is she able to export it? if not did got her availability to check in screen sharing?

**Comment by niranjand22** [comment]
mr sujay will ask pallavi user to check in uat company

**Comment by niranjand22** [comment]
Sent multiple follow up asked also called multiple times to confirm..feedback not yet recievd

**Comment by niranjand22** [comment]
follow up mail sent

**Comment by audhi3k** [comment]
Mr @niranjand22 can you update the status
CC Mr @narayana3kt - we  have completed the task but client not giving confirmation for closure - to your attention

**Comment by audhi3k** [comment]
@panduc , kindly deploy in Production, Mr @niranjand22  kindly follow and close this point

**Comment by niranjand22** [comment]
We did same changes what ever was done in UAT. Closing this case now
