### ISSUE TITLE
Vouchers Report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#358]
Fervid Team Requirement

1. They want company logo in the vouchers report
2. They require Company CAN No. in the voucher report

**Comment by niranjand22** [comment]
Rename  Registration No Field to CIN No. in Company Information table

**Comment by Ejaz3KT** [comment]
I have explained to MS. @sruthi1017 about the requirement she is working on it

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
![Image](https://github.com/3ktech/General/assets/125632927/7df06d0c-5219-4bf8-a424-4ed64b169916)

Ms. @sruthi1017 added the company logo and CIN No. in the voucher reports need to showcase to the client and get confirmation.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Ms. @sruthi1017 As we discuss today Please Place the CIN No. below address

CC: @audhi3k

**Comment by sruthi1017** [comment]
hi @Ejaz3KT changes has been done in the posted voucher as we discussed yesterday, test whether it is working fie

**Comment by Ejaz3KT** [comment]
@sruthi1017 as we discuss in the call please update the company address, Email, GST No., PAN No. State. in the voucher report.

@audhi3k

**Comment by sruthi1017** [comment]
@Ejaz3KT changes has been done in voucher report and it is available in dev_sandbox can u please check.

CC:@audhi3k

**Comment by audhi3k** [comment]
Waiting for client confmation
