### ISSUE TITLE
In COA new two fields required - MIS Group 1, MIS Group 2, MIS Group 3 is available, Please create another two fields like MIS Group 4 and MIS Group 5 CAS-01229-D5F3V3

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#359]

**Comment by niranjand22** [comment]
![Image](https://github.com/3ktech/General/assets/116243958/bfe00d28-9a1e-4fcd-a8bf-4ef66ded1977)

**Comment by niranjand22** [comment]
In MIS Group Field colum kindly create two more Option for Group 4 and Group 5.

For Mis 4 Group 4 has to be mapped and for Mis 5 Group 5 has to be mapped

**Comment by niranjand22** [comment]
Field is added and tested..in UAT waiting for client confirm to deploy in live

**Comment by niranjand22** [comment]
@panduc  you can deploy in live

 Checked. Everything okay you can move It to live Please.

Regards.
Sujay

**Comment by niranjand22** [comment]
@panduc  Please deploye in live

**Comment by panduc** [comment]
@niranjand22  Deployed in LIVE. Please check and confirm.
