### ISSUE TITLE
List of Finance Report is Missing in BC

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#36]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

Module | Report ID | Report Caption | Testing Status | Tested By | Testing Date | Comments | Status
-- | -- | -- | -- | -- | -- | -- | --
Finance | 50139 | Owner Update New | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50140 | Group_Head_Update New | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50160 | Update ShiptoCon | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50162 | Sub Group Billing Own   2 Update | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50082 | Cust Ledger Acc. New | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 16562 | Day Book | Found | Tabrej Alam | 09-01-2023 | BC Report ID - 18929 | Error
Finance | 16563 | Ledger | Found | Tabrej Alam | 09-01-2023 | BC   Report ID - 18932     Location Code is missing in Report Option | Enabled
Finance | 16565 | Cash Book | Found | Tabrej Alam | 09-01-2023 | BC   Report ID - 18931     Location code is missing in Report Option | Enabled
Finance | 16566 | Bank Book | Found | Tabrej Alam | 09-01-2023 | BC   Report ID - 18930     Location code is missing in Report Option | Enabled
Finance | 28 | Dimensions - Detail | Found | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50008 | Reimburseable | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50036 | Customer Detailed   Aging (NEW) | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50061 | Bill/Memo Issued   (Excel) | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50037 | Cust. Detail with   Date Filter | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50060 | Credit Notes(Excel) | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50063 | Daily Bill/Memo   Issued(Excel) | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50067 | Memo Raised Aa   On(Excel) | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50068 | Report of Bank Ledger   Recpt | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50065 | Credit Notes(Summary) | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50066 | Daily Collection | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50069 | Collection As On | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50071 | Collection Detailed   Report | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50080 | Bill/Memo   Issued(Summary) | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50079 | Writte Off | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50074 | Bounce Cheque | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50082 | Cust Ledger Acc. New | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50028 | GL Collection | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50073 | Cusotmer Collection | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50105 | Customer Detailed   Aging (Group | Not Found in BC | Tabrej Alam | 09-01-2023 |   | Enabled
Finance | 50019 | Accounts Voucher   Report | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50020 | Bank Recocilation UAT | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50118 | Cusotmer Collection   Open | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50163 | Mail To owner 1 | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50112 | Mail To owner | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50127 | Mail To Group Head | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50166 | Outstanding Bill Mail   Owner1 | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50141 | Outstanding Bill Mail   Owner | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50142 | Mail Bill To Group   Head | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50158 | Mail To Sub-Group   Owner | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50159 | Mail Bill To Sub   Group Head | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50167 | Posted sales Invoice   PDF | Found | Tabrej Alam | 10-01-2023 | Not able to preview   the report in BC | Enabled
Finance | 50122 | Cusotmer   Collection_mod | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50194 | TDS Report | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50138 | Merged Bill and CRN | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50164 | Mail Cust. Aging (All   Groups) | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50144 | Customer Detailed   Aging Mail | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50145 | Customer Aging Mail | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50195 | TDS Report New | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled
Finance | 50172 | Email Dig Sign | Not Found in BC | Tabrej Alam | 10-01-2023 |   | Enabled

</body>

</html>

**Comment by panduc** [comment]
Have enabled most of the reports. Please start the testing for those enabled report.

Some standard report (Day Book, Bank Book, Ledger and Cash book) needs to be discussed.

Other Customized reports are related Email report. Internally Technical team will discuss and come up with ideas.

**Comment by 3ktech** [comment]
@TabrejAlam3K , we need to discuss about this task as it is difficult to track if we have all the reports in 1 task. Let us discuss tomorrow on how to handle this
@audhi3k , @panduc

**Comment by TabrejAlam3K** [comment]
@3ktech  I have list of 67 Finance Reports, If you have required separately so that I will create an individual ticket for the listed reports.

@audhi3k @panduc

**Comment by audhi3k** [comment]
I don't think that we have to create task for each report, these are not available in BC

**Comment by panduc** [comment]
@TabrejAlam3K Enabled all the customized reports. Please start doing testing.

there are 4 reports which needs to be created as Report extension. I will update after the analysis.

**Comment by sandhya3k** [comment]
@TabrejAlam3K  can u please test the ledger report?

**Comment by panduc** [comment]
@TabrejAlam3K Day Book, Ledger, Cash Book and Bank book reports are created as report extension and available for testing. Please connect with @sandhya3k if any inputs required.

**Comment by TabrejAlam3K** [comment]
Now I am able to find all the report.
This ticket is based on for only I was not able to find the reports in BC, so currently I am closing the ticket.
