### ISSUE TITLE
In GL entry please bring all dimension values CAS-01230-Z4Q2F7

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#360]

**Comment by niranjand22** [comment]
@panduc  please update once customization done

**Comment by niranjand22** [comment]
Hi @panduc  Can you take up this customization

**Comment by niranjand22** [comment]
Hi @audhi3k  Cilent ahs sent mail to mve change to live..Please move to live.

**Comment by audhi3k** [comment]
@niranjand22 , Deployed in LIVE, kindly check and confirm on closure

**Comment by niranjand22** [comment]
Asked client to check and confirm

**Comment by niranjand22** [comment]
closig for non response from clientt..we have deployed this to live
