### ISSUE TITLE
TP Reports header and footer sections change

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#363]

**Comment by 3ktech** [comment]
Here you go for the requirement from customer.

![image](https://user-images.githubusercontent.com/104021916/237037325-89f6eb1b-3cb9-4c9a-b0d8-1b003c4a3513.png)

**Comment by sandhya3k** [comment]
i have done the customization above the screenshot attached the pdf please refer.

[TP.pdf](https://github.com/3ktech/General/files/11430868/TP.pdf)

cc : @3ktech  @audhi3k

**Comment by sandhya3k** [comment]
@3ktech  I took the backup from production
please find the attachment, but iam unable to upload the rdl file

[Default (5).docx](https://github.com/3ktech/General/files/11505096/Default.5.docx)
