### ISSUE TITLE
Re: Merit - Unable to dispatch invoice over BC

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#364]

**Comment by niranjand22** [comment]
Please update status here for this @TabrejAlam3K

**Comment by panduc** [comment]
@TabrejAlam3K as discussed Please get the users ID and password and do the setup

https://yzhums.com/1799/

use "Set up Email" instead of SMTP mail setup. Please let me know if you need any support.

**Comment by niranjand22** [comment]
Hi @TabrejAlam3K  . Please update the latest status here on this issue.. and share the required user id and password

**Comment by TabrejAlam3K** [comment]
Hi Mr. @niranjand22 - they are not going to share any of their passwords. We need to find the other route to resolved it.

**Comment by niranjand22** [comment]
@panduc  kindly lookinto this case

**Comment by panduc** [comment]
@niranjand22 @TabrejAlam3K 
we have configured the Email setup and able to send Email successfully in Production. Client also confirmed.

**Comment by TabrejAlam3K** [comment]
Mr. @niranjand22 - Please close this ticket client has confirm.

![Image](https://github.com/3ktech/General/assets/116171982/e6b643d7-5f29-4fe5-b9e2-750ca9a608bd)

CC : @audhi3k
