### ISSUE TITLE
Posted Boolean should be ture for Division (IPR) - Page 50078

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#369]
On Collection Detail Card (50078, Card) - Posted Boolean should be true if the Division alone is **IPR** else posted Boolean should be non-editable.

![Image](https://user-images.githubusercontent.com/116171982/237273911-b4fea2f1-02a8-42a3-aab2-e2fd08260674.png)

**Comment by TabrejAlam3K** [comment]
@sandhya3k - As per our discussion please complete the development and let me inform then we can test and informed to the client for UAT.

CC : @audhi3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

please check UAT env

cc: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - It is working fine in UAT can you please move this in to the Production.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Changes is not moved into the Production yet.

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/13ea0c39-01c2-4fdc-9b6a-9656e7355dbe)

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/96aca3af-e03b-47ab-ad4d-9a651c6b2e02)

**Comment by TabrejAlam3K** [comment]
As of now we are going to close this issue because client not responded on since long time, We are assuming the issue is working fine.

CC : @audhi3k
