### ISSUE TITLE
Unable to enter Employee in the WBS

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#37]

**Comment by 3ktech** [comment]
@Mahesh3ktech , can you look at this?

**Comment by 3ktech** [comment]
I sent you an email with the recording to reproduce this issue. @Mahesh3ktech 
CC: @audhi3k

**Comment by 3ktech** [comment]
hi @Shasthara , there was a repro steps explained in a video shared by Sigaravel. Unfortunately the video is not available with the full info. Can you please liaise with him to get the full video file and share it here so that @Mahesh3ktech  can continue.

**Comment by 3ktech** [comment]
I am keeping this on hold until then @Shasthara

**Comment by audhi3k** [comment]
I have explained to Mr Mahesh and he has fixed the issue and now under Cust Test

**Comment by Shasthara** [comment]
Noted!

**Comment by audhi3k** [comment]
Client confirmed on closure
