### ISSUE TITLE
RE: CHEQUE Reference number missing

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#371]

**Comment by niranjand22** [comment]
Mr Pushkar has to share the source file

**Comment by niranjand22** [comment]
After Feb bank reconciliation, we have noticed that the “Payment reference / Cheque numbers” are not captured in the ledger entries.

Plse find the attached Business Central extract, which shows 80+ refund transactions with no cheque number under the payment reference field.

Due to this the auto-match is not working and even manual search is difficult for us during reconciliation.

Can we plse urgently investigate it and fix it.

**Comment by niranjand22** [comment]
[Chq Ref missing.xlsx](https://github.com/3ktech/General/files/11474412/Chq.Ref.missing.xlsx)

**Comment by niranjand22** [comment]
requested me pushkar and startek team for super permission assign

**Comment by niranjand22** [comment]
hello Pushkar Apte. we would like to have source code of the custom extensions like "Startek_Int" and "StartTrek1". this will help us 

to analyze the reported issue 
to find out the root cause of the issue and 
also to provide a fix for the issue.

The Questions to ask:

do they have source code for the above mentioned extensions? If so, please share with us.
if they don't have source code, can they get the source code from previous partner who developed those extensions

**Comment by niranjand22** [comment]
Hi @3ktech, Hope you have received the source code. I hope you are aware of the requirements. kIndly take this forward

**Comment by niranjand22** [comment]
Issue is resolved in UAT waiting from confirmation from ifi team to deploy source code in live

**Comment by niranjand22** [comment]
By Startek sohon---Let me do the testing in Sandbox first and can organize a call by Wed/Thursday after 6pm AEST.

 

@Dynamics Support – Thank you for the confirmation and would like to discuss more once we have more understanding after the testing.

**Comment by niranjand22** [comment]
Cheque no is getting printed in bc but. they are having continuation query on bank reconciliation. will connect with client on this again

**Comment by niranjand22** [comment]
Hi Team,

 

I uploaded two new cheque refunds (plse find the attached file).

 

And the payment ref column now contains the corresponding cheque numbers.

 

I also did the bank rec (under the 8th Statement Date)  with just that two entries and it’s also working.

By Salini

**Comment by niranjand22** [comment]
Hi Team,

 

Before we deploy the changes to Prod, we would like to do more testing.

Kindly give us two more days and will confirm the same.--by salini

**Comment by niranjand22** [comment]
As discussed, please carry out few more testing just to cover every scenario of tolerance date, same amount with difference chq number, same chq number but different amount etc.
I have done my own testing and it looks fine so far.

Hi Dynamics support,

Once confirm by Salini, you can deploy. However, please ENSURE that no modification is done key logics of deferral journal calculation or on any other extensions and customisation.
I will even further suggest to make one copy of current production environment into sandbox so that in the event something breaks we can restore by redeploying current working extensions.

**Comment by niranjand22** [comment]
@3ktech  The Match automattical case is continuation of this case only we can use this git ID. cc @sruthi1017

**Comment by 3ktech** [comment]
@niranjand22 , thanks.

**Comment by niranjand22** [comment]
I will provide uat to client. Its working fine now.

**Comment by niranjand22** [comment]
Updated ms salini..regarding payment matching..  for testing

**Comment by niranjand22** [comment]
Hi Pushkar,

We faced two technical issues in Startek Team - one with checking Reference Numbers and the other with Payment Reconciliation. Thankfully, both problems were fixed in the Sandbox Environment.

However, before we move on to deploying the source code in the Startek Production environment, we need to be absolutely sure that the code we received is the most up-to-date version and matches what is currently used in Production. Can you please check with the Partner and confirm this for us?

Thank you so much for your help!

**Comment by niranjand22** [comment]
Pushkar will confrim to akash

**Comment by niranjand22** [comment]
waiting for deployment cofnrimation

**Comment by niranjand22** [comment]
Due to auto update customisation has been removed from  startek .sand box. can you pls update this on priority. @sruthi1017 
@3ktech .

**Comment by niranjand22** [comment]
Extensions is Published. Ms Salini will confirm fo deployment to Prod after testing.

cc @audhi3k

**Comment by niranjand22** [comment]
Client is asking to hold the deployment for few days. They will confirm it when to deoploy.
cc @audhi3k

**Comment by niranjand22** [comment]
Mr Pushkar Confirmed for Closure. For Live deployment we will create new ticket.

cc @audhi3k
