### ISSUE TITLE
Inventory cost issue-PWRPONAC/2223/0166	Nacelle Assembly cannibalization – W49 (130000000)

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#372]
Need more information- Mr. Senthil busy, he will call me back when free.

Mr. SenthilV will get connect on Friday.

**Comment by Amar-3KT** [comment]
Mr. Senthil will be available on Monday.

**Comment by Amar-3KT** [comment]
Process has been shown to Mr. Senthil. He will update today evening then we can close.

**Comment by Amar-3KT** [comment]
Today Mr. Senthil will confirm.
