### ISSUE TITLE
After application invoice entry in bank receipt voucher, cost center not getting update in line.

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#376]

**Comment by Amar-3KT** [comment]
@sandhya3k Kindly check this issue and resolved ASAP.

**Comment by sandhya3k** [comment]
Today, iam going to connect the @Amar-3KT  for this issue

cc : @audhi3k

**Comment by sandhya3k** [comment]
@Amar-3KT 

I deployed in Production, please check

cc : @audhi3k

**Comment by Amar-3KT** [comment]
@sandhya3k Now its working fine on UAT. Waiting for client Clouser on production.
