### ISSUE TITLE
Service Invoice Error CAS-01237-H6L4M6

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#379]

**Comment by niranjand22** [comment]
While raise invoice below error coming kindly resolve

![Image](https://github.com/3ktech/General/assets/116243958/75a8f596-855b-41a9-84fa-d483d27bc07f)

**Comment by audhi3k** [comment]
Dear Mr Senthil,

The Service Order doesn't exist.

Hence created service order and line, Tracking specifiication



Regards,
Audhi Lakshmi S

**Comment by audhi3k** [comment]
Dear Mr Senthil,

We have fixed the issue kindly check and confirm


Regards,
Audhi Lakshmi S

**Comment by audhi3k** [comment]
Dear Mr Senthil,

Thanks for confirming.

Time Taken – 2 hours

Regards,
Audhi Lakshmi S

**Comment by niranjand22** [comment]
Again service invoice error is coming 

Order No- PMBDR/MA/2021/0645

I have checked log entries for this document nothing it is showing




![Image](https://github.com/3ktech/General/assets/116243958/4243afe6-b954-43ea-99a7-60750c1ce8d7)



![Image](https://github.com/3ktech/General/assets/116243958/0d48da6a-a627-440b-8635-e34b1c64d221)

**Comment by niranjand22** [comment]
Required changes done

**Comment by niranjand22** [comment]
order no PMBDR/TE/2021/1455
serv in no 388

**Comment by niranjand22** [comment]
Issue is coming for 2021 year documents


![Image](https://github.com/3ktech/General/assets/116243958/d5797a05-16c7-4096-bb80-9c3d8d396767)
![Image](https://github.com/3ktech/General/assets/116243958/55528e23-29b6-49a7-82ef-75e3cc180fa2)
