### ISSUE TITLE
Vendor Outstanding Report

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#38]
See the below format with example data.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Vendor Outstanding Register (Excel Report) |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
  |   |   |   |   |   |   |   |  
Vendor No. | Vendor Name | Posting Date | Document Type | Document No. | Description | Amount (LCY) | Remaining Amount | Due date
VD-MR555555 | XYZ Ltd | 25-10-2022 | Invoice | PPI-001 | Stationary exp for   Oct'22 | -20,000 | -20,000 | 20-11-2022
VD-MR101126 | We Can Facilities   Management | 29-11-2022 | Invoice | PPI-123 | Pest control charges   for Nov'22 | -18,560 | - | 09-12-2022
VD-MR101126 | We Can Facilities   Management | 30-11-2022 | Credit Memo | PCM-123 | Pest control charges   for Nov'22 | 560 | - | 30-11-2022
VD-MR101126 | We Can Facilities   Management | 02-12-2022 | Payment | PJ-123 | Pest control charges   for Nov'22 | 18,000 | - | 02-12-2022
VD-MR999 | ABC Ltd | 10-12-2022 | Invoice | PPI-221 | Travel exp for Dec'22 | -5,000 | -5,000 | 05-01-2023

</body>

</html>

**Comment by 3ktech** [comment]
@audhi3k , is ths report based on VLE / DVLE?

**Comment by audhi3k** [comment]
We will share the field mapping for the report

**Comment by 3ktech** [comment]
@audhi3k will check the standard to check if it works well or not based on that decision has to be taken

**Comment by audhi3k** [comment]
We have suggest the standard report to the client, will get confirmation for closure

**Comment by audhi3k** [comment]
Client confirmed on closure
