### ISSUE TITLE
GST configuration and Item update

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#380]

**Comment by niranjand22** [comment]
@Amar-3KT  pls add comments an update status

**Comment by Amar-3KT** [comment]
HSN/SAC code updated 
GST group updated
GST Posting Setup updated
GST Rate updated
GST Setup created
Item card - GST group and hsn/sac code updated

**Comment by Amar-3KT** [comment]
@Ejaz3KT Kindly take confirmation from client.
