### ISSUE TITLE
Multi Payment methods for Sales

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#381]
Kindly test and confirm

**Comment by Amar-3KT** [comment]
1) If Payment term <>100 it will not allow you to close(ESC)- validation Need to be add
2) Payment Schedule List advance field should be non-editable---Not done
3)after post of advance, Advance journal will get posted-
  b) if advance posted -it should not open again-Currently we are able to open
  d) if all advance posted or if there is no advance Boolean tick in schedule payment list validation should show "There is no advance nothing to post""-- not showing any error
4) advance entry should be bank to customer only- Currently its creating customer to customer
5) payment term should be sorted based on lines
6) while posting order it should show msg do you want to post the journal lines
7) Customer ledger entry, detail customer Leder and bank ledger entry not correct after posting advance

**Comment by Ejaz3KT** [comment]
![Image](https://github.com/3ktech/General/assets/125632927/d897f31b-af0d-47f7-a8c6-e8ee3e9fd10c)@

While posting the advance it show this error message

**Comment by sandhya3k** [comment]
@audhi3k 

I have shared the all details to @Mahesh3ktech

**Comment by Mahesh3ktech** [comment]
Hi @Amarjeet Above points are completed, except 5th point standard popup message not able to block or skip. Kindly test and update.

**Comment by Amar-3KT** [comment]
1)Point 1 not done

For purchase order not able to post post advance

all other points related to advance please resolved this issue @Mahesh3ktech

**Comment by Amar-3KT** [comment]
For sales 1 point and post advance not able to post
Document No. must have a value in Gen. Journal Line: Journal Template Name=BANK RECE, Journal Batch Name=DEFAULT, Line No.=20000. It cannot be zero or empty.

**Comment by Amar-3KT** [comment]
Pending points sales:-
1)If Payment term <>100 it will not allow you to close(ESC)- validation Need to be add
2) if all advance posted or if there is no advance Boolean tick in schedule payment list validation should show "There is no advance nothing to post""
3) if advance posted then schedule should not open again-Currently we are able to open
4)while posting order it should show msg do you want to post the journal lines

**Comment by Ejaz3KT** [comment]
@Mahesh3ktech While I am testing the sales invoice I am getting this error

![Image](https://github.com/3ktech/General/assets/125632927/8690448f-f744-452c-ab4a-0ee1f5b4545f)

CC: @audhi3k @Amar-3KT

**Comment by Mahesh3ktech** [comment]
hi @Amar-3KT,

Pending points sales:-
1)If Payment term <>100 it will not allow you to close(ESC)- validation Need to be add  - **Completed.**
2) if all advance posted or if there is no advance Boolean tick in schedule payment list validation should show "There is no advance nothing to post"" - **Completed.**
3) if advance posted then schedule should not open again-Currently we are able to open - **Need to work**
4)while posting order it should show msg do you want to post the journal lines - **Standard error message.**

CC @audhi3k

**Comment by Amar-3KT** [comment]
2) I have created new order and posting advance its throwing an error-There is no advance nothing to post
3) Not able to test due to 2nd point

**Comment by audhi3k** [comment]
Multiple payment terms for Sales is not completed, work with Ms @sandhya3k

**Comment by audhi3k** [comment]
Closing this ticket , will be tracked in #519
