### ISSUE TITLE
Upload of Inventory opening balance

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#382]

**Comment by niranjand22** [comment]
@Amar-3KT 
Check the values
Post the transaction
get confirmation from the client

**Comment by Amar-3KT** [comment]
Values are missing in records.

**Comment by Amar-3KT** [comment]
Item opening posted on Opening test company.

**Comment by Amar-3KT** [comment]
We have sent mail to client. Waiting for client closure.

**Comment by audhi3k** [comment]
Done in UAT

**Comment by audhi3k** [comment]
in UAT it's completed
