### ISSUE TITLE
Support for UAT

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#384]

**Comment by Ejaz3KT** [comment]
I`ve supported Ms. Jhansi in the creation of purchase quotes, purchase orders, and purchase invoice 

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
I`ve supported Mr. Sreedhar in the creation of sales orders, cash payment vouchers, bank payment vouchers, and journal voucher.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
I`ve supported Mr. Sreedhar in the sales process with GST 

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
I`ve explained few UAT points raised on Monday to Mr. Nizam and Ms. Jhansi

**Comment by audhi3k** [comment]
As Mr Ejaz is in Fervid location
