### ISSUE TITLE
purchase order customization relating to allow preview posting without Vendor Invoice No.

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#385]
Fervid team requirement in the purchase order

1. They want to do a preview posting without entering the Vendor invoice No in the header.
2. Fervid team requires Purchase order should not be deleted after posting and it should be seen in the purchase order page status as closed.
3. They want a New field name as a model in the purchase order line when they select the item all the models related to that item should appear in that field.

CC; @audhi3k

**Comment by Ejaz3KT** [comment]
@sruthi1017 Please Update the status of this task here.

CC: @audhi3k

**Comment by Amar-3KT** [comment]
@sruthi1017 @sandhya3k Please update the status of this issue.

**Comment by sruthi1017** [comment]
Mr. Narayan said to hold this for last two days, will start the development, @sandhya3k is not handling the issue.
