### ISSUE TITLE
Posted Deferral Entries Report

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#39]

**Comment by audhi3k** [comment]
We have shared the default Deferral report to the client, they will check internally and update us

**Comment by audhi3k** [comment]
@TabrejAlam3K , check with the client on requirements

**Comment by TabrejAlam3K** [comment]
@audhi3k  Ms. Swathi will update on till upcoming Monday 30-01-2023.

**Comment by TabrejAlam3K** [comment]
@audhi3k  page is not searchable for Boopathy User so currently they are not able to review it. We need to enable the Deferral Entries page for Boopathy user.

**Comment by TabrejAlam3K** [comment]
I have create a permission set for Deferral and asked to the client for testing. He will update soon.

**Comment by TabrejAlam3K** [comment]
@audhi3k - Confirmation received form the client and both the report is visible for the User - Bhoopathy.

**Comment by audhi3k** [comment]
As there is no escalation from client after sharing this, we are closing this
