### ISSUE TITLE
Dimension Value - Should not allow to modify and delete.

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#392]
Dimension should not able to modify and delete in any conditions.

**Comment by TabrejAlam3K** [comment]
Should not allow to Edit and Delete on the below pages.

1. Dimensions (536, List)
2. Dimension Values (537, List)

**Comment by sandhya3k** [comment]
I deployed in production.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Client needs User should not able to Modify and Delete the Dimension Value once the RTB and CRTB Received form the Snowfig LCMS.

RTB - Sales Invoice
CRTB - Sales Credit Memo

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Working fine in the UAT Environment.

**Comment by TabrejAlam3K** [comment]
Confirmed by the client on 22-05-2023 for closer

CC : @audhi3k @Shasthara
