### ISSUE TITLE
UL production deployment

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#397]

**Comment by TabrejAlam3K** [comment]
I have done the Inventory Posting setup with Location in RRL-OU and Urban Ladder Company. 

Client has not yet updated whether they have done the Copy Company or not.
I was available for the Support on Saturday and Sunday.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Session is scheduled for today **(Prod testing - UL subcontracting)** from 3:00PM to 4:00PM

**Comment by audhi3k** [comment]
!st round entries done on 6th July 2023
