### ISSUE TITLE
Documentation of Data upgrade

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#4]

**Comment by Shasthara** [comment]
Padma and karthik D need help from content writer

**Comment by Shasthara** [comment]
Assign Manoj to this task

**Comment by sruthi1017** [comment]
It has been completed, and reviewed by Mahesh C

**Comment by Shasthara** [comment]
@Shasthara to share it with client

**Comment by sruthi1017** [comment]
attached the document of data upgrade.
[LKS Database Migration Steps.docx](https://github.com/3ktech/General/files/11326609/LKS.Database.Migration.Steps.docx)
