### ISSUE TITLE
Invoice Layout Issue-Reg.:CAS-01227-Z8R9J8

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#403]

**Comment by niranjand22** [comment]
Here attached Layout Issue Stock Transfer invoice, kindly fix the issue

[Stock Transfer.pdf](https://github.com/3ktech/General/files/11493925/Stock.Transfer.pdf)

**Comment by niranjand22** [comment]
I have chcked in pioeer system..amount column Is out of layout

**Comment by niranjand22** [comment]
To analyse in detail and then to start this activity

**Comment by niranjand22** [comment]
@sandhya3k  lets connect on this today

**Comment by niranjand22** [comment]
DOC NO- WBRTPY/2324/0005
Report-Tax - Invoice GST (50050)

Posted sales Invoice >Print tax GST Invoice

**Comment by sandhya3k** [comment]
@audhi3k 

Hi mam, @niranjand22  explaned the report alignment issue. After i analysis i am going to take 2 hours

cc : @niranjand22

**Comment by audhi3k** [comment]
@sandhya3k ok ma

**Comment by sandhya3k** [comment]
@niranjand22 

please check in UAT environment

**Comment by niranjand22** [comment]
U can depoly to live

**Comment by sandhya3k** [comment]
@niranjand22 

I deployed in production

**Comment by niranjand22** [comment]
Updated to client for confirmation
