### ISSUE TITLE
Transfer Order Inter-branch transactions (Goods movement)

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#407]

**Comment by Ejaz3KT** [comment]
I`ve Shown the Transfer order functionality to the fervid team

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The fervid team requires small customization in transfer orders without GST the transfer order should not post 

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The fervid team requires the transfer order should posting with GST only without GST it should not post and pop-up error message while posting the order without GST.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
HI @sruthi1017 while posting the transfer order with GST it is showing this error can you please resolve this asap for your  reference please have a look on screen  shot

![Image](https://github.com/3ktech/General/assets/125632927/213db90e-cf92-4677-b7ad-e0134e689237)

CC: @audhi3k

**Comment by 3ktech** [comment]
@audhi3k , @sruthi1017 is waiting for information to provide solution for this issue

**Comment by Ejaz3KT** [comment]
1. when we are put GST manually the transfer order is showing error it is not posting.
2. fervid team want restriction if the user is not select the same project as dimension the transfer order should not post it shows error like you not selected the same project dimension.

@audhi3k @3ktech @sruthi1017

**Comment by Ejaz3KT** [comment]
![Image](https://github.com/3ktech/General/assets/125632927/298a3785-0b35-4435-8d82-31c176875b7a)


system is showing the error when we select the GST manually

CC: @audhi3k @3ktech

**Comment by Ejaz3KT** [comment]
Technical team is still  working on it s

CC: @audhi3k @sruthi1017 @TabrejAlam3K

**Comment by audhi3k** [comment]
LIVE declared
