### ISSUE TITLE
Ship to address Functionality

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#409]
Fervid team doing business with customers or vendor books of accounts should hit in Single Ledger  with different GST locations

**Comment by Ejaz3KT** [comment]
I`ve Shown the ship to address functionality to the fervid team in the UAT session

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Mr. Sreedhar And Mr. Harish Need some more clarity on ship to address and bill to address functionality 

CC: @audhi3k

**Comment by audhi3k** [comment]
Explained to client and there is no queries on this
