### ISSUE TITLE
Finance Report - Bill/Memo Issued (Excel) ID - 50061

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#41]
Showing Error but in Navision 2016 working fine

![Image](https://user-images.githubusercontent.com/116171982/212059671-22d30729-0a43-4c47-9ccc-b7b9968d469b.png)

**Comment by panduc** [comment]
@TabrejAlam3K the report is working. it is showing Posted Sales Invoice.

I've executed in LKS Company. with Posting Date Filter: 12012019..12312019

Please test it and confirm.

**Comment by TabrejAlam3K** [comment]
Done

[50061.pdf](https://github.com/3ktech/General/files/10423212/50061.pdf)
