### ISSUE TITLE
Assembly Order how to find out Finished goods entry in dynamics

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#412]

**Comment by Ejaz3KT** [comment]
I`ve Shown the Assembly order functionality to the fervid team.

CC: @audhi3k

**Comment by audhi3k** [comment]
Explained the process and waiting for client confirmation

**Comment by Ejaz3KT** [comment]
Fervid team ask me to share the documentation related to assembly order process

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
I`ve shared the documentation related to the assembly order with to fervid team

CC: @audhi3k

**Comment by audhi3k** [comment]
LIVE declared
