### ISSUE TITLE
JV and Job G/l pre entry records removed-Need to correct FNF jv and Pay JV code

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#414]

**Comment by Amar-3KT** [comment]
Few days back we uploaded all JV and JJV records in Journal lines but today when Mr. Muthu run FNF Jv functionality all records get removed.
@Mahesh3ktech Please check FNF jv code.

**Comment by Amar-3KT** [comment]
Due to FNF jv process all voucher getting delete.

**Comment by Mahesh3ktech** [comment]
hi @Amar-3KT  condition added to skip other voucher records and it will delete the data of Fnf JV and Pay JV batch records only. kindly test and confirm.

**Comment by Amar-3KT** [comment]
@Mahesh3ktech On UAT we have tested. Its working fine. kindly update on live.

**Comment by Amar-3KT** [comment]
@Mahesh3ktech 
Please update the status.

**Comment by Mahesh3ktech** [comment]
@Amar-3KT 

Waiting for the latest source file, once we got that than ill publish to production.

**Comment by audhi3k** [comment]
Dependency on Mr Rajesh for the source code

**Comment by Amar-3KT** [comment]
Deployed on Live waiting for client closure.
