### ISSUE TITLE
Finance Report - Credit Notes(Excel) ID - 50060

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#42]
Report is different whatever the report is available in NAV 16
NAV 16 Report ID is **50065** and BC Report ID is **50060**

**Comment by panduc** [comment]
![Image](https://user-images.githubusercontent.com/110709312/212153116-08fa0718-066c-4061-a852-bf9aebb187ad.png)

**Comment by panduc** [comment]
@TabrejAlam3K  50060 Credit Notes(Excel) and 50065 Credit Notes(Summary) both the reports are running fine and it exists in NAV 2016 as well.

Both the reports shows Poste Sales Credit Memos.

I've tested in LKS company and filter Posting Date : 01012020..01302020 (MMDDYYYY)

**Comment by TabrejAlam3K** [comment]
Done

[50060.pdf](https://github.com/3ktech/General/files/10423242/50060.pdf)
