### ISSUE TITLE
TCS setup & tax invoice report change modification

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#421]

**Comment by niranjand22** [comment]
TCS should be calculated on Hardware Supply at rate of 0.1% when customer crosses 50 lakh sales.

**Comment by niranjand22** [comment]
![Image](https://github.com/3ktech/General/assets/116243958/a9302eb8-5776-448f-aaf0-ead5788a9453)
![Image](https://github.com/3ktech/General/assets/116243958/118b3f01-6443-43c3-a561-422bca5fd7f2)
![Image](https://github.com/3ktech/General/assets/116243958/effa7ebc-bebd-4d39-80e2-269058aeb1b1)
![Image](https://github.com/3ktech/General/assets/116243958/34cc8b61-70ba-4095-bae8-f3225169b86b)
![Image](https://github.com/3ktech/General/assets/116243958/84ac2972-ba72-4d16-8418-e5f12c5a2e39)
![Image](https://github.com/3ktech/General/assets/116243958/c2812ea0-5d0a-475b-a5d5-6675de9ca922)

**Comment by niranjand22** [comment]
1. Tcs 206(1H) is applicable with a 50 lakh threshold limit. It should calculate over and above 50 lahks with 0.1 %
2.  In the Tax Invoice TCS amount field should be added
3. Payable value caption should be changes to invoice total.
4.  Pan No., ARN Mo. ARN date should be added in footer of tax invoice

**Comment by niranjand22** [comment]
Pan,ARN No is avialable in cust card.

**Comment by niranjand22** [comment]
ms @sruthi1017  once u do changes pls update

**Comment by niranjand22** [comment]
UAT Provided to Client. for whole process and report changes . He will cofirm soon to move to live.

@sruthi1017  cc @audhi3k

**Comment by niranjand22** [comment]
Client confirmed for posting in Livce.. 

in sales invoice proforma invoice is coming total blank..need to connect with ms audhi for this

**Comment by niranjand22** [comment]
Had uat.. with Jagan..confirm for deploy @sruthi1017

**Comment by audhi3k** [comment]
Deployed in LIVE and training provided

**Comment by niranjand22** [comment]
![Image](https://github.com/3ktech/General/assets/116243958/9ea8bd8c-b659-4dbc-939e-f8a7b3f918c3)
