### ISSUE TITLE
Common Master (50015) - Need to check Related Job Queue

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#423]

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc As per our discussion, We have a table called Common Master and we need to find out the route where it get updated through job queue or somewhere else.

CC : @audhi3k

**Comment by panduc** [comment]
Report 50103 Batch Job for CM Update is designed to create Common Master Table data from Customer.

**Comment by TabrejAlam3K** [comment]
Please move this changes into the Production.

**Comment by panduc** [comment]
Deployment has been done to production.

**Comment by TabrejAlam3K** [comment]
this is the duplicate points of #322 I am closing this ticket.
