### ISSUE TITLE
CR2 - Hardlink in Sales Order - Dispatch

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#43]

**Comment by 3ktech** [comment]
We are waiting for more information about this task. we have call 19/01 to discuss further on this task.

**Comment by 3ktech** [comment]
@3ktech  to verify the tech availability to support @audhi3k .

**Comment by TabrejAlam3K** [comment]
Session is done with Mr. Rewat but not completed, because we are facing some issues during the session We will complete it b the next session today or tomorrow.

**Comment by Mahesh3ktech** [comment]
Debug the issue with the manual process of updating fulfillable and Barcode. And identified based on the Serial Information Number is not finding then fulfillable getting updated as false based on the parameter.

Now we have scenario which fulfillable getting updated need to debug that scenario to understand the issue.

Yesterday connected with Mr. Tabrej to do the debug activity but Server was disconnected, and it was not reconnecting again.

**Comment by TabrejAlam3K** [comment]
@Mahesh3ktech - As per the yesterday session I have shown to you the process. If you have lks credential so you can debug it at your end.

If you have any doughs so you can cross check the recorded session video.

**Comment by TabrejAlam3K** [comment]
Recorded Session Video - 

https://3ktechnologies22-my.sharepoint.com/:v:/r/personal/tabrej_a_3ktechnologies_com/Documents/Recordings/CR2%20-%20Hardlink%20in%20Sales%20Order%20-%20Dispatch-20230216_162605-Meeting%20Recording.mp4?csf=1&web=1&e=k9lQF8

**Comment by TabrejAlam3K** [comment]
@Mahesh3ktech - As per our discussion you need to check this at your end.

Sales Order No. - RR-SO-0000227437

**Comment by TabrejAlam3K** [comment]
@audhi3k - As per the scenario it's working fine.

Sales Order No. - R202302070004

**Comment by TabrejAlam3K** [comment]
@audhi3k - Mail send for UAT to the client, once they confirm then we will close this ticket.

**Comment by TabrejAlam3K** [comment]
New Sales Order Placed for Testing

T202302220001
T202302220002
T202302220003
T202302220004
T202302220005
T202302220006
T202302220007
T202302220008
T202302220009
T202302220010
T202302220011
T202302220012
T202302220013
T202302220014
T202302220015

**Comment by TabrejAlam3K** [comment]
I have tested for below orders and it's working fine.

Sales Order No. - RR-SO-0000227474
Web Order No. - T202302220015

**Comment by audhi3k** [comment]
@TabrejAlam3K, convey the client and get this testing closed.
Ask them to test for normal scenario also

**Comment by TabrejAlam3K** [comment]
In Urban Ladder Company getting error when we try to click on Post Receive


![Image](https://user-images.githubusercontent.com/116171982/220849641-651c8224-316d-404b-9a58-80be99c4d4fb.png)

**Comment by TabrejAlam3K** [comment]
Mail Response received from the Client Side.

![Image](https://user-images.githubusercontent.com/116171982/220850289-90b2fd05-6d94-46ba-ad19-663dcd161fbd.png)

**Comment by TabrejAlam3K** [comment]
@Mahesh3ktech - Can you look this error when trying to add insert processing charge then it is showing error, even status is already open.


![Image](https://user-images.githubusercontent.com/116171982/221464269-42f44d50-2829-42bd-920f-955a523256d8.png)

**Comment by audhi3k** [comment]
@TabrejAlam3K  we will connect at 11 am to fix this issue

**Comment by audhi3k** [comment]
Resolved this issue over screen sharing session

**Comment by TabrejAlam3K** [comment]
@audhi3k - Facing Some new error when we try to Post Sent


![Image](https://user-images.githubusercontent.com/116171982/221487912-48e6c544-2385-4027-9912-805de84adae8.png)

**Comment by TabrejAlam3K** [comment]
Today I will connect with Mr. Rewat and Confirm the status

**Comment by TabrejAlam3K** [comment]
Today I will connect with Mr. Rewat and Confirm the status, Meeting is scheduled for today at 2:00PM to 2:30PM

**Comment by TabrejAlam3K** [comment]
I have done the session with Mr. Rewat he will test the case internally and confirm.

**Comment by TabrejAlam3K** [comment]
I have already confirm the activity on mail.

**Comment by TabrejAlam3K** [comment]
I have shared the testing steps to the client

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

<div ccp_infra_version=3 ccp_infra_timestamp=1677747726154 ccp_infra_user_hash=3391094304
ccp_infra_copy_id=255b486a-37aa-4208-bbba-7e205964cc07 data-ccp-timestamp=1677747726154>



Testing   Process | Steps | RRL-OU | Steps | UL
-- | -- | -- | -- | --
  | 1 | Create Outgoing   Jobwork |   |  
  | 2 | Release the Document |   |  
  | 3 | Send IC Partner   Purchase Order |   |  
  | 4 | In - IC Outbox   Transaction |   |  
  | 5 | Set Line Action -   Send to IC Partner |   |  
  | 6 | Completed Line Action   - OK |   |  
  | 7 | Post Output and   Consumption |   |  
  | 8 | Updating Item   Tracking |   |  
  | 9 | Post Receive | 1 | IC Inbox Transaction
  |   |   | 2 | Set Line Action -   Accept
  |   |   | 3 | Completed Line Action   - OK
  |   |   | 4 | Incoming Jobworkd   Order
  |   |   | 5 | Post Receive
  |   |   | 6 | Insert Processing   Charge
  |   |   | 7 | Post
  | 10 | Insert Processing Charge | 8 | Insert Processing   Charge
  | 11 | Post Expances | 9 | Post Income



</body>

</html>

**Comment by TabrejAlam3K** [comment]
@Mahesh3ktech - Please ping me once it will resolved.

![Image](https://user-images.githubusercontent.com/116171982/222481439-cebe8464-279a-4d96-840a-305277bba650.png)
![Image](https://user-images.githubusercontent.com/116171982/222481440-226d8f17-17a8-4424-bb77-217c03845114.png)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Sales Order is not available for testing with fresh document. I have send the mail to Mr. Rewat for some sales orders when we got then we can test and confirm.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Issue is not resolved till now. Let me discuss with @audhi3k and @Padma2717 on.

**Comment by Shasthara** [comment]
@Padma2717, kindly update the status

**Comment by Padma2717** [comment]
Already updated to Mr.Tabrej need a functional analysis on this issue.

**Comment by TabrejAlam3K** [comment]
@Padma2717  I am facing same error in both the company for both the scenario - Outgoing Job work and Incoming Job work. Can you please debug this.

**Post Income** - We have a button - Incoming Job Work
**Post Expanse** - We have a button - Outgoing Job Work

![Image](https://user-images.githubusercontent.com/116171982/223050345-3355b488-c7b0-42c6-aa91-d8e6771e52a0.png)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
@audhi3k 

I have Tested the Scenario

Create a Outgoing Job Work Order in RRL-OU
Send IC Purchase Order in RRL-OU
IC Outbox Transaction Send in RRL-OU
IC Inbox Transaction - Urban Ladder
Edit the Incoming Document and modify the line items - Urban Ladder
Accept the Incoming Document - Urban Ladder
Open Incoming Job Work Order(Changed Item is visible in the Orders).

**Comment by Shasthara** [comment]
@Padma2717 , please give high priority to this task and try to complete it by today

**Comment by audhi3k** [comment]
We have tested few scenarios where it's working fine, Mr @TabrejAlam3K can you share the scenario where you are getting the error for us to check it out

**Comment by TabrejAlam3K** [comment]
@audhi3k - before i was facing error on

Post Income and Post Expanse

**Comment by TabrejAlam3K** [comment]
@audhi3k @Padma2717 -I have tested it but still it is not working. We will discuss on

**Comment by TabrejAlam3K** [comment]
@Padma2717  - Currently i am holding this points till the merging of the Object.

CC ; @audhi3k

**Comment by audhi3k** [comment]
Deployed in PreProd

**Comment by TabrejAlam3K** [comment]
@audhi3k @Padma2717 - See the Error Snapshot.


![Image](https://user-images.githubusercontent.com/116171982/228154137-137de386-fcdd-4ca9-a280-acc9b00f67de.png)
