### ISSUE TITLE
Reverse Transaction Error

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#430]
**Reversal Error Snapshot.**

![Image](https://github.com/3ktech/General/assets/116171982/af8a6303-d532-49ac-ab53-d59ce2fc066f)

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - As per our last discussion have you debug the error. Please update your comments here.

CC : @audhi3k @narayana3kt

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

As discussed, please replicate the scenario in sandbox environment

cc : @audhi3k  @narayana3kt

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

As discussed, please confirm for the next step?

cc : @audhi3k

**Comment by TabrejAlam3K** [comment]
We have already replicated the scenario in Copy of Production company it was working fine.

@audhi3k - @sandhya3k  said this is the base functionality error. she need some discussion on it.

**Comment by audhi3k** [comment]
Mr @TabrejAlam3K We can connect at 11:30 am tomorrow morning

**Comment by audhi3k** [comment]
As there is no request on the issue, we are closing this ticket
