### ISSUE TITLE
NKG Debit Credit not showing correctly.

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#431]

**Comment by Amar-3KT** [comment]
@Mahesh3ktech When NKG team transferring data from one company to another company amount not updating correctly.

**Comment by Amar-3KT** [comment]
Technical not available

**Comment by Amar-3KT** [comment]
Technical not available

**Comment by panduc** [comment]
@Amar-3KT  as analyzed data transfer is working fine source to Destination company. 

Source Company:  NKG India Coffee Pvt Ltd
Destination Company: NKG India IFRS


![Image](https://github.com/3ktech/General/assets/110709312/00f01a3f-f6f7-4bce-8572-e3bbc969ef16)



Findings after analysis:
1. There is an issue in Source company for Additional Currency Amount debit and Credit not matching.

**Comment by Amar-3KT** [comment]
1) We have done some entries now its working fine debit and credit both are updating correctly in both companies.
2) Exchange rate updating same for debit and credit.
3) Also, we follow all same step as suggested by Mr. Suresh(NKG) and found correct entries.
4) Mr. Suresh also done some entries at his side its working fine.

**Comment by Amar-3KT** [comment]
As per Mr. Suresh request we are closing this issue as of now. He is also not facing any issue in this month.
CC @audhi3k
