### ISSUE TITLE
Training on BC- Elegrow

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#432]

**Comment by niranjand22** [comment]
I have connected and explain each field in each sheet to Mr jigneshon master data template..they will fill data and share to us

**Comment by niranjand22** [comment]
Day 1- Topic Cpverd
Overview of Setup Done-
<html>
<body>
<span><span class="ui-provider gs b c d e f g h i j k l m n o p q r s t u v w x y z ab ac ae af ag ah ai aj ak" dir="ltr">

Create Company
--
Run Tax Engine
Create Accounting Period
Fill Company Information
GST Reg No.
Update States
GST Group
GST Rates
GST Setup
Assessee Code
TDS Section
TDS Rates
Country




  Customer
  Vendor
  Bank
  Fixed Asset

</span></span>
</body>
</html>

</span></span>
</body>
</html>

**Comment by niranjand22** [comment]
will resume this parrallel when itegration process will start

**Comment by niranjand22** [comment]
sales and purchase process done. for FA module client has asked to hold beaofre sharing all the time records on rlegrow

**Comment by audhi3k** [comment]
Dropped so closed
