### ISSUE TITLE
RTB and CRTB not respond back to LCMS because of error - Invoices

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#435]
Error - 

The length of the string is 19, but it must be less than or equal to 10 characters. Value: 49.7699999999999999

**Comment by TabrejAlam3K** [comment]
Mr. @panduc - Please resolved it we need to close it before 3:00PM today.

![Image](https://github.com/3ktech/General/assets/116171982/9d6d2bbe-5e5b-4226-9b9d-38e2666e6af4)

CC : @audhi3k @Shasthara @narayana3kt

**Comment by panduc** [comment]
Identified the issue in Page Extension 50017. applied the fix.

**Comment by panduc** [comment]
@TabrejAlam3K  as discussed the solution has been deployed in Production. Please communicate to user.

**Comment by TabrejAlam3K** [comment]
Yes now the error gone and invoice get auto downloaded without any error.
