### ISSUE TITLE
Credit Note Design-Chavans

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#436]

**Comment by niranjand22** [comment]
[Credit Note.docx](https://github.com/3ktech/General/files/11550336/Credit.Note.docx)

**Comment by niranjand22** [comment]
In Sales Credit Memo Page They need option for preview post this credit note prinout.

SCM>Posting>Print>Preview Post>  Credint Not should be visible.
In Posted SCM Page > Posting > Print> Preview Post> Credint Not should be visible

**Comment by Amar-3KT** [comment]
[Credit.Note (1).xlsx](https://github.com/3ktech/General/files/12047453/Credit.Note.1.xlsx)

**Comment by Amar-3KT** [comment]
@sruthi1017 Please find the attachment file of Credit Note Field mapping

**Comment by niranjand22** [comment]
Hi Amar , Ihad call with Jagan..

We need to create manualy field with caption =refrence No  in Sales Credit memo page and posted sales credit memo page and map it in report .

 @Amar-3KT

**Comment by niranjand22** [comment]
Had uat.. with Jagan..please align fiels in report @sruthi1017

**Comment by audhi3k** [comment]
Deployed in LIVE
