### ISSUE TITLE
Debit Note Design -Chavans

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#437]

**Comment by niranjand22** [comment]
[Debit Note.docx](https://github.com/3ktech/General/files/11550359/Debit.Note.docx)

**Comment by niranjand22** [comment]
In Purchase  Credit Memo Page They need option for preview post this debit note prinout.

PCM>Posting>Print>Preview Post> Debit  Note should be visible.
In Posted PCM Page > Posting > Print> Preview Post> debit  Note  should be visible

**Comment by niranjand22** [comment]
[Debit Note Mappings.xlsx](https://github.com/3ktech/General/files/12046414/Debit.Note.Mappings.xlsx)

**Comment by niranjand22** [comment]
Had uat.. with Jagan..pls align the mention fields in report..discussed uver call @sruthi1017

**Comment by audhi3k** [comment]
Deployed in LIVE
