### ISSUE TITLE
Posted Purchase Invoice Report

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#438]

**Comment by niranjand22** [comment]
[Posted Purchase Invoices.xlsx](https://github.com/3ktech/General/files/11561111/Posted.Purchase.Invoices.xlsx)

**Comment by Amar-3KT** [comment]
@sruthi1017 
As discussed, Kindly check following fields in posted sales/Purchase reports: -
1) Taxable value
2) Tax Rate
3) SGST, CGST and IGST amount
4) Payment Staus

**Comment by niranjand22** [comment]
Had uat.. with Jagan..confirm for deploy @sruthi1017

**Comment by audhi3k** [comment]
Deployed in LIVE
