### ISSUE TITLE
Trial Balance report- Total Amount not showing on Live, In UAT its showing- Please check extensions.

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#439]

**Comment by Amar-3KT** [comment]
Hi @Mahesh3ktech Please look into this issue.
Report ID- 6

**Comment by Mahesh3ktech** [comment]
Hi @Amar-3KT, changes has been done, total amount is reflecting.
kindly check and update.

**Comment by Amar-3KT** [comment]
@Mahesh3ktech Total amount not showing... please check


![Image](https://github.com/3ktech/General/assets/111888825/36115afc-2df0-40b7-9be1-b128a3908dd2)

**Comment by Amar-3KT** [comment]
Its working fine
