### ISSUE TITLE
Finance Report - Memo Raised Aa On(Excel) ID - 50067

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#44]
I have run same report in NAV 16 with date filter 01.01.22..16.01.23
but report output is different in BC from NAV.

See the attachment in BC Report is showing output value blank

![Image](https://user-images.githubusercontent.com/116171982/212662970-56556982-e253-40c2-a98b-577aae0c968a.png)

**Comment by panduc** [comment]
@TabrejAlam3K The empty page issues has been resolve. Please check and confirm.

**Comment by TabrejAlam3K** [comment]
Done

[50067 (2).pdf](https://github.com/3ktech/General/files/10442052/50067.2.pdf)
