### ISSUE TITLE
Voucher Register Cust- Amount in words issue-Please take total amount field

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#443]

**Comment by Amar-3KT** [comment]
For reference run report with 100DBBP222339 document no

**Comment by sruthi1017** [comment]
Hi @Amar-3KT changes has been done in the report, test whether it is working fine

**Comment by Amar-3KT** [comment]
@sruthi1017 Still same issue. Kindly check

![Image](https://github.com/3ktech/General/assets/111888825/500dd4b4-2bb6-42ff-9b7a-4d33b67eef0d)

**Comment by sruthi1017** [comment]
hi @Amar-3KT i updated the changes in the sandbox of UAT-Fichtner, can u check if t is ok we will move it to the production

**Comment by panduc** [comment]
@Amar-3KT the fix is available at Sandbox. Please check and provide the feedback to Sruthi.

**Comment by Amar-3KT** [comment]
Fichtner team need to confirm on UAT

**Comment by audhi3k** [comment]
Mr @Amar-3KT  can you update the status

**Comment by Amar-3KT** [comment]
As discussed today evening with Mr. Murali, 1st need to resolve interdivision issue in bank receipt and cash payment voucher. after this need to work other issues

**Comment by Amar-3KT** [comment]
Amount in word working fine.
