### ISSUE TITLE
Error on posting purchase order due to multipayment customization

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#444]

**Comment by Amar-3KT** [comment]
![Image](https://github.com/3ktech/General/assets/111888825/5434a6f0-36a9-4776-91c1-b2fac75aa51b)

**Comment by sandhya3k** [comment]
@Amar-3KT 

Please test on Fervid Copy Environment?

**Comment by Amar-3KT** [comment]
Now not getting error...
