### ISSUE TITLE
Finance Report - Daily Collection ID - 50066

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#45]
Facing error when try to run the report in BC

![Image](https://user-images.githubusercontent.com/116171982/212667035-3cfa9013-ceee-4560-9562-e486086af69d.png)

**Comment by panduc** [comment]
@TabrejAlam3K  . I've tested in UAT LKS company and filter Posting Date : 01012022..01302022 (MMDDYYYY)

Please test it again.

**Comment by TabrejAlam3K** [comment]
Done

[50066.pdf](https://github.com/3ktech/General/files/10442087/50066.pdf)
