### ISSUE TITLE
amend the VAT Number quoted at the foot of the HOLYROOD COMMUNICATIONS LTD sales invoice template in the TP instance of BC to GB432546309

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#452]

**Comment by Shasthara** [comment]
please amend the VAT Number quoted at the foot of the HOLYROOD COMMUNICATIONS LTD sales invoice template in the TP instance of BC to GB432546309, thanks

 

![Image](https://github.com/3ktech/General/assets/117992956/4440ab00-2a87-4e9c-8385-a3d7f4ad6ee5)



 

Please note that this amendment should only take place in the HOLYROOD company in the TP instance of BC, thanks.

**Comment by Shasthara** [comment]
@sandhya3k -- Give full priority to this task, check with Karthik D for more information. 

cc: @audhi3k , @3ktech

**Comment by sandhya3k** [comment]
@Amar-3KT 

please check the 50100 report id which is pos sal inv?
i deployed in production

cc: @3ktech  @Shasthara  @audhi3k

**Comment by Amar-3KT** [comment]
THis issue resolved.
