### ISSUE TITLE
Posted Purchase Memo customization 

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#454]
1.	Company “registration” need to change as a Company GST registration
2.	“Excise amount” no need to come 
3.	Tax and Total column should be below format 
 
4.	Rate of GST is  not available

**Comment by niranjand22** [comment]
[Posted Purchase Credit Memo.pdf](https://github.com/3ktech/General/files/11571468/Posted.Purchase.Credit.Memo.pdf)

**Comment by niranjand22** [comment]
Mr Amar, Please do field mapping for this. You can take reference of Posted sales invoice  report for field mapping

**Comment by 3ktech** [comment]
@niranjand22 , i am changing the status to New. Please all requred details like field mapping and then change it to Todo so that it can be taken for development. I am assigning this to @sruthi1017

**Comment by sruthi1017** [comment]
hi @niranjand22 update once the field mapping is done 
CC : @3ktech

**Comment by 3ktech** [comment]
@Manoj01021999 , save as the sales credeitmemo report and change the data item as Purchase credit memo and go on from there.

**Comment by Manoj01021999** [comment]
@niranjand22 update once the field mapping is done
and confirm once it is able to access the pioneer

cc: @3ktech

**Comment by Manoj01021999** [comment]
@niranjand22 as per teams confirmation
update me once u r available

c: @3ktech @audhi3k

**Comment by 3ktech** [comment]
hi @audhi3k , i had a discussion with @niranjand22 about this task and understood that you are going to do this task. could you please confirm this?

**Comment by audhi3k** [comment]
Mr Karthik @3ktech , you can align Tech resource

**Comment by 3ktech** [comment]
@sruthi1017 , once the posted sales creditmemo is done, save the report as posted purch creditmemo and change the dataitems for purchase module.

**Comment by TabrejAlam3K** [comment]
Mr. @Prakash3K - Connect with technical and update the comment.

CC : @audhi3k

**Comment by Prakash3K** [comment]
@audhi3k- Sruthi K started working on it.

CC: @sruthi1017

**Comment by 3ktech** [comment]
the server was not available on Friday to take this up. hence this task has been planed for today @Prakash3K  and @TabrejAlam3K

**Comment by sruthi1017** [comment]
hi @Prakash3K as we discussed can you provide me the field mapping

**Comment by sruthi1017** [comment]
hi @Prakash3K as we discussed i designed the layout can u please provide me the format and field mapping for address and gst calculation so that i can do the further development
CC: @3ktech

**Comment by sruthi1017** [comment]
tried by commenting code for sales shipment buffer and modified the report as per the purchase module but it is not working the report it self is not printing with this method

**Comment by Manoj01021999** [comment]
@Prakash3K 
Report is ready and is there any modifications let me know 
CC: @3ktech @audhi3k

**Comment by Prakash3K** [comment]
@Manoj01021999 
Total values are not coming correctly.

CC: @audhi3k @3ktech

**Comment by audhi3k** [comment]
Mr @Manoj01021999 what's the due date for this task

CC: @3ktech

**Comment by Prakash3K** [comment]
@Manoj01021999  What is the status of this ticket.

**Comment by Manoj01021999** [comment]
@Prakash3K 
Report is ready 
cc: @audhi3k @3ktech

**Comment by audhi3k** [comment]
Mr @Prakash3K , kindly test the report do the UAT with the client

**Comment by Prakash3K** [comment]
Hi @Manoj01021999 GST No. is not coming.

CC: @audhi3k

**Comment by Prakash3K** [comment]
@Manoj01021999 Kindly deploy in production environment


CC: @audhi3k @3ktech

**Comment by Prakash3K** [comment]
Client confirmed to closure.

@audhi3k @Tushargupta3K
