### ISSUE TITLE
Posted Service Memo Custumization CAS-01256-X8P6Z0

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#455]

**Comment by niranjand22** [comment]
[Posted Service Credit Memo.pdf](https://github.com/3ktech/General/files/11571475/Posted.Service.Credit.Memo.pdf)

**Comment by niranjand22** [comment]
1.	Company “registration” need to change as a Company GST registration
2.	“Excise amount” no need to come 
3.	Tax and Total column should be below format 
 
4.	Rate of GST is  not available (they need cgst sgst igst ) in report similar like sales invoice

**Comment by audhi3k** [comment]
The report is customized and available in Posted Credit Memo page => Print button.  Kindly check and get the confirmation from the client

**Comment by niranjand22** [comment]
I have checked and asked client to confirm

**Comment by niranjand22** [comment]
client confimed to deploy in live and proceed for sales and purchase posted credit memos

**Comment by niranjand22** [comment]
ayyapan confrim over team for closure.

cc @audhi3k
