### ISSUE TITLE
PDC against Purchase order/Sales Order

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#458]

**Comment by sandhya3k** [comment]
Vendor part design is completed.

**Comment by Ejaz3KT** [comment]
Ok @sandhya3k Madam I`ll test and update you

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

please test on dev_sandbox

**Comment by sandhya3k** [comment]
@Ejaz3KT 

I hope, u understand the functionality. please test accordingly and let me know if any quiries

**Comment by Ejaz3KT** [comment]
@sandhya3k Madam Yes I`ve understand the functionality and I am started testing the PDC process if any queries are there I`ll inform you

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
1. When we are cancel or get any minor error the PDC document is automatically moves to PDC archive list.
2. In vendor archive document list should show vendor related PDC document only and In customer archive document list should show customer related PDC document should reflect.
3. Without posting the first advance line the user should not post second advance line.
4. After posting the document the check box in the payment schedule list get YES.

CC: @sandhya3k @audhi3k @3ktech

**Comment by Ejaz3KT** [comment]
1. When we cancel the PDC process or get any error, the PDC vendor/customer document automatically moves to the vendor document.
2. In vendor archive PDC list should show only vendor PDC documents only and customer archive PDC list should show customer PDC document only.
3. After posting only the checkbox get true in payment schedule list 

CC: @audhi3k @sandhya3k @3ktech

**Comment by Ejaz3KT** [comment]
![Image](https://github.com/3ktech/General/assets/125632927/41d535df-6ce4-47fd-ab5e-e67f85d6d5e3)

Ms. @sandhya3k the field which I mark in that field the amount is not calculating properly please check and resolve the issue

CC: @audhi3k @3ktech

**Comment by sandhya3k** [comment]
@Ejaz3KT 

Please test on sandbox environment

cc : @audhi3k

**Comment by Ejaz3KT** [comment]
@sandhya3k I`ve tested the PDC process I find this issues
1. The amount is not deducting properly (not showing remaining amount properly)
2. After posting the PDC system allowing us to post again the PDC with same Check No.

CC: @audhi3k
