### ISSUE TITLE
Delivery terms and payment terms should reflect in approval entries page and request to approve page

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#459]

**Comment by Manoj01021999** [comment]
@Ejaz3KT 
it is working fine kindly check in UAT
cc. @audhi3k  @3ktech

**Comment by audhi3k** [comment]
Completed, and showed to the client and waiting for confirmation to close

**Comment by Ejaz3KT** [comment]
client has confirmed we can close this ticket

CC: @audhi3k
