### ISSUE TITLE
Finance Report - Collection As On ID - 50069

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#46]
I have run same report in NAV 16 with date filter 01.01.22..16.01.23
but report output is different in BC from NAV.

See the attachment in BC Report is showing output value blank

![Image](https://user-images.githubusercontent.com/116171982/212671641-67836f10-4391-4e9d-8163-8f5d55d6f268.png)

**Comment by panduc** [comment]
@TabrejAlam3K  Empty page issue has been resolved. Please do check and confirm.

**Comment by TabrejAlam3K** [comment]
Not match with NAV 16 Report output data

I have put the same date filter - 01.01.2022..01.30.2022 - in NAV16 working fine

[50069.pdf](https://github.com/3ktech/General/files/10442191/50069.pdf)

**Comment by 3ktech** [comment]
@panduc , can you share more information with @sandhya3k to let her carry on with this task.

**Comment by TabrejAlam3K** [comment]
@sandhya3k I have shown to what is changes between NAV16 to BC Report. Please update it here once it will done.

**Comment by TabrejAlam3K** [comment]
Done - Now the location wise data is coming
In previous record location data is not available so it's not coming in previous records.

[50069 (2).pdf](https://github.com/3ktech/General/files/10486543/50069.2.pdf)
