### ISSUE TITLE
Enhancement in Indent Process

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#463]

**Comment by audhi3k** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Page | Requirement | Priority
-- | -- | --
Page 1 | Vendor   No. to be removed from the line page | 1
  | Quantity   available to be updated on selection of Item no. (Now it is updating when we   move to second line) | 13
  | Quantity   available field => additional filter to be applied 1. Remaining quanity   >0, 2. Global Dimension 1 and 3. Global Dimension 2 (Value from Respective   header for point 2 and 3) | 2
Page 2 | Vendor   No. to be removed from the line page | 3
  | Reopen   functional to added, wherein when status to be updated as <blank> | 5
  | Field   Amount should be non-editable | 4
Page 3 | Add   2 fields to be added 1. Vendor 2 and 2. Vendor 3 (Both are with lookup to   Vendor list i.e., Similar to Vendor) | 6
  | Validation   1 for these 2 fields,      to update Vendor 2 => Vendor should not be blank     to update Vendor 3 => Vendor 2 should not be blank | 7
  | Validation   2 for these 2 fields,      to update Vendor 2 => if same value is update in Vendor should pop   error     to update Vendor 3 => if same value is update in Vendor 1 or Vendor2   should pop error | 8
  | Purchase   Type, change the caption of the option from Contract to Quote | 9
  | If   the Purchase Type is Quote => Vendor 2 and Vendor 3 should be editable | 10
  | Create   Purchase Document => Purchase header to be created with document Type   => Purchase Type | 11
  | If   purchase Type is Quote => if the vendor 3 is filled 3 document to be   created, if vendor 3 is not filled and vendor 2 is filled 2 document to be   created, if only vendor is filled 1 document to be created | 12



</body>

</html>

**Comment by Shasthara** [comment]
Point no 13: Add variant code in requisition lines/Issue and indent lines

**Comment by Amar-3KT** [comment]
Page 1-Requisition (50140, Document)--- Requisition list

Page 2-Requisition Lists (50106, List)----Issue and Indent Slip List

Page 3 - Requisition Purchase Process (50107, List)---Indent Purchase action

@sandhya3k For your reference

**Comment by Mahesh3ktech** [comment]
Hi @Amarjeet, All the above points completed, except multiple orders or quotes should create based on quantity.

**Comment by Amar-3KT** [comment]
@Mahesh3ktech  Pending points:-
1) Quantity available to be updated on selection of Item no. (Now it is updating when we move to second line)
2) Reopen functional to added, wherein when status to be updated as- After reopen not able to edit requisition.
3)Create Purchase Document => Purchase header to be created with document Type => Purchase Type

**Comment by Mahesh3ktech** [comment]
hi @Amar-3KT, Above points 1 and 2 is completed. 3rd point debugging the issue to identify the cause to correct.

**Comment by Amar-3KT** [comment]
In 3rd point having filter issue.

**Comment by Mahesh3ktech** [comment]
hi @Amar-3KT, 3rd point issue is cleared, kindly check and update.

**Comment by Amar-3KT** [comment]
We are getting some error on Purchase action page.
For purchase invoice taking Quote no series

**Comment by Amar-3KT** [comment]
@Mahesh3ktech  its working fine can you move it to sandbox

**Comment by Mahesh3ktech** [comment]
hi @Amar-3KT, I have moved changes to sandbox environment. can you check and confirm.

**Comment by audhi3k** [comment]
Image
I am Facing this error while converting the requisition document to purchase document.

**Comment by audhi3k** [comment]
1.Requisition Sub form

a)Shortcut Dimension 1 and Shortcut Dimension 2 should rename with Branch and Department.

b)Quantity should be without decimal, currently it is coming till four decimal.

2.Issue and Indent Slip

 a)Quantity to Purchase should be without decimal currently it is coming till four decimal. 

 b)If I put the value in Quantity to Purchase Amount should be changed based on this. (Quantity to Purchase * Price = Amount). 
3.Indent Purchase Action

 a)Amount is coming wrongly, it should be (Quantity * Price = Amount). 
Purchase Quote: -

Request Receipt Date = Indent Required Date

Requisition No. = Indent Requisition No.

CC: @audhi3k @TabrejAlam3K

**Comment by audhi3k** [comment]
#540

**Comment by Mahesh3ktech** [comment]
hi @audhi3k, @TabrejAlam3K, Above points are completed, kindly check.

**Comment by Amar-3KT** [comment]
Material Indent

Requisition List
1)When we updating dimension after taking line then on line qty available not updating, dimension line also not updating

Indent Purchase Action 
1) When we taken vend1, vend2, vend3, -then i am able to remove vend 2(vend1 and vend 3 we can take now)
there should be validation 1st remove vend3 
2) Dimension not updating on purchase action(Purchase order, Quote, invoice)

Purchase Quote
1) purchase quote req no and date not updating in header(Boolean true in Purchase & payable setup)
2) Hide posting date in purchase quote list page and enable document date and  request receipt date-Please update on all environment

**Comment by Amar-3KT** [comment]
.

**Comment by 3ktech** [comment]
@Ejaz3KT , the development is done. to test a full iteration by developer, we need to have some data in the sandbox. can you please help @sandhya3k  to have test data to deliver this task?
@audhi3k

**Comment by Ejaz3KT** [comment]
Ok

**Comment by sandhya3k** [comment]
@Ejaz3KT 

Please test on indent process, It is available in sandbox and dev_sandbox environments

cc : @audhi3k , @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - It is working fine i have tested it on Indent Requisition No. **FSS-REQ/23-24/046** 

Scenario Tested - I have taken 4 line items and for every line item i have selected 3 vendors.

Got Result - 3 Quotes get created with 4 line items.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
As per the UAT with the client they confirmed for closure.

CC : @audhi3k
