### ISSUE TITLE
Vendor Dimension should be auto Created while creating a Vendor Master

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#468]

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - As per our screen sharing session it is working fine in NAV16.

Requirement - While Creating a new vendor record it should get auto created Dimension Value under the Dimension Code **Vendor**
Dimension Code - Vendor
Dimension Value Code - Vendor No.
Name - Vendor Name

CC : @audhi3k @narayana3kt

**Comment by panduc** [comment]
@TabrejAlam3K I've fixed this issue and deployed the changes in UAT environment. Please test and confirm.

CC : @audhi3k @narayana3kt

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - Only Name is coming code is not coming as blank, I have created one new vendor as Tabrej Alam and their Vendor Code is V01921 but in Dimension it is coming as blank.


![Image](https://github.com/3ktech/General/assets/116171982/ebb4a2ba-0d72-4f1d-9cd9-93232801a2ae)

**Comment by panduc** [comment]
Hi @TabrejAlam3K  the issue has been fixed. tested it is working fine. Please check in UAT and confirm so we can move to Production

**Comment by panduc** [comment]
Tabrej tested and confirmed. moved the solution to production.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - Client confirmed it is working fine in Production, One small changes required.
