### ISSUE TITLE
Finance Report - Collection Detailed Report ID - 50071

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#47]
Found error when try to run the report in BC

![Image](https://user-images.githubusercontent.com/116171982/212673404-09b15a87-2801-4d9c-a06b-45628712dda2.png)

**Comment by panduc** [comment]
@TabrejAlam3K  Modified the changes.

Tested with filter. Posting Date: 01012022..02022022 (MMDDYYYY). Attached the sample output.

**Comment by panduc** [comment]
[Collection Detailed Report_Output.pdf](https://github.com/3ktech/General/files/10430818/Collection.Detailed.Report_Output.pdf)

**Comment by TabrejAlam3K** [comment]
Done

[50071.pdf](https://github.com/3ktech/General/files/10442247/50071.pdf)
