### ISSUE TITLE
PDC entry in single line

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#471]

**Comment by audhi3k** [comment]
Need to discuss with client to understand the requirement

**Comment by 3ktech** [comment]
Please share more details about this issue for the resolution

**Comment by audhi3k** [comment]
The financial entry will be double entry only

**Comment by TabrejAlam3K** [comment]
Hi Mam I am closing this ticket it is pending since long. In future we will create a new ticket if having any issues.

CC : @audhi3k
