### ISSUE TITLE
Amount auto deduction in PDC

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#473]

**Comment by sandhya3k** [comment]
@Ejaz3KT 
please test in sandbox  env

@audhi3k

**Comment by Ejaz3KT** [comment]
@sandhya3k Madam the auto amount deduction is not working properly please check.

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

I hope it is working please update

cc : @audhi3k

**Comment by Ejaz3KT** [comment]
@sandhya3k Madam I`ve tested these amount auto deduction in PDC process is working fine.

CC: @audhi3k
