### ISSUE TITLE
Page Alignment with respect VAT and other field which are not required

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#477]

**Comment by 3ktech** [comment]
@Ejaz3KT , can you add more values to the requirement to take this up for development

**Comment by audhi3k** [comment]
@Ejaz3KT, kindly update the details

**Comment by Ejaz3KT** [comment]
VAT notification popup should be removed from

**Comment by Manoj01021999** [comment]
@Ejaz3KT 
there is a missing in the setup it is clear for another sandbox kindly check it

**Comment by audhi3k** [comment]
Enable through setup
