### ISSUE TITLE
Bank Payment Voucher-Issues

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#48]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/DELL/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/DELL/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Issue   Description | Tested By | Testing Date | Comments | Status
-- | -- | -- | -- | --
Bank payment voucher and bank   receipt voucher-Button "Import Salary" not vailable | Amarjeet Singh | 12-01-2023 | In nav 2016 Navigate Menu button available but in Bc not   available | Completed
Bank payment voucher-Report   "HDFC ChECK MULTI LINE" not vailable(Check printing new 50031) | Amarjeet Singh | 12-01-2023 | In nav 2016 Navigate Menu Report available but in Bc not   available | Completed

</body>

</html>

**Comment by panduc** [comment]
@Amar-3KT  The above mentioned points are done. Please check and confirm.

**Comment by audhi3k** [comment]
Done
