### ISSUE TITLE
Purchase report alignment

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#488]

**Comment by audhi3k** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Changes in Purchase   order report
--
1. Company Name Font to be   increased,
2. GST Registration No. and PAN No. to be   included,
3. State to included in the address,
4 GST Amount Breakup and Amounts



</body>

</html>

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K, reports changes are done, kindly test and confirm.

**Comment by TabrejAlam3K** [comment]
Attached file is the final PO Report

[Fervid PO Report Final.pdf](https://github.com/3ktech/General/files/11631711/Fervid.PO.Report.Final.pdf)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Ejaz3KT - Please forward this to the client for testing.


[Purchase Order Final.pdf](https://github.com/3ktech/General/files/11632309/Purchase.Order.Final.pdf)


CC : @audhi3k

**Comment by Ejaz3KT** [comment]
Hi Mr. @Mahesh3ktech Need to adjust the GAP so the GST No. should be visible in the PO report, See the bill to side the GST No. is not properly printing Please make the changes in the PO report.

CC: @audhi3k @TabrejAlam3K 

![Image](https://github.com/3ktech/General/assets/125632927/afdf59b4-b823-4b5f-bdc0-11aa6e68efbb)

**Comment by Ejaz3KT** [comment]
![Image](https://github.com/3ktech/General/assets/125632927/f4d5cf46-402e-4276-80e7-4cc7a89b2962)

Hi @Mahesh3ktech the amount in words is not calculating properly please resolve this issue ASAP

CC: @audhi3k @TabrejAlam3K

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Correction required on purchase order reports.

**Comment by audhi3k** [comment]
@sandhya3k  publish in Sandbox

**Comment by sandhya3k** [comment]
@audhi3k
I published in sandbox please check

**Comment by audhi3k** [comment]
Working fine

**Comment by sandhya3k** [comment]
@Ejaz3KT 
please test on sandbox env

**Comment by Ejaz3KT** [comment]
@sandhya3k Swift code is not printing in purchase order report

![Image](https://github.com/3ktech/General/assets/125632927/795edb49-2240-4e7f-8013-e96ccdf56a3e)

@audhi3k @TabrejAlam3K

**Comment by Ejaz3KT** [comment]
Final output of purchase order report 

[Purchase order report Final output.pdf](https://github.com/3ktech/General/files/11718306/Purchase.order.report.Final.output.pdf)

@audhi3k @TabrejAlam3K

**Comment by Ejaz3KT** [comment]
I`ve showcase the purchase order report to Ms. Jhansi she said ok it is fine

**Comment by TabrejAlam3K** [comment]
Mr. @Ejaz3KT have showcase with the client, now waiting their confirmation.

**Comment by audhi3k** [comment]
Confirmed by client
