### ISSUE TITLE
Bank Receipt Voucher-Issues

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#49]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/DELL/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/DELL/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Issue   Description | Tested By | Testing Date | Comments | Status
-- | -- | -- | -- | --
Bank Receipt Voucher- In   "Collection No" field drop down list not available | Amarjeet Singh | 06-01-2023 | In Nav 2016 working fine | Completed
Bank rcpt voucher-Button   "Get Open posted line for TCS on Payment calculation" not vailable | Amarjeet Singh | 12-01-2023 | In nav 2016 action Menu button available but in Bc not   available | Completed

</body>

</html>

**Comment by panduc** [comment]
@Amar-3KT  Completed the mentioned points. Please check and confirm.

![Image](https://user-images.githubusercontent.com/110709312/212981137-f3b1ff41-5002-4dcc-be37-b217c51e2257.PNG)

**Comment by audhi3k** [comment]
done
