### ISSUE TITLE
Due statement Email delivery from BC:CAS-01259-B6F2K4

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#492]
Hi Team, 

We would like customize the AR due statement dispatch from BC as like invoice dispatch. Kindly raise ticket on this and help us on this matter at the earliest. 

Regards
Boo

**Comment by TabrejAlam3K** [comment]
I have done the discussion with the client on.

Requirement - Button required on Customer card called **Email Due Statement** and the Setup required just like a base Email Button.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Below Mail Body Requested by the Client.

Dear Sir/Madam,  
 

Hope this email finds you well. Please find attached the due statement as of today. We are bringing to your attention that amount of GBP XXX is due. On that GBP XXX is overdue and which needs immediate settlement. Please get back to us with the payment date for these dues.  


-If you have any questions on this invoice, don’t hesitate to address it immediately to 
accountsuk@meritgroup.co.uk or boopathy.dakshinamurthy@merigroup.co.uk. We will get back to you shortly.  


-Please quote your Customer Account Number & Invoice Number when making payment. Else please make sure to deliver the Remittance advice to above mentioned email id before the payment. 


-Default or delay in making payments according to agreed terms may result in late payment fees.  

Yours sincerely, 

   

Thank you  

Kind Regards,  

Finance – Merit Data & Technology Limited  

accountsuk@meritgroup.co.uk  

   

Merit Data & Technology Limited | 11th Floor, The Shard | 32 London Bridge Street | London | SE1 9SG | 
http://www.meritgroup.co.uk/

**Comment by Shasthara** [comment]
@TabrejAlam3K Please explain this issue to Karthik D

**Comment by TabrejAlam3K** [comment]
Hi Mr. Kartik D @3ktech - Please take this task and close it. I have already informed to you and share the git ticket also.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
Hi Mr. Kartik D @3ktech - Approval Received from the client side. I need to deliver this till 14th June 2023. Please help us on high priority.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. Kartik D @3ktech - Please update the status of the issue.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 
can we connect for this?

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - As per our discussion please update the status of the points.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - As per our discussion once you complete the development please let me know.

Report need to be attached inside the mail - **Standard Statement (1316, Report Request)**

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - What is current updates on please leave your comments here.

CC : @audhi3k

**Comment by panduc** [comment]
Hi @TabrejAlam3K  basic porotype is ready. tested. I'm incorporating the remaining development.

CC : @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K completed the development and did the unit testing.

Step1: 


![Image](https://github.com/3ktech/General/assets/110709312/02976d2f-b6cd-464d-8fe4-813fb528ff8e)


Step2:


![Image](https://github.com/3ktech/General/assets/110709312/40b9c29a-7bf5-4399-bf58-3fe037831afa)



Steps3: Output


![Image](https://github.com/3ktech/General/assets/110709312/bfdb10f8-f273-4039-91ee-bd78c3152429)


As discussed I need basic information to run the report start and End Date and default to Email id. Let's discuss tomorrow and finalize the solution.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - Where you have done the development i am not able to see anything in Merit UK Tenant Sandbox.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - I have tested it in LKS UAT as per the requirement it is working fine let me check with the client


![Image](https://github.com/3ktech/General/assets/116171982/afee0661-e77a-486e-b000-900bf4b27301)


Please move this changes for Merit Sandbox Environment (UK Tenant).

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - As per the our discussion today please deployed it on Merit UAT/Production (UK Tenant) today.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Mr. @panduc  first you need to move the development what every you have done, They want to see what you have done.

Please move the changes into the Merit Sandbox Environment.

 To Mail ID - It should be Customer Email ID.
Date filter should be - till Date of current financial years (Customer Ledger Entries)

CC : @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K  we have deployed in UATProd. 

modified the above mentioned change of Email ID and date filter for report.

URL: https://businesscentral.dynamics.com/3df22445-c4a8-4414-87c2-c7c8abfbba5c/UATProd_20032023?company=Political%20Engagement%20Limited&node=0000233e-438d-0000-0c28-4f00836bd2d2&page=22&dc=0&bookmark=21_EgAAAAJ7_0MARQAtAEQAUAAxADAAMAAwADAAMQ

Customer List:


![Image](https://github.com/3ktech/General/assets/110709312/b89f5663-9dbd-4884-9689-0433bdea65ea)


Customer Card:


![Image](https://github.com/3ktech/General/assets/110709312/87bb7735-d21e-4188-b5cf-e3cba10620c5)


Next Action: Please ask user to configure Email accounts setup in UAT and test it. Already we assisted to configure in LIVE.

Dods.Dynamimcs has limited permission.

CC : @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K I've configured with 3ktechnologies@dodsgroup.com in company "Dods Group Limited" of environment UATProd_20032023

Email is sending with attached. Please test the customer has balance/transaction.

**Comment by TabrejAlam3K** [comment]
Ok Mr. @panduc - Let me check with the client and informed you.

**Comment by TabrejAlam3K** [comment]
I have tested and forwarded to the client.

**Comment by audhi3k** [comment]
Mr @TabrejAlam3K, can you update the status

**Comment by TabrejAlam3K** [comment]
Mr. @panduc - Changes has been removed form the below Environment.

![Image](https://github.com/3ktech/General/assets/116171982/05692c6c-90bf-433f-a33f-ffd345644a0b)

CC : @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K we do not have GIT source controller. someone would be published without my source code. who is currently working on?

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - As per our last discussion on Friday you need to Re-Deploy the Changes in Merit Sandbox, Have you done the activity. Changes it is not yet visible on the Merit Sandbox

CC : @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K the solution is enabled back. configured with [3ktechnologies@dodsgroup.com](mailto:3ktechnologies@dodsgroup.com) in company "Dods Group Limited" of environment UATProd_20032023

Email is sending with attached. Please test the customer has balance/transaction.

CC : @audhi3k

**Comment by panduc** [comment]
The option is available @
Customer Card --> Process --> "Email Due Statement"
Customer List --> Process --> "Email Due Statement"

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - Can you please setup the below reports for the Mail Attachment.

Report ID - **Standard Statement (1316, Report Request)**

CC : @audhi3k

**Comment by panduc** [comment]
Hi @TabrejAlam3K  the report is already enabled. Please test the customer which has a balance. 

I've been mentioning this as disclaimer in all updates :)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - I have tested the entries but It is not coming correctly in the report output. Can you please check the filter what you are applying.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - Please marked the below point before triggering the Mail. The field validation should be below.

Start Date - **From the first entries date**
End Date - **Current Date**
Show Overdue Entries - **True**
Aging Band Period Length - **1M+CM**
Aging Band by - **Due Date**
Log Interaction - **True**

**Request - Please close this today**

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Shared the Snapshot on teams group

**Comment by panduc** [comment]
@TabrejAlam3K the new changes has been deployed to UATProd_20032023. Please check and Confirm.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - Body Email Format should be as per the below snapshot.

![Image](https://github.com/3ktech/General/assets/116171982/6f91fcd3-8ae5-4c93-9c01-01e7a30fadbc)

**Comment by panduc** [comment]
@TabrejAlam3K Changes 1. remove empty rows between Signature part 2. try to enable hyperlink for Email 3. change the color for Currency. the changes are deployed. Please check and confirm.

**Comment by TabrejAlam3K** [comment]
Tested and forwarded to the client for UAT, still waiting their response.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - Client confirmed the process of Due Email Statement is working fine - **Please move this into the Production.**

![Image](https://github.com/3ktech/General/assets/116171982/5ec2d354-299b-4788-a5f1-e71c5dbf4c22)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Mr. @panduc - Can you please deployed it today, Client is asking me multiple time.

CC : @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K  Uploaded the latest source code to LIVE. Please inform to customer.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Thanks Mr. @panduc - We have tested one mail in the Production Environment, It was working fine. We have already informed to the client (Mr. Boopathy).

I am going to close the ticket.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Mr. @panduc - Based on the attachment amount is not matching. Please help us to close the issues.
