### ISSUE TITLE
Check book range should be add in PDC process and PDC complete functionality

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#493]

**Comment by 3ktech** [comment]
Need to discuss on the design part of this requirement

**Comment by audhi3k** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   | Bank Account No. | Line No. | Cheque Book Starting No. | Cheque Book Ending No. | Closed |   |   |   |  
  | Last Check No. | 000048 | 001000 |   |   | B0001 | 10000 | 000001 | 000050 |   |   |   |   |  
  |   |   |   |   |   | B0001 | 20000 | 001001 | 001050 |   |   |   |   |  
  |   |   |   |   |   | B0002 | 10000 | 000001 | 000050 |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  | New table to be created with name   Cheque Book |   |   |   |   |   |   |   |   |  
  | This we can button from Bank Account   Card => Cheque Book |   |   |   |   |   |   |   |  
  | Here it should show the Bank Account No. => No.(Bank Account) |   |   |   |   |   |   |  
  | New Line Bank Account No. should be assigned from Bank Account =>   No. |   |   |   |   |   |  
  | New Line "Line No." should auto increment based on Bank   Account No. |   |   |   |   |   |   |  
  | Validations |   |   |   |   |   |   |   |   |   |   |   |  
  | 1. Cheque Book Ending No. = Last   Check No., then error "Cheque Book completed" |   |   |   |   |   |  
  | 2. Last Check No. = Cheque Book   Ending No. , then error update as closed when Bank Account No. is same |   |   |  
  | 3. Last Check No. to be updated   with Cheque Book Starting No. (minus) 1, when Closed = True with next lines   Cheque Book Starting No. (minus) 1
  |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |  



</body>

</html>

**Comment by audhi3k** [comment]
Cheque Printing for PDC: 
1. it is applicable only for Vendor PDC
2. In the Vendor PDC Header => Add new field Bank Payment Method (copy from Gen. Jounral Line)
3. If the Bank Payment Method is Computer Check, then before posting Cheque to be printed

**Comment by sandhya3k** [comment]
@Ejaz3KT 

please test on sandbox environment?

cc :  @audhi3k

**Comment by niranjand22** [comment]
@TabrejAlam3K  Please check for closure of point

**Comment by TabrejAlam3K** [comment]
We are going to close the ticket as of now if required we will create a new ticket for the same in future.

CC : @audhi3k
