### ISSUE TITLE
Holyrood sales invoice and sales credit memo templates - addresses need amending

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#495]

**Comment by Amar-3KT** [comment]
sales invoice- 50100, credit memo- 50101


there are a couple of amendments needed on the below sales invoice and sales credit memo templates in the TP instance of BC:

 

Holyrood sales invoice template and sales credit memo template - please amend the Shard address in top right corner to:

Holyrood Communications Limited
Finance Department 
North & East, 11th Floor Millbank Tower 
21-24 Millbank 
London 
SW1P 4QP

**Comment by Manoj01021999** [comment]
@Amar-3KT 
It is done and available in TP production1
kindly Test It

**Comment by Amar-3KT** [comment]
@Manoj01021999  Changes not done kindly check and confirm.

**Comment by Amar-3KT** [comment]
@Manoj01021999 Now address coming correctly.

**Comment by Amar-3KT** [comment]
Please deploy on production
