### ISSUE TITLE
Fervid team requires purchase order No. in GRN report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#501]

**Comment by 3ktech** [comment]
Add more details for the development @Ejaz3KT

**Comment by Ejaz3KT** [comment]
![Image](https://github.com/3ktech/General/assets/125632927/de5799ae-2756-444a-8a35-f0bd803e2611)

In this purchase receipt they require purchase order No.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
purchase order number is printing in the purchase receipt @sruthi1017 now you can publish this in sandbox

![Image](https://github.com/3ktech/General/assets/125632927/48499a89-3c05-4473-91ac-9fbff3d4d44d)

CC: @audhi3k @TabrejAlam3K
