### ISSUE TITLE
On General Ledger Entries - Enable the Comment, Party Type, Party Code fields.

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#503]

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - As per our discussion please update your latest comments here.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

The task has been completed please test on UAT environment and also need to enable the fields in page level

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - The Comment field is available now and it also have a value, We need to discuss with the client for Party Type and Party Code.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k  - As per our discussion please share your feedback on you have done the coding for moving the field value from Gen. Journal Line to General Ledger Entries.

Party Type and Party Code we will consider as an enhancement point (already discussed with the client).

**Comment by audhi3k** [comment]
Any update Ms @sandhya3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

I need to check the scenario from ur side

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

please test on UAT environment?

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - I have tested Comment part in UAT, It is working fine. Can you move this changes into the Production.

For : Party Type and Party Code - We will work upon once approval receive from client side.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
I have informed to the client for testing the comments parts only. the client will test and confirm.

**Comment by audhi3k** [comment]
Mr @TabrejAlam3K, kindly check whether deployed in LIVE and close this case

**Comment by sandhya3k** [comment]
![Image](https://github.com/3ktech/General/assets/114206737/177c4496-41f5-4386-bdbb-0b5e075e7c79)

I deployed in production , as discussed on the call @TabrejAlam3K  please update ur comments

cc : @TabrejAlam3K @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - When we can connect on this

**Requirement** - If I put the value in the comment field then while moving the next line previous line get auto removed, It should be still remain or save the comment value.

**User Activity** - While posting the payment if user forgot to put the comment on the payment line then system is allowing to add the comment over posted entries.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Please develop this functionality  in the Development Environment first as per the suggested by Ms. Audhi Mam.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Ms. @sandhya3k - Please let me know once the development will completed.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

i need g/l  entry permission to modify the data.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 
i got this error when iam doing the internal testing
![Image](https://github.com/3ktech/General/assets/114206737/ba2e4daa-66f9-46b3-adf6-9e4130472e55)

**Comment by TabrejAlam3K** [comment]
As per the discussion with Ms. @sandhya3k - We are not authorized to modify the GL Entries.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

can u please give me the functionality how it works?

**Comment by TabrejAlam3K** [comment]
Need to update the client it is not doable.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 
 
i changed to the status from inprogress to cust_info

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - As per our discussion it is not doable.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam, 

Comment Received by Mr. Viswanathan Sir - We were told that certain specified filed we can have modification.  Even Mr. Sravan Karthik informed as one of the improved features of BC.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam - have you discussed this point with the technical, Can you please update what is the next action point.

**Comment by audhi3k** [comment]
Mr Karthik, @3ktech as discussed yesterday can you update the feasibility and timeline for the same

**Comment by TabrejAlam3K** [comment]
Hi Mr. Karthik @3ktech - Please update your comments here, It is still pending since long.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. Kartik @3ktech - As discussed with Ms. @audhi3k Mam, can you update the feasibility and timeline for the same

CC : @Shasthara @narayana3kt

**Comment by 3ktech** [comment]
hi @TabrejAlam3K , I am assigning this to @sruthi1017 , Please connect with her

**Comment by sruthi1017** [comment]
hi @TabrejAlam3K it is completed, the changes are in development environment, can u test and confirm 
CC: @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - It is not working in the Production Environment.

CC : @3ktech @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
**Requirement** - User want to add the comments on Posted General Ledger Entries.

**Issue** - When the user put any value in the comment field while moving into the second line previous line value get auto removed. It should be still remain.

CC : @audhi3k

**Comment by sruthi1017** [comment]
hi @TabrejAlam3K the changes are available in development environment, it is not deployed into the production yet
CC: @audhi3k  @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Now the changes is available in the Development Environment.

![Image](https://github.com/3ktech/General/assets/116171982/d9dcb1cc-39f7-4989-a37b-09a830bbfbdb)

Can you move this into the UAT Environment for Unit Testing with the Client.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Working in UAT Environment also.

![Image](https://github.com/3ktech/General/assets/116171982/c74eb648-0029-4c07-b1a7-dea7689efb02)

CC : @audhi3k

**Comment by 3ktech** [comment]
hi @TabrejAlam3K , i am changing the status to UAT. Please change status to next steps.
@sruthi1017

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - I have tested it into the UAT Environment and found it is working fine.

![Image](https://github.com/3ktech/General/assets/116171982/54d7e904-2076-4e89-9c32-003010e12b67)

**Please move this changes into the Production Environment.**

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - As per our discussion please move this into the Production

CC : @sruthi1017

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k and Ms. @sruthi1017 - Why it is taking to much time to deploy in the Production.

CC : @audhi3k @3ktech @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
I have tested in the Production Environment, it is working fine. Due to non response from the client side, We are going to close the ticket as of now.

CC : @audhi3k @Shasthara
