### ISSUE TITLE
CRM-BC Integration

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#504]

**Comment by niranjand22** [comment]
Field is updated as requested by crm team..

**Comment by niranjand22** [comment]
BC team has provided the hrs..CRM team is analysing the..after client hrs confirmation we have to proceed ahead

**Comment by niranjand22** [comment]
Techanical are notavailble. Please once technical will be released this process will start

**Comment by niranjand22** [comment]
<html>
<body>
<div style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, system-ui, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Web&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px;">

Entity | API Page Entity name
-- | --
Product | crmproductliststatus
Price List | crmpricelist
Price List Item | crmpricelistitem
Unit Group | crmunitgroup
Country | crmcountrylist
City | crmcitylist
State | crmstatelist

</div>
</body>
</html>

**Comment by niranjand22** [comment]
above api is created mr murali is working on flows for field mapping

**Comment by niranjand22** [comment]
Hi @Mahesh3ktech  Please update the progress here

**Comment by Mahesh3ktech** [comment]
hi @niranjand22, status of the APIs completed as below.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

<div style='box-sizing: border-box;font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2'>



Entity | Integration Type | Status
-- | -- | --
BC   Customer | CRM to BC | Completed
BC Contact | CRM to BC | Completed
Product | BC to CRM | Completed
Price List | BC to CRM | Completed
Unit Group | BC to CRM | Completed
Price List   Item | BC to CRM | Completed
Order | CRM to BC | Need to start
Order   Product | CRM to BC | Need to start
Country | BC to CRM | Completed
City | BC to CRM | Completed
State | BC to CRM | Completed
Currency | BC to CRM | Completed



</body>

</html>

**Comment by niranjand22** [comment]
Cust, State, City, Country,Currency(discussion pending with crm team), BC contact(partially completed),Product and price list(discussion pending with crm team), price list item(discussion pending with crm team),Unit group,

**Comment by niranjand22** [comment]
Hi @Mahesh3ktech  Please update recent progress here

**Comment by niranjand22** [comment]
Hi @Mahesh3ktech  Pllease update the progress

**Comment by Mahesh3ktech** [comment]
hi @niranjand22, I have completed with all the API development. below mentioned the status.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

<div style='box-sizing: border-box;font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2'>



Entity | Integration Type | Status
-- | -- | --
BC   Customer | CRM to BC | Completed
BC Contact | CRM to BC | Completed
Product | BC to CRM | Completed
Price List | BC to CRM | Completed
Unit Group | BC to CRM | Completed
Price List   Item | BC to CRM | Completed
Order | CRM to BC | Completed
Order   Product | CRM to BC | Completed
Country | BC to CRM | Completed
City | BC to CRM | Completed
State | BC to CRM | Completed
Currency | BC to CRM | Completed



</body>

</html>

**Comment by niranjand22** [comment]
In sales header api- Currrency code and CRM order no has to be included.. @Mahesh3ktech

**Comment by Mahesh3ktech** [comment]
hi @niranjand22 - as discussed changes has been done and tested.
Updated to Murali about the changes.

CC: @3ktech, @audhi3k

**Comment by 3ktech** [comment]
@niranjand22 , if you have any additional changes to be done, please record them here.

**Comment by niranjand22** [comment]
@Mahesh3ktech .. Rename External Document No In sales Invoice and sales Order --to P.O. No. and pls deploy changes to live from sand box

**Comment by 3ktech** [comment]
@Mahesh3ktech , did you take this up?

**Comment by Mahesh3ktech** [comment]
@3ktech - yes in sales Invoice report sruthi changed external document no. to PO No. and @niranjand22 Confirmed there is no field external document no. in Sales Order no need to change.

**Comment by niranjand22** [comment]
@Mahesh3ktech  we have external doc no in sales order also same has to be changed..there also (external document no. to PO No.)

**Comment by Mahesh3ktech** [comment]
hi @niranjand22 - we have changed the field external doc no in sales order as Customer PO no. kindly check.

CC: @3ktech

**Comment by audhi3k** [comment]
Dropped so closed
