### ISSUE TITLE
Print Service Invoice to Genrate Digital SIgnature bsed on Selection whether details or without details

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#506]

**Comment by niranjand22** [comment]
Posted Service Invoivce- Print Tax gst invoice

**Comment by sandhya3k** [comment]
Please check with client and update @niranjand22

**Comment by niranjand22** [comment]
Hi @sandhya3k I connected with Client. They need same changes in Service Invoice Page.
But challange over there iis They dont have request page in service invoice. 
Once we click on post and print . Report gets printed directly.

So we can create New Field In General Tab of Service Invoice Page.
Print Detail- Option Yes/No

Based on selection it report should get printed when they click on post and print.

**Comment by sandhya3k** [comment]
@niranjand22 

For this issue i need to connect with u please let me know when ur available

**Comment by niranjand22** [comment]
@sandhya3k  They want Service Invoice GST (50051) report to be displaye when they click on  post and print in service invoice

**Comment by sandhya3k** [comment]
@niranjand22 

please test on UAT environment

**Comment by sandhya3k** [comment]
@niranjand22 

Client confirm that it is working  fine as per requirement and also i deployed in live

cc : @audhi3k

**Comment by niranjand22** [comment]
![Image](https://github.com/3ktech/General/assets/116243958/0571ae71-19cf-40d0-86e8-34740ac13405)

@sandhya3k  print detail field is not available in service invoice page
