### ISSUE TITLE
Work Package code for all Voucher

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#508]

**Comment by Amar-3KT** [comment]
Please add front side work package code for all vouchers.

**Comment by Manoj01021999** [comment]
@Amar-3KT 
kindly check Work Package Code is visible in UAT
cc. @audhi3k @3ktech

**Comment by Amar-3KT** [comment]
@Manoj01021999 For journal voucher work package not available. Kindly check

CC - @audhi3k

**Comment by Amar-3KT** [comment]
@Manoj01021999 Please add work package on Live for all voucher

**Comment by Amar-3KT** [comment]
@Manoj01021999 Please deploy on Production...
CC @audhi3k

**Comment by Amar-3KT** [comment]
Confirm by client its done

**Comment by Manoj01021999** [comment]
@Amar-3KT it is done
