### ISSUE TITLE
No Series should be change based on a project

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#509]

**Comment by 3ktech** [comment]
Add more details for the development

**Comment by Ejaz3KT** [comment]
The fervid team uses different number series for each project so they need an option for selecting the number series based on their project wise.
They require this option in the purchase process and the sales process.

CC: @audhi3k @3ktech

**Comment by Ejaz3KT** [comment]
Ms. Sruthi has enabled the No field in the front end I am testing it 

CC: @audhi3k @TabrejAlam3K

**Comment by audhi3k** [comment]
LIVE declared
