### ISSUE TITLE
Customer Card List-Email Customer Aging

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#51]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/DELL/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/DELL/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Issue   Description | Tested By | Testing Date | Comments | Status
-- | -- | -- | -- | --
In customer card list - Email   Customer Aging--You can not execute this report!!! | Amarjeet Singh | 11-01-2023 | In BC and NAV Both   getting error | Open

</body>

</html>

**Comment by panduc** [comment]
@Amar-3KT 
in action " Email Customer Aging" the below condition written to popup the error. If it satisfies it running report 50145.

GLSetup.GET();
IF (UPPERCASE(USERID) <> UPPERCASE(GLSetup."Customer Aging Email User ID")) 
  AND (UPPERCASE(USERID) <> UPPERCASE('LSLAW\RAMESH.TEAM')) THEN
  ERROR('You can not execute this report!!!');

ReportTorun.RUNMODAL;

**Comment by audhi3k** [comment]
Email Customer Ageing to be tested

**Comment by TabrejAlam3K** [comment]
@sandhya3k  - As per our discussion please update on.

**Comment by TabrejAlam3K** [comment]
@sandhya3k - As per our discussion on Last Friday please update on.

**Comment by audhi3k** [comment]
This is yet to be started by Ms Sandhya - @sandhya3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K  as per our discussion, please follow the code. please let me know if u have any issues?

**Comment by TabrejAlam3K** [comment]
Thanks @sandhya3k - I will test the report and come back to you if i will face any challenges.

 (UpperCase(UserId) <> UpperCase(GLSetup."Customer Aging Email User ID")) and (UpperCase(UserId) <> UpperCase('LSLAW\RAMESH.TEAM')) then                        Error('You can not execute this report!!!');

**Comment by TabrejAlam3K** [comment]
@sandhya3k 


In NAV16 found error when i try to add my user in general ledger setup page.

![Image](https://user-images.githubusercontent.com/116171982/218387209-f4222b6d-898a-412a-961c-5bee15c85f41.png)

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Mail not triggered

See the attached Customer Ledger Entries for the Customer No. 9999


![Image](https://user-images.githubusercontent.com/116171982/218392806-01cf9c7d-3cb3-432d-941b-5dab093b082d.png)

**Comment by sandhya3k** [comment]
@TabrejAlam3K , as per our discussion, i hope it is working properly in bc Environment

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Done base on the filter report is working fine and i got the mail with respective invoice details.

On customer card email field should have proper value, based on that report is triggered. 
Report Testing Filter is below :
![Image](https://user-images.githubusercontent.com/116171982/218441767-13d5d3ba-cf7b-4a96-8dcb-fa7ace278af0.png)
