### ISSUE TITLE
RE: PORT GRN for DHHI Gear Box Invoice no 202382503

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#510]

**Comment by niranjand22** [comment]
![Image](https://github.com/3ktech/General/assets/116243958/f784f70e-a4e2-4527-8edc-f13bd33d3632)
![Image](https://github.com/3ktech/General/assets/116243958/7919c5dd-0c89-477a-86c3-e00d2f0f5db1)
![Image](https://github.com/3ktech/General/assets/116243958/2aaaf936-7647-4e3d-ab4c-4547c41ac780)

**Comment by niranjand22** [comment]
Purchase Order Doc no-PNB750/22-23/IPO0010

They have same Purchase item lines with diffrent prices. 

When they are generating Work order report lines are getting printed as required but
When they are Generating Purchase output report. Only one line is getting printed. 

It should print both the lines even if the item no is same.



@audhi3k  kindly align the Technical resource.

**Comment by niranjand22** [comment]
@audhi3k  pls allocate the technical resource

**Comment by audhi3k** [comment]
@niranjand22, we have completed the development, kindly update the client after testing

Hours required - 8 hours

**Comment by niranjand22** [comment]
ok

**Comment by niranjand22** [comment]
Hi @audhi3k , I have tested the Purchase order report still showing One line instead  of two separate lines

![Image](https://github.com/3ktech/General/assets/116243958/7614de39-7689-4ccc-9b76-f967d5441520)

**Comment by niranjand22** [comment]
I connecte with Senthil IT and Selvakumar. SHown them process of generating the report.
