### ISSUE TITLE
SyncAdvocate Synching issue in BC

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#512]

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - I need your support on this ticket, Synching is not happening for **Method - SyncAdvocate**.

You can see the details **Entry No. - 12078 in Api Trans Log**

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
See the below Sandbox Environment Data.


![Image](https://github.com/3ktech/General/assets/116171982/9e337430-0893-4a62-a3c0-d6cf33065797)

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

I hope it is working fine

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Now based on the condition it is working fine. I have already showcase with the client and related RTB get success.

Issue : First Name was missing on the Employee Master

Resolution : Repush the SyncAdvocate Method from API Trans Log then it get update in Dimension Master As Owner 1.
