### ISSUE TITLE
Purchase Quote report is required

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#513]

**Comment by sandhya3k** [comment]
@audhi3k 

please test on dev_sandbox

**Comment by audhi3k** [comment]
It's working fine for quote and order

But after the report is preview and closed, the below blank message is displayed

![image](https://github.com/3ktech/General/assets/121653651/c21c5946-db36-4fda-b938-9f221d5ef551)

**Comment by audhi3k** [comment]
Client confirmed Purchase Quote report
