### ISSUE TITLE
After the Material received fully purchase order status should be shown as closed

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#518]

**Comment by audhi3k** [comment]
Field Required
1. Purchase Line => new to be decimal field created with "Order Quantity"
this should be update with the value in Quantity when we are closing the Order
2. Purchase Header
Closed => Boolean field
Closed By => 
Closed On =>
Reason for Closure => Text Field (this should be editable in the status released)


Close PO Button => 
Condition
1. Status Should be released
2. Reason for Closure should be updated

1. Quantity should be update with Quantity received
2. Header Close should be updated as True

If Closed is True => the document should be non-editable Complete

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Only the below point is pending in this ticket, Once completed please let me know.

If Closed is True => the document should be non-editable Complete

**Comment by TabrejAlam3K** [comment]
The Closure of the Sales Order and Purchase Order is working fine.

CC : @audhi3k

**Comment by audhi3k** [comment]
LIVE declared
