### ISSUE TITLE
Issue In Multiple Payment Terms

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#519]
1. Payment terms is not filtering properly- Still not resolve
2. When we are changing the amount in lines the lines were not getting updated automatically in payment schedule list -completed and tested
3. After deleting purchase line the amount should get zero in payment schedule list - Completed and tested
4. when we remove payment terms in payment terms code the lines should remove from payment schedule - Completed and tested
5. When we are posting the advance we are getting the error

CC: @Mahesh3ktech @audhi3k @3ktech

**Comment by Mahesh3ktech** [comment]
hi @Ejaz3KT, point 1,4, and 5 is completed and you can check in dev sandbox. Once completing the point 2, and 3 ill update you.

**Comment by Ejaz3KT** [comment]
OK @Mahesh3ktech I`ll check 1,4,and 5th point 

CC: @audhi3k

**Comment by Mahesh3ktech** [comment]
@Ejaz3KT , check the point 2, and 3 it is completed.

**Comment by Ejaz3KT** [comment]
@Mahesh3ktech 3rd, 4th and 5th point is OK but 2nd point and 1st point is not working properly.

CC: @audhi3k  @Mahesh3ktech @audhi3k

**Comment by Ejaz3KT** [comment]
@Mahesh3ktech Please update the status of 1st and 2nd points 

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
@Mahesh3ktech Please update the status of this task.

@audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Please update the current status of the task.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k 

1. It should not be less then or more then 100%.

![Image](https://github.com/3ktech/General/assets/116171982/e8975478-1d74-456b-9c8c-1be96c57e0b2)

2. Bank should be mandatory for Advance only on Post Advance Button.

![Image](https://github.com/3ktech/General/assets/116171982/5cc55ffd-778c-49ca-bc7a-df0722acc4ae)

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - I have tested the below points.

1. Installment Line must be equal to 100% not more then or greater then. - **Completed and Tested**
2. Post Advance Validation - Bank Account Mandatory. - **Completed and Tested**
3. Bank Account Mandatory only for Advance Line on Payment Schedule list. - **Completed and Tested**
4. General Ledger Entries Segregation - Vendor Debit and Bank Credit it is happening now. - **Completed and Tested**

1. While closing the Installment Breakup page showing some error - **Pending**
2. After Final Posting need to review the entries. - **Pending** 

CC : @audhi3k

**Comment by Ejaz3KT** [comment]
Ms. @sandhya3k Payment terms are not filtering properly

CC: @audhi3k @TabrejAlam3K

**Comment by Ejaz3KT** [comment]
![Image](https://github.com/3ktech/General/assets/125632927/831ae4f6-f32d-42da-81f0-b376ff500af5)

This page is 100% but still can't close it.

@audhi3k @sandhya3k @TabrejAlam3K

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

please test on dev_sandbox

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Found some error.

1. While Post Advance
![Image](https://github.com/3ktech/General/assets/116171982/a55f55fb-7244-49e5-b74c-a931218ddf85).

**Comment by TabrejAlam3K** [comment]
Entries of Advance Payment - On Purchase Order

![Image](https://github.com/3ktech/General/assets/116171982/3d9080ab-d6ca-4a04-b2bf-c511b264478a)

![Image](https://github.com/3ktech/General/assets/116171982/008f99d4-5467-411a-adca-88c6f28dd5b8)

**Comment by TabrejAlam3K** [comment]
Entries of Advance Payment - On Sales Order

![Image](https://github.com/3ktech/General/assets/116171982/3d9080ab-d6ca-4a04-b2bf-c511b264478a)

![Image](https://github.com/3ktech/General/assets/116171982/f02593ac-d240-4ab9-8da8-38cf3c3c3714)

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - In Payment Schedule Amount is not getting generated. only the one points is pending related to this tickets.

**Comment by sandhya3k** [comment]
@TabrejAlam3K \

please check the amounts

**Comment by TabrejAlam3K** [comment]
Functionality of Multipayment is working fine for Sales Order & Purchase Order.

CC : @audhi3k

**Comment by audhi3k** [comment]
LIVE declared
