### ISSUE TITLE
Create UAT database with current backup

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#52]

**Comment by audhi3k** [comment]
Kindly share the time estimate

**Comment by 3ktech** [comment]
@sandhya3k , mention the reason why this task is on hold
CC: @audhi3k

**Comment by 3ktech** [comment]
@Mahesh3ktech , can you import the latest object and do a sanity check.

**Comment by audhi3k** [comment]
UAT database created with the new backup and shared with client
