### ISSUE TITLE
BC - Email set up - Access-CAS-01261-X2G3X0

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#529]
![Image](https://github.com/3ktech/General/assets/116171982/13eaf477-6471-49b5-939b-33d66b3872fe)

**Comment by TabrejAlam3K** [comment]
Functionality is working fine, Client Confirmed.

![Image](https://github.com/3ktech/General/assets/116171982/d0ab8722-f129-4dbb-ab01-232f82f82eb7)
