### ISSUE TITLE
Finance Report - Bill/Memo Issued(Summary) ID - 50080

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#53]
Output data not match as per the NAV16
In BC Side showing blank value - can you please check and confirm.
I am running with same filter - 01.01.2022..01.30.2022

**Comment by panduc** [comment]
@TabrejAlam3K @audhi3k the issue has been fixed. Please check and confirm.

I've test with Posting date: 01012011..01312021 and attached the output file.



[Report 50080 Output.pdf](https://github.com/3ktech/General/files/10449498/Report.50080.Output.pdf)

**Comment by TabrejAlam3K** [comment]
Done

[50080 (2).pdf](https://github.com/3ktech/General/files/10464941/50080.2.pdf)
