### ISSUE TITLE
Work Order Report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#530]

**Comment by Ejaz3KT** [comment]
[Fervid WO Format.docx](https://github.com/3ktech/General/files/11706013/Fervid.WO.Format.docx)

I am pasting here work order format shared by fervid team

**Comment by audhi3k** [comment]
Completed and waiting for customer confirmation

**Comment by Ejaz3KT** [comment]
The work order report has completed need to showcase to the client and get confirmation from the client 

CC: @audhi3k @TabrejAlam3K 

[Work order report.pdf](https://github.com/3ktech/General/files/11846833/Work.order.report.pdf)

**Comment by Ejaz3KT** [comment]
The fervid team is testing on it after testing is completed they will give confirmation

CC: @audhi3k @TabrejAlam3K

**Comment by audhi3k** [comment]
LIVE declared
