### ISSUE TITLE
Reversed Payment Integration Issue

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#531]
Dear Karthik,

You can refer to this RTB: 0000865802 for reversed payment. For this RTB, total 3 updates were received as below:

is_writeoff=False, is_unapplied=False, Amount=176600 (Payment received)
⁠is_writeoff=False, is_unapplied=True, Amount=176600 (Payment reverted)
⁠is_writeoff=False, is_unapplied=False, Amount=176600 (Payment received again)
There was no change in these 3 data received to LCMS apart from the is_unapplied field. Below is the sample data we received from BusinessCentral (for payment reversal):

{
      "bill_payment_amount":176600,
      "collection_location": 1,
      "is_unapplied": true,
      "is_writeoff": false,
      "local_payment_amount": 176600,
      "payment_date": "2023-06-06 17:01:41",
      "rtb_num": "0000865802"
      }

@Vivek Singh In LCMS, when we receive any payment update with is_unapplied=False, we save a new payment object with is_unapplied flag as True and update is_tickoff field of previous payment as True to mark it as reversed payment. You can refer to the attached snapshot for this.

@Karthik D Let me know if you’ve any other doubt regarding this.

**Comment by Shasthara** [comment]
@3ktech , Please need update from you.

**Comment by TabrejAlam3K** [comment]
Need to do the internal session first before moving with the client.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
I have created a new ticket for this so I am closing this tickets.

Related Ticket is #544
