### ISSUE TITLE
Bank Account Recoincilliation-Startek

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#533]
We have created data exchage definition and did field mapping. In sandbox environment.
and tried uploading Bank statement. It is updating correctly.

Ms Salini has passed some entries. it worked as per requirement..she will test with few more entries and update

**Comment by niranjand22** [comment]
Hi Team,

 

Managed to do 5 entries. Plse find the below screenshot. And it’s under BankRec #6

Also I am attaching the files that I used and its matching as required. The last entry didn’t get picked because it’s from June posting.

  salini

**Comment by niranjand22** [comment]
It is working fine in UAT. client will update for deployment to live

**Comment by niranjand22** [comment]
As discussed, please carry out few more testing just to cover every scenario of tolerance date, same amount with difference chq number, same chq number but different amount etc.
I have done my own testing and it looks fine so far.

Hi Dynamics support,

Once confirm by Salini, you can deploy. However, please ENSURE that no modification is done key logics of deferral journal calculation or on any other extensions and customisation.
I will even further suggest to make one copy of current production environment into sandbox so that in the event something breaks we can restore by redeploying current working extensions.

**Comment by audhi3k** [comment]
Closing this ticket is this related to #371
