### ISSUE TITLE
Amount Should Not be editable in Purchase Invoice for GRN CAS-01294-F3S4Q1

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#534]

**Comment by audhi3k** [comment]
Development completed, Mr @niranjand22 after testing take UAT with the client

**Comment by niranjand22** [comment]
Hi Himanshu, Thank you for connecting via Teams call. I have successfully demonstrated the entire process, and Mr. Himanshu has given his confirmation to proceed with implementing the changes in the live environment. 

@audhi3k  Please move changes to live.

**Comment by audhi3k** [comment]
Mr @niranjand22, deployed in LIVE, kindly check and closure
