### ISSUE TITLE
Material Indent Issue

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#540]
![Image](https://user-images.githubusercontent.com/125632927/246428873-e3b3b556-efaa-475a-a240-fda0e15031fb.png)

I am Facing this error while converting the requisition document to purchase document.

**Comment by Ejaz3KT** [comment]
1.Requisition Sub form 

a)Shortcut Dimension 1 and Shortcut Dimension 2 should rename with Branch and Department. 

b)Quantity should be without decimal, currently it is coming till four decimal. 

2.Issue and Indent Slip 

     a)Quantity to Purchase should be without decimal currently it is coming till four decimal. 

     b)If I put the value in Quantity to Purchase Amount should be changed based on this. (Quantity to Purchase * Price = Amount). 

3.Indent Purchase Action 

     a)Amount is coming wrongly, it should be (Quantity * Price = Amount). 

Purchase Quote: - 

Request Receipt Date = Indent Required Date 

Requisition No. = Indent Requisition No. 

CC: @audhi3k @TabrejAlam3K

**Comment by audhi3k** [comment]
Update in #463 so closing this ticket
