### ISSUE TITLE
Income Tax depreciation Report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#549]
[IT act Depreciation Sheet (1).xlsx](https://github.com/3ktech/General/files/11878120/IT.act.Depreciation.Sheet.1.xlsx)

Please Find Fixed asset income tax depreciation format 

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Ejaz3KT - Please connect with the Client with Proper requirement and Collect the Demo entries details. Let me know once you have done the session with the client.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Ejaz3KT - Field Mapping is completed Monday will connect with the technical and close it.

[Field Mapping IncomeTax Dep.xlsx](https://github.com/3ktech/General/files/11916632/Field.Mapping.IncomeTax.Dep.xlsx)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Mr. Rajesh is working on, Last Saturday we have done the understanding session.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Ejaz3KT - What is the status of this reports.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Ejaz3KT - Please update the status of the Report and close the ticket. It is pending since long.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
As per the word with Mr. @Ejaz3KT - UAT is still pending with the client.

CC : @audhi3k

**Comment by Ejaz3KT** [comment]
Waiting for the client to connect for giving UAT

CC: @audhi3k Madam @TabrejAlam3K Sir

**Comment by TabrejAlam3K** [comment]
Mr. @Ejaz3KT - Please update you latest comment here, whether you was connected with the client.

**Comment by Ejaz3KT** [comment]
Hi @TabrejAlam3K Due to client unavailability I haven't showcase to them this report 

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Mr. @Ejaz3KT - Please done the uat with the client and close the issue from here.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by Ejaz3KT** [comment]
I`ve connect with the Mr. Sreedhar on phone call he told me he will connect with me at 4pm today

CC; @audhi3k

**Comment by Ejaz3KT** [comment]
Hi in the morning Mr. Sreedhar sir told me he will connect today for the reports UAT session but unfortunately, he had a meeting with the director so he told me he will connect tomorrow

CC; @audhi3k

**Comment by Ejaz3KT** [comment]
Hi Due to client unavailability, I am not able to showcase the report  

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi I`ve shared the income tax depreciation report to the fervid team they told after analysis the report they will inform us if there any changes to be done

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The values in the report is printing in negative please change in to positive so that the values should be reflected as positive value in the report 

CC: @audhi3k

**Comment by 3ktech** [comment]
hi @Ejaz3KT , can you please be more specific with the screenshot which field needs a change and which report needs to be modified.

**Comment by Ejaz3KT** [comment]
Hi, team, I am not able to find IT Act depreciation report in the fervid environment 

![Image](https://github.com/3ktech/General/assets/125632927/3a9613a8-3f96-44c9-9ae5-400b1df509a2)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi team please remove the negative symbol in the report for your reference I`ve attached the screen short

![Image](https://github.com/3ktech/General/assets/125632927/41091bf2-9414-4c1f-a71a-7970c84b70d2)

CC: @audhi3k

**Comment by Manoj01021999** [comment]
![image](https://github.com/3ktech/General/assets/126780544/7d322d46-7c6d-4638-bf48-d397ce722173)
@Ejaz3KT updated report
CC:@3ktech @audhi3k FYI

**Comment by Ejaz3KT** [comment]
Hi @Manoj01021999 I`ve tested the report it is fine, Please check why the first line is coming as blank and remove that blank line from the report

CC: @audhi3k

**Comment by Manoj01021999** [comment]
@Ejaz3KT the issue is fixed 
kindly look into it
cc: @3ktech @audhi3k

**Comment by Ejaz3KT** [comment]
Hi, @Manoj01021999 I`ve tested the report it is working fine please deploy this report in the production environment.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi, all the changes have been done and the report is working fine now I am going to close this ticket. If any new issue comes up related to this report we can create a new ticket based on the new issues  

CC: @audhi3k
