### ISSUE TITLE
Purchase order should not be deleted after posting if the purchase & payable field => Retain PO is true

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#556]

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - This task is assigned to you please update your comments here.

CC : @audhi3k @Ejaz3KT

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Please update the status of this task

CC: @audhi3k @TabrejAlam3K

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Please update the status of this task

@audhi3k madam @TabrejAlam3K

**Comment by sruthi1017** [comment]
hi @Ejaz3KT the requirement is completed and showcased to u also, only one point is pending regarding status when we post from sales invoice, as we discussed please provide me the link between the invoice and order to update it.
@audhi3k @TabrejAlam3K

**Comment by audhi3k** [comment]
@Amar-3KT understand the issue and then update me, we will have join call on this

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Everything is working fine related to this retain PO only we need to fix is that refreshing part 

CC: @audhi3k Madam @Amar-3KT

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I`ve tested this Retain PO and it is working fine and Please deploy this in the production

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Have you deployed this in production please update the status of this activity

CC: @audhi3k @TabrejAlam3K

**Comment by TabrejAlam3K** [comment]
Confirmed by the Client now Closing the ticket.
