### ISSUE TITLE
Filed To be Added in Item ledger entry CAS-01313-Z4H8L6

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#557]

**Comment by niranjand22** [comment]
In ILE they need this three cloumn. @audhi3k  would like to discuss with u based on your availabilty

![Image](https://github.com/3ktech/General/assets/116243958/c38f5e75-93b5-4b9b-a77d-236d397e77f1)

**Comment by audhi3k** [comment]
Hi.. Mr @niranjand22 , we can connect tomorrow at 9

**Comment by niranjand22** [comment]
They need only for shipment.

@audhi3k

**Comment by niranjand22** [comment]
Selvakumar is not available..whole week. once back I can showcase and close

**Comment by niranjand22** [comment]
had call with client .Please move this specific change to Live @audhi3k

**Comment by audhi3k** [comment]
Deployed in LIVE,

**Comment by niranjand22** [comment]
closing
