### ISSUE TITLE
Report Need - reg- Slevakumar

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#558]

**Comment by niranjand22** [comment]
.

**Comment by niranjand22** [comment]
conneected with selvakuma. all data is available in ILE. 

Order No Column is also available there but is is not updating the values. need to check.

Order date column is not there..it has to be added in ILE.

@audhi3k  will talk with u on this wen u are avialble

**Comment by audhi3k** [comment]
Hi.. Mr @niranjand22 , we can connect tomorrow at 9

**Comment by niranjand22** [comment]
I had phone call with selvakumar for uat. he will be avaiable after tuesday.

@audhi3k

**Comment by niranjand22** [comment]
Selvakumar was not available..wil connect and close this tomorrow

**Comment by niranjand22** [comment]
Selvakumar is not available..whole week. once back I can showcase and close

**Comment by niranjand22** [comment]
The client is requesting a report of Purchase Orders for a specific period, irrespective of whether the material was received or not (including posted or not psoted). The report should include details such as the number of orders released by a particular buyer, the recipients of those orders, the corresponding item codes, and the total value of the purchase.

need to discuss with you for this cc @audhi3k

**Comment by audhi3k** [comment]
Create as new ticket for the new report, as the older requirement was different
@niranjand22

**Comment by audhi3k** [comment]
Deployed in LIVE, the older requirements

**Comment by audhi3k** [comment]
New ticket to be raised for the New report customization, as this is only for field addition
