### ISSUE TITLE
Jet Reports Issue - BC

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#571]

**Comment by Shasthara** [comment]
Swathi Shrinivas: Hi Karthik,

As discussed over teams, i have an issue with running jet report.

Can u pls look into this below error ?


blob:https://3ktlive.crm.dynamics.com/d6e61b6b-4dc0-4600-8845-7f1ffb9fdb37
blob:https://3ktlive.crm.dynamics.com/e4e949b1-463a-4c8c-b558-7156652e19ea

**Comment by Shasthara** [comment]
![Image](https://github.com/3ktech/General/assets/117992956/dac38c10-8065-415f-9681-5fe961f22b6c)
![Image](https://github.com/3ktech/General/assets/117992956/71bb3f45-c85c-4c17-82da-99aee9a69be2)

**Comment by niranjand22** [comment]
Hi @3ktech , At what time we can connect tomorrow with client to check this

**Comment by 3ktech** [comment]
@niranjand22 , I had a word with swathi and i need a designer license assigned to her user id to investigate this further

**Comment by niranjand22** [comment]
ok ..

**Comment by niranjand22** [comment]
I have assigned SMARTLIST DESIGNER permisson to swathi id. I f need we can give super permission also for some time. From ID provided to us by Merit. @3ktech  let me know

**Comment by niranjand22** [comment]
Had joint Call with Mr kartik D and Swathi, Merit IT team was not available in last weeek. They are back now. Once they provide designer licence to Swathi Id. Mr kartik D will work towards closure

**Comment by 3ktech** [comment]
hello @niranjand22 , i need a jet report server which was in use by Sarika and Murali. I can take the server only if they are done.

**Comment by 3ktech** [comment]
hello @niranjand22 , we have fixed this issue by doing the following:
We let Sawthi to login to Jetreport using Merit credentials. This solved the problem. Please make a note of this in case the similar issue raises.
CC: @sandhya3k @audhi3k

**Comment by niranjand22** [comment]
@3ktech  thanks for update
