### ISSUE TITLE
External documents no- Required CAS-01332-G3P3J8

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#579]

**Comment by niranjand22** [comment]
![Image](https://github.com/3ktech/General/assets/116243958/34326181-4724-48e9-9146-7ad2f9517b0f)
![Image](https://github.com/3ktech/General/assets/116243958/fa6a25dd-eada-4a4d-aa49-416374a09877)
![Image](https://github.com/3ktech/General/assets/116243958/64afe2e6-b085-443b-8ad7-b70a1662b39d)

While Extracting “Job Ledger Entries” reports we need “External documents no”  Field.

 

And this field is not available in the “Choose Column” option. Please configure the same.

 

Regards,         

Rajesh Kumar Gupta

**Comment by niranjand22** [comment]
cc @audhi3k

**Comment by audhi3k** [comment]
Deployed in LIVE,

**Comment by TabrejAlam3K** [comment]
Client Confirmed now going to close the tickets.
