### ISSUE TITLE
Sales Report - Posted Sales Credit Memo ID - 50026

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#58]
Found Error when try to run the report in BC

In NAV16 Working fine.

![Image](https://user-images.githubusercontent.com/116171982/213363449-30c9430e-fe4a-4527-a1d7-a1b83b599739.png)

**Comment by panduc** [comment]
@TabrejAlam3K The issue has been fixed. Please check and confirm.

Attached the output for reference

[Report 50026 Output.pdf](https://github.com/3ktech/General/files/10456728/Report.50026.Output.pdf)

.

**Comment by TabrejAlam3K** [comment]
Done

[50026.pdf](https://github.com/3ktech/General/files/10464735/50026.pdf)
