### ISSUE TITLE
Permission Set - Requirement Location should be filter based on the User Setup Location but User can't remove the filter on Page Level.

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#581]

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Manoj01021999 - We have discussed earlier on issue in details. Please let me know the status of the ticket.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - As per our discussion see the below.

**Requirement -**
1. Location should be auto filter based on the Location available on the User Setup for every users. - It is happening in the same manner in the UAT Environment (You need to deploy the same into the Production Environment)
2. Only the super user can remove the filter of Location from the Page **Collection Detail List (50070, List)** - It is not working need to be fix.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - It is working now, let me cross check with the client.

CC : @audhi3k

**Comment by audhi3k** [comment]
Get Confirmation on closure from client

**Comment by TabrejAlam3K** [comment]
We are holding this ticket till Friday 28-07-2023 after that I will close the ticket as resolved.

**Comment by TabrejAlam3K** [comment]
Not Responded from the client side. I am closing this ticket, if required we will create the separate ticket in future.

CC : @audhi3k @Shasthara
