### ISSUE TITLE
Cheque Voiding - Need to check and compare the Code for NAV16 & BC.

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#582]
Parent Ticket - 

[Cheque voiding: Before posting void is possible#240](https://github.com/3ktech/General/issues/240)

**Comment by TabrejAlam3K** [comment]
Error Message 

The Currency does not exist. Identification fields and values: Code=''

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

As discussed, please update ur commnets

**Comment by TabrejAlam3K** [comment]
Mr. @panduc - Can you start working on this and close it on priority.

CC : @audhi3k

**Comment by panduc** [comment]
@TabrejAlam3K was on leave on 26th and 27th. 28th was working on other high prio topic.

I will check the topic and connect with you if anything required from you.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - Please share the timeline first for this task.

CC : @audhi3k @3ktech

**Comment by panduc** [comment]
Hi @TabrejAlam3K  for issue/bug timeline can't be estimated. 

Check voiding is standard process we have to analyze on which case it is failing and suggest how to overcome. Will do the analysis and let you.

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - As per our discussion on issues in details, please let me know if you have any query on this.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - As per our discussion please compare the code between LKS NAV16 to BC.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
Raise a ticket to Microsoft.

**Comment by 3ktech** [comment]
hi @TabrejAlam3K , @Shasthara , we need to login to the environment where NAV 2016 is installed to verify the system behavior. can you please get the access and share it with @rohit3k  to look into this issue. thanks

**Comment by 3ktech** [comment]
@TabrejAlam3K , @Shasthara , any update on this pls?

**Comment by 3ktech** [comment]
@rohit3k , can you look at it?

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K Changes has been done please check and confirm!

CC : @audhi3k , @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - While voiding the check from Check Ledger Entries found the below error.

![Image](https://github.com/3ktech/General/assets/116171982/2aed2d89-7d50-435e-a68c-8e5c658b8355)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/46d82f93-b1b8-4f93-9ba3-3407db7f800a)Client confirm the 

Process of Check Voiding is working fine in the UAT Environment.
Mr. @rohit3k - Please move the changes into the Production Environment.

@sandhya3k - Please move the customization into the Production Environment.

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Due to Non Response from the Client side I am closing this ticket, Will create separate ticket if required.

CC : @audhi3k @Shasthara
