### ISSUE TITLE
Exchange Rate - Need to Increase the length of Decimal Place from 6 to 7 (In Collection Detail and Gen. Journal Line)

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#583]

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Manoj01021999 - We have discussed earlier on issue in details. Please let me know the status of the ticket.

CC : @audhi3k

**Comment by sruthi1017** [comment]
Hi @TabrejAlam3K- As i mentioned, it is not allowing to modify the DecimalPlaces property for the standard field.
CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - As per our discussion please move this into the production.

**Comment by sruthi1017** [comment]
hi Mr. @TabrejAlam3K  @sandhya3k has been deployed the changes in production.

**Comment by TabrejAlam3K** [comment]
Ok fine @sruthi1017

**Comment by TabrejAlam3K** [comment]
Ms. @sandhya3k and Ms. @sruthi1017 - The changes is not available in Production.

In UAT - It is taking till 8 Decimal places but See the below snapshot for production.

![Image](https://github.com/3ktech/General/assets/116171982/82194c92-08fb-4200-bc00-e7151cc546b5)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Ms. @sandhya3k - Please see and deployed in the production, UAT it is working fine.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k and Ms. @sruthi1017 - Please update your comment here.

CC : @audhi3k

**Comment by sruthi1017** [comment]
hi MR. @TabrejAlam3K , can u chek now the changes are published

**Comment by audhi3k** [comment]
Get Confirmation on closure from client

**Comment by TabrejAlam3K** [comment]
We are holding this ticket till Friday 28-07-2023 after that I will close the ticket as resolved.

**Comment by TabrejAlam3K** [comment]
Not Responded from the client side. I am closing this ticket, if required we will create the separate ticket in future.

CC : @audhi3k @Shasthara
