### ISSUE TITLE
Ship to & Bill to field is missing on Purchase Quote in Production

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#587]

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Please update your comment here.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We have checked but still not get anything related to the Setup.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

we will discuss in the 2nd half

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

shell we discuss?

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Please check whether we have missed something while ready the Production Environment, because the issues is coming only in the Production Environment.

I have checked all the setup where we can see.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam Now the  ship to and bill to field is visible in the purchase quote card and it is working fine



![Image](https://github.com/3ktech/General/assets/125632927/043c87ac-1e0d-4c1e-844d-e5e93f31a58f)

CC: @audhi3k Madam @TabrejAlam3K Madam

**Comment by TabrejAlam3K** [comment]
Mr. @Ejaz3KT - Can we close the ticket.

**Comment by Ejaz3KT** [comment]
@TabrejAlam3K Sir yes we can close the ticket

**Comment by TabrejAlam3K** [comment]
Issues is tested by Ejaz and found working fine, Going to close the tickets.
