### ISSUE TITLE
Fields are missing on Journal Voucher in Production

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#588]

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Please update your comment here.

CC : @audhi3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

we will discuss this part in the 2nd half

cc : @audhi3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

shell we discuss?

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Please check whether we have missed something while ready the Production Environment, because the issues is coming only in the Production Environment.

I have checked all the setup where we can see.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k The fields which are missing in journal voucher now they are visible in journal voucher page



![Image](https://github.com/3ktech/General/assets/125632927/736cb9f1-991a-4127-a031-dad7a7a63d99)

CC: @audhi3k Madam @TabrejAlam3K Sir

**Comment by TabrejAlam3K** [comment]
Mr. @Ejaz3KT - Can we close the ticket.

**Comment by Ejaz3KT** [comment]
@TabrejAlam3K Sir yes we can close the ticket

**Comment by TabrejAlam3K** [comment]
Issues is tested by Ejaz and found working fine, Going to close the tickets.
