### ISSUE TITLE
BRS - Reversed transactions

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#590]
Based on the above understanding - Yes;  The users makred with collection rights should not be allowed to remove the location filter and also they should not be allowed with any search get data for which they are not entitled except for the collection of their Branch entries created by such user only.

**Comment by TabrejAlam3K** [comment]
Suggest Line not bringing the Reversed Transaction - In NAV2016 is is working.

**Comment by TabrejAlam3K** [comment]
Hi @audhi3k Mam - Who will work upon from technical side on this issues.

**Comment by audhi3k** [comment]
Mr Karthik, @3ktech  as  discussed the value for Reversed in Bank Reconciliation line is not updating, kindly check

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - As per our Requirement Understanding session, please update your comment once you done the development.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Code Reference of NAV16

![Image](https://github.com/3ktech/General/assets/116171982/1f80e31a-77d5-4220-aa97-7b518f07f4b2)

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Tested in UAT Environment and it is working fine, I have forwarded the same to the Client for Unit Testing, Let's wait their reply.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Today I have done the Follow-up with the client over teams chat, not yet responded.

**Comment by TabrejAlam3K** [comment]
I have receive response from the client side.

![Image](https://github.com/3ktech/General/assets/116171982/68cc17e1-e63a-439b-94f0-272fe7daea90)

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Please move this changes into the production environment.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017  - Please move this changes into the production environment.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Please confirm whether you have deployed this into the production.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
I will close this ticket today if not receive any response from the client side.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
No Response Receive from the Client so We are going to close the ticket as Completed.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 and Ms. @sandhya3k - Can you move this changes into the Production Environment.

CC : @audhi3k @Shasthara @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017  and Ms. @sandhya3k - It is still pending past 8-10 days to deploy into the Production.

CC : @audhi3k @3ktech

**Comment by 3ktech** [comment]
@TabrejAlam3K , please update the status as done if it is closed.

**Comment by TabrejAlam3K** [comment]
Client Confirmed for Closure over teams chat. I am closing as completed.

![Image](https://github.com/3ktech/General/assets/116171982/cd3efc24-0e15-4e7d-98db-d1caf56f4b11)

CC : @audhi3k @sruthi1017
