### ISSUE TITLE
Alignment- RTGS Form

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#592]

**Comment by niranjand22** [comment]
Dear Sir, 

I appreciate your call. We have  noted the alignment changes requested by your team for RTGS IOB and RTGS AXIS for both companies.

**Comment by niranjand22** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



RTSG Alignment | Pioneer Wincom and Pioneer X Energy
-- | --
  |  
Navigation |  
  | Bank Ledger Entries> Select Entry> Click RTGS Axis
  | Remove Thanking You
  | Reduce Line Between Pionner  and   RBI Gap- 1 line gap is fine
  | Provide  4 Line  gap b/w Pioneer and Authorised Signatory.
  | Remove Extra Spaces from bank details and other section of report
  | Report should come in 1 page
  | Increase Pioneer Name  font by 1   size
  | Put Closing Bracket in Paisa Only Senetece
  |  
  |  
Navigation | Bank Ledger Entries> Select Entry> Click RTGS IOB
  | Remove the lines b/w Pioner and Thanking You. Keep 1 line gap
  | Increase Pioneer Name  font by 1   size
  | Provide  4 Line  gap b/w Pioneer and Authorised Signatory.
  | Remove Extra Spaces from bank details and other section of report
  | Report should come in 1 page



</body>

</html>

**Comment by niranjand22** [comment]
@sruthi1017  pls take this task

**Comment by sruthi1017** [comment]
hi @niranjand22 did all the changes as required in both reports 50039 and 50040. let me know if there are any changes
CC: @3ktech

**Comment by niranjand22** [comment]
@sruthi1017  had UAT with Client. Please depoly to live

**Comment by sruthi1017** [comment]
@niranjand22 deployed both reports in live can u test and update whether all the alignments are correct are not
cc: @3ktech

**Comment by niranjand22** [comment]
completed
