### ISSUE TITLE
Mark filed Non-Editable on Sales Invoice (Branch Code, Case & Location Code)

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#598]
![Image](https://github.com/3ktech/General/assets/116171982/166847e8-ff74-4849-90f8-34ac4b27d75c)

**Comment by TabrejAlam3K** [comment]
Please make the field Non-Editable below on the Sales Invoice Page

1. Branch Code
2. Case
3. Location Code

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. Kartik @3ktech - Please assign technical to close this issues.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Fields need to be hide from the Sales Invoice Page

1. Shortcut Dimension 1 Code
2. Shortcut Dimension 2 Code
3. Location Code

@sandhya3k - Please share the timeline for this also.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

I am going to take 45 minutes?

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

please check the UAT environment?

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Please move this changes into the production environment. It is working fine in the UAT Environment.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Can you please move this changes into the production Environment.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

I deployed in production

**Comment by TabrejAlam3K** [comment]
Thanks Ms. @sandhya3k - Validation is working fine in the Production Environment.

![Image](https://github.com/3ktech/General/assets/116171982/8aa406d7-4af8-4308-99e4-8e3e759e29d9)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
I am closing this ticket as resolved.
