### ISSUE TITLE
Purchase History Report- Pioneer

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#601]

**Comment by 3ktech** [comment]
hi @niranjand22 , please add more information here so that it can be taken for development. I am changing the status to New. Once the task is ready for development, please move this to ToDo
CC: @audhi3k

**Comment by niranjand22** [comment]
@3ktech  Hi I will provide field mapping file. Once ready

**Comment by sruthi1017** [comment]
hi @niranjand22 update once the field mapping is done
CC: @3ktech

**Comment by Manoj01021999** [comment]
@niranjand22 
i assume this is the report ID and changes are going to be done here
ID:50050	,Name:''Tax - Invoice GST"	

cc: @3ktech @audhi3k

**Comment by Manoj01021999** [comment]
@niranjand22 update once the field mapping is done
and confirm once it is able to access the pioneer

cc: @3ktech

**Comment by Manoj01021999** [comment]
@niranjand22 as per teams confirmation
update me once u r available

c: @3ktech @audhi3k

**Comment by niranjand22** [comment]
@Prakash3K 

[PurchaseOrderHistoryReport.xlsx](https://github.com/3ktech/General/files/12318651/PurchaseOrderHistoryReport.xlsx)

**Comment by audhi3k** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Development | 10
-- | --
design | 2
testing | 4
uat | 2
PM | 2
  | 20



</body>

</html>

**Comment by audhi3k** [comment]
Mr @Prakash3K, did you followed up with the client for approval

**Comment by Prakash3K** [comment]
@audhi3k, I have already sent an email to the client requesting approval for the estimated hours, but I have not received a reply from their side yet.

**Comment by shivakumar3k** [comment]
@Prakash3K please check with customer and update the status

**Comment by Prakash3K** [comment]
@audhi3k, Client is not available until 18/09/2023.

**Comment by Prakash3K** [comment]
Hi Mr. @Manoj01021999 field mapping for this ticket is done kindly proceed.


[PurchaseOrderHistoryReport (Field mapping).xlsx](https://github.com/3ktech/General/files/12726518/PurchaseOrderHistoryReport.Field.mapping.xlsx)


CC: @audhi3k @3ktech

**Comment by Manoj01021999** [comment]
@Jayanth3KT 
as we discussed kindly test and confirm me

cc:
@3ktech @gsudarsan3k  @audhi3k

**Comment by Prakash3K** [comment]
@Manoj01021999 Format is correct some information not fetching, kindly make changes

**Comment by Prakash3K** [comment]
@Manoj01021999  kindly update status

**Comment by Manoj01021999** [comment]
@Prakash3K kindly let me know the exact field 
CC: @3ktech

**Comment by Prakash3K** [comment]
@Manoj01021999 In Buyer/purchase code and Production order number data in not fetching

**Comment by Prakash3K** [comment]
@Manoj01021999 kindly update status here

**Comment by Manoj01021999** [comment]
@Prakash3K 
As we discussed in call with Shiva take it forward
CC: @gsudarsan3k @3ktech

**Comment by Prakash3K** [comment]
@Manoj01021999 In Buyer/Purchaser name field values are missing kindly check and confirm.

CC: @audhi3k, @3ktech @gsudarsan3k @Tushargupta3K

**Comment by Prakash3K** [comment]
Hi @Manoj01021999 Kindly move customization into live.

CC: @audhi3k @Tushargupta3K @3ktech

**Comment by Prakash3K** [comment]
Ticket is completed, closing due to no response from the client.


CC: @audhi3k @Tushargupta3K
