### ISSUE TITLE
PDC Status in check ledger entries is not changing from printed to Posted

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#604]

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam In check ledger entries the status for the PDC record is not changing from printed to posted please check this issue and resolve it.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam now the status in check ledger entries is changing to posted and I`ve tested it is working fine and entries also coming correctly.

![Image](https://github.com/3ktech/General/assets/125632927/a926c700-6acb-46ce-9444-64f85140cde0)

CC: @audhi3k Madam

**Comment by TabrejAlam3K** [comment]
Confirmed by the Client now Closing the ticket.
