### ISSUE TITLE
why it still takes me almost 15minutes to refresh jet reports CAS-01391-V0H2X7

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#607]

**Comment by 3ktech** [comment]
hi @niranjand22 , I have checked the TP report behavior and compared with Dods. System behaves the same. since it is a copy of Dods report, since dods report are slow, the TP reports are slow as well. I had spent 3 hours for this task
CC: @audhi3k

**Comment by niranjand22** [comment]
@3ktech  can we close this case.. Kartik ?

**Comment by 3ktech** [comment]
hi @niranjand22 , I have updated this to sarika. we cannot do much about the performance considering the current method of handling data using jet reports. I have looped you in the mail which sarika sent to external guys

**Comment by audhi3k** [comment]
This was because of RAM
