### ISSUE TITLE
Elegrow - Tax Invoice Report

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#608]
![Image](https://user-images.githubusercontent.com/116243958/258291605-c0dd4189-7bb4-4fa7-b55a-e8c94ef3c5b9.png)

**Comment by niranjand22** [comment]
[ETPL_SI23-24_029_Signed Field Mapping.docx](https://github.com/3ktech/General/files/12256888/ETPL_SI23-24_029_Signed.Field.Mapping.docx)

**Comment by niranjand22** [comment]
[ETPL_SI23-24_029_Signed.pdf](https://github.com/3ktech/General/files/12298777/ETPL_SI23-24_029_Signed.pdf)

**Comment by audhi3k** [comment]
Dropped so closed
