### ISSUE TITLE
Need to add new field for Loan Data Called PORTFOLIO

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#611]
**Requirement** - User will pass the value in the field **PORTFILIO** from LMS Data.

**Functionality** - We will import the same field data into the staging table in the field **PORTFOLIO**, after processing the Loan file it will get inserted in Bank Receipt Voucher(Gen. Journal Line) in the same filed **PORTFOLIO**, After posting the Bank Receipt Voucher the field(PORTFOLIO) value should moved into the General Ledger Entries.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - As per our discussion, Create a new field for Loan File called **PORTFILIO** as Text with Length 30. Create a new field for below tables.
1. LMSLoanDetails (50102)
2. Gen. Journal Line (81)
3. G/L Entry (17)

CC : @audhi3k @Shasthara @narayana3kt

**Comment by Mahesh3ktech** [comment]
hi Mr. @TabrejAlam3K - i have added the fields and tested through postman by pushing data to BC. kindly check and confirm.

CC: @3ktech @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment]
Mr. @Shasthara - Have you get the approval from the client for this issues. Development is completed once we receive the approval from the client then we can deploy the changes.

**Issue Status** - Development is completed

CC : @audhi3k @narayana3kt

**Comment by TabrejAlam3K** [comment]
Power Automate is pending for the new field call **PORTFILIO**, Mr. Murali need to fixed by their side.

Issue Status - BC Development is completed but Power Automate is still Pending.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
All the points has been completed, We are still waiting for time effort approval by the client side.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Shasthara - Can we close this ticket, If required will create a new ticket.

CC : @audhi3k

**Comment by audhi3k** [comment]
This is existing ticket, This is approved, we can start with the development - Mr Karthik , @3ktech

**Comment by audhi3k** [comment]
The development is completed with respect to BC- Mr @Mahesh3ktech check and confirm and integration thing to be done.

Mr Karthik @3ktech, check whether we can take up this today by Mr @Mahesh3ktech

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - Portfolio field is enabled in all the area, kindly check.

CC: @3ktech, @audhi3k, @Shasthara

**Comment by TabrejAlam3K** [comment]
Mr. @Mahesh3ktech - As per our discussion we need to add the changes in the MS Flow, Have you discussed with Mr. Murali.

CC : @audhi3k @Shasthara @3ktech

**Comment by 3ktech** [comment]
@TabrejAlam3K th etask is done from the tech perspective. we are waiting for Murali to support us. I have initiated a communication in the channel. please follow up with him for testing.
CC: @audhi3k , @Mahesh3ktech

**Comment by TabrejAlam3K** [comment]
Mr. Murali Krishna - I have tested this part also based on the MS Flow while import the data into the LMS Folder value of the field Portfolio is coming in the Loan Staging table field called Portfolio. **(MS Flow is working fine)**

Mr. @Mahesh3ktech - The Field Portfolio value is populating in the Bank Receipt Voucher(Gen. Journal Line)

Issues -	
1. While Running the Job Queue one popup message is coming Do you want to Post the Journal
2. Value of the field Portfolio is not coming in the Posted General Ledger Entries.

@Mahesh3ktech  - Can we connect of Point No. 1 and 2.

CC : @audhi3k @3ktech

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - As discussed portfolio will display in Genral Ledger Entry table. kindly check. 

CC: @3ktech @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k  - I have done the UAT session with Vridhi Team They are ok with the Customization. He will test the scenario with New File Upload.
 
Note : Query they have raise - They want filter at the time of Dimension Value Selection for the Customer Dimension and Loan Dimension.

**Comment by TabrejAlam3K** [comment]
This process is working in and confirmed by Mr. Dikshant during the screen sharing session. I am closing this tickets

@audhi3k @Shasthara
