### ISSUE TITLE
Purchase Order

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#612]

**Comment by niranjand22** [comment]
[POETPL23-24005.pdf](https://github.com/3ktech/General/files/12272824/POETPL23-24005.pdf)

**Comment by niranjand22** [comment]
[POETPL23-24005.docx](https://github.com/3ktech/General/files/12272829/POETPL23-24005.docx)

**Comment by niranjand22** [comment]
Hi @Prakash3K  pls find the PO report PDF format and word file with field mapping..you can do the remaining field mapping

**Comment by niranjand22** [comment]
@sandhya3k  pls find the field mapping word fiel..aslo pls check the PDF file which is updated here for refering proper output.

Currently it is partially mapped...line level mapping will share soon by 4:30

**Comment by niranjand22** [comment]
@sruthi1017  pls find complted field mapping of PO report

[POETPL23-24005.docx](https://github.com/3ktech/General/files/12291699/POETPL23-24005.docx)

**Comment by audhi3k** [comment]
Dropped so closed
