### ISSUE TITLE
Sales Order Report

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#614]

**Comment by niranjand22** [comment]
[SOETPL23-24015.pdf](https://github.com/3ktech/General/files/12280222/SOETPL23-24015.pdf)

**Comment by niranjand22** [comment]
Please  find field mapping file for this report cc @audhi3k 

[SOETPL23-24015 (1).docx](https://github.com/3ktech/General/files/12280226/SOETPL23-24015.1.docx)

**Comment by niranjand22** [comment]
@Mahesh3ktech  refer this  updated word fiel for IGST sgst and csgt field mapping
[SOETPL23-24015.1.docx](https://github.com/3ktech/General/files/12291707/SOETPL23-24015.1.docx)

**Comment by audhi3k** [comment]
Dropped so closed
