### ISSUE TITLE
Urban Ladder Issue Understanding Session 09082023

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#620]
1. UL Post Output - Output & Consumption both should be happen currently only Output is happening.
2. Delivery Challan should be in 3 Copy (Original, Duplicate & Triplicate).
3. Delivery Challan Unit Price - It is currently coming from Item Card, It should be come from ILE First entry.
4. New Page Required for Posted Service Invoice - Filter based on Location Code (SCON01).
5. RRL Output - After assigning the Serial Number - Barcode should be auto printed or Manual Print Required.
6. GST Reg No. in RRL - GST Reg. No. should come from UL in Delivery Challan Report and Location List.

**Comment by TabrejAlam3K** [comment]
@TabrejAlam3K  - RRL Output - After assigning the Serial Number - Barcode should be auto printed or Manual Print Required. - Get the more details from the client.

**Comment by 3ktech** [comment]
hi @TabrejAlam3K , is there any development required for this task? if so, please detail the development aspects to take it for development

**Comment by TabrejAlam3K** [comment]
Will connect on this point later.

**Comment by audhi3k** [comment]
Completed
