### ISSUE TITLE
PDC Posting Issue

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#621]
Hi @sandhya3k  madam When I am trying to post the PDC check I am facing this error please check this and resolve this ASAP

![Image](https://github.com/3ktech/General/assets/125632927/dc391ffc-88b9-4ee1-8870-cc8c09ead426)

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

please test on sandbox environment

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam I`ve tested it is working fine 

CC: @audhi3k

**Comment by audhi3k** [comment]
Resolved
