### ISSUE TITLE
E-Invoice Testing

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#623]

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - I have posted the below Document as per your request

**Posted Sales Invoice**
1. 103250 - IGST
2. 103253 - CGST/SGST
3. 103254 - IGST
4. 103255 - CGST/SGST

**Posted Sales Credit Memo**
1. 104001 - CGST/IGST
2. 104002 - IGST

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - See the below latest Posted Documents.

Posted Sales Invoice

⁠1. 103256 - IGST
2. ⁠103257 - CGST/IGST

Posted Sales Credit Memo

⁠1. 104003 - IGST
⁠2. 104004 - CGST/IGST

**Comment by sandhya3k** [comment]
@audhi3k 

Can we discuss for fieldmapping shipping details and remianing fields in invoice and credit memo?

cc : @3ktech

**Comment by 3ktech** [comment]
hi @audhi3k , as discussed, please share the design for the further enhancement to decide the ship to / bill to

**Comment by 3ktech** [comment]
@sandhya3k , deploy the change in the Keltech and assign it to Internal QA

**Comment by sandhya3k** [comment]
i published in the keltech environment. 
![image](https://github.com/3ktech/General/assets/114206737/2bec0c15-af8b-4ec8-827e-8a15ace45aa0)

cc : @3ktech  @audhi3k

**Comment by sandhya3k** [comment]
@3ktech @shivakumar3k 

I have mapped the shipping details need to test. can u please create a one doc with GST reg no?

cc : @audhi3k

**Comment by audhi3k** [comment]
Testing on Keltech E-Invoicing
