### ISSUE TITLE
Invoice Creation Issue in IBL Company

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#624]
**The Ship-to Address does not exist. Identification fields and values: Customer No.='IBLC000006',Code=''**

![Image](https://github.com/3ktech/General/assets/116171982/419f5f43-5511-4e74-bcc9-eb5696e3502a)

**Comment by TabrejAlam3K** [comment]
Hi Mr. Kartik D @3ktech - Manual Invoice creation issues, this is on high priority task because invoice is stopped.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Session done with LKS Team raise the below issues.

1. Address is not appearing on the Report (IBL Draft GST-50161)
2. Event Date (Dimension value not appearing )
3. GST Amount Calculation
4. IBL GSTIN No.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Can you help us on the Report


![Image](https://github.com/3ktech/General/assets/116171982/bd856ac9-3898-4cdb-8da9-8ac99204c7ba)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/eed2d38b-da3a-4ab7-bf74-ae13a781edde)

**Comment by TabrejAlam3K** [comment]
NAV 16 Output

![Image](https://github.com/3ktech/General/assets/116171982/42aab4f5-bad8-4bd0-a316-fa6cdb375d2c)

**Comment by TabrejAlam3K** [comment]
Tested in UAT Environment it is working and same highlighted to the Client (Mr. Viswanathan Sir). He will test and confirm then we will move the changes into the production Environment.

CC : @audhi3k

**Comment by sruthi1017** [comment]
hi @TabrejAlam3K all changes done as per the requirement and adjusted the amount to decimal places also. U can test now.
CC: @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - As per our discussion.

GSTIN of the Recipient,  Phone No., email id and event date is not fetched in the print invoice. Although CGST and SGST details are calculated and shown, they are not getting totaled for invoice value. 

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Can you please complete it.

![Image](https://github.com/3ktech/General/assets/116171982/d7867f56-e44d-4b38-b046-16d669ee452b)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
As per the yesterday session with Mr. Viswanathan Sir, He tole me to do the GST setup for IBL Company alone. It will be impacting all the financial entries also.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Deployed in the Production Environment. Tested and confirmed by the Client (Mr. Viswanathan Sir).

Closing this ticket as completed.

CC : @audhi3k
