### ISSUE TITLE
Invoice discount is not getting deducted in the reports

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#627]
Hi @sruthi1017 Invoice discount is not getting deducted in the reports please check it 

![Image](https://github.com/3ktech/General/assets/125632927/4530cb6a-ab9e-4d68-a6cf-e58560df4131)

CC: @audhi3k

**Comment by sruthi1017** [comment]
hi @Ejaz3KT all changes has been done test it and update if need any changes

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I`ve tested the reports and it is working fine 

![Image](https://github.com/3ktech/General/assets/125632927/643ec67d-fd6c-40dd-a76b-a0526c9ebcb6)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Client has confirmed and it is working fine we can close the ticket

CC: @audhi3k @sruthi1017
