### ISSUE TITLE
FA Reg Report New Modification

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#631]
**FA Report excel (50104, Report Request)**

**Comment by niranjand22** [comment]
cc @sruthi1017 

[FA Customer Report_MDT_RSP (2).xlsx](https://github.com/3ktech/General/files/12356713/FA.Customer.Report_MDT_RSP.2.xlsx)

**Comment by sruthi1017** [comment]
hi @niranjand22 , all changes done according to the requirement. the changes are available in sandbox. test and update need to any changes
CC: @audhi3k @3ktech

**Comment by niranjand22** [comment]
Hi @sruthi1017 . in Sandbox data is not available..pls deploy to live environment

**Comment by sruthi1017** [comment]
hi @niranjand22 , all the changes have been deployed into the production can u pls test and update
CC: @3ktech

**Comment by audhi3k** [comment]
Mr @TabrejAlam3K, can you take up this activity - test and release to the client by today

**Comment by TabrejAlam3K** [comment]
[FA Customer Report (11) (1).xlsx](https://github.com/3ktech/General/files/12425890/FA.Customer.Report.11.1.xlsx)

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k and Ms. @sruthi1017 - Please deploy it in the production Environment.

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k and Ms. @sruthi1017 - Please deploy it in the production Environment.

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - You are still having the publishing issues. Please let me know once it will get resolved.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Please update your current status here.

**Comment by sruthi1017** [comment]
hi @TabrejAlam3K as we discussed i am unable to publish my changes into sandbox environment of merit still i am facing the same issue

**Comment by 3ktech** [comment]
@sruthi1017 , i got  confirmation from @audhi3k  to deploy in production. please deploy and confirm us.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - While running the report facing some errro.

![Image](https://github.com/3ktech/General/assets/116171982/95eab07a-c97d-410f-9b85-c344fcfcdbc8)

CC : @audhi3k @3ktech

**Comment by sruthi1017** [comment]
hi @TabrejAlam3K code need tobe debug and check in andbox environment we need to login into sandbox CC : @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Please update your comments here.

CC : @audhi3k @3ktech

**Comment by sruthi1017** [comment]
hi @TabrejAlam3K , all changes done as per the client requirement and the data is also coming correct in header part, tested in the sandbox environment. need to publish in the production 
cc : @3ktech @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - You can publish it in the Production Environment. They will test in Production only.

CC : @audhi3k @3ktech

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

please test on production
cc : @audhi3k

**Comment by Jayanth3KT** [comment]
@niranjand22 Why I'm not able to see this ticket in case management system.

**Comment by TabrejAlam3K** [comment]
Ms. Swathi was busy on some other task so she will test and confirm.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Small changes required on this report and rest of things is working fine.
FA Posting Date : Value is not coming correctly.

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017  - Any update on. I need to close this ticket today

CC : @audhi3k @3ktech

**Comment by sruthi1017** [comment]
hi @TabrejAlam3K the changes has been done and it is working fine on the sandbox need to be deployed on live
cc: @3ktech @audhi3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K 
i deployed it in production

cc : @3ktech  @audhi3k

**Comment by TabrejAlam3K** [comment]
It has been deployed in the Production. I going to close the ticket because during the screen sharing session client asked for closure.

![Image](https://github.com/3ktech/General/assets/116171982/8740d512-3a46-4cd6-bcc1-f19cfa2b084f)

@Jayanth3KT - You can close this from the support portal also

CC : @audhi3k @Shasthara
