### ISSUE TITLE
Repair Job Work Order - Output require

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#632]
We are getting repeated error while sending the component to UL for job work.

![Image](https://github.com/3ktech/General/assets/116171982/ae29e015-6584-4694-b3c7-1ea0f255042d)

**Comment by TabrejAlam3K** [comment]
I was trying to connect with Mr. Rewat he is not available on system, He will connect after office hours.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Replicating the Same Scenario in Sandbox but facing some error.

![Image](https://github.com/3ktech/General/assets/116171982/da15ce49-2cc7-452c-83cd-9275baaa3179)

![Image](https://github.com/3ktech/General/assets/116171982/1db2a8ff-f596-40a2-be02-7c98b8bba583)

**Comment by TabrejAlam3K** [comment]
Technical Resource is not available from UL Side to debug the Issues.

CC : @audhi3k

**Comment by 3ktech** [comment]
hi @TabrejAlam3K , is there any action item required from my side. if so, please detail it.
Cc: @audhi3k

**Comment by TabrejAlam3K** [comment]
Information Passed to the Client over an Email.
Hi Mr. Rewat,

This issue was related to Document No. OU-JWO2324-00019 and it is already cleared, Please let me know if you have to face any issues.

[@Dhawal Shah](mailto:dhawal.shah@urbanladder.com) – As we have discussed I am available for the same time slot 11:00AM to 12:00PM whole week.
