### ISSUE TITLE
GST Percentage should bifurcate in purchase order preview

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#635]
"There is a two different GST percentages in the purchase line the system shows the bifurcation of those GST percentages in the purchase order preview report
Ex:  CGST 9% SGST 9%
       CGST 14% SGST 14%"

**Comment by sruthi1017** [comment]
hi @Ejaz3KT as per our discussion gst % is available in line wise, convince the client that it is not possible to add gst% in footer part
CC: @3ktech

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 client has shared for our reference a purchase order format if we see the format at the bottom there is a tax  bifurcation same thing they need in the purchase order report

![Image](https://github.com/3ktech/General/assets/125632927/b4a01d7a-7462-443c-a18a-4ba33bddd936)

CC: @audhi3k @3ktech

**Comment by sruthi1017** [comment]
hi @Ejaz3KT after u shared the refernce report i tried with hsn/sac but it is getting similar to the line level, as you are unable to connect yesterday, did u discuss with audhi mam? can we connect for this to explain the scenario.
CC: @3ktech

**Comment by 3ktech** [comment]
hi @sruthi1017  , i discussed with @audhi3k , it is doable. consider this change

**Comment by sandhya3k** [comment]
@Ejaz3KT 

can we connect for this?

**Comment by Ejaz3KT** [comment]
yes @sandhya3k madam

**Comment by sandhya3k** [comment]
@Ejaz3KT 

Once u done the field mapping please update here

cc : @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam Please find the Updated field mapping file

[PO Tax Information Field Mapping.xlsx](https://github.com/3ktech/General/files/12408829/PO.Tax.Information.Field.Mapping.xlsx)

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

Hi @Ejaz3KT, whatever u gave the field mapping, which is tax component, we have some restrictions to pick the field. 

Can u please give the different table to map the fields?

**Comment by sandhya3k** [comment]
@Ejaz3KT 

please check in sandbox environment?

cc : @audhi3k  @3ktech

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam I`ve tested the report the format and calculations are fine please make the alignment properly

![Image](https://github.com/3ktech/General/assets/125632927/000cf943-7e24-43c4-a950-c361bce9b650)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi, @sandhya3k Madam Please add the TDS column below the ISGT column and Add the IGST column after state tax in the purchase order report.

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

I hope, it is working fine please upadate ur comments?

cc : @audhi3k  @3ktech

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k  madam Please make the alignment properly in the purchase order report

![Image](https://github.com/3ktech/General/assets/125632927/e355f546-10e9-4119-8057-7e4a3b46137d)

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

please test on sandbox env?

cc : @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam I`ve tested this report I found the TDS amount is not printing properly in the report and please make the proper alignment of report

![Image](https://github.com/3ktech/General/assets/125632927/36f8ec39-34b3-43e0-ad80-310694350475)

![Image](https://github.com/3ktech/General/assets/125632927/bcb4e4d5-3ba4-430e-921d-c59006c07f0a)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam Have you fix this TDS issue in the purchase order report

**Comment by Ejaz3KT** [comment]
Hi, @sandhya3k madam every point in the report is coming & printing perfectly in the purchase order report except the alignment. Please make that alignment proper.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k madam I`ve check the alignment is perfectly coming in the report and please add the percentage and rupees symbol in the tax information table of purchase order.

**Comment by 3ktech** [comment]
@sandhya3k , this has been dragging a lot. please close this asap and update the effort

**Comment by sandhya3k** [comment]
@3ktech 

Every time it comes a new requirement after the done requirement comes alignment issues.   I will close the asp.

**Comment by Ejaz3KT** [comment]
Hi I've showcased the PO report to the client and waiting for the confirmation

CC: @audhi3k @sandhya3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

I have deployed in production please check
cc : @audhi3k

**Comment by Ejaz3KT** [comment]
Hi Report is fine Client has confirmed so I am closing this ticket

CC: @audhi3k @sandhya3k
