### ISSUE TITLE
System should accept HSN Code without selecting the GST group code

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#636]
When there is a foreign vendor the system should accept the HSN without GST group code

**Comment by 3ktech** [comment]
hi @Mahesh3ktech , connect with @Ejaz3KT for this task

**Comment by sruthi1017** [comment]
hi @Ejaz3KT as i mentioned GST group code is primary key in HSN/SAC table with out primary key we can not do it.
CC: @3ktech

**Comment by Ejaz3KT** [comment]
Hi ok @sruthi1017 ok I will convey the same to the client

**Comment by Ejaz3KT** [comment]
Hi I`ve convinced the client we can create a GST group code like GST 00 and map the HSN code for information in the report so she agreed on it we can close this ticket

CC: @audhi3k @sruthi1017
