### ISSUE TITLE
Fervid team wants User manual for PO,SO & the vouchers

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#637]
The fervid team asking for a user manual for Purchase order, sales order, and the vouchers

**Comment by 3ktech** [comment]
hello @Ejaz3KT , May i know why this task is tagged with "Development Required" as Yes

**Comment by Ejaz3KT** [comment]
Hi @3ktech By mistake it is tagged as Yes

**Comment by audhi3k** [comment]
Discuss with Ms Sarika

**Comment by Ejaz3KT** [comment]
Hi @Jayanth3KT As I explained to you how to prepare the document please reach out to me if you have any queries

CC: @audhi3k

**Comment by Jayanth3KT** [comment]
Hi @Ejaz3KT As you explained I have completed the User manual for PO.SO and Vouchers.


[User manual for PO,SO,Vouchers.docx](https://github.com/3ktech/General/files/12450192/User.manual.for.PO.SO.Vouchers.docx)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Jayanth3KT I`ve shared the user manual with the fervid team we can close this ticket

CC: @audhi3k

**Comment by audhi3k** [comment]
Shared with client
