### ISSUE TITLE
List of Report related to Mail Trigger

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#65]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

Report ID | Report Caption | Comments| Status
-- | -- | -- | --
50163 | Mail To owner 1 | Mail   is generated and excel generated in folder c:\WindowTestOwn1 is enclosed | Completed
50112 | Mail To owner | Mail is generated and   excel file generated in folder c:\WindowTest is enclosed | Completed
50127 | Mail To Group Head | Mail is generated and   excel file generated in folder c:\Group Head collection is enclosed | Completed
50166 | Outstanding Bill Mail   Owner1 | Mail is generated and   excel file generated in folder c:\Bill_CRN_Merged_Report is enclosed | Completed
50141 | Outstanding Bill Mail   Owner | Mail is generated and   excel file generated in folder c:\Bill_CRN_Merged_Report is enclosed | Completed
50142 | Mail Bill To Group   Head | Mail is generated and   excel file generated in folder c:\Bill_CRN_GroupHead_Wise is enclosed | Completed
50158 | Mail To Sub-Group   Owner | Mail is generated and   excel file generated in folder c:\Subgrp Owner2 Collection is enclosed | Completed
50159 | Mail Bill To Sub   Group Head | Mail is generated and   excel file generated in folder c:\Bill_CRN_SubGroupHead_Wise is enclosed | Completed
50164 | Mail Cust. Aging (All   Groups) | Mail is generated and   Report generated in excel and enclosed | Completed
50145 | Customer Aging Mail | Email Generation | Completed
50172 | Email Dig Sign | Email Generation | Digital Signature.

</body>

</html>

**Comment by panduc** [comment]
@TabrejAlam3K Completed Email triggering report. did completed the unit testing as well. As per the could Bc solution has created. Defined as processing only report and it  will pop up completed message.

To Email id tagged from Dimension value table. Please refer below details it might  help  for testing.

50163 --> "Dimension Value".Owner_2Email
50112 --> "Dimension Value".Owner_2Email
50127 --> "Dimension Value"."Group_Head Email"
50166 --> "Dimension Value".Owner_2Email,"Dimension Value"."Additional Email",
50141 --> "Dimension Value".Owner_2Email
50142 --> "Dimension Value"."Group_Head Email"
50158 --> "Dimension Value"."Group_Head Email"
50159 --> "Dimension Value"."Group_Head Email" property: DataItemTableView = WHERE("Dimension Code" = FILTER('SUBGRP-OWNER2'));
50164 --> "Dimension Value".Owner_2Email or "Dimension Value"."Group_Head Email"

50145-->
  IF ContactRec."E-Mail" <> '' THEN BEGIN
    ToEmail := ContactRec."E-Mail";
    EmailCheck := TRUE
  END ELSE
    ToEmail := 'viswa.accounts@lakshmisri.com';

Please reachout to me if any support needed.

**Comment by panduc** [comment]
input Date Filter: 10012022 to 10252022

**Comment by sandhya3k** [comment]
@TabrejAlam3K   

Please refer these dimensions.

50163 -->dimension code = filter (OWNER1)
50112 -->dimension code = filter (OWNER2)
50127 -->Dimension code = filter(GROUPHEAD)
50166 -->Dimension code = filter(OWNER1)
50141 -->Dimension code = filter(OWNER2)
50142 -->Dimension code = filter(GROUPHEAD)
50158 -->Dimension code = filter(SUB-GRP OWNER2)
50159 --> "Dimension Value"."Group_Head Email" property: DataItemTableView = WHERE("Dimension Code" = FILTER('SUBGRP-OWNER2'));
50164 -->   Aging reports u have to choose customer and change email id in it's contact
50145 --->  IF ContactRec."E-Mail" <> '' THEN BEGIN
ToEmail := ContactRec."E-Mail";
EmailCheck := TRUE
END ELSE
ToEmail := '[viswa.accounts@lakshmisri.com](mailto:viswa.accounts@lakshmisri.com)';

**Comment by TabrejAlam3K** [comment]
50127 - Mail To Group Head - Completed and data is matched

**Comment by TabrejAlam3K** [comment]
50166 - Pending
50141 - Pending
50142 - Pending
50158 - Pending
50159 - Pending

CC @audhi3k

**Comment by TabrejAlam3K** [comment]
Mail trigger is working for all the reports now I marked this ticket into closed.

**Comment by sandhya3k** [comment]
ok @TabrejAlam3K

**Comment by TabrejAlam3K** [comment]
@sandhya3k  I will create separate ticket for data mismatch for below reports.

50142 - Data Mismatch
50158 - Data Mismatch
50159 - Data Mismatch

CC @audhi3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K please check whether the data is coming from sales invoice header or customer ledger entry or credit memo?

cc : @audhi3k
