### ISSUE TITLE
Accrual Test report in Sandbox PDF Alignment New Requirement-CAS-01461-J4H8H0

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#653]
**Total Effort Hours - 10 Hours
Total Approved Effort Hours - 10 Hours**

Layout Example File.

![Image](https://github.com/3ktech/General/assets/116171982/0e08772b-a387-41b6-a4ca-cbe5db99a9fa)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - As per our discussion please start working on it. Please share the time effort for this how much you have required for the development.

Requirement - Need to set the PDF Report alignment (Data is coming correctly).


CC : @audhi3k @3ktech @narayana3kt @Shasthara

**Comment by TabrejAlam3K** [comment]
Time effort share with the client, Once approved will start working on it.

**Total time effort Required – 10 Hours (Development+Testing+UAT+Deploy).**

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Approval Received from the Client side, Please start working on and finish this today as we have committed.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by 3ktech** [comment]
hi @TabrejAlam3K I had discussed with @audhi3k  and concluded that aesthetical changes are not required to deliver. Kindly test abd deliver the report without alternate color in the grid.

**Comment by audhi3k** [comment]
Mr @TabrejAlam3K  what's the status of this ticket is

**Comment by TabrejAlam3K** [comment]
Hi @audhi3k Mam, I have tested and passed the same information with the client for Unit Testing.

**Comment by TabrejAlam3K** [comment]
Client need to test in the sandbox environment, based on their comments we will move the changes into the Production Environment.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k  - Approval received from the client to move the changes into the Production Environment. Please move the changes into the Production Environment and let me know.

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k  - Please deploy it in the production Environment.

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k  - Merit Accrual Schedule Report you have published in the Production but it is not reflecting, Please cross check once again.

CC : @audhi3k @3ktech

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K Problem Has been fixed now. you can check in on Production and confirm.
CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Tested in the Production Environment and found the heading of the report is coming correctly.

[Accrual Schedule in BC PDF Report.pdf](https://github.com/3ktech/General/files/12474723/Accrual.Schedule.in.BC.PDF.Report.pdf)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
1. The Column should freeze on every page
2. GL Account No. should be left alignment
3. Closing Balance is not matching with TB (01-10-22 to till date)

**Comment by TabrejAlam3K** [comment]
I am going to create a new ticket with new requirement. Closing this ticket

CC : @audhi3k @rohit3k
