### ISSUE TITLE
Work order filed to be add in purchase header

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#655]
Hi create new field name as work order in purchase header, If we select work order in that field the print preview should show work order report If it is blank it show purchase order report

**Comment by sruthi1017** [comment]
hi @Ejaz3KT it is done can u test and update
CC: @3ktech

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017, ok I`ll test and update you 

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
HI @sruthi1017 when I am selecting the work order in the work order field in the purchase quote or order I am facing this issue and the report is not generating

![Image](https://github.com/3ktech/General/assets/125632927/777879b2-083c-4a28-9c3e-a8fe7895cae0)

CC: @audhi3k

**Comment by sruthi1017** [comment]
in which company you are testing @Ejaz3KT , in sandbox of FERVID SMART SOLUTIONS PRIVATE LIMITED it is working fine can u test it once again
CC: @audhi3k @3ktech

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 ok I`ll test and update you

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 when I am clicking on print the system pop up both purchase order report and work order report at the same time and the work order field is only available in purchase quote page in purchase order page it is not available please check this issue.

**Comment by sruthi1017** [comment]
hi @Ejaz3KT all changes has been done u can test and update
cc: @3ktech

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I`ve tested the work order report it is working fine please deploy this in the production.

CC: @audhi3k

**Comment by sruthi1017** [comment]
hi @Ejaz3KT the deployment has been completed.
CC: @3ktech

**Comment by Ejaz3KT** [comment]
Ok @sruthi1017 I have tested this work order report in production and it is working fine

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi, I`ve given the UAT to Ms. Jhansi Madam she has confirmed it is fine we can close this ticket.

CC: @audhi3k @sruthi1017

**Comment by audhi3k** [comment]
Confirmed by the client
