### ISSUE TITLE
Finance Report - Posted sales Invoice PDF ID - 50167

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#66]
This report is running based on Users

User Validation is working fine in NAV16 but in BC Validation is not working.

**Comment by panduc** [comment]
User name is hard coded and File is storing in Local user drive as PDF. File storing in Local user drive is not feasible in Cloud. I will check the alternative option.

**Comment by panduc** [comment]
@TabrejAlam3K It is working fine. Attached the sample output

[LKS16-2223-00477.Pdf](https://github.com/3ktech/General/files/10527995/LKS16-2223-00477.Pdf)

**Comment by TabrejAlam3K** [comment]
Done
