### ISSUE TITLE
Sales order report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#660]
Hi I am requesting the technical person to create a sales order report same as a sales quote

**Comment by Ejaz3KT** [comment]
Hi I`ve assigned a sales quote report for the sales order it is working fine but we need to change the caption in the header and need to add tax information and the total amount of the sales order at the bottom

![Image](https://github.com/3ktech/General/assets/125632927/515a47a4-0785-4d86-a68f-d568002cab2c)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
HI @Manoj01021999 As we discussed in the call please develop the report as per the requirement.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Manoj01021999 The sales order captions are coming properly please develop the footer part also as per the requirement

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

can we connect for this ?

 cc : @3ktech  @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 


![Image](https://github.com/3ktech/General/assets/114206737/a24419bc-7529-42aa-a676-4f4941da3863)

can u test the sandbox environment?

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam I`ve tested the report the GST Percentage is not calculating and if there is two different GST Percentage only one GST Percentage showing in the lines please resolve this issue.

![Image](https://github.com/3ktech/General/assets/125632927/34f6d389-235f-42a5-8192-c7107043ccc9)

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

can you share the doc no and estimated output?

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam please find the sales order document No. Fss-SO-MP4/2324/0007

**Comment by sandhya3k** [comment]
@Ejaz3KT 

Now, it is working fine please test?

cc : @3ktech @audhi3k

**Comment by Ejaz3KT** [comment]
HI @sandhya3k Madam I`ve tested the sales order report it is working fine and There is a new requirement from the client is to be add TCS field in sales order report. So please add TDS field below IGST field.

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam please make the proper alignment in the sales order report some points are not printing in the report that needs to be added 
1. Bank details are not printing
2. Add TCS field in the report

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

shell we discuss on above points?

**Comment by Ejaz3KT** [comment]
Hi @ Sandhya Madam Please find the find the field mapping of bank account details

![Image](https://github.com/3ktech/General/assets/125632927/601fb5ec-74ba-4913-a211-96a333d4cf01)

Sales header. company bank account
Bank name : Bank account(270). Name
Account No. :  Bank account(270). Bank Account no.
Branch :  Bank account(270). bank branch no.
IFSC Code :  Bank account(270). IFSC Code

**Comment by sandhya3k** [comment]
@Ejaz3KT 

please test on sandbox env?

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam I`ve tested the report the TCS amount is not adding to the total amount

![Image](https://github.com/3ktech/General/assets/125632927/bfbee73c-d535-4292-bcb1-69d4f822fece)


![Image](https://github.com/3ktech/General/assets/125632927/838af114-6d28-46c0-959d-9c5fb58ea5f3)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam Have you fix this TCS issue in the report

**Comment by Ejaz3KT** [comment]
Hi, @sandhya3k madam sales order is working fine please deploy this in the production environment and also please find the final output of the sales order report.

[document (6).pdf](https://github.com/3ktech/General/files/12476485/document.6.pdf)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi The report is fine and it is generating properly now I am going to close this ticket.

CC: @audhi3k
