### ISSUE TITLE
Reports are not available & not generating in business central

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#661]
Hi when I am testing the reports inn business central some of the reports are not available and some reports are not generating showing error when running the report I`ve mentioned the reports below:

50010 | Material Consuption   Chit
50014 | Update Posted Sales   Invoices
50015 | BRS Report
50021 | Domestic Sales   Invoice
50022 | Inventory Correction
50023 | Sales Shipment Report
50025 | Transfer Order Resp CenterUpdate
50027 | Stock Transfer   Register
50029 | Month Wise Item Sales   Report
50090 | Sales   Register-itemwise for AM
50096 | Sales Register for AM

CC: @audhi3k @Amar-3KT

**Comment by Mahesh3ktech** [comment]
hi @Ejaz3KT - Please find the status of the below mentioned reports.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">




Report ID | Report Name | Status
-- | -- | --
50010 | Material Consuption Chit | Working - Available   for testing
50014 | Update Posted Sales   Invoices | Process Only Report -   Available for testing
50015 | BRS Report | Not Woeking in 2016
50021 | Domestic Sales   Invoice | Working - Available   for testing
50022 | Inventory Correction | Process Only Report -   Available for testing
50023 | Sales Shipment Report | Report commented need   more input to fix the deleted table and fields
50025 | Transfer Order Resp   CenterUpdate | Process Only Report -   Available for testing
50027 | Stock Transfer   Register | Not Woeking in 2016
50029 | Month Wise Item Sales   Report | Report commented need   more input to fix the deleted table and fields
50090 | Sales   Register-itemwise for AM | Working - Available   for testing
50096 | Sales Register for AM | Report commented need   more input to fix the deleted table and fields



</body>

</html>

CC: @3ktech, @audhi3k, @Amar-3KT

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech Please find the latest update on following reports


[Keltech - Reports.xlsx](https://github.com/3ktech/General/files/12448526/Keltech.-.Reports.xlsx)

CC: @audhi3k

**Comment by Mahesh3ktech** [comment]
hi @Ejaz3KT - for the report 50010 - Material Consuption Chit as per 2016 added the entry type filter. kindly check.

CC: @3ktech, @Amar-3KT, @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech I`ve tested the (50010) report it will not generate it is showing the error when I am running the report

![Image](https://github.com/3ktech/General/assets/125632927/f869b352-c302-4ee0-84f0-e98c2ed95e96)

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech I`ve tested the reports some of the reports are still not working (Generating) Please check that report which I mentioned below

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/sheik/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/sheik/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

<div ccp_infra_version=3 ccp_infra_timestamp=1693475065175 ccp_infra_user_hash=3557057386
ccp_infra_copy_id=7b5b16bd-b6b5-4342-a532-a58befee3b65 data-ccp-timestamp=1693475065175>



Report Id | Report Name | Comments
-- | -- | --
50010 | Material Consuption   Chit | Report is not   generating showing as date valid
50014 | Update Posted Sales   Invoices | Report ID is not   available in both Nav & business central
50015 | BRS Report | System is showing as   data is not valid
50022 | Inventory Correction | Report ID is not   available in both Nav & business central
50025 | TransferOrderRespCenterUpdate | Report ID is not   available in business central
50027 | Stock Transfer Register | Report   coming blank in Nav     Report is not generating in BC
 



</body>

</html>



CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech The reports which are assigned to me  for testing that all the reports are available and working fine except this 50014(Material Consumption Chit)  Please fix these reports issue and update me.

CC: @audhi3k

**Comment by audhi3k** [comment]
Mr @Mahesh3ktech  - can you update on the status of the report - 50014 - CC Mr @Ejaz3KT

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech please update the status of the 50014 report

**Comment by 3ktech** [comment]
@Mahesh3ktech , can you updated your comment here?

**Comment by 3ktech** [comment]
@Ejaz3KT , as discussed, the report 50014 is not priority for go live, i am parking it here. Please create another ticket when there is a requirement of this report.
Cc: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi As I got to know report 50014 is not a priority for going live so I am closing this ticket in the future any requirement is raise related to this report we will create a new ticket for that issue.

CC: @audhi3k @3ktech @Mahesh3ktech
