### ISSUE TITLE
Advance Bank Receipt voucher

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#662]

**Comment by Prakash3K** [comment]
1. We will receive advance amount received form customer  for that we required “ Advance Bank Receipt voucher” in that following details need to deploy  

•	Customer name, address and GSTIN
•	Serial number of the receipt voucher, not exceeding 16 characters, containing alphabets or numerals or special characters hyphen (-) or slash (/). It must be unique for a financial year
•	Date of issue
•	If the recipient is registered, the recipient’s name, address and GSTIN or UID
•	Description of the goods or services
•	Amount of advance taken
•	Rate of tax (CGST, SGST, IGST, UTGST or Cess)
•	Amount of tax (CGST, SGST, IGST, UTGST or Cess)
•	If the supply is interstate, the place of supply, along with the state name and the state code
•	Whether tax is payable on reverse charge
•	Signature or digital signature of the supplier or his authorized representative

 
2. We required Columnar Register for "GST on Advance Received " GL

**Comment by TabrejAlam3K** [comment]
Client need to share the format with us.

**Comment by shivakumar3k** [comment]
@Prakash3K please check with customer and update the status

**Comment by Prakash3K** [comment]
@audhi3k, Client shared format for Advance Bank Receipt.

[Advance Receipt voucher.xlsx](https://github.com/3ktech/General/files/12494590/Advance.Receipt.voucher.xlsx)

**Comment by 3ktech** [comment]
hi @Prakash3K , share field mapping for this report to start the development

**Comment by audhi3k** [comment]
Format seems not a receipt voucher

**Comment by rohit3k** [comment]
Hi Mr. @shivakumar3k can we have call on this.
cc: @audhi3k @3ktech @gsudarsan3k

**Comment by rohit3k** [comment]
Hi Mr. @Prakash3K Please update on this ticket once you will have discussion with client. as per our conversation we don't have update on this ticket from client.

cc: @audhi3k @3ktech @gsudarsan3k

**Comment by Prakash3K** [comment]
Hi @rohit3k sir, kindly provide your effort hours for this ticket.

CC: @audhi3k @gsudarsan3k

**Comment by Prakash3K** [comment]
[Advance Bank Receipt Voucher.xlsx](https://github.com/3ktech/General/files/12995656/Advance.Bank.Receipt.Voucher.xlsx)

@gsudarsan3k @rohit3k @Tushargupta3K

**Comment by Prakash3K** [comment]
Hi @rohit3k, client approved effort hours, kindly start working.


CC: @audhi3k @Tushargupta3K @gsudarsan3k

**Comment by Prakash3K** [comment]
Hi @sandhya3k ma'am, kindly update status.

CC: @audhi3k @gsudarsan3k

**Comment by sandhya3k** [comment]
@Prakash3K 

please test on UAT environment

**Comment by Prakash3K** [comment]
Hi @sandhya3k ma'am- As per our discussion, kindly make changes in report.


CC: @audhi3k @Tushargupta3K

**Comment by sandhya3k** [comment]
@Prakash3K 

please test

cc : @audhi3k

**Comment by sandhya3k** [comment]
@Prakash3K 

please test

**Comment by Prakash3K** [comment]
Due to internal discussion of pioneer team using applying advance on sales invoice ( Application ), ticket will be kept in hold.


CC: @audhi3k @Tushargupta3K

**Comment by Prakash3K** [comment]
Considering the client's requirement to postpone the ticket until March, we are closing this ticket now.


CC: @audhi3k @Tushargupta3K
