### ISSUE TITLE
Delivery Challan should have 3 copies - Original, Duplicate, Triplicate (CAS-01421-X7C0D5)

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#665]

**Comment by 3ktech** [comment]
3 copies to be printed. original, duplicate, triplicate

**Comment by audhi3k** [comment]
Mr Karthik @3ktech hope you have align the case to technical

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech - Please assign the technical.

CC : @audhi3k

**Comment by sruthi1017** [comment]
hi @TabrejAlam3K  changes has been made can u test and update whether it is working fine or not??
cc: @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Report itself not working as i was shown to you during screen sharing session.

![Image](https://github.com/3ktech/General/assets/116171982/b1125f2c-0674-4b77-81b1-24f64dbd9eb6)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - When we can connect on this issues.

CC : @audhi3k  @3ktech

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K - Lets Connect now..

CC : @audhi3k @3ktech

**Comment by 3ktech** [comment]
access to the Platinum Stage database is not given yet. Waiting for the access. @TabrejAlam3K , @Shasthara  can you please help here to get the access?

**Comment by rohit3k** [comment]
Report Is Getting Printed in Multiple Copy but name is Not Getting Printed like Original Duplicate Triplicate.. So i am working on It @TabrejAlam3K  @3ktech

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K Changes has been done as per requirement please check. 
CC:  @audhi3k @3ktech @Sarikab1222

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Sr No. is missing on line level it is required else let me do the UAT with the client

[Delivery Challan Report New.pdf](https://github.com/3ktech/General/files/12482047/Delivery.Challan.Report.New.pdf)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
No Response received from the client side.

**Comment by TabrejAlam3K** [comment]
Waiting for Customer Confirmation

CC : @audhi3k @Jayanth3KT @Shasthara

**Comment by TabrejAlam3K** [comment]
Yesterday follow up with the client over an email, but still no response receive form the Client side.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please move the changes into the Production Environment. After your confirmation we will close this ticket.

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
Hi Ms. @Sarikab1222 - Due to non response from the client side. Please confirm for closure.

CC : @audhi3k @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Have you move the changes into the Production Environment? After your confirmation we will close this ticket.

CC : @audhi3k @Sarikab1222

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K As per our discussion I need a session with client to get the access of Production DB to deploy the changes.

cc: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please share the effort hours for thsi issues.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - This is deployed on the Production Environment infront of the Client. You can close this from the support portal as well.
**Total Effort Hours = 20 Hours**

CC : @audhi3k
