### ISSUE TITLE
Reports are not available, not generating & Alignment issues in business central.

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#666]

**Comment by Prakash3K** [comment]
Hi when I am testing the reports inn business central some of the reports are not available and some reports are not generating showing error when running the report I`ve mentioned the reports below:


50008:  Domestic Posted Sales invoice- Report is not generating. 
50024:  Sales Credit memo Report- Instead of showing the sales credit memo report, it displaying the "Domestic Posted Sales invoice" report under this ID.
50031: Purchase Reg Itemwise- Report ID not available in BC.
50035: Vendor_Register- Not working.
50038: Posted Transfer Shipment2.0- Report ID not available in BC.
50097: Update GL Entry- Report ID not available in BC.
50098: Update Product Group- Report ID not available in BC.

**Comment by sandhya3k** [comment]
Hi @Prakash3K 

50008: Domestic Posted Sales invoice: Working (Please add the filter No.) then click on preview.
50035: Vendor Register- Working but two fields are missing which i shared on below screen shot so, I removed those two fields in the layout.
![image](https://github.com/3ktech/General/assets/114206737/077fea64-e271-4ada-bc5b-3bd2c36658f7)

50024: Sales Credit memo Report- Report caption is different, layout is same 
50031: Purchase Reg Itemwise-Report commented that needs more input to fix the deleted table and fields.
50038: Posted Transfer Shipment2.0- Report commented need more input to fix the deleted table and fields.
50097: Update GL Entry- Report commented need more input to fix the deleted table and fields.
50098: Update Product Group - Process Only Report - Available for testing.

cc : @audhi3k

**Comment by shivakumar3k** [comment]
@Prakash3K Kindly test and update the status.

**Comment by Mahesh3ktech** [comment]
hi @shivakumar3k - report 50024 issue is fixed. kindly check and update.

CC: @3ktech, @audhi3k

**Comment by audhi3k** [comment]
Create new ticket
