### ISSUE TITLE
Order Fulfillment Issues

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#668]

**Comment by TabrejAlam3K** [comment]
Hi @audhi3k Mam, Can you please check the code between Sandbox to Production with technical.

**Comment by audhi3k** [comment]
The code is not moved to LIVE, waiting for LIVE access

**Comment by TabrejAlam3K** [comment]
Today 11:00AM to 12:00PM session we will fixed it.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We have successfully merge the code in the Production Environment. Client need to test and confirmed. 

CC : @audhi3k

**Comment by audhi3k** [comment]
Confirmed by client
