### ISSUE TITLE
Credentials for the creation of collection entries at Branch level-CAS-01425-M5J5R0

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#670]
**Credentials for the creation of collection entries at Branch level**

Display name: Chandigarh BC (Username: chandigarh.bc@lakshmisri.com)
Display name: Jaipur BC (Username: Jaipur.bc@lakshmisri.com)
Display name: Gurgaon BC (Username: gurgaon.bc@lakshmisri.com)
Display name: Nagpur BC (Username: nagpur.bc@lakshmisri.com)
Display name: Allahabad BC (Username: allahabad.bc@lakshmisri.com)

[Branch credentials.docx](https://github.com/3ktech/General/files/12593819/Branch.credentials.docx)

**Comment by TabrejAlam3K** [comment]
I have already asked client to share the issues details over an email mySupport@3ktechnologies.com

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Please create this ticket on Support Portal.

CC : @audhi3k @niranjand22

**Comment by TabrejAlam3K** [comment]
@TabrejAlam3K - Will start working on today, If required approval for the same then get the approval from the Client.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Error while login

![Image](https://github.com/3ktech/General/assets/116171982/87f5faa9-8e23-4b4a-9cbc-b8234064c318)

**Comment by 3ktech** [comment]
@TabrejAlam3K , may i know what is required from developers for this ticket?

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech - I have try to login the system but still showing some error. See the error snapshot on previous comments.

CC : @audhi3k

**Comment by 3ktech** [comment]
did u setup the permission for all of these users for the above mentioned object?

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech - See the Snapshot of Role Center Page which are missing from the List.

1. Display name: Chandigarh BC (Username: [chandigarh.bc@lakshmisri.com](mailto:chandigarh.bc@lakshmisri.com))
2. Display name: Jaipur BC (Username: [Jaipur.bc@lakshmisri.com](mailto:Jaipur.bc@lakshmisri.com))
3. Display name: Gurgaon BC (Username: [gurgaon.bc@lakshmisri.com](mailto:gurgaon.bc@lakshmisri.com))
4. Display name: Nagpur BC (Username: [nagpur.bc@lakshmisri.com](mailto:nagpur.bc@lakshmisri.com))
5. Display name: Allahabad BC (Username: [allahabad.bc@lakshmisri.com](mailto:allahabad.bc@lakshmisri.com))

![Image](https://github.com/3ktech/General/assets/116171982/a5cf5acb-7ad6-437b-ad31-e8488d31404e)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Please share the time effort for the same we will take approval from the client.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Please share the effort hours how much you have required for this task.

CC : @audhi3k @3ktech

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - required effort hours are 4 hours.

**Comment by TabrejAlam3K** [comment]
Session completed with Mr. Bhupendra he will send the requirement over an email mySupport@3ktechnologies.com

**Comment by TabrejAlam3K** [comment]
Approval Request Send to the Client

![Image](https://github.com/3ktech/General/assets/116171982/ffb8550f-ffd9-432f-90a2-efee3dfe4e44)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Effort hours not approved from the client side.

**Comment by TabrejAlam3K** [comment]
I have done the session with LKS Accounts Team they said you can assign the same role center for all the User like Hyderabad

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
I have done the User permission for creation of collection entries at Branch level.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Waiting for Customer Confirmation

CC : @audhi3k @Jayanth3KT @Shasthara

**Comment by TabrejAlam3K** [comment]
Mr. @TabrejAlam3K - I have done the changes whatever they have required and forwarded the same to the Client. He will test and confirm.

**Comment by TabrejAlam3K** [comment]
Due to non response from the client side I am going to close the tickets. If raise again will created as new ticket.

CC : @audhi3k @Prakash3K @Shasthara
