### ISSUE TITLE
Loan as Dimension on the Loan Integration

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#673]
Requirement - Create Loan Id as Dimension while processing the Loan file and assign the respective Laon Dimension on General Journal Line.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - As per our discussion, Please let me know once it will get completed.

CC : @audhi3k @3ktech

**Comment by 3ktech** [comment]
hi @TabrejAlam3K , this task can not be In Progress. I need the approval to do this task until then it will be in New Status. Please change the status to Todo once approved
CC: @audhi3k , @Shasthara

**Comment by audhi3k** [comment]
This is approved, we can start with the development - Mr Karthik @3ktech

**Comment by audhi3k** [comment]
Check whether we can deliver the development by today - Mr @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - As per our discussion please see the below points.
Requirement - While Processing the Loan Data first you need to create a Loan Dimension With Loan Account No.
1. Create Loan Account No. as Dimension Value Code under the LOAN Dimension and Name should be Loan Account.
2. Assign **Applicant Code** as **Customer Dimension** and **Loan Account No.** as **Loan Dimension** on every Bank Receipt Voucher Lines.

See the below table and page references.
1. LMSLoanDetails (50102) Table
2. LMSLoanSubform (50107, ListPart) Page
3. Dimension Value (349) Table
4. Dimension Values (537, List) Page

CC : @audhi3k @Shasthara @3ktech

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - As discussed loan dimension development is done. kindly check and update.

CC: @3ktech, @audhi3k,

**Comment by TabrejAlam3K** [comment]
Mr. @Mahesh3ktech - As per our discussion we need to add the changes in the MS Flow, Have you discussed with Mr. Murali.

CC : @audhi3k @Shasthara @3ktech

**Comment by 3ktech** [comment]
@TabrejAlam3K the task is done from the tech perspective. we are waiting for Murali to support us. I have initiated a communication in the channel. please follow up with him for testing.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - this task is not related to Ms Flow I am doing testing and let you know once the testing will be completed.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - As per our discussion, While processing the Laon data I am facing some error based on your Loan Dimension Customization. Please let me know once it will get completed. 

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech  - I have tested for Loan Dimension for LMS_LoanData_28082023_V_1.0.csv@ 28/08/2023 05:43. It is working fine,
Scenario what i have tested
1. Import Loan Data
2. Process Loan Data
3. Dimension master get created with Loan Application No. under the Dimension Loan
4. Bank Receipt Voucher get Created with **Customer** & **Loan** Dimension (whatever the data is available on Loan data line wise).

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k  - I have done the UAT session with Vridhi Team They are ok with the Customization. He will test the scenario with New File Upload.
 
Note : Query they have raise - They want filter at the time of Dimension Value Selection for the Customer Dimension and Loan Dimension.

**Comment by TabrejAlam3K** [comment]
This is working fine and also show case to Mr. Dikshant during screen sharing session, I am closing this ticket as completed.

They have raise one query on the same ticket, will considered as new ticket.

@audhi3k @Shasthara
