### ISSUE TITLE
Alignment issues on reports in Business central

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#674]

**Comment by Jayanth3KT** [comment]
@Mahesh3ktech Alignment issues on report in BC as I mentioned below: 
50077-Production report
50009-Consumption report
50078-GRN report

**Comment by sandhya3k** [comment]
@Jayanth3KT 

The alignments have been completed which u mentioned in the above comments.
can u please check the sandbox environment?
cc : @audhi3k @3ktech

**Comment by Jayanth3KT** [comment]
@sandhya3k 

Working fine in sandbox environment.

CC: @audhi @3ktech
