### ISSUE TITLE
Immediate action required: Out of Database capacity-CAS-01434-Y4P3H8

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#689]

**Comment by TabrejAlam3K** [comment]
Mr. @Jayanth3KT - If you are going to create any ticket from the support portal, Please update all the requirement details whatever we have receive over an Email.

CC : @audhi3k @Shasthara @niranjand22

**Comment by audhi3k** [comment]
Mr @Jayanth3KT, why not the email is not forwarded to Mr @TabrejAlam3K

**Comment by audhi3k** [comment]
This is CRM case, hence closing it

**Comment by TabrejAlam3K** [comment]
Going to close the ticket because this ticket is related to the CRM Part.

CC : @audhi3k @Jayanth3KT
