### ISSUE TITLE
FW: ERP Error-Reg-CAS-01431-Y9N5D4

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#691]

**Comment by Jayanth3KT** [comment]
<html>
<body>
<p class="xmsonormal" style="margin: 0cm 0cm 0.0001pt; font-size: medium; font-family: &quot;Times New Roman&quot;, serif; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; background: white;"><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(36, 36, 36);"><br class="Apple-interchange-newline">               </span><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(66, 66, 66);">Refer to above subject, the following error is showing in ERP while raising a service invoice.<span> </span></span><span class="contentpasted4"><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(36, 36, 36);"> We give below the details of SR Nos. which is showing error. </span></span><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(66, 66, 66);">Kindly do the needful.</span><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(36, 36, 36);"></span></p><p class="xmsonormal" style="margin: 0cm 0cm 0.0001pt; font-size: medium; font-family: &quot;Times New Roman&quot;, serif; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; background: white;"><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(36, 36, 36);"> </span></p>

S. No. | SR. No.
-- | --
1 | SRKET/PW2021/1177
2 | SRKET/PW2122/0725
3 | SRKET/PW2122/0882
4 | SRTEN/PW2021/1343


</body>
</html>

**Comment by audhi3k** [comment]
Dear Mr Vivek,

We have fixed the issue, kindly check and confirm.

Analysis:
The service order (BDR) were not available for the highlighted document

Solution:
We have recreated the same.


Regards,
Audhi Lakshmi S

**Comment by audhi3k** [comment]
Dear Mr Vivek,

Thanks for confirming on closure

Regards,
Audhi Lakshmi S
