### ISSUE TITLE
There is nothing to post because the document does not contain a quantity or amount

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#692]

**Comment by Amar-3KT** [comment]
We are getting this error at the time of posting sales invoice.

**Comment by Amar-3KT** [comment]
@Mahesh3ktech - We are getting this error in purchase and sales process kindly check.

**Comment by Mahesh3ktech** [comment]
hi @Amar-3KT - we are not able find the error, could you please reproduce the error so it will help to debug and resolve.

CC: @3ktech, @audhi3k

**Comment by audhi3k** [comment]
Mr @Mahesh3ktech has fixed the issue in Sales and Purchase, Mr @Amar-3KT test and confirm

**Comment by Amar-3KT** [comment]
On sales invoice working fine but we are getting error in purchase order. Mr. @Mahesh3ktech Kindly check.

**Comment by Mahesh3ktech** [comment]
hi @Amar-3KT - purchase order error is resolved. kindly check and confirm.

CC: @3ktech, @audhi3k, @shivakumar3k

**Comment by audhi3k** [comment]
Issue is fixed in both purchase and sales
