### ISSUE TITLE
Commented Reports

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#699]

**Comment by sandhya3k** [comment]
@Amar-3KT 

can we connect on this ticket?

**Comment by 3ktech** [comment]
@sandhya3k , can you post your status for this task in channel
if you need any input, please highlight that as well

**Comment by sandhya3k** [comment]
@Amar-3KT 

can u please test the status as "working" reports?
[Keltech Working Report  (1).xlsx](https://github.com/3ktech/General/files/12464840/Keltech.Working.Report.1.xlsx)

cc : @3ktech  @audhi3k

**Comment by shivakumar3k** [comment]
@Ejaz3KT has to update the testing status.

**Comment by sandhya3k** [comment]
@Amar-3KT 

I have updated the below excel commented sheet please test accordingly. In the below excel total 23 reports are mentioned 3 of the reports are not working, which is 50031, 50032,50033.

[Keltech Working Report .xlsx](https://github.com/3ktech/General/files/12495582/Keltech.Working.Report.xlsx)

cc : @3ktech  @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam I`ve tested the commented reports, some reports are working fine and some of the reports are not working please check it
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/sheik/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/sheik/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Report Id | Report Name | Comments
-- | -- | --
50038 | Posted Transfer   Shipment2.0 | Working fine
50040 | Sales Invoice Report | Working fine
50045 | Sales Invoice Report   (Export) | Working fine
50046 | GSTR-3B New | Working fine
50059 | Daily Auto Mail - PDS | Report not available   in both Nav & BC
50060 | Daily Auto Mail | Report not available in both Nav   & BC
50065 | TDS Register | Report   available but not generating in BC
50067 | Update Item Values | Report   available but not generating in BC
50068 | Domestic Sales   Invoice 2.1 | GST is not calculating/PO no. not showing 
50069 | Export Posted I   Letter head | Total amount is not showing/ Buyer PO no.
50070 | Sales Invoice Report   2 | Working fine
50096 | Sales Register for AM | Report   available but not generating in BC
50097 | Update GL Entry | Report not available   in both Nav & BC



</body>

</html>

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k mentioned reports are having an issue
1. 50068 - GST is not calculated properly
2. 50069 - The invoice total amount is not showing properly

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k please update the status of This two 50068 & 50069 Reports 

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

we have commented on the code, i think the values are not calculating properly. so can u please provide the functionality that is incorrect.
cc : @3ktech  @audhi3k

**Comment by Ejaz3KT** [comment]
@sandhya3k Will Connect in a bit to discuss the functionality

**Comment by audhi3k** [comment]
Field mapping was shared

**Comment by audhi3k** [comment]
create new ticket for report
