### ISSUE TITLE
Field Length Issue

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#7]

**Comment by audhi3k** [comment]
@3ktech, can we look into the other fields

**Comment by audhi3k** [comment]
We can discuss on this at 5:30 for the rest other fields - @panduc

**Comment by audhi3k** [comment]
@TabrejAlam3K , co-ordinate with Mr KarthikD or Mr Pandu for the next field and initiate the process

**Comment by TabrejAlam3K** [comment]
As discussed with Mr. Pandu we need to analyzing the functionality of all the page first then need to connect with Mr. Pandu

**Comment by TabrejAlam3K** [comment]
@audhi3k - I am working on will update the status time to time.

**Comment by TabrejAlam3K** [comment]
@Mahesh3ktech - As per our discussion please tell me the exact way of testing because some of the table or page we couldn't able to find.

Please update on after discuss with Mr. Pandu and Ms. Sandhya

**Comment by TabrejAlam3K** [comment]
Need to sit with Ms. @audhi3k and analyzing the testing.

**Comment by TabrejAlam3K** [comment]
I have spending some times on this issues.

**Comment by TabrejAlam3K** [comment]
@audhi3k - As per our discussion with @3ktech Mr. Kartik. First some technical need to analyze the things and if they face any issue during the analysis then I will with him and provide the support to him.

@panduc - If you have any query can you please connect with Mr. Kartik.

**Comment by TabrejAlam3K** [comment]
Mr. Mahesh is working on we will provide the support if they required.

**Comment by TabrejAlam3K** [comment]
@TabrejAlam3K - Need to check the New Field Check No. and Description is populating on all the related tables. 

Bank Payment
Bank Receipt
Cash Payment
Cash Receipt
Contra Voucher
GL Entries and Preview
Bank Acc Led Entries and Preview

**Comment by TabrejAlam3K** [comment]
.

**Comment by panduc** [comment]
Mahesh has created the new fields in Table Extension.

I've shared NAV2016 LKS all Objects and explained him to setup Where used tool in his local machine and how to check a field reference is used in different place. & How that should be handled in BC.

**Comment by TabrejAlam3K** [comment]
@panduc - Thanks for the update 

I have tested the same now it is enabled on all the respective pages.

@audhi3k - I have tested the Custom Field **Cheque No.** and **Description** on all the respective journals pages pre and post documents it is coming correctly and the custom field is available on page labels.

**Comment by panduc** [comment]
Manoj has completed the Table Extension for new field addition, Page Extension to enable controls.

Next Action:
1. Manoj- He has to start with report- to map the new field instead of standard field.
2. Pandu- Business logic Enable- having issue with GIT(configuration which Sandhya working).

**Comment by panduc** [comment]
@sandhya3k started working on finalized fields. we have 9 fields to Enhance.

**Comment by sandhya3k** [comment]
@3ktech @audhi3k 

I have completed the tables and pages for field length issue. These extensions are available in UAT and Development environments.

Today @panduc was connected some time for "code units'" logics also we have completed.

Here is the list of excel for modified objects. please refer this attachment  @Mahesh3ktech  @Padma2717 

[7filedlength3kt-base Fields.xlsx](https://github.com/3ktech/General/files/11008331/7filedlength3kt-base.Fields.xlsx)

regarding this issue need to be done for reports.

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

The tables, pages, code units are completed please the test the UAT environment.

@audhi3k, I have enabled the fields in customized reports if require, base reports please send the list of reports
because of As per @panduc analysis some base reports are not using in the LKS development. 

 please refer the latest excel file.

[7filedlength3kt-base Fields.xlsx] (https://github.com/3ktech/General/files/11019978/7filedlength3kt-base.Fields.xlsx)

@3ktech need to analyze the state table of code[20] key field.

**Comment by TabrejAlam3K** [comment]
@sandhya3k - I will test and confirm regarding the same.

CC ; @audhi3k

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Some fields are not enabled and also not showing in personalize.


![Image](https://user-images.githubusercontent.com/116171982/227476798-80d95dd3-9f26-4dc8-aac0-e39578451f39.png)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
See the attached Excel.

[7filedlength3kt-base.Fields.xlsx](https://github.com/3ktech/General/files/11060334/7filedlength3kt-base.Fields.xlsx)

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Please connect once you free I will show you where i have to face the issues.

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Now It is working fine. We are moving this into UAT.

CC : @audhi3k

**Comment by panduc** [comment]
Hi @Ejaz3KT As discussed please prepare your analysis and discuss with BC Data migration team Karthik D, Padma A. Mahesh C. 

The final findings shall be discuss with Karthik D and Audhilakshmi

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - As per our yesterday discussion, have you analyzed the things whatever we discussed. Please let me know this is also on top priority points.

CC : @audhi3k @Shasthara @narayana3kt

**Comment by panduc** [comment]
@TabrejAlam3K  As discussed, I've revalidated Field length for the extended fields. it has been mapped to all the business area.

If you identified any issues. Please share us the objects details/ Business process where it fails to use extended fields.

There are 2 fields not extended. I'm extending it and share it with you for testing.

**Comment by panduc** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/PANDUR~1.CHI/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/PANDUR~1.CHI/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

<div ccp_infra_version=3 ccp_infra_timestamp=1681798297520 ccp_infra_user_hash=3015489902
ccp_infra_copy_id=7d205ed3-dec1-47fb-99e8-c045e4df7a1f data-ccp-timestamp=1681798297520>



TableNo | TableName | Table ID | Field No. | FieldName | BCLength | Std Datatype | DataType |   | Cheque | Extension   created
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
274 | Bank Acc.   Reconciliation Line |   | 14 | Check No. | Code20 | Code20 | Code35 |   | Check | Yes
276 | Bank Account   Statement Line |   | 14 | Check No. | Code20 | Code20 | Code35 |   | Check | Yes



</body>

</html>

**Comment by panduc** [comment]
Table 274 and Table 276 was not extending. working on it to extend

**Comment by panduc** [comment]
![Image](https://user-images.githubusercontent.com/110709312/233020608-bf857837-5f68-4290-9b2b-e27e366c93d2.png)

**Comment by panduc** [comment]
@TabrejAlam3K The changes are enabled and deployed in UAT. Please check and confirm.

**Comment by TabrejAlam3K** [comment]
@panduc - Please share the audited sheet whatever we discussed with Ms. @audhi3k Mam as per the last session.

@sandhya3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - Please leave your comments here.

**Comment by audhi3k** [comment]
Since there is no queries on this for more a month, we are closing this ticket
