### ISSUE TITLE
New Company in Prod Environment Configuration

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#700]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Tabrej/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Tabrej/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

2 | CR2: Opening   balance | Fri 25-08-23 | Wed 30-08-23 |  
-- | -- | -- | -- | --
2.1 | New company Configuration | Mon 28-08-23 | Thur 31-08-23 | Tabrej,   Audhi
2.2 | Training on Opening Balance | Thur 31-08-23 | Thur 31-08-23 | 3K,   Vridhi Team
2.3 | Create Opening balance | Thur 31-08-23? | Thur 31-08-23? | Vridhi   Team
2.4 | Smoke test | Fri 08-09-23 | Fri 08-09-23 | 3K,   Vridhi Team

</body>

</html>

**Comment by TabrejAlam3K** [comment]
Process Following
1. Tax Engine Setup
2. Create Accounting Period
3. Import Configuration Package from old company and Export in the New Company.
4. No. Series - Remove last Date and Last No. Used from all the no. series.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam, We have done the below Task

1. Tax Engine Setup - **Completed**
2. Create Accounting Period - **Completed**
3. Import Configuration Package from old company and Export in the New Company - **Completed**
4. No. Series - Remove last Date and Last No. Used from all the no. series. - **Completed**

**Comment by audhi3k** [comment]
Check the Voucher Account configuration in company information

Do Mock test
Create a purchase invoice with GST, TDS and try preview posting

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k 
Check the Voucher Account configuration in company information - **Done**

Do Mock test
Create a purchase invoice with GST, TDS and try preview posting - GST not Calculating

**Comment by audhi3k** [comment]
We will connect to check the configuration

**Comment by TabrejAlam3K** [comment]
Mr. Dikshant is travelling today, he has requested we will connect tomorrow morning

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Waiting for Customer Confirmation

CC : @audhi3k @Jayanth3KT @Shasthara

**Comment by TabrejAlam3K** [comment]
Closing this ticket we have created a new ticket for this as per the current communication.

@Jayanth3KT - If it is available in the support portal you can close this also.

New ticket #789 

CC : @audhi3k @Shasthara
