### ISSUE TITLE
Action: Sales Invoice - should be available before posting-

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#701]

**Comment by Jayanth3KT** [comment]
Sales invoice should be generated before posting. Please make suitable corrections and generate sales invoice report before posting.

**Comment by Amar-3KT** [comment]
They required new report same as posted sales invoice report for pre document.

Please assign technical..........Also share technical effort to create new report
@3ktech

**Comment by Amar-3KT** [comment]
7hrs technical and functional 4 hrs required 1 PM hrs =total 12 hrs need to send for approval

**Comment by Amar-3KT** [comment]
We are waiting for client approval.

**Comment by audhi3k** [comment]
Closing this ticket and will create when Client requires
