### ISSUE TITLE
Dimension Detail Report - Requirement already sent-CAS-01442-B7D4X2

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#702]

**Comment by Jayanth3KT** [comment]
The attached report is extracted using “Dimension – Details”, after verifying the report we found that “balance amount” ie. Difference between credit and debit amount at each subtotal (bolded entries) are available in NAV 2009 whereas it is missing in DYN 365 BC.

 

Please map the field “Balance Amount” (Credit – Debit).

 

A screenshot of a computer


![Image](https://github.com/3ktech/General/assets/142868335/a63f88a4-43e1-4280-8a23-65ce045aac2d)



Description automatically generated



-The attached report is extracted using “Dimension – Details”, after verifying the report we found that “balance amount” ie. Difference between credit and debit amount at each subtotal (bolded entries) are available in NAV 2009 whereas it is missing in DYN 365 BC.

[Dimensions - Detail.pdf](https://github.com/3ktech/General/files/12451448/Dimensions.-.Detail.pdf)


Kindly refer the column “Net change” where the difference is shown at each level of total.


[Dimensions - NAV 2009.pdf](https://github.com/3ktech/General/files/12451467/Dimensions.-.NAV.2009.pdf)

**Comment by sruthi1017** [comment]
done the changes as per the requirement but there is no data in the sandbox to test it whether it is working fine or not 
cc : @3ktech @Amar-3KT

**Comment by Amar-3KT** [comment]
Hi @sruthi1017 Please deploy on production and let me know once you done.

**Comment by Amar-3KT** [comment]
Hi @sruthi1017 Please add grand total and update on production. Thanks

**Comment by sruthi1017** [comment]
hi @Amar-3KT added the total can u pls test and confirm 
cc: @3ktech

**Comment by Amar-3KT** [comment]
Hi @sruthi1017 -Print narration and net amount field not available kindly check.

**Comment by Amar-3KT** [comment]
@sandhya3k, @sruthi1017   Please deploy on live

**Comment by audhi3k** [comment]
Closure confirmation on Project review meeting - 13th September 2023 and there are 2 new requirements for which below ticket is created

[DYN 365 BC / Fichtner India/ 3KT / 12.09.2023 / Mur-012 / Dimension detail report - comments -CAS-01492-C1M4F5#777](https://github.com/3ktech/General/issues/777)
