### ISSUE TITLE
Report Layout Section-CAS-01449-K0G6G9

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#710]

**Comment by Jayanth3KT** [comment]
Following reports are yet to be deployed in PROD:

<html>
<body>


FRD Heading |   | DEPLOYED IN PROD
-- | -- | --
FCI-046 | OT_07 | g. Free Lance Report | Tested | Yet to be deployed
FCI-032 | OT_10 | a. Sales Register - GST (58236) | Tested | Yet to be deployed
FCI-033 | OT_11 | b. Cust/Vendor Ledger (58106) => Print Detail, Show Narration (all Filters are used) | Tested | Delivered
FCI-034 | OT_12 | c. Collection Advice (58102) | Tested | Yet to be deployed
FCI-035 | OT_13 | d. Sales Register (58025) | Tested | Yet to be deployed
FCI-040 | OT_18 | i. Sales Invoice – before Posting | Tested | Yet to be deployed
FCI-041 | OT_19 | j. Sales Invoice – After Posting | Tested | Yet to be deployed
FCI-042 | OT_20 | a. GSTR - Purchase Excel (58241) | Tested | Yet to be deployed
FCI-043 | OT_21 | b. Purchase Register (58026) | Tested | Yet to be deployed
FCI-046 | OT_24 | e. Vendor Payment Upload (50504) | Completed | Delivered
FCI-074 | OT_32 | a. TDS Pending | Completed | Delivered
FCI-075 | OT_33 | b. TDS Received | Completed | Delivered
FCI-044 | OT_02 | b. Ledger (16563) =>  Filter (Print Details, show Balance, Print Name, Cost Centre, Voucher Narration) | Tested | Yet to be deployed
FCI-046 | OT_04 | d. Dimension - Detail (28) => Print Narration | Tested | Delivered
FCI-048 | OT_06 | f. Voucher Print - Post & Print from Voucher | Tested | Provided
FCI-058 | OT_16 | f. Customer - Balance to Date (121) | Tested | Delivered
FCI-060 | OT_18 | h. Customer - Summary Aging Simp.(109) | Tested | Delivered
FCI-066 | OT_24 | d. Vendor - Balance to Date (321) | Tested | Delivered
FCI-068 | OT_26 | f. Vendor - Summary Aging Simp. (58082) | Tested | Delivered
FCI-076 | OT_34 | c. Customer Ageig with Description | Tested | Solution delivered but we found bugs

<p class="x_MsoNormal" aria-hidden="true" style="margin: 0cm; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(36, 36, 36); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> </p>
</body>
</html>










<html>
<body>
<p class="x_MsoNormal" style="margin: 0cm; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(36, 36, 36); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Please find below list of reports for your testing.</p><p class="x_MsoNormal" aria-hidden="true" style="margin: 0cm; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(36, 36, 36); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> </p>

  |   | FRD Heading |  
-- | -- | -- | --
FCI-046 | OT_07 | g. Free Lance Report | Tested
FCI-032 | OT_10 | a. Sales Register - GST (58236) | Tested
FCI-033 | OT_11 | b. Cust/Vendor Ledger (58106) => Print Detail, Show Narration (all Filters are used) | Tested
FCI-034 | OT_12 | c. Collection Advice (58102) | Tested
FCI-035 | OT_13 | d. Sales Register (58025) | Tested
FCI-040 | OT_18 | i. Sales Invoice – before Posting | Tested
FCI-041 | OT_19 | j. Sales Invoice – After Posting | Tested
FCI-042 | OT_20 | a. GSTR - Purchase Excel (58241) | Tested
FCI-043 | OT_21 | b. Purchase Register (58026) | Tested
FCI-046 | OT_24 | e. Vendor Payment Upload (50504) | Completed
FCI-074 | OT_32 | a. TDS Pending | Completed
FCI-075 | OT_33 | b. TDS Received | Completed
FCI-044 | OT_02 | b. Ledger (16563) =>  Filter (Print Details, show Balance, Print Name, Cost Centre, Voucher Narration) | Tested
FCI-046 | OT_04 | d. Dimension - Detail (28) => Print Narration | Tested
FCI-048 | OT_06 | f. Voucher Print - Post & Print from Voucher | Tested
FCI-058 | OT_16 | f. Customer - Balance to Date (121) | Tested
FCI-060 | OT_18 | h. Customer - Summary Aging Simp.(109) | Tested
FCI-066 | OT_24 | d. Vendor - Balance to Date (321) | Tested
FCI-068 | OT_26 | f. Vendor - Summary Aging Simp. (58082) | Tested
FCI-076 | OT_34 | c. Customer Ageig with Description | Tested

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by Amar-3KT** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/DELL/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/DELL/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">
<span style='font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial'>



Freelance   Report | 50001 | not running
-- | -- | --
Sales register GST | 50100 | Running fine
Sales register | 50102 | Running fine
Sales invoice report before   posting | 50010 | Doc no filter not available
Sales invoice report after posting | 50149 | Running fine
GSTR Purchase . Excel | 50011 | running fine
Purchase Register | 50008 | Running fine
Vendor payment upload | 50504 | Running fine
TDS Pending | 50002 | Please update Filter details
TDS Received | 50003 | Please update Filter details
Cust/Vendor ledger | 58106 | Running fine
Collection Advice | 50009 | Running fine



</body>

</html>

**Comment by Amar-3KT** [comment]
@sandhya3k  Kindly check remarks. Let me know once you available for above reports.

**Comment by Amar-3KT** [comment]
Hi-@sandhya3k - Any update for pending reports.

**Comment by 3ktech** [comment]
hi @Amar-3KT , @sandhya3k  is on leave today and will get back to you tomorrow.
Cc: @audhi3k

**Comment by sandhya3k** [comment]
@Amar-3KT 

can we connect for this ticket?

cc: @3ktech  @audhi3k

**Comment by Amar-3KT** [comment]
50001 verified field filter need to add on document no.

**Comment by sandhya3k** [comment]
@Amar-3KT 
![image](https://github.com/3ktech/General/assets/114206737/8a563172-5237-43dd-b0e7-c066de12954d)
can u find the above attachment?
cc : @3ktech

**Comment by Amar-3KT** [comment]
@sandhya3k -Please add document no filter on production environment for 50010 report.

**Comment by sandhya3k** [comment]
@Amar-3KT 

i deployed in production please check

**Comment by audhi3k** [comment]
Confirmed closure on Review Meeting 13thSep2023
