### ISSUE TITLE
Purchase Process issue in Keltech

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#711]

**Comment by Amar-3KT** [comment]
1) Select order type before posting- Validation
2) Purchase invoice direct unit cost cannot be changed- Validation required
3) vendor workflow template not available
4) When we are selecting Material PO No then bc closed automatically. 
5) Release and reopen button should be available.

@Mahesh3ktech Please update above mentioned point status

CC @audhi3k @3ktech

**Comment by Mahesh3ktech** [comment]
hi @Amar-3KT - completed the first point and working on remaining points.

  i. Select order type before posting- Validation - **Completed**
 ii. Purchase invoice direct unit cost cannot be changed- Validation required - Changes done need to test.

CC: @3ktech, @audhi3k

**Comment by Amar-3KT** [comment]
@Mahesh3ktech -1 and 2 working fine please check 3,4 and 5 point

**Comment by Mahesh3ktech** [comment]
hi @Amar-3KT - all the above issues are resolved. and related to 3rd point i have added screenshot for your reference, we have action called Reset Microsoft Templates by clicking this we can recreate all microsoft templates.


![Image](https://github.com/3ktech/General/assets/110819826/3a5cdbdb-b951-4e59-8df2-72cc5a0044a7)


CC: @3ktech, @audhi3k @Sarikab1222

**Comment by shivakumar3k** [comment]
All quires are addressed.
