### ISSUE TITLE
Urban Ladder New Requirement Points

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#712]
1. Delivery Challan Unit Price - It is currently coming from Item Card, It should be come from ILE First entry.
2. New Page Required for Posted Service Invoice - Filter based on Location Code (SCON01).
3. RRL Output - After assigning the Serial Number - Barcode should be auto printed or Manual Print Required.
4. GST Reg No. in RRL - GST Reg. No. should come from UL in Delivery Challan Report and Location List.

**Comment by 3ktech** [comment]
Please define the requirements in detail @TabrejAlam3K

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech 

1. Delivery Challan Unit Price - In the Delivery Challan Report Unit Price is picking form the Item Card, It should be from the ILE first entries.
3. New Page Required for Posted Service Invoice - Create a new page with Name Posted Service Invoice. It should be copy of Poste Sales Invoice only need to apply the filter on Service Invoice.
5. RRL Output - After assigning the Serial Number - In the Item Tracking page, While assigning the Serial number give one button called Print Barcode on outgoing job work order card.
6. GST Reg No. in RRL - In RRL we have mention Company GST Reg No. it should be print on UL Company Delivery Challan Reports.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please let me know if you have required more discussion on this.

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - As discussed please work upon on the below points.

1. Delivery Challan Unit Price - It is currently coming from Item Card, It should be come from ILE First entry.
2. New Page Required for Posted Service Invoice - Filter based on Location Code (SCON01).

Point 3 & 4 Will connect again

CC : @audhi3k @3ktech

**Comment by audhi3k** [comment]
Mr @rohit3k update on the status of point 1 and 2

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K Changes has been done as per requirement for pint no. i & ii please check and confirm. When we can connect for point no 3 & 4 

CC: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Point 3 & 4 is pending for customer discussion.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
We have repinged Mr. Rewat for the understanding session.

CC : @audhi3k @Shasthara

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K Do we have any update on this.?
cc: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Waiting for Customer Confirmation

CC : @audhi3k @Jayanth3KT @Shasthara

**Comment by TabrejAlam3K** [comment]
Closing this ticket because we have created new ticket for the individual points.

CC : @audhi3k @Shasthara @Jayanth3KT
