### ISSUE TITLE
XBS Integration issue

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#713]

**Comment by rohit3k** [comment]
@audhi3k , @3ktech 

We were having discussion with Client and understand the issue. Data is not coming into "Purchase Staging List" Table it is XBS who is Pushing the Data from there end through the SOAP URL. I have checked the Web Services, and it is there. Manually Client is Doing Something from XBS Side and after that Data is Coming into "Purchase Staging Table. ".. We have asked him to Connect with XBS to fix the issue.

**Comment by shivakumar3k** [comment]
Mr. Suresh will check with XBS team and confirm.

**Comment by Jayanth3KT** [comment]
Hi @rohit3k this ticket haven't raised in case management could you please elaborate how this ticket is created.

CC: @Shasthara @audhi3k

**Comment by shivakumar3k** [comment]
Client check with XBS team and issue with XBS only.
Now auto Import is working fine.

**Comment by shivakumar3k** [comment]
Closing this Incident with Clint approval.
Mr. Devraj & Ms. Pooja confirmed the.
