### ISSUE TITLE
Missing exciting customization

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#714]

**Comment by Amar-3KT** [comment]
2. Create Material Indent, item reclass on production
3. Excess Variation list 50014 page,5000 table
4. Revaluation journal by product50021 page
5. Product cost allocation list 50025
6. Product cost allocation 50007

**Comment by Mahesh3ktech** [comment]
hi @Amar-3KT - these pages are republished, and it is available. kindly check.

CC: @3ktech, @audhi3k

**Comment by Amar-3KT** [comment]
Create Material Indent, item reclass on production
Revaluation journal by product50021 page

above 2 customization not available other are available. Kindly check.
@Mahesh3ktech 

CC @3ktech

**Comment by Mahesh3ktech** [comment]
hi @Amar-3KT - due to training, I have published to UAT environment and the changes available UAT. 

CC: @3ktech

**Comment by audhi3k** [comment]
Mr @Mahesh3ktech publish in Sandbox

**Comment by audhi3k** [comment]
Customization published in Sandbox
