### ISSUE TITLE
Sales Report - Credit Note GST Tax ID - 50174

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#72]
Output data not matched with the NAV16 Report Output data

1. Amount in Words
2. Total Amount

**Comment by panduc** [comment]
@TabrejAlam3K  The  issues has been fixed. Please check and confirm. Attached reference output

[Print Credit Note GST Branch- 50174 Output.pdf](https://github.com/3ktech/General/files/10510780/Print.Credit.Note.GST.Branch-.50174.Output.pdf)

**Comment by TabrejAlam3K** [comment]
Done



[50174 (2).pdf](https://github.com/3ktech/General/files/10516994/50174.2.pdf)
