### ISSUE TITLE
Jet Reports Error-CAS-01433-M6C3N6

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#720]

**Comment by Jayanth3KT** [comment]
Please can you review this file as it seems BC India is not working for me in this report.


[Jet Report P&L Data - FY24 Q2.xlsx](https://github.com/3ktech/General/files/12483833/Jet.Report.P.L.Data.-.FY24.Q2.xlsx)



![Image](https://github.com/3ktech/General/assets/142868335/c36c9f30-1307-4086-a3cb-3e8c5032ebef)

**Comment by audhi3k** [comment]
Mr @Jayanth3KT , add the email here for the consultant to look up the issue

**Comment by TabrejAlam3K** [comment]
Ms. Swathi is not available for discussion once discuss will update here.

CC : @audhi3k @Shasthara @Jayanth3KT

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Jayanth3KT - Who raised this ticket please share that mail id here.

![Image](https://github.com/3ktech/General/assets/116171982/baaa14c0-4141-4f3e-a5dc-8066fea9afbe)

CC : @audhi3k @Shasthara

**Comment by Jayanth3KT** [comment]
Hi Mr. @TabrejAlam3K  kish.sharma@dodsgroup.com raised this ticket from Merit group.
<img width="579" alt="image" src="https://github.com/3ktech/General/assets/142868335/169428e4-9eba-4b30-abde-6a7caf1c5b2c">
<img width="638" alt="image" src="https://github.com/3ktech/General/assets/142868335/5a703d5c-8a90-45b9-8733-5900ea08c035">

CC: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT - Please forward the mail to me

**Comment by Jayanth3KT** [comment]
Hi @TabrejAlam3K Forwarded to you.

**Comment by TabrejAlam3K** [comment]
Need to discuss with the client and get the more information about the ticket.

@audhi3k @Shasthara @Jayanth3KT

**Comment by TabrejAlam3K** [comment]
Closing this ticket as per the customer request.

![Image](https://github.com/3ktech/General/assets/116171982/a7456ffb-c4c3-4907-9d9b-c3e02d33dfdc)

CC : @audhi3k @Shasthara @Jayanth3KT
