### ISSUE TITLE
MDT - E-mail set up-CAS-01463-H6Z1M4

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#723]
****Approved** Hours - 8**

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech - Can we connect on the requirement

Requirement - They are sending mail form the BC but in the mail no signature is coming. They want to add custom signature in the mail body.

Mr. Pandu has done the same development for merit already.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
**Without Signature Snapshot.**

![Image](https://github.com/3ktech/General/assets/116171982/5bc55673-92c5-459d-a607-4fe98e4ee159)

**With Signature Snapshot.**

![Image](https://github.com/3ktech/General/assets/116171982/e2fb5bd0-2b01-49a7-8ef4-8303dca93b60)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech  Kartik D - Please align the resource to discuss the issue and share the time effort for the same. We need to start working on it.

CC : @audhi3k @Shasthara 

@Jayanth3KT - Please update the support portal case id here.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please update your comment here, how much time you required for this task.

CC : @audhi3k @Shasthara @3ktech

**Comment by TabrejAlam3K** [comment]
Approval Receive form the Client.

![Image](https://github.com/3ktech/General/assets/116171982/d895e2b9-4ae7-4652-854f-71ad12c238f9)

CC : @audhi3k @Shasthara

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K Changes has been done as per requirement. we will require Client Signature in order to move the changes into Production.
cc: @audhi3k @3ktech

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K as per our discussion you will have word with client and you will ask them, on how many places they want signature to be added. till the time i am marking this ticket as Cust_info.
cc: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Email Signature required on Sales, Purchase and also in BRS

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - What is the status of the ticket.

CC : @audhi3k @3ktech @Shasthara

**Comment by TabrejAlam3K** [comment]
Need to discuss with the client from where we can trigger the Email Option.

CC : @audhi3k @Jayanth3KT

**Comment by TabrejAlam3K** [comment]
We are closing this ticket as completed, Client confirmed during the call.

@Jayanth3KT - You can close this ticket from the support portal.

CC : @audhi3k
