### ISSUE TITLE
LMS Integrations Live Deployment

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#724]

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech  - Please start working on it.

CC : @audhi3k @3ktech @Shasthara

**Comment by audhi3k** [comment]
Mr @3ktech, today we have to start with deployment, hope you have planned

**Comment by TabrejAlam3K** [comment]
Closing this ticket we have created a new ticket for this as per the current communication.

@Jayanth3KT - If it is available in the support portal you can close this also.

New ticket #789

CC : @audhi3k @Shasthara
