### ISSUE TITLE
In Accrual Report add the GL Account in Closing table-CAS-01477-N2N3T5

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#725]
Earlier Approved Hours 5 Hours

Additional Hours - 7 Hours (Due to requirment was changed)

Additional Hours - 3 Hours (Due to requirment was changed)

**Total - 15 Hours**

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - As per our discussion please add the below GL Account in the Accrual Closing table. Please share the time effort for the same.

424750
611200
617700
710400
740200
740500
770500
780900
999000

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please share the time effort for the same.

CC : @audhi3k @Shasthara 

@Jayanth3KT - Please update the support portal case id here.

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K I would be Require 3 hour to complete the changes.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Approval mail send to the client.

![Image](https://github.com/3ktech/General/assets/116171982/7eb02572-632d-4cd7-ab3b-1731ca4c3449)

CC : @audhi3k @rohit3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Approval receive form the client, Please start working on it and complete it by today.

![Image](https://github.com/3ktech/General/assets/116171982/dac8d851-ee46-4734-a7ba-5cdfe93b237a)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please move the changes into the Production Environment and confirm.

CC : @audhi3k @3ktech @sandhya3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please move the changes into the Production.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - What is the status of the ticket.

CC : @audhi3k @3ktech @Shasthara

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K T as i told you this has been done on Sandbox. Please confirm #726 GST Description which is 4th no point of that ticket so that all work Deploy Together.
cc: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
We are still waiting for Client updated on the tickets.

CC : @audhi3k @Shasthara @Jayanth3KT

**Comment by TabrejAlam3K** [comment]
Waiting for Customer Confirmation

CC : @audhi3k @Jayanth3KT @Shasthara

**Comment by TabrejAlam3K** [comment]
Client (Ms. Swathi) was committed he will test on 13-09-2023 and confirm but still waiting for the response from their side.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - We need to discuss on this report is not coming correctly in the Production Environment.

CC : @audhi3k

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K Let's Connect for this.
cc: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
As per our Session with the Client (Ms. Swathi) She will check and update by today EOD.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @rohit3k - Please deploy this into the Production and let us know. Client confirmed for closure after deployment in the Production.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - As per our discussion with the client she confirmed for closure after moving the changes into the production, the changes is deployed in the production?

CC : @audhi3k @Shasthara @3ktech

**Comment by TabrejAlam3K** [comment]
Client confirmed for closure. I am closing the tickets

![Image](https://github.com/3ktech/General/assets/116171982/1bf8f52b-7071-4d94-8b0c-ce4e900f0a77)

CC : @audhi3k @Shasthara @Prakash3K
