### ISSUE TITLE
GST description & Vendor new field requirement-CAS-01476-T6G9F9

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#726]
**Approved Hours - 12**

**Requirement**

1. On Vendor Card add new field Called **Department** - User will select the Department value from the New Department table data.
2. MSME certificate number (Length 20) - It should be combination of **Alphabet +Numbers +Special Characters**
3. On Vendor Card add new field called - Secondary Contact - Value should be come form the existing Contact records.
4. GST Description - While selecting the value in the filed GST Credit on Purchase Invoice Line after Preview Post Description changes, It should not be changed.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech  Kartik D - Please align the resource to discuss the issue and share the time effort for the same. We need to start working on it.

CC : @audhi3k @Shasthara 

@Jayanth3KT - Please update the support portal case id here.

**Comment by TabrejAlam3K** [comment]
Approval Receive from the Client

![Image](https://github.com/3ktech/General/assets/116171982/d4fdc304-a6fc-4821-bbd6-ca87063ba396)

CC : @audhi3k @Shasthara

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K I have gone through the process which you have guided. but there is no issue related to point no 4. please reconfirm the issue.
CC: @audhi3k @3ktech

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K Once you get clarity on point no. 4, from client, please update accordingly till the time i am making this ticket as Cust_info.  Rest 3 point is completed it will Deploy on Production by today EOD.
cc: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - We have done the session with the Client, Can we connect now??

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - As per our discussion please update the status of the ticket, If you need any support from our side please ping me anytime.

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - As per our discussion please update the status of the ticket, If you need any support from our side please ping me anytime.

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - What is the status of the ticket.

CC : @audhi3k @3ktech @Shasthara

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K Development has been done of Point No. 4 on Sandbox please check and confirm.
cc: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
We are still waiting for Client updated on the tickets.

CC : @audhi3k @Shasthara @Jayanth3KT

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Can we connect on this?

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please deploy this into the Production Environment.

@sandhya3k - Please support Rohit to deploy.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Mr. @rohit3k  - This is not yet deployed in the Production, May i know the reason why it is taking too much time for the Deployment.

CC : @audhi3k @Shasthara @3ktech

**Comment by TabrejAlam3K** [comment]
Mr. @rohit3k - He will fix it by today before lunch.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - As per our discussion please make the correction as required and let us know for testing.

CC : @audhi3k @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - It is not working for **Release** status. Please close this as on priority.

CC : @audhi3k @Shasthara @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - It is not working for Release status. Please close this as on priority.

CC : @audhi3k @Shasthara @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - What is the status of the ticket.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - What is the status of the ticket.

CC : @audhi3k @Shasthara @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi @rohit3k - I have tested and now it is working fine in the Sandbox Environmet.
1.	PI-CHE-003158
2.	PI-CHE-003161

CC : @audhi3k @Shasthara @3ktech @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - We have done the Testing on the Puchase Invoice on the below Document
1. PI-CHE-003161 - It is working fine in  both the cases
2. PI-CHE-003163 - It is not working in both the cases

Please debug this and let me know.

CC : @audhi3k @3ktech @gsudarsan3k

**Comment by TabrejAlam3K** [comment]
Hi @rohit3k - As discussed yesterday please provide your analysis comment on above mention document number.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - I have done the uat with the client she is ok on this, Can you move the changes into the production as well?

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Thanks for your support. I am closing this ticket as completed, Client confirmed for closure.

![Image](https://github.com/3ktech/General/assets/116171982/383a82ca-3d02-4095-8575-b352ab9b573b)

CC : @audhi3k @Shasthara @Prakash3K
