### ISSUE TITLE
How to Amend Vendor Payment Remittance template-CAS-01464-F5B2J3

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#727]
Technical-3hrs
Functional-2hrs
PM- 1hr
**Total=6hrs**

**Comment by Jayanth3KT** [comment]
I would like to have guidance on how to amend vendor remittance template on dynamics for the 2 operational entities on the system.

We currently have the current remittance produced by the system when we make a vendor payment (see attached file Excel PJ-PE0000457), however we will need to include the logo, footnotes and specific wordings to ensure it looks like the one Dods used to send (attached Remit).

I have amended the excel remittance manually ( refer to remittance payment attached) , but we will need to ensure that the system is set up with the correct vendor payment remittance template. 



[Compass Remittance.pdf](https://github.com/3ktech/General/files/12500218/Compass.Remittance.pdf)
[Remittance Payment PJ-PE000457.pdf](https://github.com/3ktech/General/files/12500219/Remittance.Payment.PJ-PE000457.pdf)
[Excel _PJ-PE000457.pdf](https://github.com/3ktech/General/files/12500220/Excel._PJ-PE000457.pdf)

**Comment by Amar-3KT** [comment]
@3ktech -Please align technical also share the efforts for the same.

**Comment by Amar-3KT** [comment]
@Jayanth3KT - Please let me know once its approved. Thanks

**Comment by audhi3k** [comment]
[Total Politics Requirement#731](https://github.com/3ktech/General/issues/731)

**Comment by Amar-3KT** [comment]
Hi @sruthi1017 - We have received approval for this ticket please start the work.

CC @audhi3k @3ktech

**Comment by Amar-3KT** [comment]
Technical-3hrs
Functional-2hrs
PM- 1hr
Total=6hrs

**Comment by Amar-3KT** [comment]
@sruthi1017 We have to complete this ticket by today. I request you to complete technical part before 2nd half. Thanks

**Comment by Amar-3KT** [comment]
Hi @sruthi1017 - Is this done?

**Comment by Amar-3KT** [comment]
@sruthi1017 Please deploy on production. Thanks

**Comment by TabrejAlam3K** [comment]
Hi @sruthi1017 - Please update your comments here?

CC : @audhi3k @Shasthara @Jayanth3KT

**Comment by sruthi1017** [comment]
hi @TabrejAlam3K  it is done and deployed in production also
cc: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT & @Prakash3K - Please update the email address of the client here, Who raised this ticket.

CC : @audhi3k @Shasthara

**Comment by Jayanth3KT** [comment]
Client I'D- ana.lopez@totalpolitics.com

CC: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Mr. @Amar-3KT  have tested the issue it was working fine, I am closing this ticket with due to non responded by the client side since long time.

Mr. @Jayanth3KT - You can close this ticket from the support portal as well.

CC : @audhi3k @Shasthara
