### ISSUE TITLE
ERROR -Shankar and Parvathy-CAS-01466-F4Z7V5

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#729]

**Comment by Prakash3K** [comment]
We have try to create the vendor during that time we got this error ,kindly do the needful.




![Image](https://github.com/3ktech/General/assets/140147250/5ebaac65-2a0b-4e53-8ae6-e501b0f900cf)

**Comment by audhi3k** [comment]
Dear Mr Ayyapan,

In the Shankar and Parvathy company the workflow is not enabled.  Kindly check and confirm

Analysis:
The company Shankar and Parvathy was created by Pioneer.  In that company the workflows are not enabled for any process or Master

Solution:
Workflow to be configured and the send for approval or without approval proceed with Vendor


Regards,
Audhi Lakshmi S

**Comment by Prakash3K** [comment]
@audhi3k Can I Close this ticket due to no response, We will create as new in future if the client will raise the same points.

**Comment by Prakash3K** [comment]
Client confirmed to close this ticket.

CC: @audhi3k ,@Tushargupta3K
