### ISSUE TITLE
Sales Report - Credit Note Branch Logo ID - 50175

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#73]
Output data not matched with the NAV16 Report Output data

1. Amount in Words
2. Total Amount

**Comment by panduc** [comment]
@TabrejAlam3K  The  issues has been fixed. Please check and confirm. Attached reference output

[Print Credit Note GST  Branch Logo 50175 Output.pdf](https://github.com/3ktech/General/files/10510768/Print.Credit.Note.GST.Branch.Logo.50175.Output.pdf)

**Comment by TabrejAlam3K** [comment]
Done


[50175 (2).pdf](https://github.com/3ktech/General/files/10516198/50175.2.pdf)
