### ISSUE TITLE
Total Politics Requirement

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#731]

**Comment by TabrejAlam3K** [comment]
Requirement Received

1. Report need to be fixed - Vendor Ledger Entries >>> 
2. Email Address need to be changed - Email Body
3. Payment Journal - Exported data format should be changed - "DODS CRP" = "Total Politics".
    
![Image](https://github.com/3ktech/General/assets/116171982/41f8ca55-f799-41d2-a807-c73a0390f700)

**User was connected during the call
Ana Lopez
Agne Krasauskaite**

@audhi3k 
@Shasthara - Please assign the technical which i will explain the requirement.

**Comment by audhi3k** [comment]
[How to Amend Vendor Payment Remittance template-CAS-01464-F5B2J3#727](https://github.com/3ktech/General/issues/727)
Duplicate ticket
