### ISSUE TITLE
Customization As per Gap Documents

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#733]

**Comment by Amar-3KT** [comment]
Hi @3ktech -Is Gap document customization done on Sandbox?

**Comment by 3ktech** [comment]
hi @Amar-3KT , the gap points are not taken care yet,

**Comment by Amar-3KT** [comment]
Okay thanks

**Comment by Amar-3KT** [comment]
Mr. @3ktech -As per gap document all points are taken care?

**Comment by Amar-3KT** [comment]
https://3ktechnologies22.sharepoint.com/:x:/s/MS_BizAppsExecutionProjects-External-3KTBizApps_KeltechNAVtoBCMigration/Ef0Jp_mgqONAi8waClGYUR8Bi4vba9JQYrMzbRNH9Gnhmg?e=33Qu9F

**Comment by Amar-3KT** [comment]
@gsudarsan3k -Please update planned time in above mention excel link

**Comment by sandhya3k** [comment]
@Amar-3KT 

please test on the purchase order report?

cc : @gsudarsan3k  @3ktech

**Comment by audhi3k** [comment]
Completed - Keltech in LIVE
