### ISSUE TITLE
Reg: Workflow Error-CAS-01472-W1V1F1

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#735]

**Comment by Jayanth3KT** [comment]
I checked several times, there seems no issue from our side on the error regarding Workflow and Workflow User Groups. So Kindly check from your end and update.



![Image](https://github.com/3ktech/General/assets/142868335/42c19cae-d3ba-46b0-82dd-734397f99ed1)
![Image](https://github.com/3ktech/General/assets/142868335/c8dfdb55-b208-4495-91a4-37a80f92331c)
![Image](https://github.com/3ktech/General/assets/142868335/d60a1fda-b3c2-4b70-8ca6-425e77f61dc4)

CC: @shivakumar3k

**Comment by 3ktech** [comment]
hi @Jayanth3KT , does this task require developer's attention? please elaborate if developer's attention is required.

**Comment by shivakumar3k** [comment]
Required Changes done in live. Waiting for Customer closer confirmation.

**Comment by shivakumar3k** [comment]
@Jayanth3KT Kindly check with Mr. Vivek and get closer approval to close this incident.

**Comment by shivakumar3k** [comment]
Closer confirmation received from Mr. Vivek.
