### ISSUE TITLE
Dynamic issues-CAS-01453-D7H3Y0

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#739]
**Total Effort Hours = 1 Hours**

**Comment by Prakash3K** [comment]
I need to post payment journal, but keep getting error message bellow, but can understand where is the error?



![Image](https://github.com/3ktech/General/assets/140147250/c53324ef-e8cb-415c-903a-04928bdc44d3)



[If requesting support.docx](https://github.com/3ktech/General/files/12523824/If.requesting.support.docx)

**Comment by Amar-3KT** [comment]
@Prakash3K -Please provide concern person detail.

**Comment by Amar-3KT** [comment]
User required process documents related to payment journal with screenshot

**Comment by Amar-3KT** [comment]
By EOD if we not received any information from user side then we will close. 13-9-23

**Comment by Amar-3KT** [comment]
As discussed with Ms. Ana , she required changes in payment journal for export option. We have done changes

waiting for confirmation.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Shasthara - Please get the confirmation from the Client (Ms. Ana).

CC : @audhi3k @Jayanth3KT

**Comment by TabrejAlam3K** [comment]
Consernt Person (Client) - agne.krasauskaite@totalpolitics.com

**Comment by TabrejAlam3K** [comment]
Mr. @Amar-3KT  have tested the issue it was working fine, I am closing this ticket with due to non responded by the client side since long time.

Mr. @Jayanth3KT - You can close this ticket from the support portal as well.

CC : @audhi3k @Shasthara
