### ISSUE TITLE
Sales Report - Credit Note GST ID - 50147

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#74]
Amount in words not correctly remaining things is looks good

**Comment by panduc** [comment]
@TabrejAlam3K  The  issues has been fixed. Please check and confirm. Attached reference output

[Report 50147 Output.pdf](https://github.com/3ktech/General/files/10510752/Report.50147.Output.pdf)

**Comment by TabrejAlam3K** [comment]
Done



[50147 (2).pdf](https://github.com/3ktech/General/files/10516973/50147.2.pdf)
