### ISSUE TITLE
Training Manual for Dynamics 365 business central- CAS-01460-V8N2P2

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#740]

**Comment by Prakash3K** [comment]
My name is Ana Lopez, I just started at Total Politics as Financial Controller. I would like to check if you have any training documents for Dynamics or any portal where I could go and get training on different modules, Accounts payables, accounts receivables, cash flow management, build reports etc.

**Comment by Amar-3KT** [comment]
User required documents with screenshot. She will share list of module.

**Comment by Amar-3KT** [comment]
By EOD if we not received any information from user side then we will close. 13-9-23

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT & @Prakash3K - Please update the email address of the client here, Who raised this ticket.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Based on the @Amar-3KT comment I am closing this ticket due to non responded from the client side.

@Prakash3K - you can close this ticket from the support prtal as well.

CC : @audhi3k @Shasthara

**Comment by Jayanth3KT** [comment]
Client id: Ana.Lopez@totalpolitics.com 

CC: @audhi3k @Shasthara
