### ISSUE TITLE
Priority Report issue

### ISSUE THREAD

**Issue by shivakumar3k** [3ktech/General#741]
50024 - Invoice total Amount and in words not printing.
50068 - Total Amount showing wrong value GST Values are not considered & PO details aslo not printing.
50069 - Buyer PO no, Invoice total & Taxable Value not printing
50070 - Amount not printing.

**Comment by Mahesh3ktech** [comment]
hi @shivakumar3k - All the above mentioned reports are fixed. kindly check and update.

CC: @3ktech, @audhi3k

**Comment by shivakumar3k** [comment]
@Mahesh3ktech  E-Invoice details are not fetching in Reports.
Invoice No **MYS232400034**

**Comment by Mahesh3ktech** [comment]
hi @shivakumar3k E-invoice details are printing in reports 50070, and i have mapped the fields in report 50024 but there is no data to test. in report 50038 - fields are not available to map.

CC: @3ktech, @audhi3k, @Amar-3KT

**Comment by Amar-3KT** [comment]
...

**Comment by Amar-3KT** [comment]
Once we complete E-Invoice and E-way then we will close this ticket. Technical working on E-Invoice and E-Way.

**Comment by audhi3k** [comment]
Completed - Keltech in LIVE
