### ISSUE TITLE
Keltech report issue.

### ISSUE THREAD

**Issue by shivakumar3k** [3ktech/General#742]
50035 - printing in multiple pages
50046 - The Tax Component does not exist. Identification fields and values: Tax Type='SGST',ID='0'
50050 - printing multiple pages alignment 
50066 - printing multiple pages

**Comment by Mahesh3ktech** [comment]
hi @shivakumar3k - All the above mentioned reports are fixed. kindly check and update.

CC: @3ktech, @audhi3k

**Comment by audhi3k** [comment]
Reports are tested
