### ISSUE TITLE
E-Invoice testing-KELTECH

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#746]

**Comment by Amar-3KT** [comment]
,The field Assessable Amount (Total Amount - Discount) must match the regular expression '^
d+.?
d{0,2}$'.,The field Assessable Amount (Total Amount - Discount) must be between 0 and 999999999999.99.,The field Total Amount (Unit Price * Quantity) must match the regular expression '^
d+.?
d{0,2}$'.,The field Total Amount (Unit Price * Quantity) must be between 0 and 999999999999.99.,The field Unit Price must match the regular expression '^
d+.?
d{0,3}$'.,The field Unit Price must be between 0 and 999999999999.999.

**Comment by Amar-3KT** [comment]
Hi @sandhya3k- We are getting above error in MYS232400036 sales invoice doc.

**Comment by Amar-3KT** [comment]
Sales credit memo MYSCN23240001 in this doc we are getting error -The length of the string is 10, but it must be less than or equal to 5 characters. Value: Kilo Grams.

Note- Please take Unit of measure code.
@sandhya3k - Kindly check

**Comment by Amar-3KT** [comment]
We will connect @11:30.

CC @audhi3k @sandhya3k

**Comment by sandhya3k** [comment]
@Amar-3KT 


can u please test on e-way bill ?

cc : @audhi3k @3ktech

**Comment by Amar-3KT** [comment]
Hi @sandhya3k - E-way bill not creating kindly check doc-VNR232400892

**Comment by Amar-3KT** [comment]
@sandhya3k Please check E-Invoice following point:

1) After generation of e-invoice msg should popup E-invoice successfully generated other validation also check.***DONE
2) Check e-invoice with charge item
3) Cancel option should work for e-invoice
4) E-invoice should be available on pre document and it should generate at the time of posting
5) E-Invoice should also be available for sales credit memo and transfer shipment.
6) Multiple line -MYS232400044 - E-Invoice not generating. Please check
7) E-invoice should generate for export customer
8) In case of unregister customer-msg Should show ---"E-Invoicing is not applicable for Unregistered Customer."
9) E-Invoice not working in case of Round off

**Comment by Amar-3KT** [comment]
![Image](https://github.com/3ktech/General/assets/111888825/b1fee0e1-f2bc-47d8-9495-8c245c220e04)

@sandhya3k -Kindly check MYS232400043

**Comment by sandhya3k** [comment]
@Amar-3KT 

Please test on cancel e-way bill? and as discussed on the roundoff is coming correctly. and i need to clarify one thing for "G/l account" in the sales invoice line 

cc : @3ktech  @audhi3k

**Comment by shivakumar3k** [comment]
Deployed to Live.
