### ISSUE TITLE
FW: RTB Records with Error

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#748]
**Excel Data Shared by the Client on 06-09-2023**

[In Billing Process.xlsx](https://github.com/3ktech/General/files/12551429/In.Billing.Process.xlsx)
[Not Posted.xlsx](https://github.com/3ktech/General/files/12551430/Not.Posted.xlsx)

**Comment by TabrejAlam3K** [comment]
We have done the Repush and Reupload activity based on the client excel sheet. I need to confirm from the client whether LCMS Status updated or not.

@3ktech - We have tested random email, Mail trigger is working fine.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech - As per our discussion against the RTB number invoice is generated but in LCMS Response Queue Invoice Number coming as blank.

We have around 30 similar records which having the same issues. Reset of Mail was triggered yesterday and I got the mail also.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Waiting for Customer Confirmation

CC : @audhi3k @Jayanth3KT @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Shasthara - Can we close this ticket

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Mr. @TabrejAlam3K - I have update all the RTB records which was In Billing Process and Not Posted, Same I have update in the Daily LKS Standup call.

**Comment by Jayanth3KT** [comment]
Hi @TabrejAlam3K can I know source of this ticket this isn't raised in case management.

CC: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Team I am closing this ticket from the git.

Duplicate ticket ID - #782

CC : @audhi3k @Shasthara
