### ISSUE TITLE
MDT - E-mail set up and Vendor Name-CAS-01475-M0B7S4

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#749]
**Approved Hours - 10**

**Comment by Prakash3K** [comment]
@TabrejAlam3K 

In BC software we require 

1) E-mail option in two fields namely 
      a) Posted Purchase Invoice 
      b) BRS
2) In the report called "TDS entries", we want a "Vendor Name" filed.

Kindly let us know the hours required and other related details.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech - Please align any technical to discuss on time effort which i need to share with the client today.

**Requirement**
1. Email Button Required on Page called **Email**
    1.1 Posted Purchase Invoice (Posted Purchase Invoices (146, List)) under the Print/Send.
    1.2 Bank Account Reconciliation (Bank Acc. Reconciliation List (388, List)) and Report should be auto attached inside the mail (Bank Acc. Recon. - Test (1408, Report Request)).
2. Vendor Name (TDS Entries (18691, List)) Customer field required and value should be come based on the vendor no available on the line level.

CC : @audhi3k @Shasthara @Jayanth3KT

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - As per our discussion please share the time effort for the same. If you have still any doughs on this we can connect again.

CC : @audhi3k @Shasthara @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Please share the time effort for the same.

CC : @audhi3k @Shasthara @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - We have receive the approval mail on this, You can work upon and complete it within the time line.

CC : @audhi3k @Shasthara @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Please update you development status, Delivery date of the ticket is today.

**Comment by sruthi1017** [comment]
hi @TabrejAlam3K dev has been completed u can test by posting an purchase order

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Please move the changes into the Production Environment. Client confirm for closure after moving in the Production.

CC : @audhi3k @Shasthara @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Please move the changes and confirm. Client is still waiting.

Ms. @sandhya3k - Please us to deploy in the Production

CC : @audhi3k @Shasthara @Prakash3K @3ktech

**Comment by sandhya3k** [comment]
@TabrejAlam3K 

I am deploying

**Comment by sandhya3k** [comment]
done @TabrejAlam3K  u can check?

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Client confirm for closure, You can close this ticket from the support portal as well.

CC : @audhi3k @Shasthara
