### ISSUE TITLE
Sales Report - Credit Note GST Tax Logo ID - 50176

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#75]
Amount in words not correctly remaining things is looks good.

**Comment by panduc** [comment]
@TabrejAlam3K  The  issues has been fixed. Please check and confirm. Attached reference output

[Report 50176 Output.pdf](https://github.com/3ktech/General/files/10510747/Report.50176.Output.pdf)

**Comment by TabrejAlam3K** [comment]
Done



[50176.pdf](https://github.com/3ktech/General/files/10516169/50176.pdf)
