### ISSUE TITLE
Purchase Invoice Report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#750]

**Comment by audhi3k** [comment]
Mr @3ktech Tech resource is required in the second half - Mr @Ejaz3KT  is preparing field mapping,  
Mr @Ejaz3KT ping once field mapping is completed

**Comment by Ejaz3KT** [comment]
Hi Team Please find the field mapping for the purchase invoice report


[Purchase invoice Report Field Mapping.xlsx](https://github.com/3ktech/General/files/12575155/Purchase.invoice.Report.Field.Mapping.xlsx)



CC: @audhi3k @3ktech

**Comment by Mahesh3ktech** [comment]
hi @Ejaz3KT - Report is created and working as per the requirement. kindly test and confirm.

CC: @3ktech, @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech I`ve Tested the purchase invoice report In the tax information table the total amount is printing incorrectly please check that for your reference I am attaching the screenshot.

![Image](https://github.com/3ktech/General/assets/125632927/f1c1a3a4-38f8-4a47-864b-5c4c5f3f7b29)

CC: @audhi3k

**Comment by Mahesh3ktech** [comment]
hi @Ejaz3KT - now the taxable total value is corrected. kindly check and update.

CC: @3ktech, @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech I`ve tested the Purchase invoice report it is working fine you can deploy this report in the production  and I am requesting to add Print/Send button in purchase invoice card and I am attaching final report of purchase invoice report.

[document (12).pdf](https://github.com/3ktech/General/files/12601378/document.12.pdf)

CC: @audhi3k

**Comment by audhi3k** [comment]
Mr @Mahesh3ktech kindly deploy in production by today

**Comment by Ejaz3KT** [comment]
HI report is working fine Client has confirmed I am closing this ticket

CC: @audhi3k
