### ISSUE TITLE
Sales Invoice  Report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#751]

**Comment by audhi3k** [comment]
Mr @3ktech Tech resource is required in the firts half - Mr @Ejaz3KT will start the field mapping today second half,  
Mr @Ejaz3KT ping once field mapping is completed

**Comment by Ejaz3KT** [comment]
Please find the field mapping for the sales invoice report 

[Sales Invoice Report Field Mapping.xlsx](https://github.com/3ktech/General/files/12576998/Sales.Invoice.Report.Field.Mapping.xlsx)

CC: @audhi3k @3ktech

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Please update the status of sales invoice report 

CC: @audhi3k

**Comment by sruthi1017** [comment]
hi @Ejaz3KT dev has been completed only bifurcation part is pending will complete and inform u.

**Comment by Ejaz3KT** [comment]
ok @sruthi1017

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017  Total amount is not coming correctly please check and amount in words font colour make it as black

![Image](https://github.com/3ktech/General/assets/125632927/2f1f8533-f0f5-4723-acc7-440186a8416b)

**Comment by sruthi1017** [comment]
now u can test @Ejaz3KT

**Comment by Ejaz3KT** [comment]
HI @sruthi1017 I`ve tested the report the ship to address is not printing properly please check that and add rupees symbol to amounts

![Image](https://github.com/3ktech/General/assets/125632927/f88b7815-cb7f-4efa-bc20-51f06ad06109)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Please update the status of this report

**Comment by sruthi1017** [comment]
hi @Ejaz3KT the changes are available in sandbox u can test and update whether require any modifications

**Comment by Ejaz3KT** [comment]
ok @sruthi1017

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I am getting this below error when opening the report

![Image](https://github.com/3ktech/General/assets/125632927/c2c63d39-8ea3-4e97-9f4b-dfac61642cbd)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 In sales order report Give space in between Po No and Po Date, Contact information is not printing and please make the alignment properly

**Comment by Ejaz3KT** [comment]
HI @sruthi1017 Sales Invoice report is working fine please deploy this in the production environment.

[document (19).pdf](https://github.com/3ktech/General/files/12684301/document.19.pdf)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I am requesting to please deploy this in the production

**Comment by sruthi1017** [comment]
hi @Ejaz3KT it is already been deployed into production, sandhya and me cross checked it is available in production can u pls check once

**Comment by Ejaz3KT** [comment]
The report has been deploy in production need to get client confirmation

CC: @sruthi1017 @audhi3k

**Comment by Ejaz3KT** [comment]
Hi Team sales invoice report is working fine and I am closing this ticket

CC: @audhi3k
