### ISSUE TITLE
MDT - Error in Invoicing-CAS-01478-S9P9H0

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#752]
**Approved Hours 24**

Extra Effort 2 Hours.

**Total Effort Hours = 26**

**Comment by Jayanth3KT** [comment]
Hi Team,

We find that Invoice amount for the document no. PSI/MUM/FY24-009 is being wrongly computed in "Print" option, however the effect in Books of Accounts is fine. Attaching the before mentioned invoice. 

Requesting you to look into and correct the calculation. 


[Sales - Invoice_MDT_RSP.pdf](https://github.com/3ktech/General/files/12557990/Sales.-.Invoice_MDT_RSP.pdf)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech - It is urgent issues which we need to resolved on priority.

CC : @audhi3k @Shasthara @Jayanth3KT

**Comment by audhi3k** [comment]
Mr @Mahesh3ktech kindly connect with Mr @TabrejAlam3K and take up the activity

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech See the below details. Please share the time effort also please before starting the activiry.

Report ID - sagSalesInvoiceINGST (50101, Report Request)
Document No. - PSI/MUM/FY24-009

CC : @audhi3k @Shasthara

**Comment by 3ktech** [comment]
@TabrejAlam3K , we dont have source code for this report. Can you discuss and let us know if we can start a new report? Please let us know so that i can share effort for the approval. Please note that it is going to be a new report from scratch.
CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech  - I will update you one done the session with the client

CC : @audhi3k @Shasthara @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Effort Hours Approved by the Client. Please start working on it and complete it as committed.

![Image](https://github.com/3ktech/General/assets/116171982/7809338d-54d7-49aa-8c61-07b38a6fae74)

 CC : @audhi3k @Jayanth3KT

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech  - Please update you development status here, Delivery date of the ticket is 15-09-2023.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Please start working on this and close it.

CC: @audhi3k @Shasthara @Prakash3K

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - Report is development is completed. kindly check and update.

CC: @3ktech, @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - It is not working in the Sandbox Environment. Please check at you end.

CC : @audhi3k @Shasthara @Prakash3K

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - i have republished my changes now report is working fine and i have demonstrated you the same. kindly check and confirm.

CC: @3ktech, @audhi3k, @Shasthara

**Comment by TabrejAlam3K** [comment]
hi @Mahesh3ktech  - Can we have short call? Report is still not working.

CC: @3ktech, @audhi3k, @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Can we connect on this?

CC : @audhi3k @Shasthara @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi @Mahesh3ktech - I have tested and found it is working fine in the Sandbox Environment.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Clinet(Mr. Pavan) will test and confirm in Sadbox, beased on their confirmation we will move the changes into the production Environment.

CC : @audhi3k @Mahesh3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Have you done the changes whatever we have discussed.

After done the changes please move this into the production environment as well.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Have you done the changes? I need to close this on priority basis.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @sandhya3k - Please connect with Mr. @Mahesh3ktech  and deploy the report into the Production Environment.

CC : @audhi3k

**Comment by sandhya3k** [comment]
@TabrejAlam3K 
u can check in production

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - You can close this ticket as completed from the support portal. I am closing from the Git.

Client confirmed for closure.

![Image](https://github.com/3ktech/General/assets/116171982/75632dfc-2ed4-43a0-b55e-14d55ba7e265)

CC : @audhi3k @Shasthara
