### ISSUE TITLE
opening balance showing as credit in balance field

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#754]
opening balance In cash book report showing as credit but it show as debit in balance column please check what is the logic for this issue

**Comment by Ejaz3KT** [comment]
Hi @Manoj01021999 Please update the status of this task

**Comment by Manoj01021999** [comment]
@Ejaz3KT 
As we discussed kindly take it further any clarification let me 
know
cc: @audhi3k @3ktech

**Comment by Ejaz3KT** [comment]
This issue has not been resolve we need to analyze internally

**Comment by Ejaz3KT** [comment]
Hi I`ve updated this issue to Mr.@gsudarsan3k he told me he check and revert back with the solution

**Comment by Ejaz3KT** [comment]
HI @gsudarsan3k Please update the status this issue

**Comment by rohit3k** [comment]
Hi Mr. @Ejaz3KT This Report has been completed and has been deployed on Production with Your Permission.
If anything, remain please do let us know.

cc: @audhi3k @3ktech @gsudarsan3k

**Comment by Ejaz3KT** [comment]
Hi Mr. @rohit3k I`ve tested the report now it is working fine need to showcase it to the client and get confirmation

![Image](https://github.com/3ktech/General/assets/125632927/d264f660-d8cf-46f0-b106-09670534b3da)

CC: @audhi3k @3ktech @gsudarsan3k

**Comment by rohit3k** [comment]
Hi Mr. @Ejaz3KT Can you please confirm.
cc: @audhi3k @gsudarsan3k

**Comment by Ejaz3KT** [comment]
Hi team cash bool report issues has been resolved and it is working fine so I am closing this ticket

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi team cash bool report issues has been resolved and it is working fine so I am closing this ticket

CC: @audhi3k
