### ISSUE TITLE
GST is not mapped in purchase invoice report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#755]

**Comment by Mahesh3ktech** [comment]
hi @Ejaz3KT - changes has been done. kindly check and update.

CC: @3ktech

**Comment by Ejaz3KT** [comment]
Hi, @Mahesh3ktech I`ve tested the purchase invoice report the GST Amount is printing in that report and it is working fine please deploy this in the production.

CC: @audhi3k

**Comment by audhi3k** [comment]
Mr @Mahesh3ktech kindly deploy in production by today

**Comment by Ejaz3KT** [comment]
The GST has been mapped in the purchase invoice report and it is confirmed by the client stated  as it is fine so I am closing this ticket

CC: @audhi3k
