### ISSUE TITLE
Total Amount Is incorrect in sales Quote & order report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#756]
The caption is not changing in sales order report from quotation to sales order I have share the screen for your reference

![Image](https://github.com/3ktech/General/assets/125632927/0e196d3c-69fd-45d0-8eb6-bc678dae9abb)

CC:  @sandhya3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

please test on sandbox env?

cc : @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam caption is changing madam it is fine but the total is coming incorrect please check this madam

![Image](https://github.com/3ktech/General/assets/125632927/161397e1-dfe8-4dd1-9973-3f0feaa6add4)

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I`ve tested the reports Now the total amount for both reports printing correctly and please deploy this in the production

CC: @audhi3k

**Comment by audhi3k** [comment]
kindly deploy in production by today

**Comment by Ejaz3KT** [comment]
The Total amount in the sales reports is now coming correctly so we can close this ticket

CC: @audhi3k
