### ISSUE TITLE
Delivery Challan Report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#757]

**Comment by 3ktech** [comment]
@Ejaz3KT , please share the field mapping here

**Comment by Ejaz3KT** [comment]
@3ktech Ok ill share

**Comment by Ejaz3KT** [comment]
Hi Team Please find the attached DC report format with field mapping 

[DC Field Mapping.xlsx](https://github.com/3ktech/General/files/12596661/DC.Field.Mapping.xlsx)
[DC Dynamics.pdf](https://github.com/3ktech/General/files/12596660/DC.Dynamics.pdf)

CC: @audhi3k @Mahesh3ktech @3ktech

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Please update the status of this report

CC: @audhi3k

**Comment by sruthi1017** [comment]
hi @Ejaz3KT the gst amount is not fetching line wise it is calculating for the whole document need to debug and close the issue in another 2-3 hrs i'll releae this for testing

**Comment by Ejaz3KT** [comment]
ok @sruthi1017

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 There are lot of changes need to be done in the report below are mentioned
1. Headers captions are replicating
2. In state field state name should be print not state code
3. Total Amount is not correct
4. Add round off field above total field
5. Alignment should be proper 

![Image](https://github.com/3ktech/General/assets/125632927/3fcf609d-d733-494b-b0b5-5f195402b968)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Please Update the status of this report

**Comment by sruthi1017** [comment]
hi @Ejaz3KT the changes are available in sandbox u can test and update whether require any modifications

**Comment by Ejaz3KT** [comment]
ok @sruthi1017

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I am getting this below error when opening the report

![Image](https://github.com/3ktech/General/assets/125632927/c2c63d39-8ea3-4e97-9f4b-dfac61642cbd)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 In this report GSTIN no. & State code is not printing please check and make the alignment properly

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Delivery challan report is working fine please deploy this in the production

[document (18).pdf](https://github.com/3ktech/General/files/12684057/document.18.pdf)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I am requesting  you to please deploy this in the production

**Comment by sruthi1017** [comment]
hi @Ejaz3KT it is already been deployed into production sandhya and me cross checked it is available in production can u please check once

**Comment by Ejaz3KT** [comment]
Hi @Sruthi ***@***.***> ok I’ll check and update

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Ejaz3KT** [comment]
The report has been deploy in production need to get client confirmation

CC: @audhi3k @sruthi1017

**Comment by Ejaz3KT** [comment]
Hi Team as per the client requirement we have developed the report and the report is working fine so I am closing the ticket

CC: @audhi3k
