### ISSUE TITLE
Add GST amount button in purchase invoice card to calculate GST Amount in lines

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#759]
Hi Team Fervid team requires GST Amount button in the purchase invoice card for the calculation of GST assessable Value in the purchase line this button is already in the purchase order card for our reference I`ve attached the screen below:

![Image](https://github.com/3ktech/General/assets/125632927/43ef1326-0194-466d-b8f4-e57c66d4da96)

CC: @audhi3k @3ktech

**Comment by Mahesh3ktech** [comment]
hi @Ejaz3KT - GST Amount button added and it calculating GST Amount.

CC: @3ktech, @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech I`ve tested this GST amount button it is working fine Please deploy this in the production company

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
It is working fine and showed to the client confirmed also 

CC: @audhi3k
