### ISSUE TITLE
Sales Report - Credit IBL Note GST ID - 50143

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#76]
Found Error in BC when I try to run the report.
Company - INSTITUTE OF BUSINESS LAWS

![Image](https://user-images.githubusercontent.com/116171982/214530611-d883c85f-a3e6-49f8-a36e-ddffb4173362.png)

**Comment by panduc** [comment]
[Credit IBL Note GST 50143 Output.pdf](https://github.com/3ktech/General/files/10510725/Credit.IBL.Note.GST.50143.Output.pdf)

**Comment by TabrejAlam3K** [comment]
Format not match see the attached NAV16 Format

Missing Field
CGST%
SGST%
IGST%

**Comment by panduc** [comment]
@TabrejAlam3K  Please share the document  no or  the sample attachment

**Comment by TabrejAlam3K** [comment]
See the attached NAV16 Output.

![Image](https://user-images.githubusercontent.com/116171982/215397479-3a14bc3b-20e6-40f1-b8b7-499aca618932.png)

**Comment by panduc** [comment]
@TabrejAlam3K I've fixed the issue. Attached tested document. Please check and confirm.

[report 50143_ Output.pdf](https://github.com/3ktech/General/files/10553504/report.50143_.Output.pdf)

**Comment by TabrejAlam3K** [comment]
Done



![Image](https://user-images.githubusercontent.com/116171982/216900353-d808d103-b163-40d2-b893-ee19d41a00b9.png)
