### ISSUE TITLE
Need a fix for ECOMM-1498 : GenStore | BC | -CAS-01480-Z7M5T1

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#761]

**Comment by Jayanth3KT** [comment]
Hi Padma,

GenStore | BC | Production support to set the default Price Type & Is Display Price Type

Need to set for all Sales Price List

Default Price Type as : OM
Is Display Price Type as : Yes to same row for which Is Display is set for Price Slab

**Comment by Padma2717** [comment]
Task completed on 20-09-2023 , total hours 21

**Comment by Padma2717** [comment]
Completed points
1. Need to set for all Sales Price List
   1.	Default Price Type as : OM
   2.	Is Display Price Type as : Yes to same row for which Is Display is set for Price Slab 
   3.             Changed the price type from OM to IB
2.Added the filters for Price Type code and Price List code and Product No. and tested and coordination with Mr.Arun

**Comment by Padma2717** [comment]
Task completed . Effort hours 21
