### ISSUE TITLE
JSON E-invoice 

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#762]

**Comment by Prakash3K** [comment]
Json is uploaded and e-invoice is raised but cannot download the raised e-invoice from Winrar file.

@audhi3k @shivakumar3k

**Comment by gsudarsan3k** [comment]
Hi @Prakash3K  Do you have the requirement to start this task.

CC: @audhi3k @3ktech

**Comment by Prakash3K** [comment]
[Json E-invoice.docx](https://github.com/3ktech/General/files/12830819/Json.E-invoice.docx)

This is the format we got confirmed with client, Kindly make configuration as per format. Further information we can connect

@audhi3k, @gsudarsan3k @Tushargupta3K

**Comment by rohit3k** [comment]
Hi Mr. @Prakash3K Changes has been done on UAT Please check and confirm if anything remains.
cc: @audhi3k @3ktech

**Comment by Prakash3K** [comment]
I closing this ticket with 3 hours and remaining 7 hours will be added in upcoming GST integration ticket.
 
CC: @audhi3k @Tushargupta3K
