### ISSUE TITLE
ECOMM-1478 : GenStore | SwiftLink | BC |-CAS-01481-H8K4R0

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#764]
@Jayanth3KT  @Prakash3K
kindly close this ticket

**Comment by Jayanth3KT** [comment]
The Job Queue Event to handle the Order Copy is failed with "An Unexpected error occurred after a database command is executed"

**Comment by Padma2717** [comment]
Close the ticket . Effort hours : 2
