### ISSUE TITLE
ECOMM-1490: GenStore | SwiftLink | BC - F |-CAS-01484-L0P9S8

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#765]

**Comment by Jayanth3KT** [comment]
Need to analyse & come up with stratergy to integrate the Item Level order status of a sales order
- we can provide the data at the order item level current status like Invoiced, Shipped, Delivered, Not Invoiced

**Comment by Padma2717** [comment]
Discussion with Customer and Functional for the ticket EComm -  1491 .  So kindly close this . Effort hours : 2
