### ISSUE TITLE
Permission Set as per users-LKS

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#77]

**Comment by audhi3k** [comment]
@Amar-3KT guide Mr Ejaz

**Comment by niranjand22** [comment]
around 34 common permission are updated in excel

**Comment by niranjand22** [comment]
need to get access contol table list from live environment LKS team,

**Comment by TabrejAlam3K** [comment]
@audhi3k - As per out last discussion with Mr. Viswanathan Sir, he is not able to provide the single table data. We need to check internally.

**Comment by audhi3k** [comment]
Highlighted to Mr Karthik, he is co-ordinating to get the data

**Comment by TabrejAlam3K** [comment]
@3ktech - can you please provide the **Access Control** table list from live environment, LKS team is denied for that particular information(He will not provide the data).

CC : @audhi3k

**Comment by 3ktech** [comment]
@TabrejAlam3K , ,i have requested LKS team to restore a copy of the backup in the server. Post this i will extract and share you
@audhi3k

**Comment by panduc** [comment]
Hi @audhi3k  Attached the LKS permission extracted from Latest DB.

[LKS USER Permissions.xlsx](https://github.com/3ktech/General/files/10967717/LKS.USER.Permissions.xlsx)


CC: @3ktech

**Comment by niranjand22** [comment]
Permission sets are created

All( 5 table data has to be added(13723,16541,464,452,409))
Super
Expense
Collection
ADCS All

**Comment by niranjand22** [comment]
Map the user from nav to BC and assign the permissions

**Comment by niranjand22** [comment]
there are many users not available in BC

**Comment by TabrejAlam3K** [comment]
@niranjand22 - See the attached Development Environment Snapshot.


![Image](https://user-images.githubusercontent.com/116171982/227102293-20b621fd-5836-4ce1-85db-90dccee4b4f8.png)

**Comment by niranjand22** [comment]
IN BC permission sets are updated for the users which are matching in nav

**Comment by niranjand22** [comment]
Assign the roles(profile) from nav to BC.

**Comment by niranjand22** [comment]
we are not having access to live..to see the profile ID mapped to user

**Comment by niranjand22** [comment]
done
