### ISSUE TITLE
Remove Tax Bifurcation table from purchase order report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#772]

**Comment by Mahesh3ktech** [comment]
hi @Ejaz3KT - changes has been done. kindly check and update.

CC: @3ktech

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech I`ve tested the purchase order report it is working the tax bifurcation table has removed from the report now you can deploy this report in the production

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The Tax bifurcation has removed from the purchase order report now we cannot able to see the bifurcation in the report and client has confirmed aslo
