### ISSUE TITLE
E-Way Bill - Keltech

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#773]

**Comment by Amar-3KT** [comment]
@3ktech @sandhya3k -Please provide detail e-way print button currently its no available.

CC @audhi3k

**Comment by Amar-3KT** [comment]
@sandhya3k -Please check following points:

1) Cancel option should work for e-way***DONE
2) Cancel date and status should update as cancel eway***DONE
3) MSG should popup
 e way generated successfully
e way canceled successfully
e way is already generated for this irn
4) Detail Print option should available

**Comment by audhi3k** [comment]
Completed
