### ISSUE TITLE
Need to Remove the Value from the Layout - 50170  Print Tax Invoice Logo-CAS-01503-B2K4H6

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#774]

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech - Need to remove the value from the Report

GST Amount: 0
HSN : 998212

![Image](https://github.com/3ktech/General/assets/116171982/34b98504-6ece-487d-98c4-787d1aaf62fc)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - Please deploy it in the Production.

CC : @audhi3k @sruthi1017

**Comment by TabrejAlam3K** [comment]
**Total Consume Hours is 2**

**Comment by TabrejAlam3K** [comment]
Waiting for Customer Confirmation

CC : @audhi3k @Jayanth3KT @Shasthara

**Comment by TabrejAlam3K** [comment]
@TabrejAlam3K - Changes has been completed and confirmed by the Client during the screen sharing session.

**Comment by Jayanth3KT** [comment]
Hi @TabrejAlam3K can I know source of this ticket this isn't raised in case management.

CC: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Jayanth3KT - This ticket was raise through an Email.

this ticket is already closed and the client also asked for closure.

**Total Effort time is 2 Hours**

CC : @audhi3k @Shasthara

**Comment by Jayanth3KT** [comment]
Hi Mr. @TabrejAlam3K  this ticket is closed in case management(support portal)

CC: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
I am closing this ticket as completed.
