### ISSUE TITLE
Dimension detail report - comments 

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#777]

**Comment by Jayanth3KT** [comment]
Dear 3KT Team,

Further to the deployment of Dimension detail – report in PROD environment, we would like to have the following points to be incorporated in the report.

Opening balance to be brought in the report.
Comments given in JJV should be printed in the Dimension Detail – report.
Two reports are shown while searching for “Dimension Detail – report”, kindly rename reports or keep only the relevant report to avoid confusion.

(There was an attachment  file couldn't upload in GIT)

**Comment by Amar-3KT** [comment]
@3ktech Please provide technical efforts for the same points.

**Comment by Mahesh3ktech** [comment]
hi @Amar-3KT - yesterday evening i have connected with Jayanth to discuss about task but he is not having sufficient information. Can we connect today to discuss requirement.

CC: @3ktech

**Comment by Amar-3KT** [comment]
Yes we can connect.

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech The opening balance should be printed in this dimension detail report now the opening balance is not printing in the report

**Comment by Ejaz3KT** [comment]
The work is in progress

**Comment by Mahesh3ktech** [comment]
There is no data to test in sandbox, @Ejaz3KT adding the data to test the report.

CC: @3ktech

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech Please mentioned the effort hours you required for the report development so I can get approval from the client

CC: @audhi3k @Amar-3KT

**Comment by Amar-3KT** [comment]
We are waiting for total 9hrs approval. 6hrs for technical 2hr for functional and 1hr for pm

**Comment by Mahesh3ktech** [comment]
hi @Amar-3KT - changes are done, kindly check and confirm.

cc: @3ktech, @audhi3k

**Comment by audhi3k** [comment]
Mr @Mahesh3ktech, what the status of this ticket.

CC: Mr @gsudarsan3k

**Comment by gsudarsan3k** [comment]
Hi @audhi3k It is working fine in UAT (because of less data) in the production it is not working as expected. today @Mahesh3ktech is taking a copy of the prod and going to test the issue and fix it.

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech Can I know the status of this report and can we connect for the discussion 

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech I hope you have fixed the issue now the opening balance is coming correctly in the report please update the status & connect with me if you have any queries 

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
HI @Mahesh3ktech Can you please update the status of this task

CC: @audhi3k @Amar-3KT

**Comment by Shasthara** [comment]
@Mahesh3ktech - kindly update the status here

**Comment by Mahesh3ktech** [comment]
hi @Shasthara - opening balance issue resolved, data is corrected. and now only the alignment of the report is pending, ill complete it today by 11am.

CC: @Ejaz3KT, @audhi3k, @gsudarsan3k

**Comment by Mahesh3ktech** [comment]
hi @Ejaz3KT - Changes has been done kindly check and update.

CC: @audhi3k @3ktech @gsudarsan3k @Shasthara

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech Ok I``ll test and update you 

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech UAT has been done with the fitchner client they will check the report with different combinations and confirm with us for the deployment

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech Please deploy the dimension detail report changes in the Fitchner live environment so they can test the report with different scenarios and give us confirmation ASAP

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech Mr. Murali told me that take the time and explore the possibilities for adding the opening balance 

CC: @audhi3k

**Comment by Prakash3K** [comment]
Hi @Ejaz3KT, kindly update current status.

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech Client has raised new point in report is whether there are no transactions in that month opening balance should be print

CC: @audhi3k @Mahesh3ktech

**Comment by Ejaz3KT** [comment]
Hi @Mahesh3ktech Please update me once the narration issue is resolved because we have to fix the render issue today

CC: @audhi3k

**Comment by Shasthara** [comment]
@Mahesh3ktech , @Ejaz3KT - when you close this ticket ?

**Comment by Ejaz3KT** [comment]
We are waiting for client confirmation once they confirm we can close the ticket

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi Team I`ve tested the report and its is working fine the issue has been resolved I am going to close this ticket

CC: @audhi3k @Mahesh3ktech

**Comment by Ejaz3KT** [comment]
Hi Mr. @Prakash3K Please close this ticket in the support portal with the 10 hours of total effort

CC: @audhi3k @Mahesh3ktech
