### ISSUE TITLE
GST Reg No. in RRL - GST Reg. No. should come from UL in Delivery Challan Report and Location List-CAS-01495-N6N7S2

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#780]
GSTIN of the vendor should appear on the Delivery challan raised as part of the Outgoing Job work order. Currently the source is GST registrations page, which need to be changed to Vendor card > GSTIN

**Comment by TabrejAlam3K** [comment]
Need to discuss with the client and get the more information about the ticket.

@audhi3k @Shasthara @Jayanth3KT

**Comment by TabrejAlam3K** [comment]
@TabrejAlam3K - Yesterday follow up with the client over an email, but still no response receive form the Client side.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @Sarikab1222 - Can I Close this ticket due to no response, We will create as new in future if the client will raise the same points.

CC : @audhi3k @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi Ms. @Sarikab1222 - Due to non response from the client side. Please confirm for closure.

CC : @audhi3k @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - When can we connect on this issues.

![Image](https://github.com/3ktech/General/assets/116171982/a113f024-60d4-4dd7-8da2-8f542b4995bb)

CC : @audhi3k @Sarikab1222

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K  Changes has been done on UAT Please Check and confirm.
cc: @audhi3k @3ktech

**Comment by audhi3k** [comment]
Mr @TabrejAlam3K  hold this ticket

**Comment by TabrejAlam3K** [comment]
Hi Ms. @Sarikab1222 - This issue has been fixed on Staging Sandbox, Can we deployed into the Production Environment?

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please be available for 30 min to deply the changes into the Production today. I will confirm the timing.

CC : @audhi3k @Shasthara @Sarikab1222

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K at what time you want my availability.

cc: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Mr. @rohit3k - Based on client availability.

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K please inform me at least 30 Minutes before.

**Comment by TabrejAlam3K** [comment]
UL will be available on monday to deploy the changes.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Discussed with Mr. Dhawal he said we will deploy it on production on Monday 27-11-2023.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Mr. @rohit3k  - Please provide the changes on Code level what you have done for this ticket, UL team want to review it before publishing into the Production.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Code reference share with the client for reveiw, Waiting for client confirmation for deployment.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Deployment confirmaiton pending at client end.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Final mail to send to the client, If you no response received we will close this ticket tomorrow.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - When we can deploy the changes into the Production Environment.

![Image](https://github.com/3ktech/General/assets/116171982/47ff26d4-d7aa-4795-aac3-644a20d34fcd)

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
Ticket has been deployed on the Production Environment. I am closing from the Git

**Total Effort Hours = 4 Hours**

CC : @audhi3k @Shasthara
