### ISSUE TITLE
Troubleshooting – Troubleshooting events of the subject/Problem statement-CAS-01497-X3Z8P3

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#781]

**Comment by Jayanth3KT** [comment]
[Troubleshooting – Troubleshooting events of the subject/Problem statement]

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Shasthara - Please explain the requirement or activity what we need to do on this.

CC : @audhi3k @3ktech @Jayanth3KT

**Comment by TabrejAlam3K** [comment]
@TabrejAlam3K - Mr. @Shasthara will provide the more details about the requirement.

CC : @3ktech

**Comment by Jayanth3KT** [comment]
Hi @3ktech As a first step of troubleshooting, Somendra is expected to send the event of “Invoice movement not executed where the current mail mechanism did not send mail as the team suspects D365 BC did not send invoice against specific RTB numbers despite of Accounts department processed the RTB and invoice is raised. The RTB number/Invoice numbers are expected from Somendra before Sep 06’23.

CC: @audhi3k @Shasthara @TabrejAlam3K

**Comment by audhi3k** [comment]
Closure for non-response
