### ISSUE TITLE
Data Correction – 3KT has received about 240 records of RTB – In Billing and about 87 records of Not Posted status. These are to be processed manually-CAS-01496-F2Z9Y2

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#782]
[In Billing Process (002).xlsx](https://github.com/3ktech/General/files/12608688/In.Billing.Process.002.xlsx)
[Not Posted (002).xlsx](https://github.com/3ktech/General/files/12608689/Not.Posted.002.xlsx)

**Total Consume Hours 10.5**

**Comment by Jayanth3KT** [comment]
Data Correction – 3KT has received about 240 records of RTB – In Billing and about 87 records of Not Posted status. These are to be processed manually

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Shasthara - As per our discussion we have already completed the Manual Activity.

CC : @audhi3k @Jayanth3KT

**Comment by TabrejAlam3K** [comment]
@TabrejAlam3K - I have update all the RTB records which was In Billing Process and Not Posted, Same I have update in the Daily LKS Standup call.

**Comment by TabrejAlam3K** [comment]
Mr. @Shasthara - Can we close this ticket.

CC : @audhi3k @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - I am closing the ticket as completed, during the session he confirmed for closure.

CC : @audhi3k @Shasthara
