### ISSUE TITLE
ECOMM-1477 : GenStore | SwiftLink | BC | System is removing the price slabs when sales price list is changed from Draft to Active-CAS-01440-L9Y8J4

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#783]
@Jayanth3KT 
Task completed and deployed into Production close the ticket.

**Comment by Jayanth3KT** [comment]
Hi Padma,

We need a fix for the below issue.

ECOMM-1477  : GenStore | SwiftLink | BC | System is removing the price slabs when sales price list is changed from Draft to Active

When are creating the sales price list, it will be in draft mode, when all the items price slabs are fine, we change the sales price list from Draft to Active.

The issues is, when we are doing this, the system is removing the price slabs for the items as duplicate.

**Comment by Padma2717** [comment]
Task completed and deployed in Production . Effort hours : 12
