### ISSUE TITLE
ECOMM-1439 | GenStore | SwiftLink | BC | Need to enhance the sale pricelist to include the PriceType CAS-01324-C9H1K2

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#784]
@Prakash3K  @Jayanth3KT  

Task completed and deployed into production Kindly close the ticket

**Comment by Prakash3K** [comment]
Currently the price list has a provision to have a price slabs, we need to include PriceTypes in it for the each of the customers.

PriceTypes :

OM – Open Market

IB – Install Base

RRC – Rental Reagent Contract

  We need
 1. Enhance the get APIs of it.  
 2. Provision to upload the price details in excel format.

**Comment by Padma2717** [comment]
Task completed and deployed in Production Effort hours : 51
