### ISSUE TITLE
Need a fix for the ECOMM-1478-CAS-01455-P0W9Q5

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#785]
@Jayanth3KT 

Duplicate Task

**Comment by Jayanth3KT** [comment]
We need a fix for the ECOMM-1478 : GenStore | SwiftLink | BC | The Job Queue Event to handle the Order Copy is failed with "An Unexpected error occurred after a database command is executed"

Basically, we seed that.

The Job Queue Event to handler has failed in the GenWorks Sandbox with the with "An Unexpected error occurred after a database command is executed" but the it got fixed after the Environment update
But again, the same issue happed in GenWorks Sandbox

Please look into this issue on priority as we have panned production release by 31st Aug 23.

**Comment by Padma2717** [comment]
Duplicate ticket kindly close
