### ISSUE TITLE
Need a fix for ECOMM-1466:GenStore | SwiftLink | BC | Need to capture the all order header level fields in Sales Order CAS-01354-K0H1J5

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#786]
@Prakash3K  @Jayanth3KT 
Task completed and deployed into production, kindly close the ticket.

**Comment by Prakash3K** [comment]
We are not able to see the few fields of order header level info in Sale order in BC, Order Copy and New Order notification mail.

we must ensure that all the below order level fields are populated correctly.

"DocumentSourceCode": <-- Order Source (SWIFTLINK/ESTORE/..)

"DocumentSourceNo": <-- Unique SwiftLink order numner

"SellToCustomerNo": <-- Sell to customer code

"BillToCustomerNo": <-- Bill to customer code

"ShipToCode": <-- Ship To Code

"PODate": <-- PO Date

"POReferenceNo": <-- PO Referecne numebr

"RequestedDeliveryDate": <-- Requested delivery date

"OrderComments": <-- Order Comments

"OrderTrackingCode": <-- Order tacking code, sales person & code

"OrderInstruction": <-- Order instruction

Currently we enter the values for these fields anytime in workflow and save in saving the draft order. but in sales order header the data is not getting captured.

**Comment by Padma2717** [comment]
Task completed deployed in Live, Effort hours : 28
