### ISSUE TITLE
Need a fix for ECOMM-1479-CAS-01456-G5X6Z7

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#787]
@Jayanth3KT  @Prakash3K 

Task completed under customer testing

**Comment by Jayanth3KT** [comment]
Hi Padma,

The current GW Email Attachment Handler runs only for all the orders which are placed after the Job queue is started. But we need a enhancement for the same with below use cases.


ECOMM-1479: GenStore | SwiftLink | BC | Needs an enhancement to Codeunit ∙ 50110 ∙ GW Email Attachment Handler to run for a configurable range.

We should have provision to

The Current process should be enhanced to take all the unprocessed orders for a day, when the event is running
If current event is running it should not conflict with new if the previous process is not completed
We should have a provision to run the process for a date rage, in this case it should process the orders by date from start date to end date

**Comment by Padma2717** [comment]
Duplicate ticket
