### ISSUE TITLE
ECOMM-1472 | GenStore | SwiftLink | BC | Need API to Update the details of existing SalesOrder's Attachement by giving Attachment File name or by Invoice No CAS-01383-D7Z5L0

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#788]
@Prakash3K 

Task completed and deployed into production.  Kindly close the ticket .

**Comment by Prakash3K** [comment]
Need a API to - Update the details of existing SalesOrder's Attachement for a givin SalesOrder, Attachment File name or Invoice No

The Parameters to be passed to API

Sales Order Number
Attachment File Name Or
InvoiceNo
We should be able to update only passed details.  Example we can

 Attachment / FileName : upload new file
"InvoiceNo": "GWTN23-24_PH0810",
"InvoiceDate": "2023-07-19",
"EWayBillNo": "",
"ConsignmentNo": "40710325504",
"Expecteddeliverydate": "2023-07-19",
"DocketNo": "40710325504",
"Deliverynotedate": "2023-07-19",
"Deliverypartnerid": 2,
"Destination": "Chandigarh",
"DeliveryStatus": 14

**Comment by Padma2717** [comment]
Task completed . Effort hours 24
