### ISSUE TITLE
UAT and Handover the Production Environment

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#789]

**Comment by TabrejAlam3K** [comment]
**8 September 2023**

Hi Mr. Dikshant Jain

Good Morning

Can we connect on the below points for testing and closing.
1.	Trial Balance Report
2.	Opening Balance

[@Abhishak Saxena](mailto:abhishak.saxena@vridhihomefinance.com) – Sir can you share the Loan & Customer Excel file which having not more then 5-10 lines for us. We want to test in the Live Production Environment without posting.

**Comment by TabrejAlam3K** [comment]
**8 September 2023 - Audhilakshmi S**
Dear Mr. Abhishak,

Good Day.

We would like to do Internal Testing with the real data, hence we would require some sample data for Customer and loan i.e., 5 records on each file

Can you share it, so that we can test with the real and to do the UAT

**Comment by TabrejAlam3K** [comment]
**12 September 2023 - Abhishak**
Dear Audhilakshmi,

Just confirm me 
1.	you need this data from 01st Apr 23 onwards or it can be of past also?
2.	After testing will you clean this data on production or next time we need to remove this data from data dump?

**Comment by TabrejAlam3K** [comment]
**12 September 2023 - Tabrej**
Hi Mr. [@Abhishak Saxena](mailto:abhishak.saxena@vridhihomefinance.com) Sir,

1.	Yes, you can provide the any random data we want to check the process only.
2.	After testing the flow of entries, We will clean all the records from the BC.

**Comment by TabrejAlam3K** [comment]
**13 September 2023 - Abhishak**
Dear Tabrej,

Attached are the file which we can place. 
We have given 2 FTP locations, let me know the FTP location to place.

**Comment by TabrejAlam3K** [comment]
I have done the Internal Testing and UAT as well with Mr. Dikshant. LMS Integration is working fine.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam - We have delete all the sample/testing data from the Production Environment.

**Comment by TabrejAlam3K** [comment]
@TabrejAlam3K - I have done the LMS Integration testing in the Production Environment and found it is working fine.

UAT - Done the UAT with the client (Mr. Dikshant).

Production Environment is ready to use with the Live data.

**Comment by Jayanth3KT** [comment]
Hi @TabrejAlam3K can I know source of this ticket this isn't raised in case management.

CC: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
I am closing this ticket as completed. Client started the production entry in the New Environment.

I have spend total 8 Hours for this ticket.

CC: @audhi3k @Shasthara @Prakash3K
