### ISSUE TITLE
New Page Required for Posted Service Invoice - Filter based on Location Code (SCON01).-CAS-01419-L8F1K9

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#790]
**Total Effort Hours = 4 Hrs**

**Comment by Jayanth3KT** [comment]
New Page Required for Posted Service Invoice - Create a new page with Name Posted Service Invoice. It should be copy of Poste Sales Invoice only need to apply the filter on Service Invoice.

**Comment by TabrejAlam3K** [comment]
29 August 2023

**Comment by TabrejAlam3K** [comment]
@TabrejAlam3K - Yesterday follow up with the client over an email, but still no response receive form the Client side.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please move the changes into the Production Environment. After your confirmation we will close this ticket.

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
Hi Ms. @Sarikab1222 - Due to non response from the client side. Please confirm for closure.

CC : @audhi3k @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Have you move the changes into the Production Environment? After your confirmation we will close this ticket.

CC : @audhi3k @Sarikab1222

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K As per our discussion I need a session with client to get the access of Production DB to deploy the changes.

cc: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please share the effort hours for thsi issues.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - This is deployed on the Production Environment infront of the Client. You can close this from the support portal as well.
**Total Effort Hours = 4 Hrs**

CC : @audhi3k
