### ISSUE TITLE
GSTIN of the vendor should appear on the Delivery challan raised as part of the Outgoing Job work order. Currently the source is GST registrations page, which need to be changed to Vendor card > GSTIN-CAS-01417-G0W9K4

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#792]

**Comment by Jayanth3KT** [comment]
GSTIN of the vendor should appear on the Delivery challan raised as part of the Outgoing Job work order. Currently the source is GST registrations page, which need to be changed to Vendor card > GSTIN

**Comment by TabrejAlam3K** [comment]
Mr. @Jayanth3KT - You can close this ticket because this is copy of ticket #780. I am closing this from the Git

CC : @audhi3k @Shasthara
