### ISSUE TITLE
Add Discount Column and Discount total column In PQ,PO & PINV reports

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#797]
Hi Team The fervid client requires a discount column and discount total amount column in the purchase order report purchase quote report and purchase invoice report

CC: @3ktech @audhi3k

**Comment by audhi3k** [comment]
Ms @Sarikab1222, for your reference.  This is the new requirement from Fervid

**Comment by Sarikab1222** [comment]
Ok, @Ejaz3KT  - Pls maintain in the issue register and also add the effort hours besides it.

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 In the reports the discount field added correctly but the calculation is coming wrong please check 

![Image](https://github.com/3ktech/General/assets/125632927/d3d26210-a5ba-4ce5-b76c-89610412d06d)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 The discount calculation in the Purchase order report is working fine please add this same discount field to the purchase quote, Purchase Invoice, and work order then deploy into the production

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 The discount field is not add in the purchase reports please check once

**Comment by Manoj01021999** [comment]
Hi @sruthi1017 this Ejaz accessing @Manoj01021999 laptop I Can`t able to find the discount column in purchase reports.

![Image](https://github.com/3ktech/General/assets/126780544/a924cf17-636f-484f-8bae-3730e5212a84)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Please deploy this in the production ASAP

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The report changes has been deploy in production need to get client confirmation

CC: @audhi3k @sruthi1017

**Comment by Ejaz3KT** [comment]
Hi team The Fervid client has confirmed regarding this discount column in purchase reports so we can close this ticket

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi Team client has confirmed I am closing the ticket

CC: @audhi3k
