### ISSUE TITLE
86 CRTB and 42 RTB records which are appearing as In Cancellation Process and In Billing Process-CAS-01502-J3N4G2

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#798]
**Total Effort Hours - 3.5 Hours**

**Updated Total Effort Hours is 6.5 including 25%**

**Comment by Prakash3K** [comment]
[RTB-In Billing Process.csv](https://github.com/3ktech/General/files/12608458/RTB-In.Billing.Process.csv)



[CRTB-In Cancellation Process.xls](https://github.com/3ktech/General/files/12608465/CRTB-In.Cancellation.Process.xls)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Shasthara - It will take minimum of 3 Hours Effort at our end. Please get the approval for this.

CC : @audhi3k @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Shasthara - As discuss no need approval on this. I am going to start working on it.

CC : @audhi3k @Prakash3K

**Comment by TabrejAlam3K** [comment]
**Issue in MS Flow**

[11:55 am] Karthik D

ErrorCode: Internal_RecordNotFound  The API Webhook Subscription does not exist. Identification fields and values: Subscription Id='7fbee94ef8a945ec80ae4425f3d1399c'  CorrelationId:  9fed5a50-f53c-40c6-b602-23212f16be7b.

clientRequestId: 02b0c887-ea1d-4e35-905b-d060d6e7f26b

[11:56 am] Karthik D

All of a sudden the flow stopped triggering

[11:56 am] Karthik D

when we turn off and turn on the flow, getting the above mentioned error

**Comment by TabrejAlam3K** [comment]
[RTB-In.Billing.Process_Updated.xlsx](https://github.com/3ktech/General/files/12616796/RTB-In.Billing.Process_Updated.xlsx)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Shasthara - I have already spend 5 hours on this and if the Ms Flow issue will resolved. It will take another 1-2 hours to complete.

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
All the RTB and CRTB is procssed successfully and informed client as well while the Daily Standup call.

Only Once RTB was not success - Issue was instead of Invoice No. it was taking invoice no. as RTB no.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
As per the confirmation over an email by the client (Mr. Vivek), I am going to close the ticket.

@Prakash3K - You can close the ticket from the support portal as well.

CC : @audhi3k @Shasthara
