### ISSUE TITLE
Purchase Register Report

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#799]

**Comment by Prakash3K** [comment]
While executing purchase register report,  we are struck with the below errors and could not use the report.

a. Credit memo details are not captured in the report.

b. Could not execute the report for August due to below error.




![Image](https://github.com/3ktech/General/assets/140147250/d52a0acc-2d12-41c9-925b-64ee2ddd4d98)



[Purchase register (2).xlsx](https://github.com/3ktech/General/files/12616276/Purchase.register.2.xlsx)

**Comment by sruthi1017** [comment]
hi @Ejaz3KT the report is now available in sandbox can we connect for this.
CC : @3ktech @gsudarsan3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 The report is not working fine it is sowing incorrect data and also purchase credit memos are not coming

CC: @audhi3k

**Comment by sruthi1017** [comment]
hi @Ejaz3KT it is not possible to display the credit memos in the same report we have to create new report for credit memos

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 OK and what are the effort hours you need to develop a separate report for the posted purchase credit memo (Purchase register)

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
Ms. @sruthi1017 is working on this  task please  update the status after completing this task @sruthi1017

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 The report is fine please deploy this in the in production

[Purchase register (2).xlsx](https://github.com/3ktech/General/files/12747972/Purchase.register.2.xlsx)

CC: @audhi3k @Amar-3KT

**Comment by sruthi1017** [comment]
hi @Ejaz3KT as we discussed yesterday can u please share me the field mapping for new format and requirement.
cc: @audhi3k @3ktech @gsudarsan3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 ok I`ll Share

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I`ve tested the report some fields are having issues can we connect to discuss those issues

CC: @audhi3k @Amar-3KT

**Comment by sruthi1017** [comment]
yes @Ejaz3KT we can

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 As we discussed in the call Please make the changes
1. Calculate Invoice value (Taxable + CGST + SGST + IGST= Invoice Value)
2. Rate is not coming properly
3. Add the credit Memo Caption
4. In Place of supply full state name should be shown
Please make the changes and update me ASAP
CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
Due to client unavailability, I`ve done the UAT today

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
Mr. Murali told me he would connect after lunch for the UAT session but due to time posting work he is not connected 

CC: @Amar-3KT @audhi3k

**Comment by Ejaz3KT** [comment]
I am trying to connect with Mr. Murali for the UAT session he is not available at this moment

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
Mr. Murali sir said he will connect in the second half for the UAT session

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Today  Mr. Murali has not connected with me for the UAT session due to his busy schedule 

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
UAT session has been done with Mr. Murali he will check at their end and give us confirmation

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
Waiting for the Client's confirmation

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I had a call with Mr. Murali he told me to deploy this report in the production I am requesting you to Please deploy this purchase register report in the Fitchner production environment.

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
Due to Ms. @sandhya3k Madam being on leave to so deployment has not been done  today

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @gsudarsan3k  Is the changes has deployed in the production?

CC: @audhi3k @Amar-3KT @sruthi1017

**Comment by Ejaz3KT** [comment]
Report is fine client has confirmed we can close the ticket

CC: @audhi3k @sruthi1017
