### ISSUE TITLE
System Entries and Detail Trial Balance Entry Not Matching

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#802]
**PPI-CHE-002454**

**Comment by gsudarsan3k** [comment]
Hi @sandhya3k please coordinate with @TabrejAlam3K what needs to be done for this task

CC: @audhi3k @3ktech

**Comment by audhi3k** [comment]
It's functional ticket, tech support not required

**Comment by TabrejAlam3K** [comment]
Hi @audhi3k Mam We need to connect on this and analyze this.

**Comment by TabrejAlam3K** [comment]
Closing this old ticket because the client have raised recently against the same.

CC : @audhi3k @Shasthara @Prakash3K 

New Ticket #844
