### ISSUE TITLE
Transaction Date and Value Date issue

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#803]
**Requirement**

Transaction Date = Posting Date (Gen. Journal Line)
Value Date = Document Date (Gen. Journal Line)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Transaction Date and Value Date is not working, Can we connect and close this issue?

This is high priority task which we need to fix it on priority basis.

CC : @audhi3k @Shasthara @3ktech

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Transaction Date and Value Date is not working, Can we connect and close this issue?

This is high priority task which we need to fix it on priority basis.

CC : @audhi3k @Shasthara @3ktech

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - issue has been fixed. kindly check and update.

CC: @3ktech, @audhi3k, @Shasthara

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - as confirmed to move the changes to production is done.


CC: @3ktech, @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - If the ticket is available on the support portal you can close this.

**Total Effort time - 3 Hours.**

I am going to close this ticket as completed.

CC : @audhi3k @Shasthara
