### ISSUE TITLE
Modifications in the purchase invoice report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#804]
Hi Team we need to modified below points in the purchase invoice report

1. GST Bifurcation in Purchase Invoice Report 
2. Round Off field should be below to TDS field
3. TDS Amount should show In Negative
4. The name of the supplier should be removed from the Purchase invoice report
5. Caption should be changed from inter-state tax to Integrated tax
6. Calculation Issue in Tax Bifurcation table
CC: @audhi3k @3ktech

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Can we connect For this Ticket

**Comment by sruthi1017** [comment]
yes @Ejaz3KT

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 The changes has not done yet in the report please check the report 

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
HI @sruthi1017 Please deploy changes this in the production ASAP

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The report has been deploy in production need to get client confirmation

CC: @audhi3 @sruthi1017

**Comment by Ejaz3KT** [comment]
Hi team The Fervid client has confirmed regarding this discount column in purchase reports so we can close this ticket

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi Team client has confirmed and I am closing the ticket

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi Team client has confirmed and I am closing the ticket

CC: @audhi3k
