### ISSUE TITLE
Issues related to job Consumption Entries

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#805]

**Comment by Jayanth3KT** [comment]
I have observed the one Job Task No. is having different job task descriptions and some cases Job task descriptions are not coming.


Hence, while passing the job consumption entry  “ job task description” field should come automatically ( and this field should be Un-editable and mandatory) based on Job Task no.

Further, one job Task No. should not be allowed multiple names.

(we need to bring the Vertical also – Wind and Solar and task no should have separate coding to avoid using the same task no for solar and wind.)

Please work out the same.

**Comment by Jayanth3KT** [comment]
Hi @3ktech could you align technical person to this ticket. Need to discuss and need to make changes.

CC: @audhi3k

**Comment by Mahesh3ktech** [comment]
hi @Jayanth3KT requirement is not clear kindly discuss with client.

CC: @3ktech, @audhi3k

**Comment by Jayanth3KT** [comment]
Hi @Mahesh3ktech 

1.	We will create a new table with 3 Field as 
2.	Task Sl. No. - Code 20
3.	Task No. - Similar to Task no. in Job Task Table
4.	Description - text field Similar to description field in Job Task Table

	In the Job Task table, the following to be modified: 
1.	New lookup field will be added to the new table (highlighted in point 1 field a)
2.	On selection of the above field the data from Task no. and description from the table to be updated in the Job Task line in Task no. and Description field respectively
3.	The fields Task no. and Description will be done non-editable.  

(we need to bring the Vertical also – Wind and Solar and task no should have separate coding to avoid using the same task no for solar and wind.)

**Comment by Jayanth3KT** [comment]
Hi @Mahesh3ktech  we got approval from client, we can start working on it.


![Image](https://github.com/3ktech/General/assets/142868335/78aaad1e-b2ab-4bda-b41d-cb36b5cc9c63)



CC: @audhi3k @3ktech

**Comment by Jayanth3KT** [comment]
Hi @Mahesh3ktech UAT has been done with client and they agreed for previous requirement changes.

 they have requested to add 2 more points.

1. Have to make Job posting group Field mandatory.
2. Vertical row should appear in Task no lookup table.

CC: @audhi3k  @3ktech

**Comment by Mahesh3ktech** [comment]
hi @Jayanth3KT - changes has been done and demonstrated to you. kindly check and confirm.

cc: @3ktech, @audhi3k, @gsudarsan3k

**Comment by Jayanth3KT** [comment]
Hi @3ktech There is new requirement point to be added

1. Job task no to be added in job journal line.

CC: @audhi3k @3ktech

**Comment by Mahesh3ktech** [comment]
hi @Jayanth3KT - changes has been done. kindly check and update.

cc: @3ktech, @gsudarsan3k, @audhi3k

**Comment by Jayanth3KT** [comment]
Hi @Mahesh3ktech Kindly deploy changes into live.

CC: @audhi3k @Tushargupta3K @3ktech

**Comment by Mahesh3ktech** [comment]
hi @Jayanth3KT - deployment is done in live. kindly check.

cc: @3ktech, @gsudarsan3k, @audhi3k

**Comment by Jayanth3KT** [comment]
@Mahesh3ktech Client confirmed to close this ticket Thankyou.


CC: @audhi3k @Tushargupta3K @3ktech
