### ISSUE TITLE
Sales invoice templates - amend telephone numbers/add text

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#809]

**Comment by Jayanth3KT** [comment]
Hi team,

Can you please amend the telephone number quoted on the sales invoice template across the x3 companies in BC (Political Engagement Limited, Holyrood Communications Limited & Fenman Limited).


![Image](https://github.com/3ktech/General/assets/142868335/bf350394-7835-46a8-970d-ede69c6e31c9)


Please amend the above to the below:


We accept all major credit cards except AMEX – call Credit Control on +44 (0) 207 593 5565 or 5622.

Customer Service +44 (0) 207 593 5669.

**Comment by TabrejAlam3K** [comment]
@TabrejAlam3K - I will connect with the Client and get the proper requirement.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
**Report ID - 50100 (Company - Holyrood Communications Ltd.)**

Requirement : 
1. Remove Text - We accept all major credit cards except AMEX - call credit control on +44 (0) 20 7593 5669.
2. Add Text - **We accept all major credit cards except AMEX – call Credit Control on +44 (0) 207 593 5565 or 5622.
    Customer Service +44 (0) 207 593 5669.**

CC : @audhi3k @Shasthara @3ktech

**Comment by TabrejAlam3K** [comment]
Thanks Ms. @sruthi1017

**Comment by TabrejAlam3K** [comment]
@Jayanth3KT - I am closing this ticket as confirmed by the client(Mr. Chris Bennett (External)) on team external group chat.

![Image](https://github.com/3ktech/General/assets/116171982/ecba2bbd-c565-4bfe-9412-22b7b66993bf)

CC : @audhi3k @Shasthara
