### ISSUE TITLE
Amend telephone number in email template in BC

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#810]

**Comment by Jayanth3KT** [comment]
Hi – please amend the telephone number highlighted in the below email - this is the email that is sent out of BC across the x3 companies in BC (Political Engagement Limited, Holyrood Communications Limited & Fenman Limited).


If you wish to settle by credit/debit card then please call us on 0207 593 5565, quoting your invoice number.


![Image](https://github.com/3ktech/General/assets/142868335/b672c3fb-d65b-4671-8a3b-4e340bf195ac)

**Comment by TabrejAlam3K** [comment]
@TabrejAlam3K - I will connect with the Client and get the proper requirement.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
I am closing this ticket as completed because client have tested and they are not highlighted the issue again.

Mark as 2 hours for closure.

CC : @audhi3k @Shasthara @Prakash3K
