### ISSUE TITLE
Customer Job Queue is not Working

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#813]

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - This is the priorith taks which we need to close today. Please make your self free from the other task.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - This is the priorith taks which we need to close today. Please make your self free from the other task.

CC : @audhi3k @Shasthara

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - issue has been fixed, kindly check and update.

CC: @3ktech, @audhi3k, @Shasthara

**Comment by TabrejAlam3K** [comment]
It is working fine and also informt to the Client (Mr. Dikshant).

I am closing this ticket as completed.

CC : @audhi3k @Shasthara @Prakash3K
