### ISSUE TITLE
Option to create Terms & Conditions manually

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#817]
Hi Team In the present case there is no option to create New terms & conditions in dynamics so the fervid team is requesting to provide them an option to create new terms & conditions as per their requirements 

![Image](https://github.com/3ktech/General/assets/125632927/18b9bade-2dc6-45d0-91ee-008eaf518ee6)

I am requesting the technical team please let me know what is the actual Hours your required for this ticket

CC: @audhi3k @3ktech

**Comment by sruthi1017** [comment]
hi @Ejaz3KT can we connect for this

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 yes

**Comment by sruthi1017** [comment]
hi @Ejaz3KT it is not possible to add manually to an option field or enum field from front end 
CC: @gsudarsan3k @3ktech @audhi3k

**Comment by Ejaz3KT** [comment]
I`ve explained the scenario to the fervid team if we provide manually new terms & conditions are not reflected in the reports Now I am closing this ticket if they require this functionality we can create a new ticket for the same 

CC: @audhi3k
