### ISSUE TITLE
11CRTB and 103 RTB records which are appearing as  In Cancellation Process and In Billing Process CRM:0023133

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#818]

**Comment by Jayanth3KT** [comment]
Dear Shasthara,
Further to our today’s discussion, I am still able to see almost 103 RTBs in In Billing process (refer to attached xls) this list contains the  and 11 CRTBs, though most of the CRTBs were created between 13th Sep to 20th Sep, however, there are two CRTBs (0000877192 & 0000875893) of 7th July and 4th Aug which are still pending. Please let me know if any further discussion is required in regard to it.
 

[CRTB-2023-09-20.xls](https://github.com/3ktech/General/files/12696872/CRTB-2023-09-20.xls)
[RTBS In Billing Process-20-Sep-23.csv](https://github.com/3ktech/General/files/12696873/RTBS.In.Billing.Process-20-Sep-23.csv)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Shasthara - I need 7 hours for this taks including 25%. Please provide the approval beased on that, I will start working on it.

CC : @audhi3k @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Shasthara - As per our discussion with the client (Mr. Vivek) no need to workupon this ticket. I am closing this ticket.

@Jayanth3KT - You can close this from the support portal as well.

CC : @audhi3k
