### ISSUE TITLE
New Request: Adding CE Field to the posted sales invoices report

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#819]
**Total Consumed Hours = 3 Hours**

**Comment by Jayanth3KT** [comment]
I would like to add a field on the posted Sales Invoices report in BC>Sales>Posted Sales Invoices, I have tried through my personalized option, but this does not work.

What I need is the Customer Engagement>CE Sales Order No and CE Quote No Data from each invoice on the posted sales invoice report.

This is where CE Sales Order it is located on each invoice:


![Image](https://github.com/3ktech/General/assets/142868335/275cb8ed-b37f-4152-8432-c9bf2c369306)

Let me know if you need more information or require further explanations.

**Comment by gsudarsan3k** [comment]
Hi @sruthi1017 Get the requirement from @TabrejAlam3K  and work on it. 

CC: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
@Jayanth3KT - Please forward the requirement mail to me which you have received from the client side.

Request - before creating any ticket in git please forward the mail which you have received from the client agingst the task.

CC : @audhi3k @Shasthara @gsudarsan3k

**Comment by sruthi1017** [comment]
hi @TabrejAlam3K , as we discussed please update once you received the sufficient requirement from client
cc : @3ktech  @gsudarsan3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - I have done the session with the client. Please share your effort hours on this.

Requirement : -
Need to add two fileds called **CE Sales Order No.** & **CE Quote No.** on the below list page.
1. Posted Sales Invoice - Posted Sales Invoices (143, List)
2. Posted Sales Credit Memo - Posted Sales Credit Memos (144, List)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - See the below screen short.

![Image](https://github.com/3ktech/General/assets/116171982/7abae3d7-c035-41bc-a86c-4259f14393e7)

![Image](https://github.com/3ktech/General/assets/116171982/aa2cd8a9-efda-4561-b009-d2fc8f62c9d3)

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Can you please update the status of this ticket.

CC : @audhi3k @Shasthara

**Comment by sruthi1017** [comment]
hi @TabrejAlam3K  the changes has been done for two pages and published into the sandbox environment can u please test and confirm
cc : @3ktech @audhi3k @gsudarsan3k

**Comment by TabrejAlam3K** [comment]
Hi @sruthi1017 - I have tested it is working fine, Please move the changes into the Production Environemt.

CC : @audhi3k @Shasthara @3ktech @gsudarsan3k

**Comment by TabrejAlam3K** [comment]
Client Confirmed for Closure.

![Image](https://github.com/3ktech/General/assets/116171982/5ab2f670-d044-470b-942c-3f0e504a244b)

CC : @audhi3k @Shasthara
