### ISSUE TITLE
Detailed Trial Balance Report - Merit

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#82]
Client required the dimension field on report output - currently dimension is not coming in reports.
We will start working on next discussion on Monday 30-01-2023.

**Comment by TabrejAlam3K** [comment]
@audhi3k  See the attached sample requirement excel sheet I have receive from the customer.


[Detail Trial Balance (1).xlsx](https://github.com/3ktech/General/files/10554304/Detail.Trial.Balance.1.xlsx)

**Comment by audhi3k** [comment]
@3ktech, Mr Karthiik as discussed kindly share the time estimate for the same

**Comment by TabrejAlam3K** [comment]
See the attached Shortcut dim code against these new fields in this report.

[Detail Trial Balance (1).xlsx](https://github.com/3ktech/General/files/10556177/Detail.Trial.Balance.1.xlsx)

**Comment by audhi3k** [comment]
@3ktech, kindly share the time estimate

**Comment by TabrejAlam3K** [comment]
@audhi3k  - As per the today session with Mr. Bhoopathy he asked about the status of this issues.

**Comment by sandhya3k** [comment]
@TabrejAlam3K  please check the report?

**Comment by TabrejAlam3K** [comment]
Report tested internally in Sandbox_India and asked to the client for self testing. Once they confirm then we will move this into the production environment.

CC @audhi3k

**Comment by TabrejAlam3K** [comment]
Client is tested this into the sandbox and share the feedback it looks good.

@sandhya3k  - Can you please move this into production in **Indian Tenant** as well as **UK Tenant**.

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Once the report will move into the Production please inform me, based on your information We will update to the client.

**Comment by sandhya3k** [comment]
Hi @TabrejAlam3K, i moved to production. Can u please check and confirm?

**Comment by TabrejAlam3K** [comment]
Thanks @sandhya3k  I have passed the same information to the client.

**Comment by sandhya3k** [comment]
@TabrejAlam3K can u please update the regarding UK tenant as well?

**Comment by TabrejAlam3K** [comment]
Confirmation Received from the client.

![Image](https://user-images.githubusercontent.com/116171982/218392448-26c773bd-a5e1-4dfa-8ae6-531c85134de5.png)
