### ISSUE TITLE
Vendor Payment Monitoring

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#820]

**Comment by Prakash3K** [comment]
They would like to track their vendor payment against the Purchase Order /Bills.

Whether there is any option available in the ERP to do the same or need any customization

CC: @audhi3k @shivakumar3k

**Comment by Jayanth3KT** [comment]
We have shared the processes to apply entries for the advance payment, we have shared some customization  to be done. Client has to confirm customization and requirement fulfillment.

CC: @audhi3k @Tushargupta3K

**Comment by Jayanth3KT** [comment]
Client has mentioned that some system entries are generated when they apply posted purchase invoice with Payment. 
But as we checked on our side by posting invoice and then payment  and then their application no automatic entries GST extra  entries created. Need to discuss with client and ask what process they are following.

CC: @audhi3k @Tushargupta3K

**Comment by Jayanth3KT** [comment]
As discussed with client, client has not used apply entry from a long time so there are too many open entries to apply and client only want to apply for payment entries not want to apply for RCM vendor payment entries, We have suggested to follow standard process to apply all the entries it will help to reduce manual GST work, client is internally discussing to apply all open pending entries and also whether to apply in future all entries and get report from system.

Hence ticket will be kept in hold till their confirmation.

CC: @audhi3k @Tushargupta3K

**Comment by audhi3k** [comment]
Mr @Jayanth3KT, I would like to discuss with you on this

**Comment by Prakash3K** [comment]
Considering the client's requirement to postpone the ticket until March, we are closing this ticket now.


CC: @audhi3k @Tushargupta3K
