### ISSUE TITLE
FA registers & Accrual schedule in Merit UK

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#822]
**Client Approved Hours - 6 Hours**

**Comment by Jayanth3KT** [comment]
Hi Tabrej,

As you know that we have customised "FA registers" and "Accrual schedule" reports in Merit data IND BC environment, we now need the same reports to be developed/customized in Merit data UK environment too.

Pls use the same logics and report formats. Let me know for any clarifications.

[@Audhilakshmi S](mailto:Audhilakshmi.s@3ktechnologies.com), Hi audhi, is there any update on the GST applied entries after the discussion we had that day ?

cc: @audhi3k 
(Mail has been forwarded to you @TabrejAlam3K )

**Comment by TabrejAlam3K** [comment]
Hi @3ktech - We have already develop the report in Merit India Tenant, Same report We need to publish for the Merit UK Tenant, Please let us know how much time effort you have required for this.

**FA Register** is Done by @sruthi1017 & @sandhya3k  for India Tenant

**Accrual schedule** is Done by @rohit3k for India Tenant

CC : @audhi3k @Jayanth3KT

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - This is approved by the client. Please deploy it in the UK Tenant Sandbox for testing. Once the client will confirm we will move the report in the UK Tenant production environment.

![Image](https://github.com/3ktech/General/assets/116171982/be154eb0-c09a-4aea-b998-fdb0608d0a62)

CC : @audhi3k @Prakash3K @Jayanth3KT

**Comment by sruthi1017** [comment]
hi @TabrejAlam3K the two reports has been published in sandbox can u please test and confirm 
CC: @3ktech @gsudarsan3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Thanks, let me completed the UAT with the client and let you know to deploy into the production.

CC: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
Hi @sruthi1017 - Changes is available in the Sanodbox, Please deployed it into the production.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi @sruthi1017 - Both the reports are available in the Sandbox & Production as well. Thanks

I have updated to the client(Ms. Swathi), She will test and let us know in this week.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - Accrual Report format is not coming correctly in the UK Production.

@rohit3k - Please help us to publish the same report whatever we have develop for India Tenant.

CC : @audhi3k  @sandhya3k

**Comment by TabrejAlam3K** [comment]
Hi @rohit3k & @sruthi1017 - Please update your comment here whether you guys deployed the changes?

CC : @audhi3k @Shasthara

**Comment by sruthi1017** [comment]
hi @TabrejAlam3K yes the changes has been deployed into sandbox and production as well
in first half itself it is completed
cc: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi have informed the Client (Ms. Swathi) she will check and confirm.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Today I will follwup with the client and update.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @sruthi1017 - Changes has been remove again form the Sandbox and Prodution.

@sandhya3k @rohit3k - Can you please check and disucss internally to fix the issues.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Accrual Schedule report is working fine and client confirmed for closure.

CC : @audhi3k @Shasthara

**Comment by niranjand22** [comment]
Connceted with Ms Swathi for FA Register.

Query- In FA Register Report --Commulative Depreciation column value is coming zero for few records(sold fixed assets).

Commulative Depreciation-total of depreciation in given timeframe.

Solution- This might be happening beacuse on the date of sale of fixed asset evrything is reveresed including Depreciation. So thats why it is showing cummulation depreciation as zero for those record.

if above is the correct reson for zero value in cummulative dep column. the ms swathi is fine with this.

cc @audhi3k

**Comment by niranjand22** [comment]
When an asset is eventually sold or put out of use, the accumulated depreciation associated with that asset will be reversed, eliminating all records of the asset from the company's balance sheet.

**Comment by niranjand22** [comment]
FA Register issue is resolved.

**Comment by niranjand22** [comment]
Ms Swathi will confirm by today for this reports to deply in UK Live.

**Comment by Jayanth3KT** [comment]
@niranjand22 kindly update the current status of this ticket and Due date for this ticket.


CC: @audhi3k

**Comment by niranjand22** [comment]
Sent Multiple follow up to Ms Swathi. She has to confirm. For deplyment to live.

**Comment by niranjand22** [comment]
Changes are not visioble in UK tenant. @sruthi1017  Please deploy the changes in UK tenant. cc @TabrejAlam3K

**Comment by niranjand22** [comment]
@sruthi1017  iss this deployed to UK live  tenant  ?

**Comment by niranjand22** [comment]
works fine we can closw thiss tickdt

@sruthi1017 @Prakash3K  cc @audhi3k
