### ISSUE TITLE
Issue in Employee Posting Group | Dynamics 365 CAS-01535-Y7F3Y6

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#824]
**Total Consume Hours = 1 Hours**

**Comment by Prakash3K** [comment]
@TabrejAlam3K - As requested, we are facing Issue in selecting the Employee Posting Group in Dynamics 365. The Posting Group has been created but the same is not available to select in the Drop-Down List. Kindly resolve this as soon as possible.

**Comment by TabrejAlam3K** [comment]
@Prakash3K - Please update the Case Id and Creation Date as well.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
I am closing this ticket as completed.

@Prakash3K - Please close this ticket from the support portal.

CC : @audhi3k  @Shasthara
