### ISSUE TITLE
Amend VAT number on Holyrood sales invoice template

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#826]

**Comment by Jayanth3KT** [comment]
Hi – can you please amend the VAT Number quoted at the bottom of the HOLYROOD COMMUNICATIONS LIMITED sales invoice template to GB432546309 – please note that this only needs to be amended in the company HOLYROOD COMMUNICATIOINS LTD in BC, thank you.



![Image](https://github.com/3ktech/General/assets/142868335/bb279c19-a8e4-4109-81e8-c5cf2a8dc3d0)


 

[Sales Invoice SI-HR001080.pdf](https://github.com/3ktech/General/files/12727390/Sales.Invoice.SI-HR001080.pdf)


(This mail has been forwarder to you)

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT - Please forward the mail to me which you have received from the client side.

I am not going to ping everytime to share the related mail.

CC : @audhi3k @Shasthara

**Comment by Jayanth3KT** [comment]
As, I mentioned in git that I have forwarded all mails that tickets have been assigned to you. ( Don’t know why it’s not triggering )

**Comment by TabrejAlam3K** [comment]
Changes has been done, waiting for customer confirmation.

CC : @audhi3k @Shasthara @Jayanth3KT

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT & @Prakash3K - Please update the email address of the client here, Who raised this ticket.

CC : @audhi3k @Shasthara

**Comment by Jayanth3KT** [comment]
Client i'd-chris.bennett@totalpolitics.com

CC: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Client confirmed for closure.

![Image](https://github.com/3ktech/General/assets/116171982/c632ccb7-2b5f-4990-8809-dff4a67393f9)

CC : @audhi3k @Shasthara @Jayanth3KT
