### ISSUE TITLE
Inventory Valuation Report Requirements

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#827]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/d085cad0-c357-4f59-9f47-56336dff2613)

**Comment by sandhya3k** [comment]
@Prakash3K  can u connect for above issue?

cc : @audhi3k

**Comment by Jayanth3KT** [comment]
Hi @sandhya3k we got effort hours approved by client you can start.


![Image](https://github.com/3ktech/General/assets/142868335/27398556-3b96-4ea6-9d9f-3e2cbec68909)

CC: @audhi3k

**Comment by sandhya3k** [comment]
ok
@Jayanth3KT

**Comment by sandhya3k** [comment]
@Jayanth3KT 

As discussed, once u got the information from the client please update here

**Comment by Jayanth3KT** [comment]
@sandhya3k kindly update the status.

CC: @audhi3k @3ktech

**Comment by sandhya3k** [comment]
@Jayanth3KT 

Not yet started, i am working another task. Give me some time.
@audhi3k @gsudarsan3k

**Comment by sandhya3k** [comment]
@Jayanth3KT 

please test UAT environment. report id : 50095 

cc : @audhi3k  @gsudarsan3k

**Comment by Jayanth3KT** [comment]
HI @sandhya3k 

I have tested with client and client mentioned these below things to change:

1. Should remove expense , total and duplicate header.( They want all locations detail in one single report )
 
Kindly make changes 

CC: @3ktech @audhi3k

**Comment by sandhya3k** [comment]
@Jayanth3KT 

As discussed, The new points have been completed please test

cc : @audhi3k  @gsudarsan3k

**Comment by Jayanth3KT** [comment]
Hi @sandhya3k Report generation is taking hours in customized report, where in standard report come's within minutes kindly fix this issue.

CC: @audhi3k @3ktech

**Comment by Jayanth3KT** [comment]
Hi @gsudarsan3k any update.

CC: @audhi3k @Tushargupta3K @3ktech

**Comment by audhi3k** [comment]
Mr @gsudarsan3k, can you mention the due for this task

**Comment by Jayanth3KT** [comment]
@gsudarsan3k can i know status of this ticket.

CC: @audhi3k  @Tushargupta3K

**Comment by Prakash3K** [comment]
Hi @gsudarsan3k sir, Can i know status of this ticket.

CC: @audhi3k @Tushargupta3K

**Comment by Jayanth3KT** [comment]
Hi @sandhya3k kindly deploy it in live DB, we got confirmation from client.

CC: @audhi3k @Tushargupta3K @gsudarsan3k

**Comment by sandhya3k** [comment]
@Jayanth3KT 

Deployed in live

cc : @audhi3k @gsudarsan3k

**Comment by Jayanth3KT** [comment]
Its taking more than 1.3 hours to generate 1 month report in live, however client want auto save feature.

CC: @audhi3k @Tushargupta3K  @gsudarsan3k

**Comment by Jayanth3KT** [comment]
Hi @sandhya3k Report header part is not fetching in PWESPL company live.


CC: @audhi3k @Tushargupta3K @gsudarsan3k

**Comment by Jayanth3KT** [comment]
Hi @3ktech Any update on this.

CC: @audhi3k  @Tushargupta3K

**Comment by sandhya3k** [comment]
@Jayanth3KT '

please test on production

**Comment by Jayanth3KT** [comment]
@sandhya3k  WORKING FINE IN PRODUCTION 


CC: @audhi3k @Tushargupta3K

**Comment by Jayanth3KT** [comment]
Completed
