### ISSUE TITLE
Cost Difference

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#828]

**Comment by Jayanth3KT** [comment]
<html>
<body>
<p class="MsoNormal" style="margin: 0cm 0cm 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">kindly clarify the below issue</p><p class="MsoNormal" style="margin: 0cm 0cm 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> </p><p class="MsoNormal" style="margin: 0cm 0cm 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">-We  have done the entry on 30-06-23 total cost was<span> </span><span style="color: black;">1,56,646.00</span></p><p class="MsoNormal" style="margin: 0cm 0cm 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="color: black;">- After analysis we came to know this entry should not come ,same it was reversed today the cost was 4,18,956.09 , we need to reverse only this 1,56,646.00. this will impact our costing kindly resolve the issue asap.</span></p><p class="MsoNormal" style="margin: 0cm 0cm 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> </p><p class="MsoNormal" style="margin: 0cm 0cm 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> </p>

  |   |   | Posting Date |   |   |   | Job Description | Quantity | Unit Cost | Unit Cost (LCY) | Total Cost | Total Cost (LCY) | Ledger Entry No.
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   | 30-06-2023 |   |   |   | Best Cotton Mills Private Limited solar | 20.755 | 7,547.38617 | 7,547.38617 | 1,56,646.00 | 1,56,646.00 | 18919
  |   |   | 27-09-2023 |   |   |   | Best Cotton Mills Private Limited solar | -20.755 | 20,185.79113 | 20,185.79113 | -4,18,956.09 | -4,18,956.09 | 20788

<p class="MsoNormal" style="margin: 0cm 0cm 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> </p>
</body>
</html>

**Comment by Tushargupta3K** [comment]
As discussed with client over call, This issue occured due to updated unit cost in job planning line at the time of reversal.
They need a provision that User- RajeshKG can edit this unit cost in job planning line before posting.

**Comment by Jayanth3KT** [comment]
We are facing issues in unit cost picked for many NSI items like Land, etc which is specific cost to specific customers.
In spite of costing method being “Specific”, the system picks Average cost which varies drastically.

We require unit cost to pick the cost input done at the time of creating the lot/serial no., when we select lot/serial no.at time of job consumption. Currently, unit cost gets automatically updated with Average cost irrespective of Lot/serial no. selected.

Please connect in case of further clarifications required.

**Comment by Jayanth3KT** [comment]
The customisation is not recommended process so we will figure out alternate way.
There will be new ticket with all required Information.
Hence ticket will be closed
CC: @audhi3k @Tushargupta3K
