### ISSUE TITLE
FW: Holyrood Communications Ltd. - Sales Invoice SI-HR001122

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#829]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/db955598-7b8e-4b84-bcf0-b95a0c033737)


(Mail has been looped to you Mr. @TabrejAlam3K )

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT - Changes has been done, You can reply on the original client mail.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi @Jayanth3KT & @Prakash3K - Please update the email address of the client here, Who raised this ticket.

CC : @audhi3k @Shasthara

**Comment by Jayanth3KT** [comment]
Client i'd: creditcontrol@totalpolitics.com

CC: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Client confirmed for closure.

![Image](https://github.com/3ktech/General/assets/116171982/c632ccb7-2b5f-4990-8809-dff4a67393f9)

CC : @audhi3k @Shasthara @Jayanth3KT
