### ISSUE TITLE
Bank Receipt Voucher - points raised in UAT 27thJan2023

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#83]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Page | Details | Status
-- | -- | --
User Setup | Location code to be   added in User Setup | Open
Collection   list | Location code from   the user to update and should not beupdated by users other than accounting   manager | Open
Collection   Entry Modification | GoTo button on   collection Entry Modification | Open
  | Modification and   Search is not available | Open
Bank Receipt   Voucher | The following to be   add/remove | Open
  | 1. Payment made by   =>Add | Open
  | 2. Income Account   =>Add | Open
  | 3. Collection 1   column Remove | Open

</body>

</html>

**Comment by TabrejAlam3K** [comment]
I am testing this into Development.

1. User Setup - Completed

![Image](https://user-images.githubusercontent.com/116171982/215430139-bc64ecf1-b8ba-418c-9abc-cd162e23d163.png)

4. Bank Receipt Voucher - Completed

![Image](https://user-images.githubusercontent.com/116171982/215430682-874faf32-39ff-419a-b6d7-7eb76daaaf13.png)

**Comment by TabrejAlam3K** [comment]
<html>
<body>


Page | Details | Status
-- | -- | --
User Setup | Location code to be added in User Setup | UAT
Collection list | Location code from the user to update and should not beupdated by users other than accounting manager (Profile Role Pending) | UAT
Collection Entry Modification | GoTo button on collection Entry Modification | Open
  | Modification and Search is not available | Open
Bank Receipt Voucher | The following to be add/remove | UAT
  | 1. Payment made by =>Add | UAT
  | 2. Income Account =>Add | UAT
  | 3. Collection 1 column Remove | UAT


</body>
</html>

**Comment by audhi3k** [comment]
Collection Entry detail list (new page - 50119), the filters available in page 50084 should be applied here

**Comment by audhi3k** [comment]
@Mahesh3ktech, kindly complete the filter in the new page before 11 am

**Comment by niranjand22** [comment]
Collection list- Location should be editable for Accounting Manager Role. @Mahesh3ktech

**Comment by niranjand22** [comment]
Hi @audhi3k  What is the requirment in this point 

Collection Entry Modification | GoTo button on collection Entry Modification

**Comment by audhi3k** [comment]
All the points mentioned here are tested and completed, 
@Amar-3KT  explain the functionality process to Mr Niranjan @niranjand22, for him to support in LKS
