### ISSUE TITLE
MDT - Invoicing Error

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#831]
Hi Tabrej,

I am getting this below error message after posting a sales invoice, but its not preventing from posting.

Can you pls check and resolve ?

![Image](https://github.com/3ktech/General/assets/116171982/c3c141b8-7cb7-4549-8dcd-c726b6c590db)

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/f5cd9f05-e909-492c-b11b-840b25fdbd72)

**Comment by TabrejAlam3K** [comment]
Mr. @Prakash3K - Please assign the case id for this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Please update me once you have done the analysis.

CC : @audhi3k @Shasthara

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K -comment line issue in report is fixed, and Invoice posting error is due to postcode is having character value and there is check in e-invoice for postcode value due to that error displaying after invoice got posted.    CC: @3ktech, @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Please move the changes into the Merit India Production.

CC : @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
I am closing this ticket, Client (Mr. Pavan) Confirmed for Closure.

![Image](https://github.com/3ktech/General/assets/116171982/670ca4b4-5dac-44d6-b31d-04e7a6513621)

CC : @audhi3k @Shasthara @Prakash3K
