### ISSUE TITLE
"Delivery challan sale and purchase

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#835]

**Comment by Jayanth3KT** [comment]
Last we  have confirmed “ Delivery challan sale and purchase “ . it was working fine  based  on our outcome  which was we received

,now it’s not solved today, we tried to make DC same GST is calculated . please refer below .


![Image](https://github.com/3ktech/General/assets/142868335/183af47f-d84d-47ff-aa8d-815f871a717e)

**Comment by Jayanth3KT** [comment]
Hi @3ktech sir would you kindly assign @rohit3k to this ticket for customization.

(This issue is previously worked Technically by Rohith sir & Functionally Me)

CC: @3ktech @audhi3k

**Comment by Prakash3K** [comment]
Closing this due to no response from client.

CC: @audhi3k @Tushargupta3K
