### ISSUE TITLE
Round Off Calculations issue in the reports

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#838]
Hi team the round off value is not printing in all the reports I am requesting to the technical person please make the round off calculation should be print in the report

![Image](https://github.com/3ktech/General/assets/125632927/d5678de6-ae57-4aec-a91b-b68cf1411e56)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Please update the status of this task and mention the effort hours you required

CC: @audhi3k

**Comment by sruthi1017** [comment]
hi @Ejaz3KT the round off has been added to all the reports test and update
cc; @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I`ve tested all the reports and the round-off value it is working fine I am requesting you please deploy this in changes in the production

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The UAT session has been done with the fervid team and they have confirmed so we can close the ticket

CC: @audhi3k
