### ISSUE TITLE
Finance Report - Batch Job For Discarded Entry ID - 50100

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#84]
Report not found in BC. See the attached NAV-16 Snapshot. 

![Image](https://user-images.githubusercontent.com/116171982/216026827-441566b1-e113-4275-b8ae-d7a0dad4432c.png)

**Comment by panduc** [comment]
@TabrejAlam3K  The report has been enabled and ready for testing.

**Comment by TabrejAlam3K** [comment]
Report Found.

![Image](https://user-images.githubusercontent.com/116171982/216896727-a707233c-e8a8-4dc4-aba8-ade037533af9.png).

**Comment by TabrejAlam3K** [comment]
Yes report is working find I have tested with the below filter

Location = BANGALORE
Receipt No. = <>''

When i run this report then the related entries is removed form the Collection Details List.
