### ISSUE TITLE
HSN Inwards Report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#840]
There are two report that needs to be developed 
1. GSTR 9
2. GSTR 9C

Regarding this report field mapping I`ll provide it ASAP

I am requesting a technical resource and mentioned the efforts that are required

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
HI @Manoj01021999 Please find the HSN inward and outward format and field mapping for the GSTR 9 report


[HSN Inward Field Mapping.xlsx](https://github.com/3ktech/General/files/12827061/HSN.Inward.Field.Mapping.xlsx)

[1c. 18. HSN Inward Format.pdf](https://github.com/3ktech/General/files/12827065/1c.18.HSN.Inward.Format.pdf)

**Comment by Ejaz3KT** [comment]
I need to connect with the Fervid client to get information about some fields in the GSTR 9 report

CC: @audhi3k

**Comment by Manoj01021999** [comment]
@Ejaz3KT 
As we discussed in the call 
layout is created and field mapping is done as per requested
CC: @3ktech @gsudarsan3k

**Comment by Ejaz3KT** [comment]
Hi @Manoj01021999 can start testing the report

**Comment by Ejaz3KT** [comment]
Hi @Manoj01021999 Please make the below mentioned changes in the report

 1. Please make the alignment proper so the field does not move to the next page
 2. In Rate of tax field only percentage should print like 18, 12, 5 not like GST18, GST28
 3. In UOC field Nos should be print
 
I`m requesting you to please make the changes ASAP

[HSN Inward report.pdf](https://github.com/3ktech/General/files/12928096/HSN.Inward.report.pdf)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Manoj01021999 Please republish the HSN report in sandbox because the report is coming as blank

**Comment by Ejaz3KT** [comment]
Hi @Manoj01021999 Please change the tax rate percentage in this report

CC: @audhi3k
