### ISSUE TITLE
HSN Outwards Report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#842]
Hi @Manoj01021999 Please find the field mapping for the GSTR 9C report and let me know if can we connect to discuss the field mapping
[HSN Outward filed mapping.xlsx](https://github.com/3ktech/General/files/12827062/HSN.Outward.filed.mapping.xlsx)
[1b. 17. HSN Outward Format.pdf](https://github.com/3ktech/General/files/12827064/1b.17.HSN.Outward.Format.pdf)

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
I need to connect with the Fervid client to get information about some fields in the GSTR 9C report

CC: @audhi3k

**Comment by Manoj01021999** [comment]
@Ejaz3KT
As we discussed in the call
layout is created and field mapping is done as per requested
CC: @3ktech @gsudarsan3k

**Comment by Ejaz3KT** [comment]
Hi @Manoj01021999 can start testing the report

**Comment by Ejaz3KT** [comment]
Hi @Manoj01021999 Please make the below-mentioned changes in the report

 1. Please make the alignment proper so the field does not move to the next page
 2. In the Rate of tax field only percentages should print like 18, 12, and 5, not like GST18, GST28
 3. In the UOC field Nos should be print
 4. Negative sign should remove 
 5. 
[HSN Outward report.pdf](https://github.com/3ktech/General/files/12928208/HSN.Outward.report.pdf)

I`m requesting you to please make the changes ASAP


CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Manoj01021999 Please change the tax rate percentage in this report

CC: @audhi3k
