### ISSUE TITLE
GST Entry Errors - Application entries

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#844]
**Total Effort hours = 2 Hours**

**Comment by Prakash3K** [comment]
@TabrejAlam3K 

Hi Audhi,

As discussed two weeks back, below is the issue we are still facing. Pls resolve the same at the earliest as its impacting our BS account balances.

Some automated GST application entries are being posted in the BC - Merit IND tenant, under the user id of my team. Since i am the approver, their user id shouldn't appear for any posted entry. These entries are making changes in different GST account balances. Can u pls check the root cause for this ?

Also pls let us know if these can be retrospectively reversed without manually passing the entries as GJ ?

**Comment by TabrejAlam3K** [comment]
I will replicate the same scenario before first half.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @audhi3k Mam - I have replicated the same scenarion with diffrent GST Group code but there are no extra line created.

Analysis - Extran line get created only in case of GST Group Code RCM.

**Comment by TabrejAlam3K** [comment]
Today I will follwup with the client and update.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam - Whether we can disable the Reverse transaction for RCM case.

**Comment by audhi3k** [comment]
Mr @TabrejAlam3K  Then GST group to be created without RCM

**Comment by TabrejAlam3K** [comment]
Ok @audhi3k Mam, She want disable the transaction only with same GST group code RCM12.

**Comment by TabrejAlam3K** [comment]
Mr. @Amar-3KT Done the session with the Client (Ms Swathi) she will discuss with Meirt Internal Management and let us know. Holding this ticket for Today & Tomorrow.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Client confirmed for closure, I am closing this ticket as completed.

![Image](https://github.com/3ktech/General/assets/116171982/2d0b5b0b-426b-4941-be2f-9e81cdaf73ae)

CC : @audhi3k @Shasthara
