### ISSUE TITLE
Bank Receipt Voucher

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#85]
1. In the Bank receipt voucher, while pulling the record from Collection detail and if the cheque no. is more than 10 character.
2. Dimension from the Applies-to Doc No. should be updated in the journal lines

**Comment by audhi3k** [comment]
@panduc, the above two points are working in NAV2016 and not in BC

**Comment by audhi3k** [comment]
@panduc, kindly assign this to @Mahesh3ktech

**Comment by audhi3k** [comment]
@Mahesh3ktech kindly complete the point before 11 am today

**Comment by audhi3k** [comment]
Deployed to UAT and tested
