### ISSUE TITLE
Sending Vendor Remittances Automatization

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#851]

**Comment by Prakash3K** [comment]
@Amar-3KT 

Hello,

I would like to check how many hours will require you to do an automatization flow on BC to send vendor remittances when a vendor payment is created.

So, when Agne is on this screen, and once she has posted all the payments created, the system automatically sends remittances to ALL the vendors that are receiving the payment.



![Image](https://github.com/3ktech/General/assets/140147250/054ef428-ce6b-449c-8235-f29da63dd7bb)

Kindly let us know how many hours will this take, for authorisation.

**Comment by audhi3k** [comment]
Technical resource to be aligned

**Comment by Amar-3KT** [comment]
@3ktech -Please share technical efforts for the same.

**Comment by sandhya3k** [comment]
@Amar-3KT 

I will require 11 hours.

**Comment by Amar-3KT** [comment]
Technical 11 hrs, Functional 6.5hrs and for PM and other 4.5 hrs= Total 22 hrs we required.

We need to take approval from client.

**Comment by Amar-3KT** [comment]
Hi @sandhya3k - Client Approved hrs. Please start working.

**Comment by sandhya3k** [comment]
@Amar-3KT 

Please test the all scenario's?

**Comment by Shasthara** [comment]
@Amar-3KT - Kindly Update latest status

**Comment by Amar-3KT** [comment]
after posting multiple entry with same vendor mail should trigger only one time.
@sandhya3k

**Comment by sandhya3k** [comment]
@Amar-3KT 

please test on copyprod sandbox 

cc : @audhi3k  @gsudarsan3k

**Comment by Amar-3KT** [comment]
Please check in case of 2 same vendor and 1 different vendor line. Same PDF receiving @sandhya3k

**Comment by Amar-3KT** [comment]
additional 21 mail sent to client waiting for approval.
technical 13hrs functional 5hrs and pmo 3hrs

**Comment by Amar-3KT** [comment]
Please check field format of attachment-

**Vendor ledger pdf format**

[_PJ-HR000389.pdf](https://github.com/3ktech/General/files/13319264/_PJ-HR000389.pdf)


**Our attachment**

[Remittance Advice ABCS01.pdf](https://github.com/3ktech/General/files/13319269/Remittance.Advice.ABCS01.pdf)

**Comment by Amar-3KT** [comment]
@sandhya3k -Above mentioned working fine. I am checking other scenario.

**Comment by Amar-3KT** [comment]
1) Email should not send to vendor if we get any error at the time of payment journal posting.
2) Remaining amount should update correctly.

**Comment by Amar-3KT** [comment]
@sandhya3k Please update the status.

**Comment by Amar-3KT** [comment]
@sandhya3k Please update the status.

**Comment by niranjand22** [comment]
Had call with the client. On paymet system is triggerign two mails to vendor. needs to be fixed. @sandhya3k  
cc @audhi3k

**Comment by sandhya3k** [comment]
@niranjand22 

can u please test the copyprod ?

cc : @audhi3k

**Comment by niranjand22** [comment]
Hi @sandhya3k  tested-mail is not gettng trigger. i have not recved any mail after the payment.

**Comment by sandhya3k** [comment]
@niranjand22 

I got the mail, please change the ur mail id in vendor card

**Comment by Amar-3KT** [comment]
Remaining amount not correct.

**Comment by niranjand22** [comment]
resolved..
