### ISSUE TITLE
Removal of  DCPL and DODS from Jet reports

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#852]

**Comment by Prakash3K** [comment]
@Amar-3KT 


![Image](https://github.com/3ktech/General/assets/140147250/a1f4a537-847a-4b0b-8408-82c78c295b64)

**Comment by Amar-3KT** [comment]
[05.August (1).xlsx](https://github.com/3ktech/General/files/12813257/05.August.1.xlsx)

**Comment by Amar-3KT** [comment]
@3ktech -Please align technical person for this ticket.

**Comment by sandhya3k** [comment]
@Amar-3KT 

As discussed, please find the 

[05.August.1.xlsx](https://github.com/3ktech/General/files/12842851/05.August.1.xlsx)

excel file.
cc : @audhi3k

**Comment by Amar-3KT** [comment]
We have done changes related to jet report and waiting for client confirmation.

**Comment by Amar-3KT** [comment]
@Prakash3K - Total time taken 3hrs

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Shasthara - I have discussed with Ms. Ana Lopez she will connect tomorrow 9:00AM UK time.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
I have done the session with the client.

Recorded Link - https://3ktechnologies22-my.sharepoint.com/:v:/g/personal/tabrej_a_3ktechnologies_com/EdNkZxAWTxpMoACyEqgI6LoBM8LAamy4u325r2uN9NozwA

CC : @audhi3k @Amar-3KT @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam - Mr. Amar is not available, I need support from other resource on this because I am not aware about the functionality of Jet Report.

CC : @audhi3k @Shasthara @gsudarsan3k

**Comment by TabrejAlam3K** [comment]
As per discussed with Mr. @Amar-3KT - This is completed, We are going to close this ticket.

Mr. @Prakash3K - Please close this ticket form the support portal also with **Effort hours = 3 Hours**

CC : @audhi3k
