### ISSUE TITLE
Additional Configuration in Dynamics & LMS

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#853]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Tabrej/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Tabrej/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Sr No. | Requirement | Solution
-- | -- | --
1 | The Loan File from LMS   containing the transactions should have the Branch Name which should be   mapped with the Dimension of Branches already created in Dynamics. | New Filed Called Branch Name include as Dimension   similar of Customer and Loan Account Number
2 | The Loan File will have the   additional two columns which would be used in future for data usage. The data   of these two Columns should have the functionality of using as a Dimension | New Filed Called Field 1,Field 2 include as Dimension   similar of Customer and Loan Account Number
3 | The Loan file will have   additional two columns which can be used for sending any other data as   required. The data of these two columns will not be used as a Dimension | New Filed Called Field 3 and Field 4 Normal field for   capture the data
4 | The Employee Code, Department,   Location and Branch will be interlinked with Employee Code. If Employee Code   is entered then the other dimensions i.e., Branch, Department and Location   will be auto populated | While assigning the Employee   Dimension on General Journal line related dimension should auto come whatever   the dimension available on the Employee Card.
5 | The Loan Account Number,   Customer Code and Branch Code will be interlinked where if the Loan Account   Number or Customer Code is entered then the Customer Code or Loan Account   Number and Branch would be auto populated | Need to Provide the Solution or   How we can achive this or whether it is doable or not
6 | A Single customer can source   different Loan from multiple branches hence, we would map Loan with the   Branch | Need to Provide the Solution or   How we can achive this or whether it is doable or not

</body>

</html>

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - As discussed please share the time effort for first 4 points.

CC : @audhi3k @Shasthara @gsudarsan3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Please update your commect here, due date of this ticket is 12th Oct. Please colse this before.

CC : @audhi3k @Shasthara

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - kindly confirm have we got client confirmation on effort hours for this task.

CC: @3ktech, @audhi3k, @gsudarsan3k

**Comment by gsudarsan3k** [comment]
Hi @TabrejAlam3K can you please confirm for us to start working on this ticket? Because we don't see the customer confirmation. 

CC: @audhi3k @3ktech

**Comment by TabrejAlam3K** [comment]
I am closing this ticket becasue we have created individual ticket for each point.

CC : @Shasthara @Jayanth3KT @Prakash3K @audhi3k
