### ISSUE TITLE
Unit cost in job consumption entries

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#855]

**Comment by Prakash3K** [comment]
@Tushargupta3K 

We are facing issues in unit cost picked for many NSI items like Land, etc which is specific cost to specific customers.
In spite of costing method being “Specific”, the system picks Average cost which varies drastically.

We require unit cost to pick the cost input done at the time of creating the lot/serial no., when we select lot/serial no.at time of job consumption. Currently, unit cost gets automatically updated with Average cost irrespective of Lot/serial no. selected.

Please connect in case of further clarifications required.

**Comment by Jayanth3KT** [comment]
Closing this ticket due to Merging with #828

CC: @audhi3k @Tushargupta3K
