### ISSUE TITLE
PO closed without GRN

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#858]
I`ve tested the purchase order process step by step everything is fine there is no possibility of closing the PO without receiving the items 

CC: @audhi3k

**Comment by audhi3k** [comment]
Highlight this in the review call, we will discuss on it

**Comment by Ejaz3KT** [comment]
Ok @audhi3k Madam

**Comment by Ejaz3KT** [comment]
I`ve resolved the issue the solution needs to be showcase to the client 

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
I`ve explained the scenario to the fervid team they will check from their end and confirm us

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The issue has been resolved and has Fervid Team is confirmed so I am closing the ticket

CC: @audhi3k
