### ISSUE TITLE
Item Card Mandatory Field

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#859]

**Comment by Prakash3K** [comment]
![Image](https://github.com/3ktech/General/assets/140147250/e538de6e-da7d-49e3-8f07-add02495c3a7)


CC: @audhi3k @Tushargupta3K @3ktech

**Comment by Prakash3K** [comment]
@3ktech Please assign technical person to this ticket. 

CC: @audhi3k @Tushargupta3K

**Comment by Mahesh3ktech** [comment]
hi @Prakash3K - As per requirement changes are done. kindly check and confirm.

CC: @3ktech, @audhi3k, @gsudarsan3k

**Comment by Prakash3K** [comment]
Hi @Mahesh3ktech- UAT has been done with client and they have change their requirement now in UAT session to make other changes.
 
Requirement

1. Users without entering mandatory fields in item card should automatically turn on blocked Boolean.

2. Once the user entry all the mandatory fields in item card should automatically turn on blocked Boolean.

CC: @audhi3k @3ktech

**Comment by Prakash3K** [comment]
Hi @Mahesh3ktech client has approved effort hours kindly start work. 

CC: @audhi3k @3ktech

**Comment by Mahesh3ktech** [comment]
Hi @Prakash3K - changes are done. kindly check and confirm.

CC: @3ktech, @audhi3k, @gsudarsan3k

**Comment by Mahesh3ktech** [comment]
hi @Prakash3K - deployment is completed to live environment. kindly check.

cc: @3ktech, @audhi3k, @gsudarsan3k

**Comment by Prakash3K** [comment]
Thank you @Mahesh3ktech, Client confirmed to closure.

CC:  @audhi3k @Tushargupta3K @gsudarsan3k
