### ISSUE TITLE
Debit Amount and Credit Amount Column to be added in all voucher pages

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#86]

**Comment by 3ktech** [comment]
@panduc , can you look at this.

**Comment by panduc** [comment]
@audhi3k @Amar-3KT The debit Amount and Credit Amount column visibility based on  General Ledger Setup --> Show Amounts 

The field is visible in all pages(Tested in UAT)

![Image](https://user-images.githubusercontent.com/110709312/217517783-5aad034c-6715-4a0f-a1d7-d2b692f6ba35.png)

. Attached screenshot.

**Comment by niranjand22** [comment]
The debit amount column and credit amount column are available in all vouchers. in DEV and UAT both environment
