### ISSUE TITLE
Barcode Allocation Issue - Transfer Order

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#865]
Dear Team, 

We are getting barcode allocation issues while transferring the finished goods, barcodes are not getting updated against shipment lines in both companies.

Please check and resolve the issue on an urgent basis.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Please assign the Case Id for this ticket.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k  Mam - Mr. Rewat said it should be auto assigned based on the FIFO basis.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - I have discussed with the client he will create one document and let us know, Once the client will share the document I will ping you.

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
Currently holding the UL ticket.

**Comment by TabrejAlam3K** [comment]
Holding this ticekt till Friday 10-11-2023 after that we will close it.

CC : @audhi3k @Sarikab1222

**Comment by Jayanth3KT** [comment]
Hi @TabrejAlam3K sir any update ?

CC: @Shasthara @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Ms. @Sarikab1222 - I am closing this ticket due to non responses by the client side, If they will raise it again so we will create a new ticket for this.

Mr. Jayanth - You can close this ticket from the support portal with **Closure Effort hours = .5 Hours**

CC : @audhi3k
