### ISSUE TITLE
Issue Reported - Consumption and Output Issue (OU-JWO2324-00043)

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#868]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 


![Image](https://github.com/3ktech/General/assets/140147250/0d605ca3-b969-4c85-9680-c62b353bc2d1)



![Image](https://github.com/3ktech/General/assets/140147250/2cec8239-86f8-40cc-ac72-89c192407047)

**Comment by TabrejAlam3K** [comment]
We have done the Posting of Older Document with Mr. Rewat.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Manual Entry Posting completed at the time of screen sharing session. You can close this from the support portal as well.
**Total Effort Hours = 4 Hrs**

CC : @audhi3k
