### ISSUE TITLE
Posting Description Error

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#869]
**Total Effort = 4 Hours**

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/867e9095-f354-497f-b71d-48dc2eaa0c02)


Client i'd- vimala.srinivasan@meritgroup.co.uk

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - When we can connect on this to discuss and close.

CC : @3ktech @audhi3k

**Comment by rohit3k** [comment]
Hi Mr. @TabrejAlam3K We can Connect Now. calling you in personal Chat
cc: @3ktech @audhi3k

**Comment by TabrejAlam3K** [comment]
As per our discussion over chat Ms. Vimala is busy in some other activity once she will free we will connect and discuss on the new requirement.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please move the changes into the Production and let me know.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Client confirmed for closure. I am closing this ticket beased on the client confirmation.

![Image](https://github.com/3ktech/General/assets/116171982/73871bf0-0d3e-469b-b100-4a07dd3b85a5)

CC : @audhi3k @Prakash3K
