### ISSUE TITLE
Issue Reported - Job Work Components not updated 10th Oct-23

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#872]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 

User email id: rewat@urbanladder.com


![Image](https://github.com/3ktech/General/assets/140147250/fa68812e-848e-412d-acdf-ebbafb4e1f9f)



![Image](https://github.com/3ktech/General/assets/140147250/f57fbc36-3015-4a3a-a585-bd90aa208ef2)

**Comment by TabrejAlam3K** [comment]
I am closing this ticket becasue issue was resolved while screen sharing sesison.

@audhi3k @Sarikab1222 @Prakash3K
