### ISSUE TITLE
GSTR1-File Format

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#876]

**Comment by Prakash3K** [comment]
@Amar-3KT 

User id: muralikrishnanm@fichtnerindia.com


![Image](https://github.com/3ktech/General/assets/140147250/ff767bb5-7953-408e-8dd7-1c5048454b13)

**Comment by Amar-3KT** [comment]
Issue- In GSTR-1 report some export data not reflecting.

Analysis- We have analyzed and found that in customer card "GST Customer Type" is missing and in ship to address "GST Customer Type" is missing due to this some export invoices not reflecting in gstr-1 report.

Solution- They can reverse entry and create again or fill missing data manually in excel sheet. Also, user need to update "GST Customer Type" as Export for export customer.

**Comment by Ejaz3KT** [comment]
I`ve got the confirmation from the client we can close this ticket

CC: @audhi3k
