### ISSUE TITLE
Issue Reported - Consumption and Output Issue || Repeated issue || OU-JWO2324-00077 || OU-JWO2324-00083

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#878]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 

User Id: rakesha@urbanladder.com



![Image](https://github.com/3ktech/General/assets/140147250/dd7d4ef8-b034-44d8-ab1c-aaf5280bc9bb)




![Image](https://github.com/3ktech/General/assets/140147250/8d94e901-8235-48db-be56-191a07913314)

**Comment by TabrejAlam3K** [comment]
As Discuss with Mr. Rewat he need to check the inventory and post it again.

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
Completed during the session with the Client (Mr. Rewat).

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
I am closing this ticket as completd.

@audhi3k @Sarikab1222
