### ISSUE TITLE
Data Migration Activity

### ISSUE THREAD

**Issue by Mahesh3ktech** [3ktech/General#88]

**Comment by Mahesh3ktech** [comment]
There are three sessions completed and in first session explained data transfer from the NAV to extension dummy table. and then based on the activity there are some doubts clarifications in second session. After completion of data transfer taken backup and doing the NAV 16 to BC 14 Upgrade Steps process.

**Comment by 3ktech** [comment]
@Shasthara  , Can you push Rajesh to get this issue resolved and support the KT move on.
CC:@audhi3k

**Comment by Mahesh3ktech** [comment]
Converted the NAV database to BC 14 and Compiling objects with later mode then While doing Build server application objects getting error.  

Error: The LKSBC21_IN database has version 1051 which is not supported by this version of Microsoft Dynamics 365 Business Central Server. Please contact your administrator.

Then reimporting the objects and then doing the same activities to avoid the error, now able to do the build server application objects and the trying to Run data upgrade but it is failing.

**Comment by Mahesh3ktech** [comment]
Before build server application we resolved all errors manually and then we proceed for build server application objects then it got successful and then we run data upgrade is also successful.

Then we generated symbols successfully, then in the next procedure while compiling we are getting error, that we are checking.

**Comment by Shasthara** [comment]
add Padma to this task.

**Comment by Mahesh3ktech** [comment]
KT with Rajesh.

We completed BC 14 to BC 21 data transfer and now we are in BC 21. Next, we need to start cloud upgrade it going to take 5 to 6 hours.

**Comment by Mahesh3ktech** [comment]
I have started with Nav 2016 original objects data transferring to UPG Dummy Objects.

1.NAV 2016 database restored.
2.deleting existing instance, breakpoints, Users, and Access Control and creating new instance.
3.Imported the Dummy UPG objects with validation and now doing data transfer from original table to UPG dummy table.

**Comment by Mahesh3ktech** [comment]
Mr.Rajesh asked me to provide the list of objects which dummy field involved in dummy tables. listed and provided.

**Comment by Ejaz3KT** [comment]
[Bank_Ledger Entry_Bc.xlsx](https://github.com/3ktech/General/files/11085773/Bank_Ledger.Entry_Bc.xlsx)

@audhi3k madam data is not available in the new cheque no 2 field.

**Comment by Ejaz3KT** [comment]
@audhi3k I`ve tested and the data is matching for all the companies

**Comment by audhi3k** [comment]
Completed
