### ISSUE TITLE
The Loan File from LMS containing the transactions should have the Branch Name which should be mapped with the Dimension of Branches already created in Dynamics.

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#881]

**Comment by niranjand22** [comment]
Shashthara said to work on this ticket and considered this as approved.

cc @audhi3k

**Comment by niranjand22** [comment]
Connected with Tabrej and discussed the requirnment wih mahesh. @Mahesh3ktech  to start the technical activity.

**Comment by niranjand22** [comment]
@Mahesh3ktech  pls update the progress here

**Comment by Mahesh3ktech** [comment]
hi @niranjand22 - Branch field dimension mapping is done. kindly check and confirm. 

CC: @3ktech, @audhi3k, @gsudarsan3k

**Comment by TabrejAlam3K** [comment]
Vridhi Team is not available today we will connect on Wednedsay 25-10-2023

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Have you checked the issue what we have discussed?

CC : @audhi3k  @Shasthara

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - issue is fixed, kindly test and confirm.

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - Deployment is done in prod environment.

cc: @3ktech, @audhi3k, @Shasthara

**Comment by TabrejAlam3K** [comment]
Confirmed for Closure while screen sharing session with Mr. Dikshant

Hi Mr. @Prakash3K - You can close this ticket from the support portal.

CC : @audhi3k @Shasthara
