### ISSUE TITLE
The Loan file will have additional two columns which can be used for sending any other data as required. The data of these two columns will not be used as a Dimension

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#883]

**Comment by niranjand22** [comment]
Shashthara said to work on this ticket and considered this as approved.

**Comment by niranjand22** [comment]
Connected with Tabrej and discussed the requirnment wih mahesh. @Mahesh3ktech  to start the technical activity.

**Comment by Mahesh3ktech** [comment]
hi @niranjand22 - fields are added.

**Comment by TabrejAlam3K** [comment]
Field are available on the LMSLoanStatusList Page called Field 1 and Field 2

**Comment by TabrejAlam3K** [comment]
UAT done with the Client Mr. Dikshant and he ok with issue is completed.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Client confirmed for Closure of this ticket. Please move the changes into the Production DB.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Please whether the ticket is deployed into the Production Environment?

CC : @audhi3k @Shasthara

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - Deployment is done in prod environment.

cc: @3ktech, @audhi3k, @Shasthara

**Comment by TabrejAlam3K** [comment]
Confirmed for Closure while screen sharing session with Mr. Dikshant

Hi Mr. @Prakash3K - You can close this ticket from the support portal.

CC : @audhi3k @Shasthara
