### ISSUE TITLE
The Employee Code, Department, Location and Branch will be interlinked with Employee Code. If Employee Code is entered then the other dimensions i.e., Branch, Department and Location will be auto populated

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#884]

**Comment by niranjand22** [comment]
- when emplyee code dimesion is selected in jv.

- system should check the similar emplyeed code in employee master.

- then from that employee master system should pick all the dimesion associated with that specific emplyeee and update all associated dim back to JV.

solution for this has to be anaylysed.

cc @audhi3k

**Comment by niranjand22** [comment]
HI @Mahesh3ktech  Can you please update progress on this ticket

**Comment by Mahesh3ktech** [comment]
hi @niranjand22 - All the four points are completed. kindly test and confirm.

CC: @3ktech, @audhi3k, @gsudarsan3k

**Comment by TabrejAlam3K** [comment]
I have tested on the Journal Voucher page - while selecting the Value in the Employee Dimension field all the realted dimension get updated in the Dimension Set Entries page.

**Comment by TabrejAlam3K** [comment]
UAT done with the Client Mr. Dikshant and he ok with issue is completed.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Client confirmed for Closure of this ticket. Please move the changes into the Production DB.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Please whether the ticket is deployed into the Production Environment?

CC : @audhi3k @Shasthara

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - Deployment is done in prod environment.

cc: @3ktech, @audhi3k, @Shasthara

**Comment by TabrejAlam3K** [comment]
Confirmed for Closure while screen sharing session with Mr. Dikshant

Hi Mr. @Prakash3K - You can close this ticket from the support portal.

CC : @audhi3k @Shasthara
