### ISSUE TITLE
A Single customer can source different Loan from multiple branches hence, we would map Loan with the Branch

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#886]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Tabrej/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Tabrej/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Customer   ID | Loan Account No. | Branch
-- | -- | --
CN0000000000181 | VHF100000000134 | DELHI
CN0000000000181 | VHF100000000135 | MUMBAI
CN0000000000181 | VHF100000000136 | CHENNEI

</body>

</html>

**Comment by TabrejAlam3K** [comment]
Vridhi Team is not available today we will connect on Wednedsay 25-10-2023

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Discussed with the Client, In Future we can use Change Dimension for this case.

@audhi3k - Need small discussion on it.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam - Need to discuss with you regarding this.

**Comment by TabrejAlam3K** [comment]
Hi @audhi3k Mam - Vridhi team is not available today, they want session tomorrow. What time slot is feasible for you.

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k - I need you free time to connect with Vridhi Team to discuss the issues.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Jayanth3KT - You can close this ticket from the Support portal, I am going to close from the Git

**Close with Effort Hours = .5 Hours**

CC : @audhi3k @Shasthara
