### ISSUE TITLE
Posting Description setup - UK Tenant

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#888]
_****Effor Hours Requested = 14 Hours**_
Technical = 6 Hours
Functional = 5 Hours
Buffur = 3 Hours**

**Comment by Prakash3K** [comment]
@TabrejAlam3K 



![Image](https://github.com/3ktech/General/assets/140147250/922bddaa-8f15-4a8e-a50a-9f45fe7b1e55)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please publish the changes for UK Tenant as well.

Ms. @sandhya3k - Please help us to publish into the UK Sandbox & Productin as well.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
@rohit3k @sandhya3k - Sahre the time effort first how much time it will take.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k When we can connect on this?

1. While Preview Posting if the Posting Description is not available on the Header then the Description should come based on the Line Value.
2. In Customer Report - Document No. and Description field value not coming properly need to fix the field layout.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k - Please share the time effort first before starting the activity on this if it will take more then 4 hours.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Standard Statement (1316, Report Request)

**Comment by TabrejAlam3K** [comment]
Approval not yet approved by the client side.

**Comment by niranjand22** [comment]
"Hi Boopathy Dakshinamurthy Good Morning.
 
We need 12 hrs for Posting Description setup - UK Tenant case. Kindly apporve the hours so we can begin the work.
 "

**Comment by niranjand22** [comment]
Hi @Prakash3K customer confirmed for closure of this ticket. we can close this with 12 hr

cc @Prakash3K  @audhi3k

**Comment by Jayanth3KT** [comment]
Closed this ticket hence its closed in case portal.

CC: @audhi3k
