### ISSUE TITLE
Cannot install the add-in

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#889]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 

User Id: pasquale.docile@dodsgroup.com



![Image](https://github.com/3ktech/General/assets/140147250/f5388cf1-6b8a-4b4b-9bfe-6c6d0a237b30)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - It is related to CRM ticket. Please connect with Mr. @Shasthara and confirm.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Can you discuss with Mr. @Shasthara and delete the issue from the Git Please.

CC : @audhi3k

**Comment by Prakash3K** [comment]
Hi @TabrejAlam3K sir, I'm closing this ticket from the Git, because this ticket not related to BC.

CC: @audhi3k @Shasthara
