### ISSUE TITLE
BNG232400312 E-invoice generation issue

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#892]

**Comment by shivakumar3k** [comment]
Getting below mentioned error while creating E-Invoice for posted sales invoice.

**",For Sl. No 1, Total item value does not match with taxable and tax values of that item"**



![Image](https://github.com/3ktech/General/assets/141639359/1d821b7d-6524-4094-9415-0f28c5f94c80)

**Comment by sandhya3k** [comment]
@shivakumar3k  sent a mail to gsp team once i got the response from them i will update

**Comment by audhi3k** [comment]
Duplication of #880
