### ISSUE TITLE
Issue Reported - Incoming JW Order #IC-JW324-00039

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#894]
**Effort hours = 2 Hours**

**Comment by Jayanth3KT** [comment]
@TabrejAlam3K 

User id: rewat@urbanladder.com



![Image](https://github.com/3ktech/General/assets/142868335/0f37467c-37be-406c-ba98-df65689a55d8)

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam - I have discussed with Mr. Rewat he told we need to post the Two documents, before posting need to disable the Post Button.

**Comment by TabrejAlam3K** [comment]
I am closing this ticket as completed

Mr. @Prakash3K - You can close this ticket from the support portal as well with **effort hours = 2 Hours**

CC : @audhi3k
