### ISSUE TITLE
Issue Reported - IC-JW324-00044 (UL-Incoming JW Order)

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#895]

**Comment by Jayanth3KT** [comment]
@TabrejAlam3K 

User id: rewat@urbanladder.com



![Image](https://github.com/3ktech/General/assets/142868335/e6d70612-2450-48b5-881f-5f3206d5f6bd)

**Comment by TabrejAlam3K** [comment]
Mr. Rewat Confirm for Closure

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - You can close this ticket form the support poratl. I am going to close from the Git.

**Total Effort Hours = 6 Hours**

CC : @audhi3k
