### ISSUE TITLE
Credit Notes Deferral

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#896]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 

User id: kish.sharma@dodsgroup.com



![Image](https://github.com/3ktech/General/assets/140147250/ca0aaf50-82b0-43f6-ae74-fd9563bb280c)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Please loop me in this Original Email.

CC : @audhi3k @Shasthara

**Comment by niranjand22** [comment]
Connected with Mr Kish. He want new Report which diplayes

Sales Credit Memo No          Posting Date 


and all the deferal associated with credit memo. 

![Image](https://github.com/3ktech/General/assets/116243958/4e0f986b-80bc-48d5-919a-269185a65608)

Need to analys and provide time esimate to kish Sharma.

**Comment by niranjand22** [comment]
[10:21 AM] Niranjan Dewda
Hi Mr Kish, Good Morning.
[10:22 AM] Niranjan Dewda
Can we connect for Defer Schedule Report, I would like to convey and discuss  some information to you.once you available

**Comment by niranjand22** [comment]
Mr Kish is not avaialable

**Comment by niranjand22** [comment]
Sent follow up to mr kish for connect

**Comment by niranjand22** [comment]
Had call with Kish, showed him standard fuctionality of deferal report. He will think and update in 2 days. waether to take this case or cance.

cc @audhi3k

**Comment by Jayanth3KT** [comment]
Hi @niranjand22 sir Any Update. 

CC: @Shasthara @audhi3k

**Comment by niranjand22** [comment]
close thist with 2 hr. @Prakash3K  cc @audhi3k
