### ISSUE TITLE
Data Request

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#897]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 

User Id: kish.sharma@dodsgroup.com



![Image](https://github.com/3ktech/General/assets/140147250/0028ef57-6045-4d27-87e8-a769ac1edfff)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Please loop me in this Original Email.

CC : @audhi3k @Shasthara

**Comment by niranjand22** [comment]
Connected with Kish sharma for this.

They are requesting to add one more column in General Ledger Entries. 

Currently they are having amount column showing all the values in GBP.

They want one more amount column which shown the resoective currecy amount. 
eg for Euro Invoice it should show euro amount, and for dollar invoice it should show dollar amount,

need to anyalys and provide time estimation to client to for approval.

![Image](https://github.com/3ktech/General/assets/116243958/e6198c27-44d2-4319-8eb2-eab74a088146)

**Comment by niranjand22** [comment]
SInce the request amount column is available in cutomer ledger entry so customer has confirmed for closure of this ticket. Fuctional Time consumed for this ticket is 0.5 hour.

cc @audhi3k  @Prakash3K
