### ISSUE TITLE
error with service contract approvals - 2 items are stuck for months

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#898]

**Comment by Jayanth3KT** [comment]
These two items are stuck with few weeks. So kindly rectify that issue and update us.



![Image](https://github.com/3ktech/General/assets/142868335/45309b10-6de6-4189-9b95-013c36c7f864)

**Comment by Prakash3K** [comment]
During the teams call session provided solution to client 


CC: @audhi3k @Tushargupta3K

**Comment by Jayanth3KT** [comment]
Completed 

CC: @audhi3k @Tushargupta3K
