### ISSUE TITLE
Cannot post the journal below

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#899]
**Communication & review time effort = .5 Hours**

**Comment by Prakash3K** [comment]
@TabrejAlam3K 

User id: pasquale.docile@dodsgroup.com



![Image](https://github.com/3ktech/General/assets/140147250/43769926-3fb0-4fc9-ad3b-da73df4268a4)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - This issue has been resolved by the Client it self, You can close this from the Support Portal as well.

![Image](https://github.com/3ktech/General/assets/116171982/7820d386-e4d6-4c63-97c1-c715c6dacc32)

CC : @audhi3k @Shasthara
