### ISSUE TITLE
Digital signature

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#9]

**Comment by audhi3k** [comment]
Digital Signature is completed in UAT for 5 reports UAT is also the same
For Service Contract - we have get confirmation whether the signature to fixed or dynamic

**Comment by audhi3k** [comment]
@niranjand22 , co-ordinate with client for completed reports relating to deploy in LIVE, For service contract - get confirmation

**Comment by audhi3k** [comment]
@sandhya3k update once digital signature for the service contract report is embedded in the last page

@niranjand22, update once you receive confirmation from client on UAT and deployment

**Comment by sandhya3k** [comment]
I sent a mail to Mr. Amaya regarding this issue. Once, I got the source I will update @audhi3k mam.

**Comment by sandhya3k** [comment]
@niranjand22  please test the service contract report?

**Comment by audhi3k** [comment]
UAT is provided to the client, the digital signature is printing while generating the report from Server and if the same is generated in the direct system the report is not getting generated

@sandhya3k, kindly look up to the issue

**Comment by sandhya3k** [comment]
@audhi3k Now Iam working on LKS, once it is done, i will check.

**Comment by audhi3k** [comment]
Ok ma

**Comment by 3ktech** [comment]
@sandhya3k to check this issue.

**Comment by audhi3k** [comment]
@sandhya3k get the access from Mr Senthil or Mr Sethil IT, In case any support required kindly ping me

**Comment by audhi3k** [comment]
@sandhya3k, the files saving in server is fine for Pioneer, but explore the possibility to save the file in the local machine which might be the requirement for other client in future

**Comment by sandhya3k** [comment]
@audhi3k Today, Mahesh is busy with server for his customization once, the server free i will deploy the code for DS saving for server.

**Comment by sandhya3k** [comment]
@audhi3k  I have changed the code in UAT. now, it is saving in server path only. when they click Digital Signature action button in local or Server.

**Comment by sandhya3k** [comment]
@audhi3k  waiting for client response

**Comment by sandhya3k** [comment]
@audhi3k 

I have moved the DS objects from the pioneer UAT environment to the live environment (Pioneer). And also sent the mail to client so, i moving the status InProgress to UAT
