### ISSUE TITLE
GSTR 9C 2a Report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#901]
Hi @Manoj01021999 Please find the GSTR 9C 2a report format and field mapping

[2a. 9C Offline Tool_PT-III(9).pdf](https://github.com/3ktech/General/files/12817663/2a.9C.Offline.Tool_PT-III.9.pdf)
[Field Mapping 2a. 9C Offline Tool_PT-III(9).xlsx](https://github.com/3ktech/General/files/12817728/Field.Mapping.2a.9C.Offline.Tool_PT-III.9.xlsx)

**Comment by Manoj01021999** [comment]
@Ejaz3KT 
as we discussed and kindly check and let me know the changes
