### ISSUE TITLE
Add new fields in purchase register report

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#904]
The Fitchner Team is required to add this below-mentioned field in the purchase register report. I`ve attached the workbook for our reference. 
                            Field Name:
                            Location Code
                            Cost center Code
                            Document date
                            HSN/SAC CODE
                            GST Credit
Please allow a technical resource to develop the report
CC: @audhi3k @Amar-3KT @3ktech @gsudarsan3k

**Comment by Ejaz3KT** [comment]
Please find the field mapping for the purchase register report 

[New field mapping of Purchase register.xlsx](https://github.com/3ktech/General/files/12927918/New.field.mapping.of.Purchase.register.xlsx)

CC: @audhi3k @Amar-3KT @3ktech @gsudarsan3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 As we discussed during the call please mention the effort hours you required for the development

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
I`ve sent the mail to Mr. Murali regarding the efforts hours we required to develop this requirement waiting for the approval

CC: @audhi3k @Amar-3KT @sruthi1017

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I`ve tested the  purchase register report I found the issue where in credit memo description is printing two time please check and resolve the issue

[Purchase register.xlsx](https://github.com/3ktech/General/files/13022146/Purchase.register.xlsx)

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
HI @sruthi1017 I`ve tested the report in the report description is not coming properly please check

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I`ve tested the report I found two issues in the report
1. Document date is printing wrong
2. Invoice value is incorrect (Because TDS is not deducting in the report)  

CC: @audhi3k

**Comment by sruthi1017** [comment]
hi @Ejaz3KT the tds calculation part is done and published can u pls test and update
cc: @audhi3k @gsudarsan3k

**Comment by Ejaz3KT** [comment]
ok @sruthi1017

**Comment by Ejaz3KT** [comment]
HI @sruthi1017 I`ve tested this report the TDS calculation is not fine please check once 

CC: @audhi3k

**Comment by sruthi1017** [comment]
hi @Ejaz3KT the reference document no u have shared , for that document no. in tds entries itself the tds amount is showing blank can u pls cross check and confirm can we connect for this
cc: @audhi3k

**Comment by Ejaz3KT** [comment]
HI @sruthi1017  Yes we can connect

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I`ve tested the purchase register report it is working fine now need to showcase it to the client and get confirmation

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
UAT has done with the client waiting for confirmation from the client to deploy the changes in the production

CC: @audhi3k @sruthi1017

**Comment by Prakash3K** [comment]
@Ejaz3KT- Client provided confirmation to deployment.

![Image](https://github.com/3ktech/General/assets/140147250/3d840cd5-08e4-41c2-bf8c-e1ea202dbf4b)

CC: @audhi3k @sruthi1017

**Comment by Ejaz3KT** [comment]
Ok Mr. @Prakash3K

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Please deploy the changes in the production company 

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 changes Has been deployed in the production

CCL @audhi3k

**Comment by Ejaz3KT** [comment]
Deployment has been done in the production and client also confirm as report is working fine we can close the ticket

CC: @audhi3k @sruthi1017
