### ISSUE TITLE
Mur-019 / Narration/comments to be made mandatory

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#906]

**Comment by Prakash3K** [comment]
@Amar-3KT 

User id: muralikrishnanm@fichtnerindia.com



![Image](https://github.com/3ktech/General/assets/140147250/08a3eac4-64df-486f-aedc-1c118a7df6dc)

**Comment by Ejaz3KT** [comment]
as we discussed in call I hope you have understand the requirements please tell me the efforts for this customization

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
I`ve sent the mail to Mr. Murali regarding the efforts hours we required to develop this requirement waiting for the approval

CC: @audhi3k @Amar-3KT @sruthi1017

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Please find the attached table this will help you to customize the exact  requirement

<html>
<body>


Financial Transaction | Remarks
-- | --
Sales Invoice | Header Invoice -> Comments
Sales credit memo | Header Credit memo -> Comments
Purchase invoice | Header Invoice -> Comments
Purchase credit memo | Header Credit memo ->Comments
Bank payment / cash payment | Header Process ->Voucher Narration
Bank receipt/ cash receipt | Header Process ->Voucher Narration
Journal Voucher | Header Process ->Voucher Narration
Job G/L Voucher | Line -> Comments
Contra | Header Process ->Voucher Narration


</body>
</html>

CC; @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 I`ve tested this task I found some issue over this can we connect to discuss those issues

CC: @audhi3k

**Comment by sruthi1017** [comment]
hi @Ejaz3KT all the changes has been done and published for all pages can u pls test and confirm
cc: @audhi3k @gsudarsan3k

**Comment by Ejaz3KT** [comment]
Ok @sruthi1017 I`ll test and update you

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 The customization is working fine and I`ve to connect with client for the UAT

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
UAT has done with the client waiting for confirmation from the client to deploy the changes in the production

CC: @audhi3k @sruthi1017

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 Client has confirmed please deploy the changes in the production company

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sruthi1017 changes Has been deployed in the production

CCL @audhi3k

**Comment by Ejaz3KT** [comment]
Deployment has been done in the production and client also confirm as report is working fine we can close the ticket

CC: @audhi3k @sruthi1017
