### ISSUE TITLE
Membership Payment Trans list extension missing

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#907]

**Comment by Jayanth3KT** [comment]
@niranjand22 

![Image](https://github.com/3ktech/General/assets/142868335/abf7ae73-421d-4386-9dff-6ff0b8657a23)

**Comment by niranjand22** [comment]
Hi @3ktech  , Due to update from Microsoft the Custum extension has been removed from Startek UAT Envirnment. Kindly Allocate the resource to Publish the Extension gain.

CC @audhi3k

**Comment by niranjand22** [comment]
Deplyed to UAT. 

cc @audhi3k

**Comment by niranjand22** [comment]
This case has been closed. @sruthi1017  can u pls update your consumed time here

cc @audhi3k  @Prakash3K
