### ISSUE TITLE
Fw: LNES Invoice format

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#908]

**Comment by TabrejAlam3K** [comment]
See the Pdf copy of the invoice, It is printing in two page out of first page alone is coming as blank.

[document (18).pdf](https://github.com/3ktech/General/files/12927650/document.18.pdf)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Mr. @Prakash3K - Please create a ticket in the support portal and assign the case id for this.

Contact Person - boopathy.dakshinamurthy@meritgroup.co.uk

CC : @Shasthara

**Comment by TabrejAlam3K** [comment]
Mr. @niranjand22 - See the attached document for your references.

CC : @audhi3k

**Comment by niranjand22** [comment]
Sure will take this

**Comment by niranjand22** [comment]
@3ktech  Hi ..pls allocate technical resource for this

**Comment by niranjand22** [comment]
Connected with Boopathy..

Whenever ther is multiple line items in posted sales invoice. It shows the first page as blank and start priniting forn next page.

Posted Sales Invoice No
SI-MR103453
SI-MR103566

![Image](https://github.com/3ktech/General/assets/116243958/e6a46305-c160-485b-90ff-ccec279f42af)
![Image](https://github.com/3ktech/General/assets/116243958/a761d1d5-94da-48f8-b020-28bf48f93896)

**Comment by niranjand22** [comment]
mail is alreday shared  and Had chat with Mr Boo today he will confirm to deploy in live .

**Comment by niranjand22** [comment]
Lines is fine..now Footer area needed to be fixed for all pages. @sruthi1017  let me know once you  done this

**Comment by niranjand22** [comment]
**Hi Boopathy,

We have fixed the footer also in Merit Sandbox, we have also increased the Document No. Field size by two digit.
Kindly find the attached invoice.

Once checked kindly confirm for Live deployment.
**

**Comment by niranjand22** [comment]
"Thanks for the call. It looks fine now. 

But please add the page number as discussed over call. "-Mr Boopathy

Thank you for the call Mr Boo,

During our conversation, both aspects were functioning as anticipated. We will incorporate page numbers and proceed with the deployment to the live environment.

 @sruthi1017 

Cc- @audhi3k

**Comment by niranjand22** [comment]
Hi client confirmed for deploy to live .

@sruthi1017

**Comment by niranjand22** [comment]
report - 50100

**Comment by niranjand22** [comment]
Hi @sruthi1017  pls move changes to live client has confirmed.

**Comment by niranjand22** [comment]
Deplyed to live, updated to Mr Boo. @Prakash3K  you can close this case with 8 hrs. 

we took 8 hrs apporval for this.
cc @audhi3k
