### ISSUE TITLE
In Vouchers, the description should be updated based on the Dimension value name that is assigned to the respective journal line

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#91]

**Comment by audhi3k** [comment]
@sandhya3k , as discussed can you check this

**Comment by sandhya3k** [comment]
Please check @TabrejAlam3K in dev env

**Comment by TabrejAlam3K** [comment]
1. Bank Receipt Voucher - Done
2. Bank Payment Voucher - Done
3. Cash Payment Voucher - Done
4. Cash Receipt Voucher - Done
5. Contra Voucher - Done

I have created 3 Lines and Every line I have assign the 2nd line dimension on every line then the Dimension Value is got updated in Line Description.

**Comment by TabrejAlam3K** [comment]
@sandhya3k - If the test scenario is correct so that you can move this into the UAT.

**Comment by audhi3k** [comment]
Testing scenario is not correct
@sandhya3k @TabrejAlam3K  we will connect at 3:30

**Comment by TabrejAlam3K** [comment]
@sandhya3k  - You can move it to the UAT

**Comment by TabrejAlam3K** [comment]
@sandhya3k  - Please move this into the UAT and confirm. We need to test and close this

CC @audhi3k

**Comment by sandhya3k** [comment]
Hi @TabrejAlam3K I moved to UAT. Please check confirm.

**Comment by TabrejAlam3K** [comment]
Tested in UAT.

1. Bank Receipt Voucher - Completed.
2. Bank Payment Voucher - Completed.
3. Cash Payment Voucher - Completed.
4. Cash Receipt Voucher - Error - Ticket Raised in Git
5. Contra Voucher - Error - Ticket Raised in Git

@sandhya3k  - Please check the above points 4 and 5.

**Comment by TabrejAlam3K** [comment]
I am closing this ticket and create separate ticket where we are facing errors.
