### ISSUE TITLE
Validation Over 4 New Fileds for Loan File

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#913]

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Create the ticket in the Support Portal and Assign the Case id for this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - As dicussed once you complete the development activity please ping on the same ticket.

CC : @audhi3k @Shasthara

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - new points are completed. kindly check and confirm.

cc: @3ktech, @gsudarsan3k, @audhi3k, @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - I have done the UAT with the Client it is fine, You can move the changes into the Production.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Vridhi Team is not available today we will connect on Wednedsay 25-10-2023

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Please whether the ticket is deployed into the Production Environment?

CC : @audhi3k @Shasthara

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - Deployment is done in prod environment.

cc: @3ktech, @audhi3k, @Shasthara

**Comment by TabrejAlam3K** [comment]
Confirmed for Closure while screen sharing session with Mr. Dikshant

Hi Mr. @Prakash3K - You can close this ticket from the support portal.

CC : @audhi3k @Shasthara
