### ISSUE TITLE
Service REP development

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#914]

**Comment by Ejaz3KT** [comment]
Please find the attached service item & service contract required field file

[Service Module action items.txt](https://github.com/3ktech/General/files/13068506/Service.Module.action.items.txt)

[Service Item & Service contract Testing.docx](https://github.com/3ktech/General/files/13068508/Service.Item.Service.contract.Testing.docx)

**Comment by Ejaz3KT** [comment]
Service order having issue when creating the new service order we can't able to create new service order

![Image](https://github.com/3ktech/General/assets/125632927/a628a338-edec-4bf4-a857-ad53177a9fd9)

CC: @audhi3k @niranjand22 @Padma2717
