### ISSUE TITLE
Task Group under master

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#915]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/617682f5-b7ae-4ca0-ac19-bf14258b2f7a)

**Comment by Jayanth3KT** [comment]
@sruthi1017 done UAT with client, they mentioned to add one piont

Task group description to be flowed in job task line and job journal.

After completing kindly deploy to live.

CC: @audhi3k @Tushargupta3K @3ktech

**Comment by Prakash3K** [comment]
Thank you @sruthi1017, Client confirmed for closure.

CC: @audhi3k @Tushargupta3K @Mahesh3ktech
