### ISSUE TITLE
JV Entries not going in Approval Payment LCMS Window

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#916]
After 28th of July there are no Journal Voucher Entreis going into the Approval Window accept WriteOffAmount.

**Comment by TabrejAlam3K** [comment]
Entreis are available in Posted Approve Payment - LKS05-2223-00694|LKS05-2223-00695

Entreis are not available in Posted Approve Payment - LKS01-2324-00910|LKS01-2324-01790

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Please assign the case id for this.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech - Please assign the technical for this task

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @3ktech and Mr. @gsudarsan3k - Please assign technical to workup on?

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam - I have tested the same scenario in the UAT environment it is working fine and payment entries are reflecting in the Approve Payment LCMS window.

Tested - Document No. LKS04-2223-00585 Entry No. 29242 RTB No. 0000862284

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - As discussed and showcase please do the analysis and let me know you overview.

CC : @audhi3k @gsudarsan3k

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - requesting you to create a journal voucher to debug the issue.

cc: @audhi3k, @gsudarsan3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Let me once you will done you analysis.

![Image](https://github.com/3ktech/General/assets/116171982/bd26c5d6-4c1e-4498-b6f9-05e706208723)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - I need to close this issue on priority basis.

CC : @audhi3k @Shasthara

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - can we connect to discuss about the issue which need to be check the entries based on analysis. and on tuesday you are on leave, we can discuss and close today.

CC: @audhi3k @gsudarsan3k @Shasthara @3ktech

**Comment by TabrejAlam3K** [comment]
As per our discussion with the User Mr. Bhupendra he will test the same scenarion in the Copy_Prod and let us know.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
I will do the UAT session with the client then update the latest comments here.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - I have done the UAT session with the Client, Still it is not working. Need to debug the below Document which is shared by the User.

Document - LKS04-2223-00663  JVPI/2324/01/00003  0000863349
Document - LKS04-2223-00662  JVPI/2324/01/00003  0000863345

CC : @audhi3k @Shasthara

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - this above mentioned entry is posted, so kindly reproduce scenario so it will help me to debug the issue copy prod company.

cc: @audhi3k @gsudarsan3k @3ktech

**Comment by TabrejAlam3K** [comment]
Extra time not yet approved by the Client.

**Comment by TabrejAlam3K** [comment]
As per our discussion with the client, He will test and confirm for closure or he will confirm if required any support on this.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
As per our session with the client he told wait for another one more days.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
As Discussed with the Client(Mr. Bhupendra), Currently the process is working fine. I am closing this ticket and going to create a separate ticket for JV Historical Data Update. 

CC : @audhi3k @Shasthara
