### ISSUE TITLE
Applied Amount field add in Customer & Vendor Ledger Entries

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#918]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/fc2fe3c2-8fd9-417d-97f0-192bdcb312af)



[Customer Ledger Entries (4).xlsx](https://github.com/3ktech/General/files/13050930/Customer.Ledger.Entries.4.xlsx)

**Comment by Ejaz3KT** [comment]
Hi @gsudarsan3k We got the approval for the effort hours for this task we can start the work

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @gsudarsan3k Can I know the status of this task if it is completed can I start testing

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @gsudarsan3k Please let me know the status of this task

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @gsudarsan3k I`ve tested the functionality it is fine and I`ve showed to client as well, Client told he will check with their finance team and update us

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
UAT has done with Mr. Muralikrishnan sir waiting for the confirmation to deploy in the production

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @gsudarsan3k Please deploy this in the production company

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The client has confirmed we can close this ticket

CC: @audhi3k @gsudarsan3k
