### ISSUE TITLE
Bank Receipt Voucher - points raised in UAT 3rd Feb 2023

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#92]
Bank Receipt Voucher

1. Income Account is mandatory.
2. validation on over application.
3. when the application is changed, the amount is not getting changed based on new application.
4. document date should be current date, now it is the deposit date.
5. Owner1 and Owner2 getting update while moving to next line.

**Comment by 3ktech** [comment]
@audhi3k , @panduc  and @TabrejAlam3K , to discuss on the testing scenarios. @panduc  to fix the issues on priority

**Comment by TabrejAlam3K** [comment]
@panduc - If you have required any discussion on please ping me. We need to fixed it on priority.

**Comment by panduc** [comment]
@TabrejAlam3K  it was already enabled, and we need to test it together with @audhi3k  for first 3 points.

**Comment by panduc** [comment]
@TabrejAlam3K  as discussed please share the testing status of first 3 points.

**Comment by TabrejAlam3K** [comment]
@panduc 
Points No 1 - Not Tested
Points No 2 - Not Tested
Points No 3 - Tested it is not working 


![Image](https://user-images.githubusercontent.com/116171982/218635565-b69da5d6-a509-4da3-9f29-7fe865a15ad2.png)

**Comment by TabrejAlam3K** [comment]
Bank Receipt Voucher

1. Income Account is mandatory - **Working Fine (NAV16 and BC)**
2. validation on over application - **Showing Error in NAV16 but In BC no Errors** 
NAV16 Error 
![Image](https://user-images.githubusercontent.com/116171982/218708833-10cbbb2a-14b9-4329-89f3-9247b044a828.png)

3. when the application is changed, the amount is not getting changed based on new application. - Requirement (Based on Applies to Doc No. Amount should be updated) - **It's not happening in both the application NAV16 and BC.**

**Comment by sandhya3k** [comment]
@TabrejAlam3K  please test on point no :3?

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Points 3 is not working please check and confirm. Once completed please ping me.

**Comment by 3ktech** [comment]
@sandhya3k , test and update your status here

**Comment by TabrejAlam3K** [comment]
@sandhya3k  - Point No. 3 is working fine based on the Apply to Doc No. Amount is updating.

**Comment by TabrejAlam3K** [comment]
@sandhya3k - When I try to change the Apply to Doc No. then we found some error in BC


![Image](https://user-images.githubusercontent.com/116171982/219313667-ceb4279e-4c2c-49ce-becd-c00ea1b40b96.png)

**Comment by TabrejAlam3K** [comment]
@sandhya3k - As per our discussion if it is the base error so based on the code what is that functionality please tell us based on that we will check and close it.

**Comment by sandhya3k** [comment]
ok @TabrejAlam3K

**Comment by TabrejAlam3K** [comment]
Points No. 3 is working fine in UAT. I am closing this ticket if i got some error i will create a separate ticket for those.

**Comment by audhi3k** [comment]
@sandhya3k, check on the error along with Mr KarthikD

**Comment by sandhya3k** [comment]
@TabrejAlam3K  please test the UAT environment?

**Comment by TabrejAlam3K** [comment]
@sandhya3k - Dimension Set ID is working fine but

Based on the Apply to Doc No. - **Owner 1 Code and Owner 2 Code is not populating before it was working fine.** Please cross check it.

CC @audhi3k

**Comment by TabrejAlam3K** [comment]
Thanks @sandhya3k - It's Working same like NAV16.

When the user on the new line then Owner 1 and Owner 2 got updated. I am closing this ticket as completed.

CC : @audhi3k - Mam you can confirm to the client for UAT.

**Comment by TabrejAlam3K** [comment]
Information passed to the Client for UAT he will confirm if they are face issues during the UAT.

**Comment by audhi3k** [comment]
@TabrejAlam3K, we will close this ticket on Monday, as they are doing internal UAT

**Comment by audhi3k** [comment]
Client hasn't raised any issue, so closing this ticket
