### ISSUE TITLE
Mur-023 / Bank Receipt Voucher - Multiple Interdivision entries created

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#923]

**Comment by Prakash3K** [comment]
@Ejaz3KT 

User id: muralikrishnanm@fichtnerindia.com



![Image](https://github.com/3ktech/General/assets/140147250/a46673d1-d9b3-4e40-89a6-21989157b04a)




![Image](https://github.com/3ktech/General/assets/140147250/18ddd099-9b9e-4387-809b-20a80f79ce9f)

**Comment by Ejaz3KT** [comment]
The issue has been resolved now we can able to delete the lines in bank receipt voucher and I`ve to showcase & get confirmation from the client

CC: @audhi3k @gsudarsan3k

**Comment by Ejaz3KT** [comment]
Client has confirmed we can close this ticket

CC: @audhi3k
