### ISSUE TITLE
FW: AR Dashboard - Jet Report

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#924]

**Comment by Prakash3K** [comment]
@Amar-3KT 



![Image](https://github.com/3ktech/General/assets/140147250/b26b2734-e28f-4005-b430-7f1eacc11bdd)

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam - Mr. Amar is not available, I need support from other resource on this because I am not aware about the functionality of Jet Report.

CC : @audhi3k @Shasthara @gsudarsan3k

**Comment by Amar-3KT** [comment]
Mr. Chris not available i tried to connect.

**Comment by Amar-3KT** [comment]
Client not available

**Comment by Amar-3KT** [comment]
![Image](https://github.com/3ktech/General/assets/111888825/a105690f-8669-418a-b953-86eeca89fc5a)

**Comment by Amar-3KT** [comment]
We are closing this ticket due to client not available. We will create new ticket next week.

**Comment by Prakash3K** [comment]
@Amar-3KT As per client request, this ticket has been reactivated 

CC: @audhi3k @Shasthara

**Comment by Amar-3KT** [comment]
Client busy on other task

**Comment by Amar-3KT** [comment]
Mail has been sent to client if client not responding then we will close this ticket within 5 days .

**Comment by Amar-3KT** [comment]
Mail and msg has been sent to client. If no response received from client we will close this ticket on 8dec.

**Comment by niranjand22** [comment]
closed due to customer unavaialability
