### ISSUE TITLE
Re: Assigned: MDT - Error in Invoice PDF CRM:0023108

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#925]
[Chennai_PSICHEFY24-016_MDT_201023_MERIT_RSP.pdf](https://github.com/3ktech/General/files/13161535/Chennai_PSICHEFY24-016_MDT_201023_MERIT_RSP.pdf)

**Standard Sales - Invoice (1306, Report Request)**

We have a problem in invoicing format as the invoice is depicting INR even though invoice is in GBP

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Create the ticket on the support portal and assign the Case id for this.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - As discuss do the fixes and let me know once completed. Approval is not required it will be fixed within 4 hours.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sruthi1017 - As discussed changes is not reflecting in the Sandbox Environment please check and update.

CC : @audhi3k

**Comment by niranjand22** [comment]
PSI/MUM/FY24-010

**Comment by niranjand22** [comment]
The currency code is coming in the invoice now . Once mr pavan is available will give him uat

**Comment by niranjand22** [comment]
Mr Pavan is  not avaialble

**Comment by niranjand22** [comment]
gave uat to ms swathi, @sruthi1017  changes are working as expected  pls move this to live..

**Comment by niranjand22** [comment]
hi @Prakash3K  we can close this ticket. Totat hours 5.5
