### ISSUE TITLE
Bar code & QR code Functionality

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#927]

**Comment by rohit3k** [comment]
Hi Mr. @Ejaz3KT fixes has been done as per requirement Please check and confirm, it it their on Sandbox.
cc: @audhi3k @Sarikab1222 @gsudarsan3k

**Comment by Ejaz3KT** [comment]
HI Mr. @rohit3k I am testing the scenario for other documents as well if anything required I'll let you know

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
I`ve tested the whole bar code functionality all functionality is working fine we can close this ticket

CC: @audhi3k @rohit3k
