### ISSUE TITLE
Can we lock Work Order Product lines after invoicing?

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#928]

**Comment by Prakash3K** [comment]
@niranjand22 


![Image](https://github.com/3ktech/General/assets/140147250/a64b88e2-f7d6-417f-a6e6-cfef760d59b3)

**Comment by niranjand22** [comment]
@Prakash3K  this looks like crm case

**Comment by Prakash3K** [comment]
@niranjand22 ok sir let we check with Sushmith ma'am and i will close this ticket in git

**Comment by Prakash3K** [comment]
@niranjand22 this ticket related to CRM, so I'm closing this ticket in Git
