### ISSUE TITLE
October Invoice Errors in Business Central

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#929]

**Comment by Prakash3K** [comment]
@niranjand22 



![Image](https://github.com/3ktech/General/assets/140147250/dcba0e87-4702-41e4-97da-fb0eaf48d712)

**Comment by niranjand22** [comment]
@Shasthara  has to request for the spurce code.

**Comment by Mahesh3ktech** [comment]
hi @niranjand22 - we have verified the invoices which mentioned and we didn't find any duplicate line in the invoice.

**Comment by niranjand22** [comment]
we can close this tickets. @Prakash3K
