### ISSUE TITLE
Buyer Name & Buyer Code Required in Navigation -reg

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#93]
Below are the requirnment discussed  for Case- CAS-01166-P1V0Q6 

1. The Vendor Name Should Be Displayed against Source No.(Vendor No.) in Item ledger entries for Purchase and Transfer Entry. 

2. The Purchaser name and Purchaser code should also be displayed in Item Ledger Entry. Purchase and Transfer Entry. The purchaser code is available in the Purchase order.

3. Add these changes in Applied Entries (page level)

**Comment by 3ktech** [comment]
@Mahesh3ktech , analyse and share the efforts required.

**Comment by 3ktech** [comment]
@Mahesh3ktech  to discuss with @audhi3k  to clarify to share the effort

**Comment by audhi3k** [comment]
@Mahesh3ktech, as discussed and explained on the requirement, confirm on the time required

**Comment by Mahesh3ktech** [comment]
@audhi3k, 3 hours is required to complete.

**Comment by Mahesh3ktech** [comment]
@niranjand22, Source Name, purchaser code and purchaser name added to item ledger entry and Applied entries page, Kindly check and update.

**Comment by audhi3k** [comment]
@Mahesh3ktech and @niranjand22 whether the client approved the hours

@niranjand22, kindly convey 6 hours to the client

**Comment by niranjand22** [comment]
Sent mail to client for approval.

**Comment by niranjand22** [comment]
tried testing but the system was not allowing to post the purchase invoices without lot no. (even after assigning lot no. it was asking for lot no.) will discuss this internally with Mrs Audhi or with the Pioneer team.

**Comment by audhi3k** [comment]
@niranjand22, hope you have tried with kindly update the status

**Comment by niranjand22** [comment]
@Mahesh3ktech  source name is getting populated but purchase code and purchase name is not coming

**Comment by audhi3k** [comment]
@Mahesh3ktech, kindly look into this issue today

**Comment by niranjand22** [comment]
For Purchase entry it is working fine. For transfer entry needs to be checked

**Comment by niranjand22** [comment]
client is testing in uat

**Comment by niranjand22** [comment]
@Mahesh3ktech  Client has confirmed. Please move changes to live.

**Comment by audhi3k** [comment]
@Mahesh3ktech  and @niranjand22, kindly update whether deployed in LIVE

**Comment by Mahesh3ktech** [comment]
@audhi3k Today I'm going to deploy the changes in LIVE. along with Zoho master deployment at 1PM to 2PM.

**Comment by niranjand22** [comment]
@Mahesh3ktech is this deployed ?

**Comment by Mahesh3ktech** [comment]
@niranjand22 Yes, the deployment is done in Live environment.

**Comment by niranjand22** [comment]
Follow up for closure has been sent to client.

**Comment by audhi3k** [comment]
Closing the ticket, no issues raised by the client
