### ISSUE TITLE
Job no. to be made mandatory for specific G/L codes

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#931]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/63901053-dd4b-4944-9775-5e5a551ec929)

**Comment by Ejaz3KT** [comment]
Hi @Manoj01021999 As we discussed in the call please find the filters for the requirement
Purchase or sales Line:
Type: G/L account
No = Chart Of accounts Filter: Income/balance: Only income statement, Account type: Only posting
Make Job no field as Mandatary

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Manoj01021999 Fitchner client has approved for the efforts hours we can start the work now

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
HI @Manoj01021999 The customization is working fine and add the same restrictions for preview posting also

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
UAT has done with Mr. Muralikrishnan sir waiting for the confirmation to deploy in the production

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Manoj01021999 Please deploy this in the production company

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @Manoj01021999 Please ask Ms. @sandhya3k to deploy this in the production

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The client has confirmed we can close this ticket

CC: @audhi3k @Manoj01021999
