### ISSUE TITLE
Dynamic issue

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#932]

**Comment by Prakash3K** [comment]
@Amar-3KT 

User Id: agne.krasauskaite@totalpolitics.com

![Image](https://github.com/3ktech/General/assets/140147250/c828dd66-1471-4d05-8d78-1ddf2e826058)

CC: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Issue - No. Series issue due to manually they have used few Document Numbers.

Mr. @Prakash3K -You can close this from the support portal as well.

CC : @audhi3k
