### ISSUE TITLE
Unable to sent remittance, error message below

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#934]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 


![Image](https://github.com/3ktech/General/assets/140147250/8a3d5594-29af-4519-b2a1-92598e45c92d)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Please close this ticket from the support portal, I am closing this ticket from the Git

**Total Effort time = 3 Hours**

![Image](https://github.com/3ktech/General/assets/116171982/db52b03b-5586-405c-b163-80ac0ba6a1af)

CC : @audhi3k @Shasthara
