### ISSUE TITLE
Unable to post PJ error message attached

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#935]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 

User id: agne.krasauskaite@totalpolitics.com

![Image](https://github.com/3ktech/General/assets/140147250/ffcbbea6-9f86-4bb2-8cca-0543a3dace93)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - This is completed yesterday while session with the client.

You can close from the support portal also with time effort **.5 hours**

CC : @audhi3k @Amar-3KT @Shasthara
