### ISSUE TITLE
FW: Export Sales Invoice- Fob Value in inc

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#936]

**Comment by Prakash3K** [comment]
@niranjand22 

User id: suresh.guruswamy@nkg.coffee



![Image](https://github.com/3ktech/General/assets/140147250/7fcb25a6-20f7-45e0-b337-f582015eb786)



![Image](https://github.com/3ktech/General/assets/140147250/1c6525cb-e336-4e02-9fb5-39c46a8f4937)



![Image](https://github.com/3ktech/General/assets/140147250/9935d84b-c9b5-4219-89f6-81c13551e1e4)

**Comment by niranjand22** [comment]
Connected with Mr Suresh, he needs to add one more field  FOB Value in stattics Page of Sales Invoice.
FOB Value= FOB Exchange rate * Invoice value.

**Comment by niranjand22** [comment]
Hi @gsudarsan3k   need technicsl resource for this. can you pls allocate. 
cc @audhi3k

**Comment by niranjand22** [comment]
Hi @sandhya3k  Let me know when cn we connect

**Comment by niranjand22** [comment]
Hi @sandhya3k  if required time is more than 4 we have to inform client. pls update me ur estimate time

**Comment by niranjand22** [comment]
@sandhya3k  Pls share the tech effort required

**Comment by sandhya3k** [comment]
@niranjand22 

can u please one doc for UAT environment after that only i can able to give the time estimate?

**Comment by sandhya3k** [comment]
@niranjand22 

need 6 hours

**Comment by niranjand22** [comment]
Hi @sandhya3k  you can start work as discussed for technical we have taken 4 hrs

**Comment by sandhya3k** [comment]
ok @niranjand22

**Comment by sandhya3k** [comment]
@niranjand22 

please test in uat environment.

**Comment by niranjand22** [comment]
Hi @sandhya3k  have tested it, Looks Fine. Will give UAT to client on monday.

cc-@audhi3k

**Comment by niranjand22** [comment]
Hi @sandhya3k , I have given the UAT to client. he has confirmed for deployment. Just make sure you are making FOB value fielduneditable in UAT company and production company.Once done Pls proceed for deployment to live.

cc--@audhi3k

**Comment by niranjand22** [comment]
Mr Sshasrhara has asked to hold the deplyment until further confimation on Contract. 

ccc @audhi3k

**Comment by niranjand22** [comment]
Hi @sandhya3k  pls deploy to live. shashthara has confirmed

**Comment by niranjand22** [comment]
Hi @sandhya3k , is this deplyed  ??

**Comment by niranjand22** [comment]
It is deployed waiting for cust confirmation.

**Comment by Jayanth3KT** [comment]
@niranjand22 As discussed in call closing this ticket from both GIT & support portal.

CC: @audhi3k
