### ISSUE TITLE
Flows will be turned off in 15 days

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#942]

**Comment by Jayanth3KT** [comment]
Client i'd: mount055@umn.edu

![Image](https://github.com/3ktech/General/assets/142868335/206eb876-af30-4bab-89a6-f54767f60e48)

The files format is in Word doc so i have mailed the attachments

**Comment by niranjand22** [comment]
Hi @Jayanth3KT  and @Prakash3K  This issue is not from BC. This is related to Power automate and ut will be addressed by mr murali he is having call tomorrow with client. You can drop this case from here. and assign to CRM Team from Ticket Portal

cc
@Shasthara @audhi3k

**Comment by Prakash3K** [comment]
@niranjand22 I'm closing this ticket in Git, because this ticket related to CRM

CC: @audhi3k @Shasthara
