### ISSUE TITLE
Urgent, Can't post Payment journal

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#943]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/cd4d3b50-2bf0-46a4-8844-5aed2de3a706)



![Image](https://github.com/3ktech/General/assets/142868335/ae5b190b-ef46-4d58-b671-e77e638148a6)

Client I'd : agne.krasauskaite@totalpolitics.com

**Comment by Prakash3K** [comment]
@TabrejAlam3K 


![Image](https://github.com/3ktech/General/assets/140147250/d0c5c9cf-71f3-431b-b9fd-27b8627b14d1)

Kindly update status and effort hours for this ticket.

CC: @audhi3k

**Comment by TabrejAlam3K** [comment]
Mr. @Prakash3K - It is resolved mark .5 hours time effort.

CC : @audhi3k
