### ISSUE TITLE
Cess not calculated in posted purchase invoice

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#945]

**Comment by Prakash3K** [comment]
@shivakumar3k 



![Image](https://github.com/3ktech/General/assets/140147250/57e49c15-15a9-41bc-a286-0f9192650f8c)

**Comment by shivakumar3k** [comment]
Hi @gsudarsan3k in both Nav-2016 and BC mapped same report id 406 but in BC Tax details are not showing in the report. Please look into this.

**Comment by shivakumar3k** [comment]
We have not made any changes to Report ID 406, as it is an out-of-box report.
I asked the customer for eight hours of customization, but the client stated that no customization required for this report.
Therefore, I'm closing this ticket.
