### ISSUE TITLE
Customer Statement Report- Doc No Field len change.

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#948]

**Comment by niranjand22** [comment]
Hi @sruthi1017  Client has confirmed pls move changes to live

**Comment by niranjand22** [comment]
Hi @Prakash3K  you can create new ticket with above subject line contact persone Mr Boopathy . We have fixed this and deplyed to live.

You can close this ticket with 1.5 hrs.

**Comment by Prakash3K** [comment]
@niranjand22 Done sir
