### ISSUE TITLE
Customization need to move  on Production Environment

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#95]

**Comment by 3ktech** [comment]
@3ktech to discuss with client to get the app file. Kumavision app is a dependency to install the rest of the apps.
CC: @audhi3k

**Comment by audhi3k** [comment]
Whether this discussed with client @3ktech

**Comment by audhi3k** [comment]
@3ktech, Mr Karthik kindly upload all the customization in the production environment

**Comment by 3ktech** [comment]
Had a call with Murali. Waiting for his response to gain the global admin privileges.

**Comment by audhi3k** [comment]
@3ktech, Mr KarthikD did you connected with Mr Murali, do you require any support to follow up with him

**Comment by audhi3k** [comment]
@3ktech kindly update if any support required

**Comment by audhi3k** [comment]
@Amar-3KT , send mail to Mr Singaravel for admin permissions in BC Production Environment

**Comment by 3ktech** [comment]
Kuma vision app has been installed in the production. @sandhya3k , can you push all of our extension in the prod and confirm us?

CC: @audhi3k

**Comment by sandhya3k** [comment]
@3ktech ,
All the 3 extensions have deployed in production environment @Amar-3KT please check whether the extensions are available or not?
cc: @audhi3k

**Comment by audhi3k** [comment]
Working fine, closing the ticket
