### ISSUE TITLE
Ticket for Deletion of Data in Production & Disable of Dimension Field

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#950]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 


![Image](https://github.com/3ktech/General/assets/140147250/768a9fc9-f80c-42f9-87a5-46ea5ef70688)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Ad discussed let me know if required any discussion on this? Please complete it and let me know for UAT.

CC : @audhi3k

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - changes has been done. kindly check and confirm.

CC: @audhi3k, @3ktech, @gsudarsan3k

**Comment by TabrejAlam3K** [comment]
UAT done with the User (Mr. Dikshant) - Waiting for confirmation for closure of ticket.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Please move the changes into the Production Environment

CC : @audhi3k @Shasthara

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - changes has been moved to production environment. kindly check and update.

CC: @audhi3k @3ktech @gsudarsan3k @Shasthara

**Comment by TabrejAlam3K** [comment]
As discussed with the client (Mr. Dikshant) - He will reply over the mail for closure.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - You can close thic ticket from the support portal with **effort hours = 4 hours**

CC : @audhi3k @Shasthara
