### ISSUE TITLE
Change in G/L Mapping

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#951]

**Comment by Prakash3K** [comment]
@niranjand22 



![Image](https://github.com/3ktech/General/assets/140147250/2d368318-ba32-4226-9145-99fa4d43fa33)

**Comment by niranjand22** [comment]
we analysed and Ms @sruthi1017  checked the pages and tables for finding the hardcoded configuration and mentioned by IFI team. But we dint find any .  need support from @audhi3k

**Comment by niranjand22** [comment]
We have identified THE CODE. changes needs to be done once discussed with Ms Audhi. @audhi3k  @gsudarsan3k

**Comment by niranjand22** [comment]
Tested the changes. Its working fine. In Sandbox environment. Updated to client as well

cc @audhi3k

**Comment by niranjand22** [comment]
Hey @gsudarsan3k , We have recovied the cutomer confirmation for deplyment to live. You can move this changes to live.

cc @audhi3k

**Comment by Shasthara** [comment]
Please confirm whether this fix has been deployed to production. @niranjand22 @gsudarsan3k

**Comment by niranjand22** [comment]
Hi @gsudarsan3k  , client has confirmed for redelyment of changes. 

cc @audhi3k

**Comment by niranjand22** [comment]
resolved..
