### ISSUE TITLE
Finished Production order Report

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#952]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/ca8e7e88-df99-406d-aa78-6937dcd5cc54)



[Finished Production Order SL No..xlsx](https://github.com/3ktech/General/files/13234096/Finished.Production.Order.SL.No.xlsx)

**Comment by Jayanth3KT** [comment]
Hi @3ktech kindly assign technical resource to this ticket.

CC: @audhi3k @Tushargupta3K @gsudarsan3k

**Comment by gsudarsan3k** [comment]
Hi @Jayanth3KT ,

2 hrs. tech effort is required for this task.

**Comment by Jayanth3KT** [comment]
Hi @gsudarsan3k We got approval from client, we can start working.

CC: @audhi3k @Tushargupta3K

**Comment by Jayanth3KT** [comment]
HI @gsudarsan3k Any update sir ?

CC: @audhi3k @Tushargupta3K

**Comment by Jayanth3KT** [comment]
Hi @gsudarsan3k Kindly update the status of this ticket.

CC: @audhi3k @Tushargupta3K

**Comment by Shasthara** [comment]
@gsudarsan3k  kindly update the status here

**Comment by Jayanth3KT** [comment]
Hi @sruthi1017 Deploy the changes in production.

CC: @audhi3k @Tushargupta3K

**Comment by Jayanth3KT** [comment]
Completed.

CC: @audhi3k @Tushargupta3K
