### ISSUE TITLE
LCMS is not getting executed within BC

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#953]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/6fe2de49-3922-4ece-a38b-0fd2a28691f7)

@Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Jayanth3KT - You can close this ticket from the support portal.

**Total Effort Hours = .5 Hours**

Error Reason - An administrator changed one or more extensions in the application, so the page that you were working on had to be closed.

CC : @audhi3k @Shasthara
