### ISSUE TITLE
Branch Level access - Location fixing for Expanse Page.

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#957]

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Create a ticket on the support portal and assign the Case Id for this.

Contact Person : bhupendra.bhakuni@lakshmisri.com viswa.accounts@lakshmisri.com

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - Ad discussed yesterday please close this before 1st half.

CC : @audhi3k @Shasthara

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - changes has been done. kindly check and confirm.

CC: @audhi3k @gsudarsan3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech As discussed please connect with Ms. @sandhya3k and deploy the changes into the Production.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Changes has been deployed into the Production

Thanks Mr. @Mahesh3ktech & Ms. @sandhya3k 

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
I will do the UAT session with the client then update the latest comments here.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Please close the ticket from the support portal. I am closing from the Git.

**Total time effort = 4 Hours**

CC : @audhi3k @Shasthara
