### ISSUE TITLE
GST % display in Sales Invoice print format

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#959]

**Comment by Prakash3K** [comment]
@niranjand22 



![Image](https://github.com/3ktech/General/assets/140147250/821ad25a-f26c-4eb9-8e64-aeac49e0efa1)

**Comment by niranjand22** [comment]
SGST-IGST PSI- PSI/CHE/FY24-013
IGST PSI- PSI/MUM/FY24-016

IN SANDBOX INDIA - MERIT

**Comment by rohit3k** [comment]
Hi Mr. @niranjand22 Work has been done on Sandbox Please check and confirm.
cc: @audhi3k @gsudarsan3k

**Comment by niranjand22** [comment]
hi @rohit3k  pls move changes to live.

**Comment by rohit3k** [comment]
Hi Mr. @niranjand22 Chanes has been deployed on Production Please test it and confirm.
cc: @audhi3k @gsudarsan3k
