### ISSUE TITLE
Address issue in PO - Merit BC IND tenant

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#960]

**Comment by Prakash3K** [comment]
@niranjand22 



![Image](https://github.com/3ktech/General/assets/140147250/5e432fe5-24d9-4d16-9b48-37df56aa8c36)



![Image](https://github.com/3ktech/General/assets/140147250/8103b240-de4b-4ecb-83bf-77cc753d7bb7)

**Comment by niranjand22** [comment]
Connect with Ms Swathi. 

In PO Report.

In Reciver Address data should be same as ship to address. @gsudarsan3k  Kindly allocate the tech resource.
cc @audhi3k

**Comment by niranjand22** [comment]
Attaching the field mapping file @rohit3k 

[document (55).docx](https://github.com/3ktech/General/files/13264050/document.55.docx)

**Comment by niranjand22** [comment]
PO file

[document (55).pdf](https://github.com/3ktech/General/files/13264051/document.55.pdf)

**Comment by niranjand22** [comment]
I have tested it looks fine. I have asked time from client once Ms swati will be avaialble i will give UAT .

**Comment by rohit3k** [comment]
Hi Mr. @niranjand22 requirement has been done on Sandbox please check and confirm.
cc: @audhi3k @gsudarsan3k

**Comment by niranjand22** [comment]
hi @rohit3k  pls move changes to live.

**Comment by rohit3k** [comment]
Hi Mr. @niranjand22 Changes has been deployed on Production please check and confirm.
cc: @audhi3k @gsudarsan3k
