### ISSUE TITLE
Bank Voucher report - GST entries to be excluded

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#963]

**Comment by Prakash3K** [comment]
@Ejaz3KT 

User id: muralikrishnanm@fichtnerindia.com

![Image](https://github.com/3ktech/General/assets/140147250/29aa0a52-d155-4dc3-b66a-646a40cab01a)

**Comment by sandhya3k** [comment]
@Ejaz3KT 
please test on the report

**Comment by Ejaz3KT** [comment]
ok @sandhya3k  madam

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam I`ve tested the report it is working fine need to showcase to the client and get confirmation

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam The voucher Cust report is working fine I`ve showed to Fitchner client they has confirmed and we can deploy this changes in the production

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Deployment has done for this ticket @sandhya3k  madam

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The client has confirmed we can close this ticket

CC: @audhi3k @sandhya3k
