### ISSUE TITLE
DYN 365 BC / Fichtner India/ 3KT / 03.11.2023 / Mur-025 / Bank Voucher report - GST entries to be excluded

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#964]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/5262af72-f5d8-444a-9251-3aa12c0be077)



[100DBBP233390.pdf](https://github.com/3ktech/General/files/13256172/100DBBP233390.pdf)

**Comment by Ejaz3KT** [comment]
HI @Jayanth3KT This ticket is already available and created by Mr. @Prakash3K  in GIT Please remove this one

**Comment by Jayanth3KT** [comment]
Duplicate of #963  hence closing this this ticket.
