### ISSUE TITLE
Sales Credit Note come under B2B Taxable supply under GST

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#969]

**Comment by Prakash3K** [comment]
@shivakumar3k 


![Image](https://github.com/3ktech/General/assets/140147250/091a27f7-1ce1-4f1a-877b-9e919fb7151e)





![Image](https://github.com/3ktech/General/assets/140147250/bfb6c5d1-1a12-4254-aabf-fffd0df19ac4)



![Image](https://github.com/3ktech/General/assets/140147250/a7bf751a-3b98-4bd5-aa30-7ed1c130c76d)



![Image](https://github.com/3ktech/General/assets/140147250/18720fb4-d970-4d4b-8d9d-64133cb6b19b)



![Image](https://github.com/3ktech/General/assets/140147250/c9f04d21-4346-4cd7-bc1e-9eca0c948f48)

**Comment by shivakumar3k** [comment]
Hi @audhi3k mam, Please let me know your availability to schedule call with Client.
