### ISSUE TITLE
Sales Invoice - should be available before posting

### ISSUE THREAD

**Issue by Ejaz3KT** [3ktech/General#976]
Hi @sandhya3k Please find the field mapping for the sales invoice report

[Fitchner Sales Invoice Field mapping.xlsx](https://github.com/3ktech/General/files/13275832/Fitchner.Sales.Invoice.Field.mapping.xlsx)

**Comment by sandhya3k** [comment]
@Ejaz3KT 

I did not have a time to work on this report
 cc : @audhi3k

**Comment by Ejaz3KT** [comment]
ok @sandhya3k  madam

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k  Madam Any update on this report

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

Working on another priority issue for total politics please give some time

cc : @audhi3k  @gsudarsan3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

As discussed, please test on staging sandbox environment?

**Comment by Ejaz3KT** [comment]
ok @sandhya3k madam

**Comment by Ejaz3KT** [comment]
UAT has been done with the client waiting for their confirmation 

CC: @audhi3k @sandhya3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam Please deploy the sales invoice report in production company now

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Deployment has been completed waiting for the client's approval

CC: @audhi3k @sandhya3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam some changes need to be made in the sales invoice report

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
HI @sandhya3k Please find the screenshot there mentioned what are the changes we need to made


[33-23-1415_domestic_before post_sales invoice.pdf](https://github.com/3ktech/General/files/13433309/33-23-1415_domestic_before.post_sales.invoice.pdf)

[10/23 12:09 PM] Ejaz Ahmed
32102|32103|32104|13215
[9:15 AM] Ejaz Ahmed
	a	Title should be “Draft Invoice”

	b	In the header portion, remove the lines as shown in the pdf.

	c	In case of export invoice, below text needs to be printed across all foreign currencies.

“SUPPLY MEANT FOR EXPORT WITHOUT PAYMENT OF IGST UNDER LETTER OF UNDERTAKING No. ARN/RFN No.AD330323024072U”

We would like to have the highlighted ARN/RFN No. to be dynamic that is it should get captured from a field and the field /form information needs to be shared to us. This is required as it will be updated on a yearly basis.

	d	The payment advice content should exclude the word “IBAN CODE-,”

**Comment by sandhya3k** [comment]
@Ejaz3KT 

please test and if any modifications, let me know.

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Some points need to be changed in the report I've mention below:
1. In Place of supply Customer GST Reg No. is not printing
2. Rename the sales invoice to draft invoice
3. Payment information is printing wrongly 

[33-23-1377_export_point b & c.pdf](https://github.com/3ktech/General/files/13469663/33-23-1377_export_point.b.c.pdf)
[33-23-1415_domestic_before post_sales invoice.pdf](https://github.com/3ktech/General/files/13469664/33-23-1415_domestic_before.post_sales.invoice.pdf)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k Madam the client now has required new points they are mention below
1. Payment information 
     Invoice type as Taxable : Payment shall be made in favour of " Fichtner Consulting Engineers (India) Private Limited", Payable at chennai.NEFT or RTGS to account no. 50009329000 at Deuische Bank, IFSC CODE - DEUT0916CNN Chennai Branch, 
     Invoice Type as Taxable: change the please of SWIFT code and IFSC code 

2. Inn place of supply add customer GST Reg No. and Customer State code 

CC: @audhi3k

**Comment by sandhya3k** [comment]
@Ejaz3KT 

please test on staging sandbox?

cc : @audhi3k

**Comment by Ejaz3KT** [comment]
Ok @sandhya3k  madam

**Comment by Ejaz3KT** [comment]
Hi, @sandhya3k madam Please add one else condition in the sales invoice report 
i.e. If invoice type is <>'' then currency <>'' TDS certification (Form No. 16A) may please be sent to our regd. office address is given above" Information

If invoice type is <>'' then currency '' SUPPLYMEANT FOR EXPOERT WITHOUT PAYMENT OF IGST UNDER LETTER OF UNDERTAKING No. ARN/RFN No. AD330323024072U

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The issue has been resolved Mr. @Prakash3K you can close this ticket with 15 hours of effort

CC: @audhi3k @sandhya3k
