### ISSUE TITLE
Transfer order VNR.TO. 2324.0485 Issue

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#978]

**Comment by Prakash3K** [comment]
@shivakumar3k 

![Image](https://github.com/3ktech/General/assets/140147250/20cbeea3-49c2-4283-aa04-a47b2f217687)

**Comment by shivakumar3k** [comment]
Issue - While receiving transfer order system showing No Goods in transit to receive.

Solution - User posted the transfer order with out selecting Goods in transit option in Header. Due to that in Lines In-transit code showing blank values.
Because of this System showing above error.
