### ISSUE TITLE
Re: Issue Reported - Post Send from RRL to UL

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#979]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 


![Image](https://github.com/3ktech/General/assets/140147250/4a8e0c24-8e84-4eae-8ce3-19ad0aa85fac)



![Image](https://github.com/3ktech/General/assets/140147250/01730c98-248e-47ad-bb36-fe432b3cfa39)

**Comment by TabrejAlam3K** [comment]
Hi Ms. @Sarikab1222 - We have receive one new ticket from the UL team, Please provide you go ahed to working on.

CC : @audhi3k @Prakash3K

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - They have replied that this will resolved internally, so we can closed this ticket.

CC : @audhi3k
