### ISSUE TITLE
General Journal Serial Number Error

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#98]
Issue : While posting a new General Journal, the document sequel number is not updating , instead its taking previous document no.'s which were already posted.

**Comment by TabrejAlam3K** [comment]
@niranjand22 


![Image](https://user-images.githubusercontent.com/116171982/217441828-a5e2df47-ca0a-46e1-9b3e-ae94e8289668.png)

**Comment by TabrejAlam3K** [comment]
Need to debug where it is taking the previous no. series.

@audhi3k - Need any one technical who will support on.

**Comment by audhi3k** [comment]
@TabrejAlam3K we will connect on this ticket for analysis

**Comment by TabrejAlam3K** [comment]
@audhi3k - I had analyzing on that my self but i couldn't able to find anything.

**Comment by TabrejAlam3K** [comment]
@audhi3k - You will analyzing on in detailed.

**Comment by audhi3k** [comment]
Through screen sharing session explained the issue

Analysis: The posted no. series is not defined.  The document no. can be updated manually and will accepted even the post no.

Solution: To avoid such entry, assign posted no. series

**Comment by TabrejAlam3K** [comment]
Through the screen sharing session with Mr. Pavan (Merit) explained the issue

He will check this into the production and confirm.

Solution : If user don't want to post the same Voucher No. in back date so he need to marked Date Order Boolean should be true in No. Series and define the Posting No. Series in Journal Batch.

CC @audhi3k

**Comment by TabrejAlam3K** [comment]
Tested with User Mr. Pavan in Sandbox and same thing applied in the production.

I am closing this ticket.
