### ISSUE TITLE
FW: Sales invoices and credit notes with product name & product code - excel export from BC

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#980]

**Comment by Prakash3K** [comment]
@Amar-3KT 


![Image](https://github.com/3ktech/General/assets/140147250/e7abf2b5-eb1e-4a11-8065-e33fe4bf5e4f)

**Comment by Amar-3KT** [comment]
![Image](https://github.com/3ktech/General/assets/111888825/87c3d231-0145-4f65-b4e3-7851d3286f79)

**Comment by Amar-3KT** [comment]
Client busy on other task

**Comment by Amar-3KT** [comment]
Mail has been sent to client if client not responding then we will close this ticket within 5 days .

**Comment by Amar-3KT** [comment]
Mail and msg has been sent to client. If no response received from client we will close this ticket on 8dec.

**Comment by niranjand22** [comment]
closed due to custmer infirmation unavaialabilty.
