### ISSUE TITLE
Issue Reported Outgoing JW Order #OU-JWO2324-00196

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#982]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/39c5b2ee-b327-4069-83b6-6afbb83af46c)



![Image](https://github.com/3ktech/General/assets/142868335/43b650f6-a6b3-4d0e-9ed8-4f46d1c9ae4f)

**Comment by TabrejAlam3K** [comment]
As discussed with the Client (Mr. Rewat) - Once he will free we will connect and fix the issues.

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Issue has been resolved and confirmed by the client (Mr. Rewat). Please close this ticket from the support portal.
**Total Time Effort = .5 Hours**

CC : @audhi3k @Sarikab1222
