### ISSUE TITLE
In the vendor payment upload report remove space in the bank account number field

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#983]

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k There are a space is occurring in vendor payment upload report in A/c no. filed please remove that space from that field.

![Image](https://github.com/3ktech/General/assets/125632927/aca45881-48cd-4b68-9368-6857b72bf6c1)

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
Hi @sandhya3k  madam you got the solution for this report

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
I`ve tested the report the gap in account number has been removed  and now it is fine 

CC; @audhi3k @sandhya3k

**Comment by Ejaz3KT** [comment]
It is fine Please deploy this in the production company 

CC: @audhi3k @sandhya3k

**Comment by Ejaz3KT** [comment]
The client has confirmed once the changes are deployed we can close this ticket so please @sandhya3k deploy then the Changes in the production 

CC: @audhi3k

**Comment by Ejaz3KT** [comment]
The changes has been deployed in the live environment we can close this ticket

CC: @sandhya3k @audhi3k
