### ISSUE TITLE
Reverse Transaction is not happening

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#984]
Error Snapshot.

![Image](https://github.com/3ktech/General/assets/116171982/12ab747f-932b-4e72-85e2-cbf1b9254186)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Please create a ticket in the support portal and assign the case id.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Ms. @sandhya3k - The same ticket was created earlier and assign to you for debugging purpose, but due to non respnses by the client side it was close, Same issue hgihlited again. What is your bandwith whether you are able to take this task?

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
BRTT/2324/06/0343

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech - See the below document is ready for debug.


LKS01-2324-02362 | Invoice need to apply againg the Payment
BRTT/2324/08/0128 | Already applied the documents - Unapply and Reverse
BRTT/2324/08/0127 | Need to apply then Unapply then Reverse Transaction

CC : @audhi3k

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - Transactions is getting reversed now which auto applied entry scenario. kindly check and confirm.

**Comment by TabrejAlam3K** [comment]
I have done the communication with the client Mr. Bhupendra, He told he will test some document in the Copy_Prod Company and let us know with their comments.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
I was discussed with the client on issues, He said it is working fine in the Copy_Prod Environment but he want to test more scenario.

CC : @audhi3k  @Shasthara

**Comment by TabrejAlam3K** [comment]
Waiting for Client response on this.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Mahesh3ktech  - Client confirmed for move the changes into the Production Environment.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - You can close this ticket from the support portal, Client confired it is working in Copy_Prod company. It was pending for deployment, Deployment is completed.

**Total Effort hours = 20 Hrs**

![Image](https://github.com/3ktech/General/assets/116171982/1233493d-c948-4d30-a4e1-6350db9362ac)

CC : @audhi3k @Shasthara
