### ISSUE TITLE
Amending Sales Invoice Email Template

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#985]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/e3ace567-803e-41e6-a445-cda6b32b0dea)



![Image](https://github.com/3ktech/General/assets/142868335/d9d47901-d5ca-49bf-84ce-ba420859108e)



![Image](https://github.com/3ktech/General/assets/142868335/c16b464b-ba9b-4133-9299-57af1ede510d)

**Comment by niranjand22** [comment]
Changes are done. Deplyed in Live.

cc @audhi3k  @Jayanth3KT

**Comment by niranjand22** [comment]
@Jayanth3KT  Customer has confirmed for closure .pls close this case total hours consumed 2.5hrs

cc @audhi3k

**Comment by Jayanth3KT** [comment]
Closing this ticket, hence its closed in support portal.
