### ISSUE TITLE
Issue Reported - Post Expenses OU-JWO2324-00081

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#989]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/15019a08-a8ec-4bb2-ba14-264b1a130d32)



![Image](https://github.com/3ktech/General/assets/142868335/c9bb37f6-010c-4d6d-b11a-26eb3d44eca3)

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Jayanth3KT - This issue has been resolved and confirmed by the User (Mr. Rewat). Please close this ticket from the support portal. I am closing from the Git
**Total Effort Hours = .5 Hours**
 
CC : @audhi3k @Sarikab1222
