### ISSUE TITLE
50035: Many columns are missing in report.

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#993]

**Comment by Amar-3KT** [comment]
@3ktech -Please assign technical

**Comment by Amar-3KT** [comment]
@3ktech -Please assign technical.

**Comment by Amar-3KT** [comment]
@3ktech -Please assign technical

**Comment by Amar-3KT** [comment]
@gsudarsan3k - Please assign technical.

**Comment by Jayanth3KT** [comment]
Report is fine according to the requirement. client has additional requirement in this report (coloum)

CC: @audhi3k @shivakumar3k

**Comment by Jayanth3KT** [comment]
completed
