### ISSUE TITLE
50030: Total amount is not correct, PO No, PO Date, GRN No, GRN date is not coming

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#994]

**Comment by Amar-3KT** [comment]
@3ktech -Please assign technical.

**Comment by Amar-3KT** [comment]
@3ktech -Please assign technical

**Comment by Amar-3KT** [comment]
@3ktech -Please assign technical

**Comment by Amar-3KT** [comment]
@gsudarsan3k - Please assign technical.

**Comment by Jayanth3KT** [comment]
HI @Mahesh3ktech Got approval for deployment, Kindly deploy the changes.

CC: @audhi3k @shivakumar3k

**Comment by Jayanth3KT** [comment]
Completed 

CC: @audhi3k @shivakumar3k
