### ISSUE TITLE
50031: Gross total wrong, PO No, PO Date, GRN No, GRN Date not coming.

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#995]

**Comment by Amar-3KT** [comment]
@3ktech -Please assign technical.

**Comment by Amar-3KT** [comment]
![Image](https://github.com/3ktech/General/assets/111888825/2c811c1f-971a-4a7f-9211-cd68d1f764e6)

**Comment by Amar-3KT** [comment]
@3ktech -Please assign technical

**Comment by Amar-3KT** [comment]
@3ktech -Please assign technical

**Comment by Amar-3KT** [comment]
@gsudarsan3k - Please assign technical.

**Comment by Jayanth3KT** [comment]
HI @Mahesh3ktech Got approval for deployment, Kindly deploy the changes.

CC: @audhi3k @shivakumar3k

**Comment by Jayanth3KT** [comment]
Completed 

CC: @audhi3k @shivakumar3k
