### ISSUE TITLE
Incorrect Job work charges invoice genrated | IKA-2324-02526

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#996]

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Jayanth3KT - Please assign the case id for this.

CC : @audhi3k @Sarikab1222

**Comment by TabrejAlam3K** [comment]
I have done the session with Mr. Dhawal and Team.

GST amount was calculated on Incoming Jobwork Order but not calculated on Posted Invoice. See the below documents details 

Posted Invoice No - IKA-2324-02526 and External Document No. OU-JWO2324-00060

CC: @audhi3k @gsudarsan3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @rohit3k  - As discussed earlier and showcase the issue with you on Client system, how we can close this issues? if you have required any support from the other technical resource please reply here.
We need to close this ticket by today.

CC : @audhi3k @Shasthara @gsudarsan3k

**Comment by Shasthara** [comment]
@TabrejAlam3K , @rohit3k - Any update here?

**Comment by TabrejAlam3K** [comment]
![Image](https://github.com/3ktech/General/assets/116171982/92280349-e34f-44cb-8543-42d37ef0b61e)

**Comment by TabrejAlam3K** [comment]
No any response receive from the client end.

CC : @Shasthara @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi Mr. @Prakash3K - Close this ticket from the support portal. I am closing from the git.

Time Effort = 2 Hours

CC : @audhi3k @Sarikab1222 @Shasthara
