### ISSUE TITLE
Task 1

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#997]
task owner to define high level description of the task

**Comment by 3ktech** [comment]
FDD is in progress

**Comment by 3ktech** [comment]
FDD is ready for review. Please find the link [here](url)

**Comment by 3ktech** [comment]
Comment updated in FDD

**Comment by 3ktech** [comment]
Feedback is fixed.

**Comment by 3ktech** [comment]
FDD is approved

**Comment by 3ktech** [comment]
TDD preparation is in progress

**Comment by Amar-3KT** [comment]
Its for testing we can close this
