### ISSUE TITLE
November Invoice Errors in Business Central

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#999]

**Comment by Prakash3K** [comment]
@niranjand22 - 

![Image](https://github.com/3ktech/General/assets/140147250/984c94c2-3650-4500-9a1f-2cbac0dab810)

**Comment by niranjand22** [comment]
hi @Mahesh3ktech , same issue has been raised again. can u look into it now. i can show u docmuents. 

cc @gsudarsan3k

**Comment by Jayanth3KT** [comment]
@niranjand22 as MKK told to wait for two days to close this ticket.

CC: @audhi3k
